### ISSUE TITLE
Web3 NPM package can generate broken package-lock files

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#1007]
The web3 npm package [appears to be broken](https://github.com/ethereum/web3.js/issues/1914). Sometimes when it gets installed it will fail to install its dependencies and generate a broken `package-lock.json`. Since we have multiple packages with this dependency it is causing us some issues.

Generally if you end up with a broken install due to this you can run `npm install web3 --save` in the package that has the issue.

Any errors related to the following packages being missed are caused by this issue:

`typed-array-to-buffer`
`websocket`
`yaeti`

If anyone has any ideas about how to work around this until a new version of web3 gets released please chime in.

**Comment by nick** [comment]
Think this is redundant now
