### ISSUE TITLE
Test timeouts with newer versions of `ganache-core`

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#1008]
It appears that versions of `ganache-core` > `2.2.0` cause our tests to fail for `origin-js` and `origin-contracts`. These look like timeouts. @franckc and I suspect it may be due to the introduction of async request processing in `ganache-core` and our tests not handling promises correctly.

**Comment by franckc** [comment]
Here is the [link](https://github.com/trufflesuite/ganache-core/releases/tag/v2.3.0) to the ganache 2.3.0 release note that mentions the changes related to async request processing.

**Comment by tomlinton** [comment]
Closed, since `origin-js` is no longer around and `@origin/contracts` looks to be happy with a newer version of `ganache-core`.
