### ISSUE TITLE
[multi-units listing] Use per-unit commission for search ranking

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#1015]
For multi-units listing, search ranking should use the per-unit commission value rather than the total commission. So [this code](https://github.com/OriginProtocol/origin/blob/master/origin-discovery/src/lib/search.js#L187) should be updated to take into account the new perUnitCommission field being added to the data stored in IPFS for unit listings as part of #977

**Comment by franckc** [comment]
CC @sparrowDom as a FYI

**Comment by sparrowDom** [comment]
Sounds good. We might need to create another field only in elastic search at index time. Something like: 
```
boostableCommission:{
  amount: listing.commission / listing.unitsTotal,
  currency: listing.currency
}
```
