### ISSUE TITLE
Ongoing issues with npm

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#1017]
We are having a bunch of problems with `npm` and `package-lock.json`. An `npm install` can result in broken/missing dependencies even though it appears to complete successfully. I'm not sure exactly why this is, but anecdotally it looks to often fail for packages install off GitHub.

In addition to that the way `npm install` handles `package-lock.json` is not what you might expect:

- `package.json` can take precedence over `package-lock.json` if the dependency is specified with a `^version` or `~version` `npm install` can install something that is not the same as what is in `package-lock.json`
- If a package is already installed it is never checked against `package-lock.json`

Related issue #1007.

### Use `npm ci`

We do this for the Docker containers for `origin-box` and it seems to be working well. In contrast to `npm install` it:

- Always blows away `node_modules`
- Installs exactly what is in `package-lock.json`

The big advantage here is that install issues should be reproducible on every machine because it should do exactly the same thing rather than `npm install` doing whatever it pleases.

I have a branch [here](https://github.com/OriginProtocol/origin/tree/tomlinton/missing-package-locks) that implements this with `lerna`.  

### Use `yarn`

From the reading I've done a lot of people switched to `yarn` due to the non deterministic behaviour of `npm`. It gained a lot of popularity its speed vs older versions of `npm`, but I think `npm` has largely caught up now. We could try switching to `yarn` but it is more complicated than just using `npm` (extra package required, hard to remember for everyone who is used to using `npm`).

It does have a cool feature called workspaces, which is similar to lernas `--hoist` and what `pnpm` does.

### Use `pnpm`

Just thought I'd note this here as an option. It is basically `npm` but designed to work for monorepos via recursive install of packages and smart symlinking.

## Hoisting/common node_modules

Just wanted to note here that this is something I think we need to get working. With `lerna` there is a `--hoist` flag where it iterates through all the packages, brings all the dependencies up to root and installs them, then handles the linking. This requires us to sync dependencies across packages but it brings big performance gains. I have a [branch](https://github.com/OriginProtocol/origin/tree/tomlinton/enable-hoist) where I am trying to get this working well. It brings the build size from ~5gb to ~1gb and is a lot faster to install.

This can also be achieved using `pnpm` instead of `npm` or via Yarn's workspaces feature. I think it is something we need to get working to make the integration testing workable. I'd also like to use this idea to build a single image for `origin-box` rather than one for each service.

## Summary

I think `npm ci` is the best option. It requires minimal changes as well so we can try it before doing anything more drastic. But please discuss. :grin:

**Comment by micahalcorn** [comment]
![feed-me](https://user-images.githubusercontent.com/273937/49190043-8f668400-f325-11e8-96a8-80bff9394343.gif)

Thanks Tom!

**Comment by tomlinton** [comment]
Closed, no longer relevant!
