### ISSUE TITLE
Multi-Unit Listings

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1044]
Sellers should be able to create listings with a quantity available greater than one. Buyers should be able to purchase more than one unit in a single purchase. This functionality should be available for any non-fractional listing category that supports a non-zero price. This will soon equate to listings in the "For Sale" and "Services" categories.

The designs for multi-unit UI are integrated [here](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9?seid=5be35b99d2521e3d0a7d3e09). The following changes are not reflected in the mockups:

- [x] There will be no "E-commerce" category.
- [x] The photo-related elements should remain at the bottom of the listing creation form.
- [x] The quantity field should default to a value of `1` for both the seller and the buyer.
- [x] The price field label should change from "Price" to "Price (per unit)" when the quantity field value changes from 1 to >1.
- [x] No "Get OGN" elements should be displayed.
- [x] All ETH values should contain exactly five decimal places.
- [x] The "Buy Now" button copy should remain "Purchase".
- [x] The transaction detail page should conform to the design prescribed [here](https://github.com/OriginProtocol/origin/issues/1038).
- [ ] ~Listing status should be displayed as "Pending" when the currently-available quantity is `0` and there _is_ one or more open, valid offers.~
- [x] Listing status should be displayed as "Sold Out" when the currently-available quantity is `0` and there _are no_ open, valid offers.

Important behavioural points:
- [x] do not let user edit the quantity of the listing below the number of accepted(?) offers
- [x] show the amount of the inventory according to the number of created(?) offers
- [ ] in elastic search listener set the boost to the remaining commission amount:  ```min(commission - commisionPerUnit * unitsSold, commissionPerUnit)```

Also keep in mind the following [corner cases](https://docs.google.com/document/d/19zrYx15LEdFzbkquH9AyoUEE3_fNkVqdH4uTJgSJuA0/edit#). 

**Pull Requests for this ticket:**
- https://github.com/OriginProtocol/origin/issues/1044#event-2006293854 (listing creation flow)
- https://github.com/OriginProtocol/origin/pull/1102 (everything else in the DApp)

**Comment by sparrowDom** [comment]
thanks @micahalcorn for creating this issue

**Comment by micahalcorn** [comment]
@sparrowDom thanks! 👏 Do you know if any of the items listed above should be retained as separate issues?

**Comment by sparrowDom** [comment]
@micahalcorn just went over the description of this issue. Only the elasticsearch listener part remains not done. Have moved it to [a separate issue](https://github.com/OriginProtocol/origin/issues/1167).

**Comment by sparrowDom** [comment]
I think we can close this now.

**Comment by micahalcorn** [comment]
Resolved by #1059 & #1102 ✅
