### ISSUE TITLE
Create listing steps

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#1048]
Boost listing should have step `index 3`(instead of 4) and review should have step `index 4` (instead of 5).

<img width="510" alt="screenshot 2018-12-06 00 51 49" src="https://user-images.githubusercontent.com/579910/49551873-5b74fb00-f8f1-11e8-9611-c0282ddb8dcb.png">
<img width="777" alt="screenshot 2018-12-06 00 51 54" src="https://user-images.githubusercontent.com/579910/49551874-5dd75500-f8f1-11e8-9ff2-1dd29bb8bde5.png">

**Comment by sparrowDom** [comment]
@jordajm just noticed this bug.

**Comment by sparrowDom** [comment]
Btw @jordajm I am also doing create listing progress bar steps (just letting you know so that we don't both develop the same functionality): 

<img width="499" alt="screenshot 2018-12-06 01 01 11" src="https://user-images.githubusercontent.com/579910/49552144-9592cc80-f8f2-11e8-8034-cb1f1b2182ec.png">

**Comment by micahalcorn** [comment]
Considering this done ☑️
