### ISSUE TITLE
Indexed Reviews

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1058]
We should index reviews and serve them from -discovery like we do for listings and offers. Ideally, someday, they would be searchable, but the concern for now is that fetching them seems to involve querying listings and/or offers from the blockchain, which [can be problematic](https://github.com/OriginProtocol/origin/issues/799).

**Comment by franckc** [comment]
Happy to take this on. Would be about 3-4 days of work. Just not sure if this is a high priority ?

**Comment by micahalcorn** [comment]
@BrunoBernardino let me know if this is something that you would like to take on. 🙂

**Comment by franckc** [comment]
Chatted with @micahalcorn - With the graphQL rewrite, most of the discovery server will get deprecated. So it's not worth adding more functionality to it. I'm actually going to close this issue since it is not longer relevant.

**Comment by micahalcorn** [comment]
Thanks @franckc 👍 Should we do the same for users?
