### ISSUE TITLE
Indexed Users

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1061]
We should index users and serve them from -discovery like we do for listings and offers. Ideally, someday, they would be searchable, but right now they seem to be plagued by [this issue](https://github.com/OriginProtocol/origin/issues/799) at times. I suppose that we may not be able to tackle this until we move forward with an identity solution.

**Comment by franckc** [comment]
Yes, I was waiting a bit to get clarity on our direction for Identity before indexing users...
Though I can totally index the current user if we think it is a painpoint - amount of work is fairly small, I'd estimate it at 2-3 days.

**Comment by joshfraser** [comment]
Yeah, let's wait till we have a plan for v2 of identity. Would rather put our energy into figuring that out first.

**Comment by franckc** [comment]
With the graphql migration, most of the discovery back-end will be deprecated (except search).
Closing this issue as no longer relevant.
