### ISSUE TITLE
[origin-dapp | UX] Make listings in DAI as a default

### ISSUE THREAD

**Issue by gubatron** [OriginProtocol/origin#1070]
I've said this to other similar projects, eventually they end up doing it.
It makes no sense and it's a horrible user experience dealing with prices in a volatile token like ETH.

List in DAI by default.

**Comment by micahalcorn** [comment]
Thanks @gubatron 👍 We already support other ERC 20 tokens at our protocol layer but have not yet incorporated any other than ETH into our DApp. [We have also decided to support TrueUSD](https://medium.com/originprotocol/origin-will-support-leading-stablecoin-trueusd-a6975b909604) and will consider other stablecoins. We would love for you to get involved!

**Comment by gubatron** [comment]
just found out about it, and it looks great so far. Will take a look at the code to add/edit/display listings to see if there's anything I can do to make listings by default, or at least suggested in stablecoins erc 20 tokens first.

**Comment by gubatron** [comment]
are you by any chance the one listing that hacker house up in Boulder? and also are you a founding member of the project? I also run a publication called DiarioBitcoin.com, it'd be cool to interview you guys, we're always looking for decentralized commerce solutions that can help level the e-commerce field in latin america

**Comment by joshfraser** [comment]
The hacker house was posted by Andrew Hyde. I'm one of the founders and happy to chat. Send me an email at josh@originprotocol.com.

**Comment by micahalcorn** [comment]
Closing in favor of #1673 & #1676 ☑️
