### ISSUE TITLE
Back on create listing form 

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#1081]
Steps to reproduce: 
- choose create listing
- pick any category ("for sale" -> "computers" for example)
- press next
- when the details step is active press "back"

this UI is displayed that seems broken: 
<img width="1300" alt="screenshot 2018-12-12 10 15 24" src="https://user-images.githubusercontent.com/579910/49859201-3acc0a00-fdf7-11e8-8cc7-236ef6526840.png">

**Comment by micahalcorn** [comment]
Haha, good catch @sparrowDom but @jordajm is too fast. 😄 https://github.com/OriginProtocol/origin/pull/1079

**Comment by sparrowDom** [comment]
Nice, fixed before it was reported 🚀
