### ISSUE TITLE
Upgrade origin-discovery to use graphql@^14.0.2

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#1085]
The version in use in the `origin-discovery` `package.json` is `^0.13.2` which is quite old and is mismatched with the versions in @nick's experimental packages which makes lerna complain about it for hoisting. We should upgrade to a newer version if there is no reason we haven't done this already.

I think there are a few breaking changes in the newer version.

**Comment by tomlinton** [comment]
Great, thanks @ambrosehundal! Please ping us in the engineering channel on Discord if you have any questions.

**Comment by micahalcorn** [comment]
@ambrosehundal I've added you to the GitHub organization. Once you accept the email invitation, we can assign this issue to you and you will be able to push a branch rather than create a fork.
