### ISSUE TITLE
While helper active ("Get started selling on Origin!") can't scroll

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#1091]
Currently on main-net dapp I can not scroll to the bottom of the page as long as "Get started selling on Origin!" welcome window is active. 
<img width="1920" alt="screenshot 2018-12-14 10 24 29" src="https://user-images.githubusercontent.com/579910/49994752-a397bb80-ff8a-11e8-94bc-1bc55d2a1045.png">

**Comment by micahalcorn** [comment]
The conditions required for that modal to appear are:
- have no OGN
- have no listings
- have not completed seller onboarding tutorial
Thus, using "account 11" or higher with a clean blockchain and local storage should reproduce it.

**Comment by franckc** [comment]
I got the same issue but related to the "Mainnet Beta" modal. Here is how to reproduce:
 - Open a browser which does not have Metamask installed
 - Got to https://dapp.originprotocol.com/#/
 - Mainnet Beta modal appears (and notice that while modal is displayed the scroll bar on the right is visible)
 - Dismiss the Mainnet Beta modal
=> scroll bar on the right disappears.

**Comment by micahalcorn** [comment]
Resolved by #1197 🤞
