### ISSUE TITLE
Search filters not working

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#1092]
With the recent schema changes the search filters are no longer working
<img width="1920" alt="screenshot 2018-12-14 10 24 29" src="https://user-images.githubusercontent.com/579910/49998730-4bb28200-ff95-11e8-92e4-ac64110a9766.png">

Pull Request: https://github.com/OriginProtocol/origin/pull/1094

**Comment by micahalcorn** [comment]
Resolved by #1094 ✅
