### ISSUE TITLE
Search filters dropdowns not closing 

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#1093]
This might be related to the latest removal of jQuery from the DApp code. The following cases are not working: 
- Category dropdown (next to general search) 
  - does not close when you click out (anywhere on the webpage)
  - does not close when you click on the button that opened it in the first place
- search result page filters (Price for example) does not close when you click out of the dropdown. 

<img width="565" alt="screenshot 2018-12-14 13 40 39" src="https://user-images.githubusercontent.com/579910/50004129-68a38100-ffa6-11e8-9d0e-75bbc6c6441a.png">
<img width="673" alt="screenshot 2018-12-14 13 40 52" src="https://user-images.githubusercontent.com/579910/50004130-693c1780-ffa6-11e8-9af8-b9b82b0bb7ed.png">

**Comment by DanielVF** [comment]
This is working in DApp2, so I'm closing this issue.
