### ISSUE TITLE
Redundant code - or missing something?

### ISSUE THREAD

**Issue by victorwiebe** [OriginProtocol/origin#1095]
https://github.com/OriginProtocol/origin-js/blob/10191926afa6c52a0468fa5e6532ecff4e5b08fe/contracts/contracts/identity/KeyHolderLibrary.sol#L139

Hi trying to understand this line. It seems weird to OR || these two together, as you only need to call it once in claim type 2, as any claim types <=2 will pass. Why call function twice?

In the keyhaspurpose function there is this so that passing in 2 will satisfy 1&2

if (purposes[i] <= _purpose) {
                isThere = true;
                break;

Sorry, just trying to point out redundant code here - or throw it out there in case I am misunderstanding something here. This is my favourite open source example of 725 735. Good work

**Comment by victorwiebe** [comment]
Hi, out of curiousity what are you moving towards? another solidity codebase? Any additional links on new origin projects is appreciated

**Comment by victorwiebe** [comment]
Will you guys use the erc725 contract from alliance ?

**Comment by franckc** [comment]
@victorwiebe we don't have immediate plans to deploy the new ERC 725 contract that is being developed by the alliance - but we'll continue to support the alliance and contribute to its work.
In the near-term, a big focus for Origin is user growth. As part of that, we are exploring solutions for identity that would still be decentralized but very low cost for the user.  We don't have yet anything to share but everything we do is open source so expect soon to see some updates from us on this front ! :)

**Comment by DanielVF** [comment]
@victorwiebe For now we've moved to using this simple contract for tracking identity profiles:

https://github.com/OriginProtocol/origin/blob/master/origin-contracts/contracts/identity/IdentityEvents.sol
