### ISSUE TITLE
Create an origin-common or similar package to decouple packages

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#1097]
We have a few packages with strange interdependencies. It'd be great if we could create a package with common code that other packages could import. Some examples:

- `origin-token-transfer` depends on `origin-faucet/lib/token` and `origin-faucet/lib/config`
- The `event-listener` and `origin-discovery` apollo server and joined in a single package due to shared models. It'd be better if they could be separate packages.
- Aside from interdependencies there is some straight duplication of code, e.g. `_contractHelper.js` exists in both `origin-contracts` and `origin-discovery`

I think there are a few more bits and pieces that would be better placed in a common package too. Some relevant discussion [here](https://github.com/OriginProtocol/origin/pull/1057#discussion_r241931928).

**Comment by cuongdo** [comment]
@tomlinton Thanks for filing this and providing context. I'm starting on this today.

**Comment by franckc** [comment]
Thanks @cuongdo ! Let's chat about discovery/listener. In particular would be good to discuss where we thing DB models should live.

**Comment by cuongdo** [comment]
After discussing with @franckc,  we were thinking of something like this:

```
origin-common/ - holds generally reusable code
    lib/_contractHelper.js  - from origin-contracts, etc.
    lib/token.js  - from origin-faucet/lib
    lib/config.js - from origin-faucet/lib
    lib/retries.js - from origin-js/utils
    {models,migrations}/*.js - maybe later, models from origin-discovery so that listener can become its own package
```

Additionally, we'd create the following `origin-token` structure:

```
origin-token/
    faucet/
    scripts/ - for contract migration script, referral rewards, etc.
    transfer/ - moved from origin-token-transfer
        client/
        server/
```

@tomlinton do you have any input? I'm not sure what's possible & reasonable with Lerna & npm.

**Comment by micahalcorn** [comment]
@tomlinton is this still relevant considering https://github.com/OriginProtocol/origin/issues/1624 ❔

**Comment by tomlinton** [comment]
Some of it is and some of it isn't. I'll raise a separate issue.
