### ISSUE TITLE
Editing listings with a picture

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#1099]
When editing a listing that has a preexisting picture and the user does not update the picture with a new one, continuing on listing details step fails with form errors (the step where user inputs title, description, picture etc)
<img width="609" alt="screenshot 2018-12-16 01 14 27" src="https://user-images.githubusercontent.com/579910/50048591-aef4ff00-00d0-11e9-938b-fcd097b81f9e.png">

**Comment by micahalcorn** [comment]
Resolved by #1135 ✅
