### ISSUE TITLE
Impossible Seller-Initiated Dispute Invitation

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1106]
We currently prompt the user to initiate a dispute if she starts to leave a poor rating (< 3️⃣⭐️). This isn't possible or relevant for the seller since the funds have already been released. The prompt should be conditioned based on the state of the offer.

**Comment by bleushark1988** [comment]
Hi. I would like to fix this issues. Can you detail for work?

**Comment by micahalcorn** [comment]
This is temporarily negated by https://github.com/OriginProtocol/origin/issues/1723 and hopefully will not resurface 🙏
