### ISSUE TITLE
Mobile Localization

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1111]
There are no immediate plans to add translations to the wallet app. I suspect that we'll want to handle this at some point in the relatively near future.

**Comment by micahalcorn** [comment]
Related: https://github.com/OriginProtocol/origin/issues/760 🌐

**Comment by micahalcorn** [comment]
According to @joshfraser, we are getting feedback from the community team that users are complaining that the mobile wallet hasn't been translated into Chinese or Korean. We may want to handle this using [FBT](https://github.com/facebookincubator/fbt) at the same time that the React Native code is rewritten to use GraphQL.

**Comment by tomlinton** [comment]
This is done, more languages will be added to mobile as the translations come in from Crowdin.
