### ISSUE TITLE
Create listing workflow - image upload issue

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/origin#1112]
As described by Alessandro in Discord:

>I'm experiencing some weird behaviours uploading listings.
It's related, I think, to the pictures.
I got the same error of few days ago that I thought was related to some weird character in the description.
I cleaned the text in Brakets for this new accommodation.
I inserted the title, description, price and pics.
Clicked to proceed and I got the error "Please fix errors before continuing."

>I tried to put only the text without uploading any image, tried to proceed and no error.
Then I went back, uploaded the images, tried to proceed and I got the error again.
I tried to delete the last pic, proceed and it went on.
So I went back, uploaded again the last pic and this time no error at all.

**Comment by Natasha08** [comment]
I have been unable to reproduce this for a brand new listing. I have DM'd  Alessandro
