### ISSUE TITLE
Trapped commission funds when seller finalizes an offer

### ISSUE THREAD

**Issue by cuongdo** [OriginProtocol/origin#1118]
To reproduce:

1. Seller creates listing with commission
2. Buyer makes offer
3. Seller accepts offer, which transfers commission to Marketplace contract
4. Allow finalization period to pass
5. Seller can now finalize, because the finalization period has passed. The contract [does not pay commission in this case by design](https://github.com/OriginProtocol/origin/blob/master/origin-contracts/contracts/marketplace/v00/Marketplace.sol#L313).
6. The commission funds are now trapped in the Marketplace contract.

One solution is to refund the listing deposit upon offer finalization by the seller.

Note: this is audit finding 8

**Comment by micahalcorn** [comment]
Resolved per @nick ✅
