### ISSUE TITLE
Change default language for SMS verification in India

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#1124]
The Twilio API guesses a language for SMS verification based on the country of the phone number. We got a report in Discord that for India it defaults to Hindi which a large part of the population cannot read so it'd be better if we default to English for India. We can explicitly set the language to English for Indian phone numbers.

<img width="702" alt="screen shot 2018-12-22 at 11 35 01 am" src="https://user-images.githubusercontent.com/489202/50366282-b4c17780-05dd-11e9-9bd3-63355507f928.png">

**Comment by BrunoBernardino** [comment]
I can work on this change. I did some small research and while https://en.wikipedia.org/wiki/India states there's no national language, the [Constitution of India](https://en.wikipedia.org/wiki/Constitution_of_India) states both Hindi and English as the main languages, so it should be a safe change.
