### ISSUE TITLE
Add field to listings to allow filtering by the marketplace that created the listing

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#1134]
This is something that will be needed fairly soon for the marketplace creator. There needs to be a field on listings to allow a white label marketplace to only display listings that were created through it. The most straightforward method would be something like `marketplaceHostname`. If you create a listing on `toms-market.origindapp.com` this hostname would be recorded in that field, and during the retrieval of listings on that marketplace the listings would be filtered by this field.

The disadvantage of this method is that the hostname of the marketplace can't be easily changed. Another option would be to tie it to the Ethereum address of the account that created the white label marketplace (this is currently recorded in the configs).

Anyone have any thoughts? From chatting with @franckc I think this might have been discussed already.

**Comment by franckc** [comment]
+1 for using the ETH address of the market place creator.

I'd also think the simplest is to record that address as a new field in the listing data stored in IPFS when the listing gets created/edited by the DApp. So that the event-listener can then read it from IPFS and index it.

**Comment by micahalcorn** [comment]
I'm told this is done. ✅
