### ISSUE TITLE
Wire up origin.js transaction stages to demo DApp

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/origin#114]
This includes anything that is on the listings, purchases, and transactions pages in UI

- [x] My Listings
- [x] Listing Purchases
- [x] Close Listing
- [x] My Purchases
- [x] Purchase Details
- [x] Mark Fulfilled
- [x] Mark Received
- [x] Collect Funds
- [x] My Sales

**Comment by DanielVF** [comment]
Yes, this has been my plan my upcoming week. PLENTY of work here.
