### ISSUE TITLE
Add badges to listings

### ISSUE THREAD

**Issue by nick** [OriginProtocol/origin#1148]
Add 'Featured', 'Sold' and 'Pending' badges to the listing search page:

<img width="160" src="https://user-images.githubusercontent.com/939/50655187-96983780-0f4c-11e9-813c-640c2917da13.png">

**Comment by micahalcorn** [comment]
Note that [the impending multi-unit PR](https://github.com/OriginProtocol/origin/pull/1102) will affect the conditional value of these badges.

**A rough summary**

- never more than one badge displayed
- single-unit listing with a current valid, not-yet-finalized offer: `PENDING`
- single-unit listing with a current finalized offer: `SOLD`
- multi-unit listing with no units available but with pending offer(s): `UNAVAILABLE`
- multi-unit listing with no units available and no pending offer(s): `SOLD OUT`

**Comment by micahalcorn** [comment]
I'm not sure if Nick's intended scope here was for what was has been known as the `ListingCard` component, but the same logic and badge applies to what has been known as the `ListingDetail` component.
