### ISSUE TITLE
Move From Private Keys To Mnemonics

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1149]
The first version of Origin Wallet will ship with the ability to export the private key for the automatically-generated wallet. This is a button that copies the key to the clipboard, which is a security issue. We should consider using a mnemonic to generate the account so that we can display this to the user. The seed words should be manually transcribed and kept offline as a backup. We will probably need to add a bit of user education to the UI, and it begs several questions about the ability to import an account, switch from one account to another, etc. We also need to design a screen for displaying the seed words.

Related: #1916

**Comment by tomlinton** [comment]
For private key based accounts we can't prompt users to backup their mnemonic when funds are detected. So the options are: a) prompt for a backup of private key, b) don't prompt. I think we should prompt for a backup but don't provide a copy to clipboard button so the user must manually write the private key in the same way that they would for a mnemonic.

The flow will be the same as https://app.zeplin.io/project/59fa2311bac7acbc8d953da9?seid=5c99591046989524fb7f0a1e except we just display the private key and don't require the user to enter it again after they back it up.

Also I notice the mocks have a "copy to clipboard" for the mnemonic, we do want to keep that given the security concern?

**Comment by micahalcorn** [comment]
In Origin Wallet, we allowed for copying the private key and then expired it from the clipboard after 30 seconds. I would vote for continuing with that pattern and certainly prompting when funds are detected. ㊙️

**Comment by tomlinton** [comment]
I think we should assume that anything that ends up in the clipboard can be read by any other app on the phone, so the length of time in the clipboard isn't the important bit here. If I was bad I'd just write an app to monitor clipboard changes and send anything that looks like a private key.

I don't see a strong reason to allow copying to clipboard. We want people writing this stuff down physically, not copying it into their Notes app. :grin:

**Comment by micahalcorn** [comment]
@crazybuster had a similar concern, but Coinbase Wallet and Trust Wallet both allow for copying. And @joshfraser wanted to optimize for people to actually back the things up. So we ended up adding the copy functionality with the expiration. ⚖️ I could go either way.

**Comment by tomlinton** [comment]
Ok, I just wanted to raise it. 👍 I'll build it with the copy to clipboard.

**Comment by joshfraser** [comment]
Understand and appreciate the security risks related to this. I'd hope that any evil app that is doing clipboard sniffing like that would get reported and taken out of the app store. As Micah said, our bigger concern is that people won't back their keys up at all if we make it too difficult for them. And writing down private keys by hand is quite painful and error-prone.

**Comment by tomlinton** [comment]
Closed #2291.
