### ISSUE TITLE
Origin Wallet on Android 🤖

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1150]
This is a placeholder for discussion of an Android version of Origin Wallet.

**Comment by joshfraser** [comment]
One of our 4 why's is around serving the unbanked & most of them will use Android devices. Even today, most of our traffic to our DApp is coming from Android. To put some hard numbers around this, 74% of the traffic to our DApp comes from mobile devices and 82% of that is from Android.

**Comment by lucadgtrip** [comment]
maybe specify here that it's temporarily only for iOS and use Metamask instead?
![screenshot 2019-02-11 at 15 36 13](https://user-images.githubusercontent.com/34341206/52566718-2ade9f80-2e13-11e9-8bd8-2c2c391a41ab.png)
A new user going to Add Listing may leave the Dapp and go into the Playstore rabbit hole otherwise.

**Comment by matthewliu** [comment]
Agree with Luca that at very minimum we should detect that it's Android and tell them that they need to use the Desktop experience unfortunately. We can even track the number of times that page hits as an indicator of how many Android "fails" we are getting.

**Comment by micahalcorn** [comment]
@matthewliu the QR code should not be showing on a mobile device. So the user who sees this should already be on a desktop. I assume that @lucadgtrip scanned this code and reached [this page](https://www.originprotocol.com/mobile). Do we prefer to put some Android disclaimer language in this modal (for a few weeks before implementing new user activation), or do we prefer to see who scans it and triggers an analytics event on the website using an Android device?

**Comment by ferdyboy69** [comment]
orgw:ab5607d7836f429e

**Comment by lucadgtrip** [comment]
yes sorry, didn't mention that I saw this using Brave on a Desktop.

**Comment by mikeshultz** [comment]
#1515 should probably wrap this up with a Play Store release to follow.

**Comment by micahalcorn** [comment]
Thanks @mikeshultz 👏
