### ISSUE TITLE
Add multi-unit identification support to GraphQL

### ISSUE THREAD

**Issue by BrunoBernardino** [OriginProtocol/origin#1162]
Separated from #1160 (more information there) and related to #1044 .

Basically, make sure we provide information in the graphql response/schema about the listing being multi-unit or not.

**Comment by BrunoBernardino** [comment]
@micahalcorn / @nick can you please confirm I didn't forget anything important (info, links, labels) in this issue?

**Comment by micahalcorn** [comment]
I think it's safe to say this has been handled, but feel free to reopen if necessary 🐇🐇
