### ISSUE TITLE
Add more statuses to Listing

### ISSUE THREAD

**Issue by BrunoBernardino** [OriginProtocol/origin#1163]
Separated from #1160 (more information there) and related to #1044 and #1045 .

Basically, make sure we add new statuses:

- `unavailable` (multi-unit, pending offer that uses existing items)
- `pending` (single unit, pending offer)
- `soldout` (multi-unit, no items)

Note `sold` and `active` already exist and should continue.

We can try to make sure we use these new statuses for the labels, as it should be a small footprint in the PR and will allow testing.

**Comment by BrunoBernardino** [comment]
@micahalcorn / @nick can you please confirm I didn't forget anything important (info, links, labels) in this issue?

**Comment by BrunoBernardino** [comment]
I thought about this and I think we should simplify and remove “unavailable” (we’d show “pending” in that situation instead). Thoughts @micah?

**Comment by BrunoBernardino** [comment]
I can work on this after #1177 gets merged (or I'll just branch from that). My vacations stop today so my cadency on contributions will diminish now. 😊

**Comment by micahalcorn** [comment]
I think it's safe to say this has been handled, but feel free to reopen if necessary 😐
