### ISSUE TITLE
Decrease ranking of pending boosted listings

### ISSUE THREAD

**Issue by cuongdo** [OriginProtocol/origin#1180]
On [staging](https://demo.staging.originprotocol.com/#/), a [new listing](https://demo.staging.originprotocol.com/#/listing/4-000-162) shows up on page 8 of the home page. Ahead of it are many pending, boosted single-unit listings. We may want to consider decreasing a listing's ranking of all units are pending so that newer, unboosted listings tend to rank higher.

**Comment by DanielVF** [comment]
Done in #2270
