### ISSUE TITLE
Exhausted Boost Not Changing Listing Card Position

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1186]
Here is a listing that seems to be in the same position on the listings grid both before and after the boost has run out.

PR that solves issue: https://github.com/OriginProtocol/origin/pull/1205
<img width="1440" alt="screen shot 2019-01-07 at 3 29 35 pm" src="https://user-images.githubusercontent.com/273937/50809204-13157800-12b7-11e9-8715-50c7148691ed.png">

<img width="1440" alt="screen shot 2019-01-07 at 3 32 17 pm" src="https://user-images.githubusercontent.com/273937/50809208-16106880-12b7-11e9-9a4d-7c3e78e42db5.png">

<img width="1440" alt="screen shot 2019-01-07 at 3 31 54 pm" src="https://user-images.githubusercontent.com/273937/50809211-17da2c00-12b7-11e9-85fa-272822fdccd6.png">

**Comment by sparrowDom** [comment]
resolved by: https://github.com/OriginProtocol/origin/pull/1205
