### ISSUE TITLE
Remove duplicate GA script tag

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin#1212]
We're currently including Google Analytics twice. We're loading it via both analytics.js and googletagmanager. We should remove one of these (probably the tag manager one).

**Comment by alexjspears** [comment]
@micahalcorn @joshfraser happy to look at this once prioritized

**Comment by DanielVF** [comment]
@alex-j-s You can start on this anytime, no need to wait!

**Comment by micahalcorn** [comment]
I think this is now invalid per https://github.com/OriginProtocol/origin/pull/1601#issuecomment-470406646 ✌️
