### ISSUE TITLE
Edit: latency issues / Create listing page / missing data

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#1216]
While editing a couple of listings on Mainnet
https://dapp.originprotocol.com/#/update/1-000-97
https://dapp.originprotocol.com/#/update/1-000-85

I add the following issues.

1) When I clicked on Edit Listing it took me to a page saying "What type of listing do you want to create?" which I did not expect to see.
2) I guessed and clicked on "Rent > Housing > Next"
3) I reached the Edit page, which is where I was excepting to land on step 1.
4) Once in Edit page ETH price was 0 and pictures missing, so I stopped: I wondered "what happens if I confirm? Will I lose the price and pics?"
![screenshot 2019-01-10 at 11 57 54](https://user-images.githubusercontent.com/34341206/50986395-684bc680-150f-11e9-8ec6-bf36478ca812.png)

5) I clicked "Back" , repeated "Rent > Housing > Next" and got back to Edit page: this time the price and pictures where there.

When I tried again a few minutes later the bug did not appear, so it may be a latency issue.
Since latency is probably to be expected we should hide the "What type of listing do you want to create?" page.

The Js console showed some errors too.
![screenshot 2019-01-10 at 16 28 19](https://user-images.githubusercontent.com/34341206/50986410-74378880-150f-11e9-9fcb-5cf0caab0a3b.png)

Environment:
Mainnet
Os x 10.14.2
Chrome

**Comment by micahalcorn** [comment]
I'm going to assume that this is fixed with DApp2. 🤞
