### ISSUE TITLE
Fractional Usage - changing from unit to fractional type makes form validation fail

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/origin#1218]
During the listing creation process, if you select a fractional usage listing type, then go back from the "details" step to the "select listing type" step and select a unit listing type, the form validation fails. We need to figure out why this happens and fix it.

**Comment by MuraraAllan** [comment]
@jordajm Are you working on that? I'm currently over creating-listing and can solve this together on my next PR.

**Comment by micahalcorn** [comment]
Resolved by #1319 ✅
