### ISSUE TITLE
Enable Messaging Button

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1220]
This button should be below the message from Origin Support instead of to the right of it

<img width="1440" alt="screen shot 2019-01-10 at 11 27 04 am" src="https://user-images.githubusercontent.com/273937/50991990-ce622a80-14ca-11e9-94c5-eac9fadbd9ac.png">

**Comment by micahalcorn** [comment]
I think the button should probably render in approximately the same place that a chat bubble would appear if you were to reply. ↘️

**Comment by New-Bee-Star** [comment]
Right

**Comment by tomlinton** [comment]
Solved by dapp2.
