### ISSUE TITLE
Auto-deploy docs on push

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin#1228]
It would be great if we could have a CI-ish system automatically build and deploy the docs when they are modified on master from a PR being merged.

In the new docs system, I have "deploy.sh" script that should handle installing dependencies, building the docs, and pushing them to the gh-pages branch.

All we should need is a recent copy of ruby (2.4+, 2.5+, 2.6+, whatever) and the "bundler" gem. (to get bundler, `gem install bundler`)

Then cd to origin-docs and run ./deploy.sh

The new docs haven't been merged yet - you can see the current version in the danielvf/newdocs branch.

**Comment by tomlinton** [comment]
Sounds good Daniel! This is what I meant when I suggested it in the chat at the engineering meeting. I'll set something up similar to our other deployment stuff where it triggers off changes in master.

**Comment by DanielVF** [comment]
Thanks. Yeah, I whooshed that one right over my head at the time.

FYI: The gh-pages branch is locked so that only certain people can commit to it. You may have to do something with that.
