### ISSUE TITLE
Edit profile does not always apply selected profile image

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#1245]
When editing my profile and selecting a profile picture, depending on which picture I select, it may or may not get applied (profile pic remains black in the profile edit modal).
- Works with picture HeadShot.jpg attached.
- Does NOT work with attached picture FranckProfile.jpg

This is reproducible on both staging and prod.

Steps to reproduce:
 - Go to https://dapp.originprotocol.com/#/profile
 - Click on the edit profile icon (little pen)
 - Click on the edit profile picture icon (little camera)
 - Select a profile picture
 - Crop modal shows up, click Continue
 => selected picture is not applied to the edit profile modal (it remains black).

HeadShot.jpg
![headshot](https://user-images.githubusercontent.com/945910/51133736-9caed380-17ea-11e9-964d-a5ef70dac547.jpg)

FranckProfile.jpg
![franck profile](https://user-images.githubusercontent.com/945910/51133753-a46e7800-17ea-11e9-9bc3-c3f23bbcbdc1.jpg)

**Comment by franckc** [comment]
@micahalcorn This is the issue I mentioned this morning regarding profile picture.

**Comment by MuraraAllan** [comment]
Maybe who work on that could also take a look into this : 

Steps to reproduce : 

- Go to https://dapp.originprotocol.com/#/profile
- Click on the edit profile icon (little pen)
- Click on the edit profile picture icon (little camera)
- Select a invalid file format as profile picture
- Crop modal shows up, click Continue

When invalid file format, error modal is empty
![screenshot from 2019-01-16 02-56-51](https://user-images.githubusercontent.com/8569238/51227217-71d39500-193a-11e9-8b49-6e5cb348dfde.png)


It seems to happen for entire profile picture when using really small images
- Go to https://dapp.originprotocol.com/#/profile
- Click on the edit profile icon (little pen)
- Click on the edit profile picture icon (little camera)
- Select ![20 2](https://user-images.githubusercontent.com/8569238/51227278-ad6e5f00-193a-11e9-98d6-381c4b19af87.jpg)  as profile image 
- Crop modal shows up, click Continue



![screenshot from 2019-01-16 03-01-51](https://user-images.githubusercontent.com/8569238/51227442-849a9980-193b-11e9-9927-1d4964da0d95.png)

Result : 

![screenshot from 2019-01-16 03-13-57](https://user-images.githubusercontent.com/8569238/51227743-d09a0e00-193c-11e9-952e-47a25348eb22.png)

**Comment by Natasha08** [comment]
@MuraraAllan what invalid format are you attempting to upload as a profile picture? Invalid formats should be disabled

**Comment by micahalcorn** [comment]
This seems to have been resolved. Thx DApp:two:!
