### ISSUE TITLE
Event-listener stops processing blocks

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#1260]
The event-listener has been observed to get stuck and stop processing blocks. The logs don't reveal anything, and since the process appears healthy to Kubernetes the container is not restarted. Deleting the pod and restarting it solved the issue and the event-listener continued processing. We should try to:

- Find out why the event-listener got stuck and address that
- Write a custom health check for the event-listener so that Kubernetes knows it has stopped processing and can restart the container

**Comment by micahalcorn** [comment]
Resolved by #1963 ✅
