### ISSUE TITLE
Token Growth Engine DApp

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#1278]
Implement user facing functionality of the token growth engine. UI specs can be found here: 
- https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c34963952509029984e5bcf
- https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c349638eddc504bd20b6b6c
- https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c34963bb7b2dabdd5509888
- https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c3496394f75bfbf05cabd90
- https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c349639414579beecfb1b04
- https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c349638dfe75bbe5bf3c840
- https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c349639eddc504bd20b6c0b
- https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c3e8b4f1e752a0ed5c13ad7
- https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c3e87fd01da695244b7f305
- https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c3349a0bae2c22086e0b579

The effort is broken down into the following milestones: 
- [x] **Milestone 1**: OGN wallet link, campaign view: accept terms, country not eligible, past campaign results
- [x] **Milestone 2**: Active campaign view: show campaign status, show campaign goals/rewards
- [x] **Milestone 2**: Implement invite friends functionality, track invites screen, send invites screen

**Comment by sparrowDom** [comment]
@franckc have created an issue with the work broken down into 3 milestones. Can you take a look if it makes sense to you?

**Comment by sparrowDom** [comment]
@franckc I would estimate 1 week per milestone.

**Comment by micahalcorn** [comment]
Can we check these boxes? ☑️

**Comment by sparrowDom** [comment]
Yup @micahalcorn thanks for bringing this up
