### ISSUE TITLE
Attestation Server Rewrite

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1303]
_From @tomlinton..._

Origin has some Python code ([origin-bridge](https://github.com/OriginProtocol/origin/tree/master/origin-bridge)) that is responsible for handling verification of accounts and attestations with third-party services. This is the last remaining Python code we have (other than our [website](https://github.com/OriginProtocol/origin-website)) and it is important for us to remove this and replace it with a JavaScript implementation to simplify our DevOps processes and so we have all of our packages written in a single language.

**Scope of Work**

Replace existing implementation of origin-bridge with a JavaScript implementation
Ensure that tests are written that are at least as extensive as the current Python implementation
Use the general structure from other Origin JavaScript packages with lint, test, and per-env commands for different environments

(Bonus): Implement some integration tests that are run as part of the Docker Compose integration tests on TravisCI

**Resources**

Tom created a branch with a [basic structure](https://github.com/OriginProtocol/origin/tree/tomlinton/js-bridge) and some utility methods and tests. Feel free to adjust as you see fit. Nick previously had some of [this code written in JavaScript](https://github.com/OriginProtocol/origin-playground/tree/master/issuer-services). Some of the logic may be useful. Integration tests are run by the origin-tests package, example available [here](https://github.com/OriginProtocol/origin/blob/tomlinton/js-bridge/origin-tests/test/1-create-listing.js). They are run on TravisCI and can be run locally with:  `docker-compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from origin-tests`

Thx guys 👊

**Comment by tomlinton** [comment]
Done #1577.
