### ISSUE TITLE
Add informational output for debugging

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1379]
As suggested by @wanderingstan, there should be some information output in the terminal when you run this package locally. For example, it should indicate the current package version, contract addresses, environment variables, etc. This will help us when someone runs into a problem that needs to be debugged in Discord or here.

**Comment by franckc** [comment]
Thanks for looking into this ! :)

Agreed we probably don't need to show the ABIs.
I like your idea of a whitelist of env variables rather than dumping everything.
Let's start with the list you proposed - I can't think of anything else yet...

**Comment by tomlinton** [comment]
Thanks @mikeshultz!
