### ISSUE TITLE
List of pinned packages

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#1388]
This issue is to maintain an ongoing list of npm packages that have been pinned to specific versions. Some of these issues may now be resolved but we'll need to go back and verify/upgrade the package. 

- terser 3.14.1 https://github.com/OriginProtocol/origin/pull/1384 - Dependency of webpack, broken release
-  web3 `1.0.0.beta.37` https://github.com/OriginProtocol/origin/pull/1347 - Unknown issue in `origin-dapp-creator-server`, didn't debug thoroughly following issue with upgrade to beta 38
- web3 `1.0.0.beta.34` pinned in most packages due to unresolved issue, also reports from @crazybuster that nothing above beta.34 will work in `origin-mobile`
- ~~ganache-core `2.2.0` in `origin-js`, tests fail with any version above this, possible due to async functionality being added to ganache, Issue https://github.com/OriginProtocol/origin/issues/1008~~

**Comment by mikeshultz** [comment]
@crazybuster Any more details on that `origin-mobile` issue?  Looks like `web3` at some point required `web3-bzz`, which requires `swarm-js`, which requires `child_process` which is breaking my build of `origin-mobile` at the moment, due to the node-native module dependency.

**Comment by mikeshultz** [comment]
This appears to be the web3 issue(or at least one of them) requiring beta 34.  https://github.com/ethereum/web3.js/issues/1802
