### ISSUE TITLE
Other Listings

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1390]
The public profile and listing detail should include a section displaying the user/seler's other listings. See the mockups [here](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c54d01707ca6e42b8552edc) and [here](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c54d01b1dfb92353b787fbd).

(Moved comment from @lskip11 to [here](https://github.com/OriginProtocol/origin/issues/965#issuecomment-462883784))

**Comment by lskip11** [comment]
I don't really understand what the idea or algorithm behind listing new items? It's not by date, or price or if it supposed to be random it's really not. I added 4 piece and all of them "randomly" shows on the 8 page next to each other! :( https://peerart.io/#/page/8

Also  I used to have 2 of my pieces placed on the first page but after I edit them (change the text and add new image) they went to the 2nd page :( not cool at all

**Comment by micahalcorn** [comment]
Thanks @lskip11 😕 I've added your response to our internal product feedback document, and I'm going to move your comment to a different issue that is more relevant.

**Comment by micahalcorn** [comment]
This has been done for the public profile but not for the listing detail page.

**Comment by micahalcorn** [comment]
Done long ago ☺️
