### ISSUE TITLE
Update DApp footer links

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin#1394]
We should update the "Visit our Website" link to say "Learn more about Origin" and add the following links to the footer of our marketplace DApp:

- Create Your Own Marketplace (https://www.originprotocol.com/creator). We can replace the "Visit our Github" link
- Legal links (These can be in a small font next to the copyright notice)
  - Acceptable Use Policy (https://www.originprotocol.com/aup). 
  - Terms (https://www.originprotocol.com/tos). 
  - Privacy (https://www.originprotocol.com/privacy). 

We should probably include these links on the whitelabeled versions of the DApp as well along with the language selector. There may be some reason I'm unaware of that these are currently hidden?

**Comment by lastgituser** [comment]
Would I have to translate these labels into all the languages necessary? In the origin-dapp/translations folder, there are many files with "footer.websiteLink: [TEXT]" with [TEXT] replaced with the translation. Would I have to keep the same variable names as well (ex: footer.websiteLink)?

**Comment by micahalcorn** [comment]
No @lastgituser 😅 You can just wrap the new strings using the `FormattedMessage` component from react-intl. It's not necessary to keep the same `id`s if the strings are changing. After you're done making changes to the component(s), `npm run translations` to generate new translation files.

**Comment by lastgituser** [comment]
@joshfraser @tomlinton I noticed an isWhiteLabel variable in the footer that prevents the labels from being displayed if it is true. Do you know why that variable is placed there? Thanks in advance.

**Comment by tomlinton** [comment]
@lastgituser it is for displaying/hiding certain links for third party marketplaces created using the [marketplace creator](https://creator.originprotocol.com).

**Comment by lastgituser** [comment]
Should I display the links in the white labeled version, or should I keep the logic as it is already?

**Comment by tomlinton** [comment]
I think it would be best to replace the "Visit our Website" text with "Learn more about Origin" and add the "Create Your Own Marketplace" link as @joshfraser mentioned. These can be displayed on white labeled marketplaces with the updated text. The legal links should also be added. Thanks @lastgituser!

**Comment by lastgituser** [comment]
Thanks @tomlinton. I replaced all the links with updated texts and added the legal links as mentioned. I was unsure what links I need to display in the white labeled version. Should I only reveal the "Learn more about Origin" and "Create Your Own Marketplace" links, or should I show all the links? Should I also reveal the language dropdown?

**Comment by tomlinton** [comment]
I think display everything is fine 👍

**Comment by lastgituser** [comment]
Thanks. I know I'm asking a lot of questions, but should I simply remove the "isWhiteLabel" variable completely if the display doesn't change with respect to the "isWhiteLabel" variable? If not, should I keep a comment showing where the "isWhiteLabel" check would have been in case we think of adding it back in? I hope I'm not bugging you too much.

**Comment by tomlinton** [comment]
Sure you can remove it completely from the footer component if it is no longer required.

**Comment by lastgituser** [comment]
Can I modify app.css to decrease the font size for the legal links to put them next to the copyright notice, or should I leave it alone?

**Comment by tomlinton** [comment]
Sure no problem.

**Comment by lastgituser** [comment]
Should I place the legal links to the left of the copyright notice or to the bottom? If I place them to the left of the copyright notice, the description will be much longer than the other elements. If that's fine, then I'd be more than happy to make the change.

**Comment by micahalcorn** [comment]
Appears to have been merged ✅
