### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by nick** [OriginProtocol/origin#1405]
Allow users to sign up for email and/or mobile notifications when there is activity on a specified listing or offer. Ideally this could be a service that can be deployed independently (eg to Heroku), though we can also have a centralized service provided by Origin.

**Comment by micahalcorn** [comment]
As @nick questioned in Discord, we need to determine which types we will or will not require or support going forward and where in the user activation flow they are introduced.

- Email
- Mobile Push
- Desktop Push
- SMS
- ?

**Comment by micahalcorn** [comment]
Changing this title to limit the scope for the first milestone 📧
