### ISSUE TITLE
Code quality and linting rules

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#1407]
We've got a lot of new code landing at the moment and I think we should look at our eslint rules and code quality guidelines for our packages.

### Eslint

We use eslint:recommended at the moment with a few extras, I'd like to add:

- camelcase - we have mixed casing in a few packages at the moment
- no-trailing-spaces - prevent trailing spaces at the end of lines
- no-whitespace-before-property - like it sounds

If anyone would like any other eslint rules or doesn't agree with these please comment. I hope to add these rules and patch up any minor errors. For those packages that have larger issues (i.e. too big for a single PR fix) I'll enable warnings and hopefully we can iteratively resolve these warnings.

### Prettier

@nick added a great pre commit hook with husky to run a lint before every push. It calls `lerna run lint` which will fail if linting doesnt pass. Of course this is dependent on the `lint` command for each package. I think we should standardise on the following commands for all packages:

```
    "lint": "eslint . && npm run prettier:check",
    "prettier": "prettier --write *.js \"src/**/*.js\"",
    "prettier:check": "prettier -c *.js \"src/**/*.js\"",
```

Prettier might not be perfect for everyone, but the important part is that it is opinionated and gives us consistency. I plan to slowly add prettier to each package during periods where people aren't doing work on those packages (due to the merge problems it might cause). @nick has already got it set up in most (all?) of the experimental packages that will come through in the rewrite.

### Commenting

We could improve our commenting, particularly for functions. If you touch a function that doesn't have a comment explaining what it does/parameters please add one. Some packages are particularly good (shoutout to `origin-discovery`).

It'd be nice to eventually be able to implement something like `eslint-plugin-jsdoc` to enforce this.

Please discuss if you have any objections/good ideas 👍

**Comment by micahalcorn** [comment]
[Here](https://github.com/OriginProtocol/origin/pull/335/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R136) are some that we had before in -dapp 📐

**Comment by tomlinton** [comment]
[Here](https://github.com/OriginProtocol/origin/blob/master/.eslintrc.js) is our current default eslint setup, with some overrides being applied in specific packages, e.g. origin-dapp has [extra configuration ](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/.eslintrc.js)for react.

**Comment by nick** [comment]
camelCase sounds good to me. The whitespace stuff should be handled automatically when we prettify the modules, but no harm in adding it in anyway I guess

**Comment by sparrowDom** [comment]
Prettier is probably also configurable? I don't know about you, but I would like it if it were not to correct the case where if statement has only 1 line of code in body and does not require parenthesis. The prettier "corrects" the following code: 
```
if (true)
  const a = 1  
```
to 
```
if (true) const a = 1  
```

while it leaves code like this alone: 
```
if (true) {
  const a = 1  
}
```

**Comment by tomlinton** [comment]
That is unfortunately not configurable, prettier made the decision not to make it an option. We could implement an eslint rule to force brackets though.

**Comment by sparrowDom** [comment]
Aha thanks. I would just leave it as it is if you ask me. It is not that highly important... at least to me.

**Comment by micahalcorn** [comment]
I think this is covered. I'll let @tomlinton reopen if he's not satisfied. 😅
