### ISSUE TITLE
Edit Listing gives a blank page

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#1438]
on https://trips.origindapp.com/#/update/1-000-378 (Creator)
Chrome os x 10.14.2
Eth: 0x36666e1fdC526f6df4638491F087e907A542BCdf

When I go to https://trips.origindapp.com/#/my-listings and click on Edit I get a blank page.

**Comment by lucadgtrip** [comment]
may be caused by https://github.com/OriginProtocol/origin/issues/1437 ?
The system tells me that messaging needs to be enable to create a listing, editing won't work neither?

**Comment by micahalcorn** [comment]
@lucadgtrip is this still an issue for you since we shipped the new version of the DApp? 🤞

**Comment by lucadgtrip** [comment]
all  works @micahalcorn !
