### ISSUE TITLE
User Feedback Collection

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1443]
As suggested by @coleman415, we should consider adding a user feedback call-to-action on our DApp(s). I suspect that we wouldn't want to user Intercom or any of the traditional, centralized tools for this. I noticed that Sentry (related #878) has a feature for prompting a user for feedback when an error is thrown. But I think we may not want to limit feedback solicitation to only instances when things are broken. We should be able to address actual bugs by following the Sentry reports.

Does anyone have any ideas for how we should deliver these user messages to our internal team? We could just build a simple form that sends an email to ourselves. There might be an existing React component that handles something like this? Or maybe we could relay messages through a server to a Discord channel? 🤔 Does it make sense to have this on our partner marketplaces?

cc @joshfraser @matthewliu @nick @tomlinton @DanielVF @sparrowDom @Natasha08 @franckc @cuongdo @wanderingstan

**Comment by joshfraser** [comment]
What about using Origin messaging as the communication mechanism?

We could have it pop up a prompt asking for feedback & when they respond it's shows up as a normal message for Origin support.

**Comment by micahalcorn** [comment]
@joshfraser I was afraid you would say that. I think we would really need to strengthen the reliability of OM first, and I don't know how soon that's going to happen. 😐

**Comment by joshfraser** [comment]
Ok, so our messaging system is so broken that not even we want to use it... 

The quickest & easiest option is to throw an email address or even a phone number up there. 

Need help? Email support@originprotocol.com or call this Twilio number.

**Comment by franckc** [comment]
If we just just want a feedback form and we decide to build it ourself, then it would be pretty straight forward to have the form post to a google cloud function that relays it to a Discord channel of our choice and/or writes it to a Google spreadsheet (I'd be happy to help with that).

If we want more advanced things such as customer chat support then I'd think we try out Intercom or equivalent for a bit.

**Comment by joshfraser** [comment]
I like the Google form w/ a webhook into Discord idea.

**Comment by micahalcorn** [comment]
The minimal version of this was done with the floating footer and nav link. ✅
