### ISSUE TITLE
Mobile DApp Browser OAuth Attestations

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1450]
As reported by @nick 👇 

![screen shot 2019-02-11 at 2 34 55 pm](https://user-images.githubusercontent.com/273937/52598415-7b9dca80-2e0a-11e9-9a93-11a7908efd7b.png)

**Comment by micahalcorn** [comment]
Hi @rohitverma007 🙂 Is this something that you're still working on?

**Comment by micahalcorn** [comment]
These bug reports may be related:

![gql0](https://user-images.githubusercontent.com/273937/55675126-e56aab80-5872-11e9-82d8-969720393f63.png)

![gql1](https://user-images.githubusercontent.com/273937/55675127-e8659c00-5872-11e9-8aa3-b2f033d4fdf3.JPG)

**Comment by nick** [comment]
Done

**Comment by micahalcorn** [comment]
@nick @shahthepro @tomlinton I can't get GitHub or Twitter to work in either Origin Marketplace or Coinbase Wallet. I just get a white screen that Coinbase Wallet reveals to be `https://bridge.staging.originprotocol.com/redirects/twitter/?oauth_token=...&oauth_verifier=...`. Are we still of the belief that these should work on mobile?

**Comment by shahthepro** [comment]
@micahalcorn That twitter issue is same as #2426. Basically session was not being persisted and for some reasons, twitter doesn't return `state` parameter in the callback URL. That should be fixed once #2449 gets merged.

What issues are you facing with GitHub?

**Comment by micahalcorn** [comment]
I have basically the same experience with the white screen living at `https://bridge.staging.originprotocol.com/redirects/github/?code=...`.

I'm just now testing on desktop and I'm getting "Invalid Attestation" there (similar to #2426).

**Comment by shahthepro** [comment]
> I have basically the same experience with the white screen living at `https://bridge.staging.originprotocol.com/redirects/github/?code=...`

There should be a `state` parameter in callback URL. I'll check why is it missing.

> I'm just now testing on desktop and I'm getting "Invalid Attestation" there (similar to #2426).

For the last 4 attestations, I somehow missed to commit my changes on `attestations_1.0.0.json` schema. Have sorted that out in #2449
