### ISSUE TITLE
Make Listing Creation Modular for multiple listing types

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#1469]
Currently, the listing creation process supports Unit and Fractional listings by means of a nest of conditionals and `if` statements. On DApp1 We've seen how this yields spaghetti code that only gets worse with more listing types.   (e.g. [here](https://github.com/OriginProtocol/origin/blob/master/experimental/origin-dapp2/src/pages/create-listing/Step2.js#L65), [here](https://github.com/OriginProtocol/origin/blob/master/experimental/origin-dapp2/src/pages/create-listing/CreateListing.js#L55-L57), or [here](https://github.com/OriginProtocol/origin/blob/master/experimental/origin-dapp2/src/pages/create-listing/Step2.js#L163-L173))

The plan is to move to a modular system, where each listing type is free to define it's own listing creation components.

## Issues
- [x] Custom prices and availability for Fractional calendar not getting saved (or not always getting saved) -- on `Details.js`, the added custom fields arn't getting added with `fields: Object.keys(props.listing)`, presumably because the `setState()` hasn't finished adding the new fields by then..
- [x] No boost on Announcements, right? (check with Nick)
- [ ] Minor js and css changes across Details.js listing types..double check
- [x] Handle **edit** mode
- [ ] Set `step` in query string when navigating around creation flow
- [x] Remove `farts`
- [ ] Correct chaining of `onChange()` from [Details]-->[Announcementlistings]-->CreateListing ? 
- [x] Get feedback from aure on creation progress bar. 
- [x] See about removing .. from `import Price from '../../../../components/___'`
- [ ] `onNext()` seems to break react pattern. Ask about it. 
- [ ] Can we get the listing-specific knowledge out of `listing/Edit.js` and into the related listign-type files?

**Comment by micahalcorn** [comment]
Should any of these be moved to a separate issue @wanderingstan? Or can this be closed? It looks like the meat of this has been resolved.

**Comment by wanderingstan** [comment]
Completed in https://github.com/OriginProtocol/origin/pull/1648 
Thanks @micahalcorn !
