### ISSUE TITLE
Creator: There was an error publishing your configuration.

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#1483]
On creating a new marketplace today I got to the last step and got:

![screenshot 2019-02-16 at 18 33 53](https://user-images.githubusercontent.com/34341206/52902460-a1b3d800-3219-11e9-88ea-019db4b21309.png)
this is the console:
![screenshot 2019-02-16 at 18 34 03](https://user-images.githubusercontent.com/34341206/52902470-a6788c00-3219-11e9-9633-249b89644ee3.png)

notes:
- chrome on mac
- metamask was connected
- metamask asked for signature and I signed
- theme: green with Navbar background edited to Black
- language: italian
- I checked "Only use listings from my marketplace"
so, all seemed fine until the last step.
Clicking on Retry did not help, nothing happens

**Comment by tomlinton** [comment]
Hi Luca, thanks for the report, what was the subdomain you used?

**Comment by lucadgtrip** [comment]
marketplace.origindapp.com

**Comment by tomlinton** [comment]
This should be resolved by #1490, let me know if you have any further problems @lucadgtrip!

**Comment by lucadgtrip** [comment]
works thanks!
