### ISSUE TITLE
Testing Strategy For DApp

### ISSUE THREAD

**Issue by digidigo** [OriginProtocol/origin#149]
At some point in the future, when development on demo-dapp slows down, it may serve the project to have a testing strategy.  

The strategy would include:

- Specific tools (e.g. jest and enzyme ) 
- Guidance for contributors as to what should be tested
- Tests that serve as good practice toward the desired approach
- Goals around coverage 

Other than helping to avoid errors in the app a few other benefits could include:

- that is would allow an easy way for new contributors to add some value ( Go write a test! )
- it can allow people to read through the tests to understand desired behavior 
- it can give confidence to new developers that they didn't break something

**Comment by inkredabull** [comment]
~3 weeks ago, upon tackling https://github.com/OriginProtocol/demo-dapp/issues/36 and realizing there weren't tests, I tried to introduce a TDD paradigm [leveraging Jest and Enzyme.](https://github.com/inkredabull/demo-dapp/blob/f2226868dacca38ac9231fb88d08edc350c7fbdf/src/components/__tests__/listing-card-prices_test.js)  Over the following weekend however, the underlying demo-dapp infrastructure changed and when I tried to rebase, ran into [dependency issues.](https://github.com/OriginProtocol/demo-dapp/pull/130#issuecomment-386159756)

**Comment by nick** [comment]
Going with Puppeteer for this
