### ISSUE TITLE
Settle on a local storage solution

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#153]
We've talked on a few occasions about using local storage for user preferences, the unpublished attestation results, etc. I have used [Store.js](https://github.com/marcuswestin/store.js/) before, but I think @nick mentioned that there is another good solution that integrates efficiently with Redux. Let's figure out what we should use.

**Comment by tomlinton** [comment]
Looks resolved by dapp2 which has a custom store.
