### ISSUE TITLE
DApp2 - Announcements / Free Stuff listing requires a non-zero price

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin#1563]
Announcements / Free Stuff listing requires a non-zero price in DApp2.

<img width="506" alt="screen shot 2019-02-27 at 9 43 24 am" src="https://user-images.githubusercontent.com/837/53498350-2c939e80-3a74-11e9-87ea-2c208db7c7da.png">

**Comment by micahalcorn** [comment]
Fixed by DApp:two:, I believe
