### ISSUE TITLE
Logo Alignment on Android

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1594]
In Origin Wallet, the logo at the top of the primary navigation stack should be centered instead of left-aligned.

![android](https://user-images.githubusercontent.com/273937/53768951-37449e00-3e8f-11e9-957d-86f4e8acb142.jpg)

**Comment by micahalcorn** [comment]
The logo is no longer relevant to the first screen, but the Wallet and Settings screens still need to have their header text's alignment repaired.

**Comment by tomlinton** [comment]
Not relevant anymore with new mobile.
