### ISSUE TITLE
Monorepo directory structure

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#1624]
Following on from a bit of a discussion we had in Discord:

Monorepos like react and babel typically put all their packages in a `packages/` dir. This makes management via lerna easy because you can just define your packages as `packages/**` in `lerna.json` and it makes things look nice.

Our setup is a little tricky because we have both packages we want to publish to npm and packages we don't, so it might makes sense to have directories other than `packages/`.

We also may want to remove the `origin-` prefixes from all the package names although I noticed react and babel keep them.

@nick came up with a proposal [here](https://gist.github.com/nick/bf35abc1ef5826f63ed3030e93b652a2) with separate directories for `backend` (stuff we run), `packages` (stuff that gets published to npm) and `dapps`. [Here](https://gist.github.com/tomlinton/43a0ff2328001bf8af8e6299e1758b11) is what it looks like without the prefixes and a few tweaks. [Here](https://gist.github.com/tomlinton/639680fa7be56b81e31c335d9039846d) is another variant where the root names all get prefixed with `packages-` to make it clear that everything in those directories is a js package.

**Comment by nick** [comment]
I prefer without the `packages-` prefix. I like calling the main dapp `marketplace`.

So the root and sub-dirs would look something [like this](https://gist.github.com/nick/3bd2efb828616edbcd88cf41361e4de9)

**Comment by nick** [comment]
Could we combine `deployment` and `development` into `devops`?

**Comment by tomlinton** [comment]
Looks nice, and yep we can do that.

**Comment by nick** [comment]
Pasting the proposal here so it's easy to see:

```
dapps
devops
docs
infra
mobile
packages
scripts
CONTRIBUTING.md
DEVELOPMENT.md
Dockerfile
LICENSE
README.md
TESTING.md
crowdin.yml
docker-compose.test.yml
docker-compose.yml
lerna.json
package.json


dapps
  admin
  graphql-simple-demo
  marketplace

infra
  bridge
  cron
  dapp-creator-client
  dapp-creator-server
  discovery
  faucet
  growth
  identity
  ipfs-proxy
  linking
  messaging
  notifications
  tests
  token-transfer
  token-transfer-client
  token-transfer-server

packages
  contracts
  eventsource
  graphql
  ipfs
  linker-client
  messaging-client
  origin-js
  services
  token
  validator
```

**Comment by franckc** [comment]
How about we discuss this during eng weekly tomorrow if time permits ? I added it to the agenda.

**Comment by franckc** [comment]
haha. @tomlinton already added it to the agenda. I'm always a step behind...
