### ISSUE TITLE
Native Mobile Marketplace

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1654]
Origin Wallet was intended as an alternative to MetaMask for [the majority of] users who are unfamiliar with DApp browsers and a browser extension as a wallet. User feedback has revealed that the standalone wallet concept presents too much confusion around linking, the primary key for the account, etc. This issue tracks the discussion of a native, end-to-end mobile marketplace application. Matt has shared a WIP document and we have started exploring designs around listing creation and purchasing. Some engineering/business decisions still need to be made involving key management, onboarding, fiat onramp, etc.

**Note**: for the foreseeable future, we will continue to support Origin Wallet and our desktop-first DApp as they are known today.

**Comment by micahalcorn** [comment]
Update: the near-term plan is to shift Origin Wallet to be primarily a marketplace application, but implemented as a webview containing our current browser-based DApp. We will no longer support linking to an external browser, be it on the same device or not.

**Comment by tomlinton** [comment]
Closed by #1917 #1918.
