### ISSUE TITLE
Withdrawn Listing Does Not Preclude Offers

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1656]
Withdrawing a listing seems to remove it from search results but not prevent a buyer from making an offer. I understand that offers are not validated against listings at the contract level, but we should probably prevent access to the listings in the DApp and/or invalidate offers that are made for them.

See https://dapp.staging.originprotocol.com/#/purchases/4-000-302-0 as a reproduction of a report of the issue.

**Comment by micahalcorn** [comment]
Bumping this per @AustinVirts who is seeing it IRL 😬

Supposedly, these offers all came in for listings that had already been withdrawn.

https://dapp.originprotocol.com/#/purchases/1-000-1098-6 (rejected)
https://dapp.originprotocol.com/#/purchases/1-000-741-11 (accepted)
https://dapp.originprotocol.com/#/purchases/1-000-740-7 (pending)

**Comment by micahalcorn** [comment]
A related question for @nick: According to Yu Pan, offers for invalid listings can be accepted but then won't be able to be finalized. Is that true, and, if so, can they be arbitrated or are they stuck?

**Comment by nick** [comment]
We can arbitrate from the admin page, yea
