### ISSUE TITLE
TIFF Image Support (or not)

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1659]
Listing creation currently fails silently if a seller tries to upload a photo that has a .tiff file type.

```
Uncaught TypeError: t.toBlob is not a function
    at HTMLImageElement.Pu.orientation (app.87c3102a.js:382)
    at Function.a.onerror (app.87c3102a.js:62)
    at HTMLImageElement.i.onerror (app.87c3102a.js:62)
```

I'm not sure that we necessarily need to support them, but we should at least show an appropriate error. [Here's one for testing](https://drive.google.com/open?id=1Ns-x7sUZS2B4j-u-jKHVd5kbJrGce6iD). 💍 For what it's worth, [GitHub supports a lot of file types, but not this one](https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests).

**Comment by tomlinton** [comment]
I haven't checked but this is most likely because `origin-ipfs-proxy` doesn't have TIFF support. So we can add it there if we want to support it, or remove the option from the DApp if we don't.

**Comment by micahalcorn** [comment]
I think the current decision is to not support them. https://github.com/OriginProtocol/origin/commit/b6674f55a802b9f03983f8d679f056ea64c1696f#diff-8696b81bc031bb686df9a17162ff66b9R9
