### ISSUE TITLE
Featured listing badge does not always show on browse and listing details page

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#1674]
For some users (me included), the featured badge does not show on the browse and listing details page for some listings (see screenshot).

@nick thinks it could be because DApp2 still fetches hidden and featured list from github even when discovery is enabled.

![Screen Shot 2019-03-12 at 10 17 03 AM](https://user-images.githubusercontent.com/945910/54221517-e1847d00-44b0-11e9-9882-49de12b3eaac.png)

**Comment by AustinVirts** [comment]
Besides what was mentioned above, two items that I have taken off of the featured list are still showing up as featured on the Origin Store.

https://store.origindapp.com/#/listing/1-000-277

https://store.origindapp.com/#/listing/1-000-276

Also, new featured items are not showing up.
