### ISSUE TITLE
Linking incompatible with created marketplaces

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#1690]
The `origin-linking` package uses a DAPP_URL via an environment variable that is directed to `dapp.originprotocol.com` which makes the mobile wallet incompatible with created marketplaces. We need to figure out a way for it to work with other marketplace URLs if we intend to support created marketplaces.

**Comment by micahalcorn** [comment]
This issue should only apply to opening the DApp from the Wallet. Signing transactions should not be affected.

**Comment by micahalcorn** [comment]
Linking will no longer be supported 💀
