### ISSUE TITLE
Beta Banner Expansion

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1704]
On small screens, the Origin Beta banner should be expandable to reveal the disclaimer as shown [here](https://zpl.io/bJZ7An9).

* Note that the copy should remain as-is in the code and not be changed to reflect what is in the mockup.

**Comment by joshfraser** [comment]
The latest plan is actually to replace this with the blue TGE banner.

Once we make that shift, we'll add a beta badge to the logo and move the warnings to the footer.
