### ISSUE TITLE
Listing Image Gallery

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1727]
The following changes should be made to the image viewing experience on the listing detail page:

- [ ] Thumbnails under the main image (shown [here](https://zpl.io/bJ7WX1r))
- [ ] Overflowing thumbnails with horizontal scroll

**Comment by ldu2** [comment]
Hi, I just submitted a pull request, regarding this issue. You can check it out [here](https://github.com/OriginProtocol/origin/pull/2151). Let me know if anything.

**Comment by micahalcorn** [comment]
Resolved by #2151 ✅
