### ISSUE TITLE
Conditioned Profile Publication

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1729]
The publish profile button should be disabled if the provisional data is no different from what is already published. Currently, a user can publish an empty identity without adding any information.

**Comment by micahalcorn** [comment]
This caused quite a bit of confusion today during our UX interviews for Origin Rewards.

**Comment by micahalcorn** [comment]
Resolved by #2002 🤞

**Comment by sparrowDom** [comment]
thanks @micahalcorn for keeping things clean
