### ISSUE TITLE
Swap Indication

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1765]
The listing detail page should indicate that a swap is necessary and have different button copy prior to initiating the currency swap. It looks like it might have ended up being slightly buried in the mocks [here](https://zpl.io/bWqgR4p).

**Comment by micahalcorn** [comment]
Bumping this after user research sessions 😩

**Comment by micahalcorn** [comment]
Here is a version of the design without the modal in the way: https://zpl.io/2j5lMQq

This would help alleviate some user confusion.

**Comment by nick** [comment]
Can be tested here:

https://originprotocol.github.io/test-builds/nick/rinkeby.html#/listing/4-000-387

**Comment by micahalcorn** [comment]
Resolved by #2025 ✅
