### ISSUE TITLE
UI improvement for when a listing has lots of images

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin#1779]
When a listing has lots of images (ex. https://dapp.tripscommunity.com/#/listing/1-000-540) the border around the main image gets pushed down. Ideally, the tray with the image thumbnails would be the same size as the main image and would allow you to scroll through the thumbnails.

<img width="865" alt="Screen Shot 2019-03-21 at 6 21 54 PM" src="https://user-images.githubusercontent.com/982234/54794756-59b41680-4c06-11e9-8244-814ee0dad9e4.png">

**Comment by micahalcorn** [comment]
Preferably just implement https://github.com/OriginProtocol/origin/issues/1727 🙏

**Comment by ldu2** [comment]
Since this is resolved in #1727, I am gonna close this issue.
