### ISSUE TITLE
Decouple profile picture from identity json blob

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#1795]
Currently the user's profile picture gets saved as binary data within the JSON of the identity.
It would be better to save the profile picture as a separate blob in IPFS and have the identity JSON referencing the URL of the profile. In particular there are a few use cases that are emerging where having a separate profile URL would be useful:
 - including the profile picture in emails
 - generating custom images including the profile picture
Ideally we would have the back-end storing the profile picture URL in the identity DB table.

Fixing this involves the following:
 - On the DApp profile page: when the user publishes their identity, have the DApp first save the profile picture in IPFS and get the URL for it, then use that URL in the identity JSON.
 - In the event listener, extract the picture URL from the identity, save it in the identity table. 
 - Update the IPFS pinner to pin both the picture and the identity

For legacy accounts, we could write a script to backfill the data. It would:
 - scan all identities from the blockchain
 - read the identity JSON and extract the profile binary data
 - save the profile picture in IPFS
 - update the identity table with the profile URL

**Comment by franckc** [comment]
CC @DanielVF since we were chatting about this today...

**Comment by DanielVF** [comment]
In theory, given a string of bytes we can theoretically convert to the matching IFPS hash. This means that we can transparently transform old identities and return a single format from graphQL as long as the images are already stored separately.

Given this, it seems like the logical place to start is the backfill script.

**Comment by DanielVF** [comment]
Here's some (possibly over generic) code to transform a buffer into its corresponding IPFS multihash.

https://github.com/alanshaw/ipfs-only-hash/blob/master/index.js

**Comment by DanielVF** [comment]
From we will need to:

- [ ] Update the pinning service. (I figured we'd wait until after we've seen that GraphQL and the listener properly are passing on the avatarURL
- [ ] Modify the DAPP to display avatars using the new style avatar URL
- [ ] Remove storing the avatars the old way, and update the admin dapp

**Comment by franckc** [comment]
Great progress @DanielVF ! In addition to the steps above, I think it would be handy to store in the identity table in the DB the IPF hash of the avatar. It would allow our back-end services (immediate use case being the notification service that sends email) to very quickly access this data as opposed to having to make a call to the blockchain to fetch it. Perhaps we could add a column "profile_hash" to the identity table ?

**Comment by DanielVF** [comment]
Once the event listener re-runs, the avatarUrl for every identity should be in the identity JSON, just like the firstName and lastName. I think we should be good without adding another field.

**Comment by franckc** [comment]
Unfortunately, currently the JSON is *not* stored in the identity DB table :(
https://github.com/OriginProtocol/origin/blob/master/infra/discovery/src/listener/handler_identity.js#L209

We could either:
 - store the JSON blob in the identity,data column. It could be lot of data to store in the for blobs that have a profile picture embedded. We could potentially replace the picture data with the IPFS hash before storing in the DB
 - store the picture hash as a separate identity.profile_hash column

**Comment by DanielVF** [comment]
I still have to remove the old way saving of avatars. Should do that next week.
