### ISSUE TITLE
Warn Brave users to put their shields down

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin#1816]
We seem to have a fairly high number of users using the [Brave browser](https://www.brave.com/) and they [often run into problems](https://github.com/OriginProtocol/origin/issues/1590) using our DApp. Unfortunately, our DApp does not work unless they disable their shields. Ideally, we would detect this browser and warn users to put their shields down instead of them thinking out DApp is broken.

**Comment by micahalcorn** [comment]
It would be nice to know what all we can detect, such as what all is [en/dis]abled; Javascript, cookies, etc. For now, we could just detect that Brave is being used and throw up a modal warning.

See also https://github.com/OriginProtocol/origin/issues/1961 😕

**Comment by AndreasB115** [comment]
@micahalcorn 
@joshfraser 
I just built on my local.
But I'm seeing any warning or issue.
I attached the screenshot.
![Screenshot 2019-08-12 at 21 50 15](https://user-images.githubusercontent.com/9155680/62893718-88649200-bd4b-11e9-84c8-f87bc5dcbdfe.png)
How can I get the issue on my side?

**Comment by AndreasB115** [comment]
@joshfraser 

![Screenshot 2019-08-12 at 22 13 26](https://user-images.githubusercontent.com/9155680/62895124-7e905e00-bd4e-11e9-9377-3b36fb11d4d4.png)

Is it warning you said?

**Comment by AndreasB115** [comment]
@franckc 
Can you see this?

**Comment by micahalcorn** [comment]
@AndreasB115 the issue is that we've received a lot of reports of some of our features not working in Brave. This could be some consequence of having shields up, cookies disabled, etc. I think our tentative plan was to just warn all Brave users that their shields should be down in order for the DApp to work. But that may not be sufficient. I think the first step is to figure out what all we can detect and then decide which warnings to display. 😐

**Comment by AndreasB115** [comment]
https://user-images.githubusercontent.com/9155680/62895124-7e905e00-bd4e-11e9-9377-3b36fb11d4d4.png

@micahalcorn It is what I'm seeing.
I think it is working.
Many users can't see like this?

**Comment by micahalcorn** [comment]
@AndreasB115 it's not a matter of the home page failing to load. There are some features that won't work correctly. Off the top of my head, I think there will be some problems with profile attestations and messaging. 🙁 I'm not sure what else.

**Comment by AndreasB115** [comment]
@micahalcorn 
So if brave browser is detected, alert "put their shields down" will be shown.
Is this task of this ticket?

**Comment by micahalcorn** [comment]
Something like that, but we should probably also detect the ability to set cookies. 🍪

**Comment by AndreasB115** [comment]
We should clarify the purpose of set cookies.
In general, using cookie is really basic and common way.
This website is not using cookie?

**Comment by AndreasB115** [comment]
@micahalcorn Am I right?

**Comment by franckc** [comment]
@AndreasB115 Not exactly. I think to start with what we'd like is as follow:
- Detect if it's Brave Browser. If it is, show a modal to warn user they should put their shields down
- Detect if cookies are disabled. If it is, show a modal to warn user they should enable cookies.
Makes sense ?
