### ISSUE TITLE
Profile Publish Confirmation

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1818]
[The "ConfirmPublish" modal](https://github.com/OriginProtocol/origin/blob/4afe18b34d18b1dad5f400a796b362c56e14316a/origin-dapp/src/pages/profile/ConfirmPublish.js) with disclaimers and explanation about what would be visible to the public seems to no longer exist. We will have a new version designed in a day or two and then want to bring this back quickly.

**Comment by micahalcorn** [comment]
@joshfraser @matthewliu I'm a bit unclear on the path forward here. In our [original mockups](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5a9f0d6053a9a2685452d94a) from the early days of identity, we were not saying anything to the user about what would and would not be publicly visible until the "Publish" button was clicked. That resulted in a clear need for the disclaimer modal that this issue references.

In our DApp:two: world, we are warning the user prior to each verification.

![publish](https://user-images.githubusercontent.com/273937/55268923-c012e780-524b-11e9-9ba8-d21c4a0068e1.png)

Thinking about a possible near-term future with "no gas" and automatic blockchain publication under the hood following each verification, there would not be an opportunity for the modal that this issue references because the user won't click a "publish" button. However, this is only true for people using our mobile app (or a desktop that includes managed keys 😉). If we are contiuing to support desktop with MetaMask, the user will still need to click a publish button. But I'm not sure that it's necessary to add an extra warning modal only for MetaMask users if we're not including it for mobile app users.

**Comment by joshfraser** [comment]
Even if we streamline the signing process with meta-transactions, it's still important that we capture clear intent from our users and they know what they're publishing to the Blockchain.

**Comment by matthewliu** [comment]
Agree with @joshfraser that we need to be super clear about this. We should be able to do it in a simplified way that doesn't require a separate Publish step though (presuming meta-txns work). People are generally quite confused about that concept.

**Comment by micahalcorn** [comment]
No longer relevant 💀
