### ISSUE TITLE
Onboarding flow doesn't detect an existing balance

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin#1829]
When you get to the end of the onboarding flow (/#/onboard/finished) we're not smart enough to detect if you've already completed all of the available attestations & have an existing balance on your wallet.

<img width="824" alt="Screen Shot 2019-03-29 at 5 36 22 PM" src="https://user-images.githubusercontent.com/982234/55268680-4ed23500-5249-11e9-86bd-36e283db031e.png">

**Comment by norbertdragan** [comment]
Sure, I'll take a look at it!

**Comment by norbertdragan** [comment]
I looked into it and noticed that the two tables were removed in #2308. Currently we display only this:

<img src="https://d2rsw2kbemic8w.cloudfront.net/items/1x2A0t1H3U3J0R3o1l05/Image%202019-08-28%20at%2012.06.15%20PM.png" style="display: block;height: auto;width: 100%;"/>

**Comment by shahthepro** [comment]
@norbertdragan Thanks for looking into this. Yes, The design of that page was updated with DApp3 and User activation v3. So I guess this issue is no longer valid. Sorry I should have closed this earlier, somehow missed it.

cc @micahalcorn I'm closing this now. Let me know if this is still valid.
