### ISSUE TITLE
"Sold" w/For Rent Listings

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1836]
When a "seller" views a For Rent listing detail page, there is a "Sold" count, which doesn't make sense because the user is not offering something For Sale. Should we just use the word "Completed" everywhere, condition the word based on the type of listing, or should these counts even be displayed for fractional listings?

**Comment by nick** [comment]
Is there an example of such a listing? Looking at the code which already has logic for this...

**Comment by micahalcorn** [comment]
@nick https://dapp.staging.originprotocol.com/#/listing/4-000-383 (Account 1️⃣)

**Comment by nick** [comment]
This listing was created before we introduced the new Fractional type.

Fractional listings show the following to the seller, so closing this

<img src="https://user-images.githubusercontent.com/939/57552930-aa084480-732a-11e9-94b3-4e1464335f8b.png" width="300" />
