### ISSUE TITLE
Fiat-Equivalent Default Price Editing

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1842]
Once the stablecoin branch is deployed, sellers will be encouraged to edit their listing prices so that they are pegged to a fiat value instead of an ETH value. Currently during editing, a listing's price field will be populated with the existing numerical value as it was stated in ETH, but it will be persisted as a fiat price if the seller updates the listing. This is problematic because a naive editor may have no intention of changing her listing's price from 1 ETH (~$140) to 1 USD ($1), but that would happen if the price field's value is left unchanged and something else on the form is intentionally updated. As discussed during the 3/20 engineering meeting, this price field should be populated with the relevant fiat-equivalent price at the time of editing.

**Comment by nick** [comment]
Done and pushed to branch
