### ISSUE TITLE
Can not create a listing of type Announcements

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#1843]
To reproduce: 
- just go on create a listing and select any of the announcement types
- try to finalise listing creation and at Metamask step the error above occurs 

<img width="1680" alt="Screenshot 2019-04-01 10 14 57" src="https://user-images.githubusercontent.com/579910/55313895-3b9db000-5469-11e9-94f4-a0832aad1e49.png">

**Comment by sparrowDom** [comment]
@wanderingstan not sure I have assigned you correctly. Was assuming that this could be a schema issue 🤷‍♂️

**Comment by shahthepro** [comment]
@sparrowDom This was not a schema issue. In the DApp, it was coded to throw error if the listing type is *not* Unit, Fractional or Fractional Hourly. 

Have submitted a PR to fix this.

**Comment by sparrowDom** [comment]
Aha I see thanks @shahthepro for clarifying this 👍
