### ISSUE TITLE
Email Attestation modal does nothing when an invalid email address is entered

### ISSUE THREAD

**Issue by shahthepro** [OriginProtocol/origin#1846]
In the Email Attestation modal, if you enter an invalid email address like "test@localhost", it should validate the address and show that the email is invalid. But nothing happens on clicking "Continue".

**Comment by micahalcorn** [comment]
Interesting @shahthepro 😕 What kind of browser are you using? I think we use an input type email, so in my experience there is native browser validation that prevents submitting an invalid address.

**Comment by micahalcorn** [comment]
Related: https://github.com/OriginProtocol/origin/issues/1834

**Comment by shahthepro** [comment]
@micahalcorn I'm using Firefox v66.0.2 (64-bit, on Ubuntu 18.04.2). Native browser validation works. But it doesn't check for domain extension. Those are optional. So, "test@localhost" is valid.
