### ISSUE TITLE
Discovery server support for Stablecoins

### ISSUE THREAD

**Issue by nick** [OriginProtocol/origin#1856]
Discovery server should perceive stablecoin listings as valid and return them in results set

Depends on #1850

**Comment by franckc** [comment]
Hmm.. Good catch @nick . I assume this is a blocker for the stablecoins launch ?

**Comment by nick** [comment]
Yea since we rely on the discovery server for returning listing IDs for the main search page

**Comment by micahalcorn** [comment]
Resolved by https://github.com/OriginProtocol/origin/pull/1850 ✅
