### ISSUE TITLE
Link To Settings w/Currency Config

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1866]
Add [a link to the wallet dropdown](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c9a4a0a14906306968790b4) so that users can navigate to the Settings page, which should include a [currency selector](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c9a4a094182f605bdf2f0b5).

**Comment by nick** [comment]
Added 'Settings' link in the dropdown in #1872 

Should we also add one in the mobile hamburger menu?

**Comment by micahalcorn** [comment]
Yes, thanks @nick 👍 I thought we did this but I can't find it.

**Comment by micahalcorn** [comment]
Ah, here it is @nick ⚙️ https://zpl.io/V1wNnWB

**Comment by micahalcorn** [comment]
Closing thanks to #1872 and in favor of https://github.com/OriginProtocol/origin/issues/1915 ☑️
