### ISSUE TITLE
Attestation Failure w/Cookies

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1867]
Some users report issues verifying email and/or Twitter. It is believed to result from the browser blocking cookies. This is common for users of Brave because the often have "shields on" and other users might have a browser extension that disables them.

**Comment by tomlinton** [comment]
This could be either a general cookie failure or the session affinity of the Kubernetes ingress failing. I've scaled down the replicas on production to 1 for the bridge and will see if it persists.

It would be good to have some cookie detection maybe, and be able to warn if attestations will fail. Or perhaps find an alternate method to verify without cookies.

**Comment by micahalcorn** [comment]
@jonhearty reported something similar happening with phone in Coinbase Wallet. I haven't been able to reproduce it yet.

**Comment by nick** [comment]
I think avoiding cookies altogether will help here. iOS is very particular about when it will or wont send cookies and the ingress is another issue.

Instead, the bridge server can return a session id as part of the 'generate-code' endpoints that we can return in the 'verify-code' endpoints as part of the JSON body. Basically doing what a cookie does handling it manually instead to avoid these annoying issues.

For example:

```
POST /api/attestations/phone/generate-code
{"country_calling_code":"1","method":"sms","phone":"555123456","identity": "0xabc123..."}

->

{"session":"abc123"}
```

```
POST /api/attestations/phone/verify-code
{"session":"abc123","code":"12345"}

->

{ ...attestation }

**Comment by nick** [comment]
Done
