### ISSUE TITLE
"How do I get crypto" content

### ISSUE THREAD

**Issue by nick** [OriginProtocol/origin#1868]
What should "How do I get cryptocurrency" link to?

<img src="https://user-images.githubusercontent.com/939/55487172-ceb22380-55ea-11e9-9cc0-c9a702dc5418.png" width="300" />

**Comment by micahalcorn** [comment]
![inbruges](https://user-images.githubusercontent.com/273937/55501072-7e44c100-55fe-11e9-8394-ae5737e559a3.gif)

**Comment by micahalcorn** [comment]
Done 😐
