### ISSUE TITLE
Return custom objects instead of raw web3 transactions from API

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#1902]
EDIT: After discussion, we changed desired approach and title was updated. Old title was "Move `waitTransactionFinished` to `origin` object" 

It's a common pattern to create and then wait for transaction. For example, this example from our docs:
```javascript
const transaction = await origin.listings.close(
      listing.address
    )
await origin.contractService.waitTransactionFinished(transaction.tx)
```

~~However, we should strive to hide `contractService` from developers, so I'd suggest moving `waitTransactionFinished()` directly to the `origin` object, or making a method on `origin` that relays the call to `contractService`.~~

EDIT: We should not return a raw web3 transaction, but should return an abstracted transaction object with a convenience function `isFinished()` for waiting for it to finish. 

The above line would then read

```javascript
const transaction = await origin.listings.close(
      listing.address
    )
await transaction.isFinished()
```

@DanielVF what do you think?

**Comment by micahalcorn** [comment]
Closing this because GraphQL 🤷‍♂️
