### ISSUE TITLE
Force one-to-one relationship between wallet and identity in user registry

### ISSUE THREAD

**Issue by tyleryasaka** [OriginProtocol/origin#1905]
This is blocked by: https://github.com/OriginProtocol/origin-js/issues/369

We currently guarantee that a wallet owns a registered ERC725 identity. But we do not enforce that an identity is used by only one wallet. It would be possible for someone to register their own custom ERC725 implementation on our user registry, and then share that identity among an unlimited number of separate ethereum wallets. I'm not sure how much of a concern that scenario is right now, but for now it's probably best to enforce a one-to-one relationship.

I discussed with @crazybuster and the simplest solution for seems to be to add a second mapping to the user registry. This mapping will be from an ERC725 identity to a wallet address. Then we will require that, when registering an ERC725 identity in the `registerUser` method, that identity has not already been mapped to a wallet address.

A possible additional benefit of this approach is that we will be able to do a reverse lookup: given an identity address, we can easily find the associated wallet.

**Comment by micahalcorn** [comment]
Considering this done since identity v2 ☑️
