### ISSUE TITLE
📙 Discovery - need way to create and maintain elasticsearch mapping files

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin#1906]
Currently we are letting elasticsearch automatically create indexes and their mappings.

This is not a good long-term solution because every field ever sent will get its own index created.

We need something like a database migration tool that keeps creates and keeps up-to-date our index mapping as needed.

@franckc

**Comment by franckc** [comment]
Closing. We now have the [es_cli.sh](https://github.com/OriginProtocol/origin/blob/master/infra/discovery/devops/es-cli.js) tool.
