### ISSUE TITLE
[Growth] Add IP and country of origin to growth_participant table

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#1908]
The country will be helpful for analytics purposes (to segment users by region) and the IP can always be a useful signal for fraud detection.

**Comment by micahalcorn** [comment]
Resolved by #1960 ✅

**Comment by micahalcorn** [comment]
@franckc maybe I should not have closed this?

**Comment by franckc** [comment]
This is done and deployed to prod. Closing.

**Comment by micahalcorn** [comment]
Fine then 🍾
