### ISSUE TITLE
Finalize Confirmation

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1909]
In DApp:one:, we prompted buyers for confirmation before finalizing. If a user started to leave a rating of ⭐️ or ⭐️⭐️, we would ask if there was a problem and suggest opening a dispute. Once a rating was set and the finalization button was clicked, we would explain that the funds would be permanently released to the seller. We should bring one or both of those back until we separate finalization from ratings/reviews and/or provide sufficient explanation of the finalization process.

**Comment by nick** [comment]
Any Zeplin screens for these? Hoping not to go 🎣in dapp1

**Comment by micahalcorn** [comment]
@nick we can keep it simple. Here is one with incorrect copy: https://zpl.io/V4e0OWJ

**Comment by micahalcorn** [comment]
@nick this may or may not be helpful: https://github.com/OriginProtocol/origin/pull/714 😐

**Comment by shahthepro** [comment]
@micahalcorn the text in Zeplin screen you shared is incorrect. If you change it, let me know. I will update it in the PR #2143

**Comment by micahalcorn** [comment]
@shahthepro sure, it's fine as-is in the PR. 🙏
