### ISSUE TITLE
Required Ratings

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1910]
We previously required a 1-5 star rating (with optional review) before allowing a buyer to finalize, but that's no longer the case. Is that intentional or should we bring them back?

Related: https://github.com/OriginProtocol/origin/issues/1909

**Comment by shahthepro** [comment]
Any decision reached for this one? If it is required, I can include this along with PR #2143

**Comment by micahalcorn** [comment]
I think we do want them, yes, @shahthepro. ⭐️

**Comment by shahthepro** [comment]
@micahalcorn Done.
