### ISSUE TITLE
Multiple referees with the same name

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#1913]
A user reports that when he shared his referral link to Twitter he sees the same name multiple times. 
![e9d1f-clip-23kb](https://user-images.githubusercontent.com/579910/55561807-1e7c1200-56f3-11e9-8079-961a1ce8f6ef.png)

moments later it seems to be getting worse: 
![Clip2net_190404171028](https://user-images.githubusercontent.com/579910/55562566-7e26ed00-56f4-11e9-94b8-384ce3a7aadd.png)

The owner of the profile expected that there should be at least some people with other names

**Comment by franckc** [comment]
I checked the data returned by the growth server and it looks ok to me.
So I wonder if there is a possibly a bug in the FE causing it to display the first/lastname of the first referee for all referees ?

**Comment by sparrowDom** [comment]
It turned out the bug was actually on fronted Apache cache acting weirdly when there is a null `id` field present in results. Fixed via: https://github.com/OriginProtocol/origin/pull/1931/files
