### ISSUE TITLE
Use BIP39 mnemonics in Origin Wallet

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin#1916]
We'll want to use a 12 word BIP39 mnemonic with a m/44'/60'/0'/0 derivation path in our wallet.

This will allow Origin wallet to be compatible with almost all of the popular wallets including MetaMask, Coinbase Wallet, MyEtherWallet, MyCrypto, imToken, Jaxx, Trezor and Exodus.

Ledger is one notable exception, but people shouldn't be reusing the seed words from their hardware wallet anyway.

**Comment by tomlinton** [comment]
Closed #2291.
