### ISSUE TITLE
Improved Mobile Onboarding + Mnemonic-Based Wallet

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1918]
Also known as "mobile 1.75", the version of our Android/iOS app following https://github.com/originprotocol/origin/issues/1917 should feature an improved oboarding experience and account management using seed phrases instead of private keys.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by micahalcorn** [comment]
Noting here that we probably want to continue to allow for importing and exporting private keys, but I think we would still want to require the involvement of a recovery phrase for other accounts 🔑 We may need to add an indicator to those that don't follow the derivation path (as MetaMask does).

**Comment by tomlinton** [comment]
Closed #2291.
