### ISSUE TITLE
Origin Rewards In Mobile Apps

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1920]
We currently prevent users of mobile wallets from accessing the Origin Rewards experience. It may actually work out of the box in Coinbase Wallet, et al, if they support the signing method that we are using. Otherwise, we should see what it would take to make it work.

![mobile-growth](https://user-images.githubusercontent.com/273937/55591704-1ddf7d80-56eb-11e9-9669-3ce5fd9efc17.png)

**Comment by micahalcorn** [comment]
@sparrowDom you might knock out https://github.com/OriginProtocol/origin/issues/1928 while you're here. 😬

**Comment by tomlinton** [comment]
This needs a bit more work for our mobile app, the rewards banner is still disabled and I need to verify the signing works.

**Comment by tomlinton** [comment]
Done now by #2146!
