### ISSUE TITLE
Origin Wallet Activation Option On Mobile

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1922]
For a mobile Safari user (for example) who is routed through the first step of user activation, there is no option presented for installing Origin Wallet. It simply tells the user that they need a crypto wallet but doesn't offer a way to get one.

**Comment by sparrowDom** [comment]
From what I remember this happens only if you start activation using Origin Rewards. Since Rewards don't support Origin wallet yet, so the wallet is actively removed from on-boarding. This should be resolved in the next sprint when we add the support for Origin Wallet when signing up for Rewards.

**Comment by micahalcorn** [comment]
@sparrowDom on my iOS Safari and Chrome, I get stuck after clicking Purchase. 🙁 

![IMG_6892](https://user-images.githubusercontent.com/273937/55687973-312b5c80-5928-11e9-831f-231ddc7bd86f.PNG)

**Comment by sparrowDom** [comment]
Resolved by: https://github.com/OriginProtocol/origin/pull/2052
