### ISSUE TITLE
Small Screen Identity Activation Step

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1926]
Step 4️⃣ of user activation on small screens should only contain the profile and email attestation flow ([as shown here](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9?seid=5bfe423fc509273f9e06eb38)) instead of offering all services.

**Comment by nick** [comment]
This should already be done

**Comment by micahalcorn** [comment]
It appears so. I was just moving all of the unchecked box sub-tasks from the monolithic user activation issues.

Although, the current UI doesn't quite match the latest designs [here](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c8700991f719638a3ea4d50) and [here](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c87009af39e0d38d45d7564). I'll go ahead and close this. We'll see what's included in the profile wizard PR and revisit this after that.
