### ISSUE TITLE
Problems Clearing Privacy Data

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1930]
If after granting EIP 1102 access to the DApp I "clear privacy data" in MetaMask, the DApp still knows my account. I'm also still able to make a purchase. I don't see how that's possible and doubt that it should be our intent.

**Comment by joshfraser** [comment]
@crazybuster was saying at lunch that he was able to get access to accounts before EIP 1102 access was even granted.

**Comment by nick** [comment]
Looks like this is fixed now. Was probably a MetaMask issue
