### ISSUE TITLE
Small Screen Missing Listing

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1932]
An identical search on small and large sceens produces varying results.

<img width="1440" alt="Screen Shot 2019-04-04 at 4 48 07 PM" src="https://user-images.githubusercontent.com/273937/55595580-73bb2200-56f9-11e9-905b-ba67ab79154f.png">

![merch-search](https://user-images.githubusercontent.com/273937/55595550-44a4b080-56f9-11e9-8315-3c9258c1b37a.png)

While this screenshot is from Coinbase Wallet, the same is true on mobile Safari. ⬜️

**Comment by nick** [comment]
Is this still an issue? Unable to reproduce

**Comment by micahalcorn** [comment]
I can't either now. I'll let @jonhearty reopen if he can.
