### ISSUE TITLE
Delay MetaMask Login Prompt

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1936]
If the user is signed out, she should not be prompted to sign in to MetaMask immediately upon loading the DApp. This should only happen in step 1 of user activation.

I think this would be solved naturally by fixing https://github.com/OriginProtocol/origin/issues/909. 🤞

**Comment by shahthepro** [comment]
@micahalcorn 

If the user already has a deployed identity, the other steps should be skipped right? Or should he still go through the "Rewards" and "Congratulations" screen?

**Comment by micahalcorn** [comment]
Yes, a user should only see the rewards and success screens once (per device, I suppose). ☑️
