### ISSUE TITLE
Enforce User Activation Messaging Requirement

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1937]
If step 1 is completed and then the user returns manually to a purchase button, she should be routed back to step 2. ♻️

**Comment by micahalcorn** [comment]
Assuming that we will begin requiring an email address until further notice, this won't be necessary. 😐

**Comment by sparrowDom** [comment]
@micahalcorn if the user completes email/profile onboarding but not messaging onboadring and returns to click on the purchase button. 

Should we force/redirect the user to enable messaging? Or at least ensure he makes an active attempt and press the skip "no thanks" button?

**Comment by micahalcorn** [comment]
No skipping ⚠️ We want to require every buyer and seller to enable messaging.

**Comment by sparrowDom** [comment]
Got it @micahalcorn  👍

**Comment by sparrowDom** [comment]
Resolved via: https://github.com/OriginProtocol/origin/pull/3132
