### ISSUE TITLE
Messaging Activation UI

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1940]
If the second of the two messaging signatures is canceled (or if a user returns with a different browser after enabling messaging), the ui should be aware that only one of the two prompts is necessary. Similarly, if either prompt is canceled, there should be an unhappy state shown that includes an "Enable Messaging" button (not shown in Zeplin).

**Comment by sparrowDom** [comment]
Resolved by: https://github.com/OriginProtocol/origin/pull/3100
