### ISSUE TITLE
Convert hide_list to use listing address (not index)

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#197]
Goal: We want our moderators to be able to easily hide listings. 

A while ago we converted the DApp to refer to listings by their contract address, instead of the old way of an array index. 

However, our "hide list" functionality is till based on array indexes. That is, objectionable listings can be hidden from view by editing the json file in the `hide_list` branch of this repo. 

We need this array to now be an array of listing addresses, and change the dapp to filter based on those listings. 

Moderators can copy-paste the listing address from the URL into the our list. (But they have no way of knowing the index.)

Complication: Should this filtering functionality live on the bridge server instead? (I think not, but it may make the logic easier.)

( @andrewhyde this one's for you! )

**Comment by DanielVF** [comment]
Hide functionality is definitely going involve the bridge server as soon as it is the way we get our listings.

**Comment by micahalcorn** [comment]
No longer necessary per @DanielVF 🗑
