### ISSUE TITLE
DApp always reports 1000 listings

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#1971]
This is because of [this](https://github.com/OriginProtocol/origin/blob/master/infra/discovery/src/lib/search.js#L233) which is a remnant of when we had pagination and not infinite scroll. We need to cleanup the old pagination code in discovery (see the arguments to the `search` function).

**Comment by franckc** [comment]
Is there actually relevance in showing the total number of listings on the browse page ?
@matthewliu @micahalcorn ?

**Comment by micahalcorn** [comment]
Good question @franckc 🤔 I don't think it serves much of a purpose when you're not searching and not filtering. Then it's a bit more debatable. So I could see wanting to have a consistent UI where the count is always there whether searching or not. Perhaps @auregimon or @matthewliu have an opinion?

**Comment by auregimon** [comment]
i think that can go away unless searching/filtering.

**Comment by nick** [comment]
Fixed in #1991
