### ISSUE TITLE
Created Marketplaces Not Filtering Listings

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1978]
As reported by wilzha on Discord regarding the staging environment...

> All 382 listings are showing up on every created marketplace in staging despite ticking of only use listings from my marketplace

**Comment by tomlinton** [comment]
This is because it isn't using the discovery server correctly, manually setting the discovery server in DApp settings works.

**Comment by nick** [comment]
Staging discovery config was commented out. Should be fixed in #1991
