### ISSUE TITLE
Change wording when contracts not found

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#198]
Currently we show this when our contracts are not found:
![image](https://user-images.githubusercontent.com/673455/40253614-6f1c4636-5aae-11e8-9398-acf24d5190c0.png)

1) "this network" should be replaced with "this network (`<network name>`)"  If its a known standard network, like "Rinkeby" or "Main Net", that should be shown. If its a test network, then just use it's number. 

2) "The Origin Contract was not found..."--> "The Origin smart contract**s** were not found..."

3) "..or deploy the contract" --> "..or deploy the contract**s**"

We already have logic for getting network name/number when we show it here:

![image](https://user-images.githubusercontent.com/673455/40254626-39cf5e1a-5ab2-11e8-92fd-355253780d2b.png)

**Comment by micahalcorn** [comment]
🤷‍♂
