### ISSUE TITLE
[Listener] Discord webhook showing [object] instead of currency

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin#1989]
Starting today at 2:44 pm EST / 11:44 am PST, the listener webhook posts to Discord now is creating titles like "ListingCreated - Water - 0.00001[object Object]"

![image](https://user-images.githubusercontent.com/837/55832942-a479cd80-5ae4-11e9-8b5b-7cac7a3127e1.png)

This would appear to be because the price "currency" changed to an object? The acual listener discord webhook code around this last changed 5 days ago.

https://github.com/OriginProtocol/origin/blob/master/infra/discovery/src/listener/webhooks.js#L39

**Comment by tomlinton** [comment]
That is right, price is now an object to support stablecoins. 🎉

**Comment by nick** [comment]
Done in #2149
