### ISSUE TITLE
Expandable reviews

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#200]
Currently, all related reviews are shown on the [listing-detail](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/src/components/listing-detail.js#L999), [purchase-detail](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/src/components/purchase-detail.js#L1131), and [user](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/src/pages/user/User.js#L133) components. This should be limited to display only the 3❔ most recent❔ with an [expandable "Read More" feature](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5a362e2a85e0b5a00efde978).

**Comment by micahalcorn** [comment]
@drewmo I would recommend just showing some additional reviews and leaving the button intact until there are no more. I also suspect that we will end up changing the number to something larger than three, but that's what was in the mock, so we'll try that for now. 👍

**Comment by drewmo** [comment]
@micahalcorn can you review this when you get a chance? The only fix that I know needs to be done on this is cleaning up the [blue caret]( origin/experimental/origin-dapp2/public/images/caret-blue.svg) as it has a border around it. Currently I set the component to show the first 3 reviews, and after you click read more it will show the next review from the query.
