### ISSUE TITLE
Earned Rewards Not Displayed

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2004]
It's my understanding that our listener is still missing some events (see #1972 & #1986), which frustrates some users who complete attestations or marketplace transactions expecting OGN rewards and they don't see them reflected in their campaign dashboards. This issue tracks those complaints.

|Discord User|Ethereum Address|
|---|---|
|elchoban|0x77335205Eb73c00214BDb38B66BC353A892b9da7|
|dice|0x04B4f215e59b9E0ed70b73508135fa2187d3B058|

**Comment by franckc** [comment]
Thanks for adding these user reports - it will hopefully help us diagnose this annoying issue.

Aside from the ETH address of users reporting an issue, would be great to know what rewards they think they are not seeing (ex: no earning for Phone|FBook|Airbnb|Twiter; or no earning for ListingSold, or ListingPurchased, or Referral).

**Comment by micahalcorn** [comment]
Considering this resolved 😬
