### ISSUE TITLE
Add additional identity attestation types

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin#2006]
Attestations for Twitter & Facebook are way less relevant for our Chinese users than wechat which is ubiquitous in Asia. They appear to have an OAuth API that we could use: 

https://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/web/login/getting-user-profile#login_getting-user-profile

Similarly, we should investigate other local options like Kakao, Naver, QQ, LINE, VK, etc. Other attestations like Github make a lot of sense to me as well. We should also consider a generalized version of the Airbnb attestation that allows you to connect your identity on any third-party website. You would submit a link to your profile on any third-party site and we can verify that you indeed control it by adding the verification phrase that we give you.

Of course, we'll need to figure out a better UI if we end up supporting a plethora of attestation types.

**Comment by micahalcorn** [comment]
Related: #1825 & #1401 😅

**Comment by micahalcorn** [comment]
Bumping this per @joshfraser ⬆️

**Comment by micahalcorn** [comment]
Closing in favor of those listed above 👆
