### ISSUE TITLE
[Profile Wizard] hardcoded reward amount

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2008]
While testing on staging, I notice the amount for attestation reward seem to be hardcoded to 10 OGN rather than pulling the amount dynamically from the backend.
See screenshot below:
<img width="762" alt="Screen Shot 2019-04-10 at 10 06 40 PM" src="https://user-images.githubusercontent.com/945910/55932182-6d3b1780-5bdd-11e9-8784-4add579b6807.png">

**Comment by sparrowDom** [comment]
This is a great catch. I guess the main question is do we want to show this reward option when user is not enrolled into Rewards Campaign? If yes we should leave it hardcoded I think. If no loading it dynamically makes the most sense. Let me ask this in Zepplin: https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c8a90a6ed2b7b0dcbfad18a

**Comment by micahalcorn** [comment]
Closed per @franckc ☺️
