### ISSUE TITLE
Fractional Usage: Buy Box

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#201]
The [listing-detail buy-box](https://github.com/OriginProtocol/demo-dapp/blob/develop/src/components/listing-detail.js#L235) needs to have the following elements added:

- [ ] **Check In** date/time selector
- [ ] **Check Out** date/time selector
- [ ] **Guests** quantity selector

https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5af35331c258e2972402369d

**Comment by jordajm** [comment]
Resolved by https://github.com/OriginProtocol/origin/pull/1107
