### ISSUE TITLE
Localize text for stable coin

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#2010]
Looks like none of the new strings got wrapped for stable coin release. 

I'm getting the low hanging fruit now, but don't have a lot of time, so we should do a full sweep later.

**Comment by micahalcorn** [comment]
Really? I thought I did this @wanderingstan. Let me take it off your hands if so.

**Comment by micahalcorn** [comment]
Lots of `<fbt` in [here](https://github.com/OriginProtocol/origin/pull/1797/files) but we might have missed some. 🙁

**Comment by wanderingstan** [comment]
Ah, I just saw there was no wrapping done in here:
https://github.com/OriginProtocol/origin/blob/master/dapps/marketplace/src/pages/listing/mutations/Buy.js

@micahalcorn no worries, I'm already deep in it from trying to fix those "just a few fixes" :) on growth. I'll have a PR up in a sec. Just testing now.
