### ISSUE TITLE
Fractional Usage: Owner's DAILY Calendar

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#202]
A new component needs to be added for a listing owner to manage the available dates and pricing for a listing.

https://app.zeplin.io/project/59fa2311bac7acbc8d953da9?seid=5b1826bd16e713444156ae61

Related: #306

**Comment by micahalcorn** [comment]
Editing this to limit the scope to daily 📆

**Comment by jordajm** [comment]
Resolved by https://github.com/OriginProtocol/origin/pull/1107
