### ISSUE TITLE
Seller-Configurable Shipping Address Requirement

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2022]
As proposed by @nick, the listing creation form should include a checkbox for requiring a shipping address from buyers. We should only present this to _**sellers**_ - not to creators of For Rent, Service, and Announcement listings. Let's also have it be automatically checked and allow users to uncheck it, if appropriate. As a result, the "next step" text in the transaction detail page should be conditioned based on the value that is set with this checkbox so that all buyers are not encouraged to send their shipping addresses via messaging.

Related: https://github.com/OriginProtocol/origin/issues/1399

**Comment by micahalcorn** [comment]
See https://zpl.io/2GGQg3Y for listing creation checkbox ☑️

**Comment by shahthepro** [comment]
Done and merged with #3241
