### ISSUE TITLE
Buyer's Confirmation of Seller Fulfillment

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2029]
Once email/sms/push notifications are prevalent and read (🤞), a buyer is likely to see that her offer has been accepted and be routed to the transaction detail page. The problem is that this page's large call-to-action will be for the buyer to finalize the transaction. Meanwhile, the well-meaning seller hasn't even had a chance to ship the item yet.

We should add an interim quasi-step for the buyer to confirm that the seller has done what she's supposed to do. This "confirmation" won't be recorded on the blockchain or on a server, but will simply update the buyer's local state on the one device.

[Here](https://zpl.io/2jQXBMW) is an example design that is wired up to the flow. We'll have to deal with figuring out how to communicate this for the various categories (copy TBD).

**Comment by micahalcorn** [comment]
@sparrowDom this is mocked up [in the 𝓓𝓐𝓟𝓟𝟛 section of Zeplin](https://zpl.io/2ZrGE1L) and would be great to get included at the same time as the new styles.

**Comment by sparrowDom** [comment]
@micahalcorn what is the thing that "seller has done that he/she was supposed to"?

**Comment by micahalcorn** [comment]
Basically that the order has been fulfilled; item received, rental completed, service performed, etc ☑️

**Comment by sparrowDom** [comment]
I might not get this completely let me sum it up and please correct me if I get it wrong: 
- buyer makes an offer on a listing
- seller confirms that offer 
- we insert an interim (non blockchain) step where buyer confirms he has - received the item, rental has been completed, service has been performed
- after that interim step there is another step where buyer finalises the transaction and funds are released to the seller?

**Comment by nick** [comment]
Storing in local storage is not ideal. Could we display the message based on time? For example for a shipped item, change message to 'release funds' x days later. Or for a home stay, display 'release funds' after the checkout date. 

Thinking about it more... isn't 'Confirm Receipt' the same thing as 'Release Funds' anyway? Why would you want to 'Confirm Receipt' but not 'Release Funds'?

**Comment by sparrowDom** [comment]
I agree with @nick. If the main concern is that we do not want to present a "scary" ReleaseFunds button when the seller has not shipped the item yet. We could display ReleaseFunds in a Modal that is opened once a Buyer clicks on a `Confirm` button?

**Comment by micahalcorn** [comment]
Yes @nick I was expecting rentals to be based on time (as shown [here](https://docs.google.com/spreadsheets/d/12pxebLfi_BbbmH53E5UTJ_swubIRXNKkhYhOQj5sOYo/edit)). I'm not sure how we would do that for sales and services without choosing an arbitrary timeframe or centrally recording the seller's claim of fulfillment.

As for a modal @sparrowDom, I think that's fine but it doesn't seem materially different. It's still conditionally two clicks.

I think that there are a lot of cases where I would want to say that I've received the item but I'm not happy. I suppose that there could be some anxiety about clicking the button if I'm not happy, but I should find the "report a problem" in that case anyway.

In the normal world, this isn't a problem because we know when the seller has marked the item as shipped. But here we're trying to handle this interim period of unknown duration where we should not be pushing the buyer to release funds.

**Comment by micahalcorn** [comment]
Yes @nick I eas expecting the time-based state change for rentals (as described [here](https://docs.google.com/spreadsheets/d/12pxebLfi_BbbmH53E5UTJ_swubIRXNKkhYhOQj5sOYo/edit#gid=0)). I'm not sure how we would accomplish that for sales and services without choosing an arbitrary timeframe or centrally recording the seller's claim of fulfillment.

@sparrowDom I think a modal would be fine, but that doesn't seem to be materially different from what is showing in the mocks. It's still a conditional two clicks.

I think there are a lot of cases where I would want to confirm receipt without releasing the funds. There may be some anxiety about clicking a "confirm receipt" button if I'm not happy, but I should be able to find "report a problem" in that case. The main thing that we're trying to accomplish is to deal with this interim period of unknown duration wherein we don't want to push the buyer to release funds when it's not yet appropriate.

**Comment by sparrowDom** [comment]
What should we do about this one? One idea was to solve it with modals. There are a couple of problems with that: 
- are the double modals problematic? Modal 1: the one with Release Funds button. Modal 2: confirmation modal
- with rentals that are past their end date. We can not automatically open Modal 1. 

Any other ideas.

**Comment by micahalcorn** [comment]
I haven't forgotten about this. 🐘

**Comment by micahalcorn** [comment]
Not sure how high of a priority this is today, but I'm wondering if we should actually consider centralizing this step. We could use the messaging pipes to record the buyer's claim that fulfillment has occurred. We may decide not to proactively show this to the seller, but it would at least be a possibility. Messaging is already centralized, and this step is relevant for arbitration, which involves access to the messages between the two parties. 🤔

**Comment by micahalcorn** [comment]
I agree that this is isn't great, but closing it out for now 😔
