### ISSUE TITLE
Cannot Accept Campaign Terms

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2036]
It seems that the campaign terms currently cannot be accepted. I and others are seeing this error regardless of what language our browser is set to.

![problems](https://user-images.githubusercontent.com/273937/56088970-dcb04180-5e3f-11e9-88d0-6c50fa6e4adb.png)

**Comment by micahalcorn** [comment]
The problem here is that the enrollment message is wrapped for translation.

![enroll](https://user-images.githubusercontent.com/273937/56089546-77614e00-5e49-11e9-8374-08f44ff88623.png)

But I don't understand why that version of the code lives in master. The last commit to that file is https://github.com/OriginProtocol/origin/commit/8deec4697b5ef56321ebe77059abc142b1f2fc6e, which occurred after https://github.com/OriginProtocol/origin/commit/7b440e914558cdbd3d7c6bfcd9b4335de1e3b235#diff-107453bd33e7be87826a051ec39daa03.

Somehow, the currently-deployed code does not include those changes. It seems that something unintended happened [here](https://github.com/OriginProtocol/origin/commit/7afa0fa0e96e66c45f45ed55f8ef6a90b55db0b3).

I'm going to stand down on this so I don't make more of a mess by trying to revert something or force a deployment at a particular commit hash.

Dad? @tomlinton 😭

**Comment by sparrowDom** [comment]
@micahalcorn looks like the problem was a sloppy fix the last time from my side. Here is the corrected code, the message seemed to be wrapped in translation on 2 locations. 
Fix: https://github.com/OriginProtocol/origin/pull/2037

**Comment by tomlinton** [comment]
Resolved by #2037.

**Comment by micahalcorn** [comment]
Ooooooohhhh it was two different lines? 🤦‍♂️ I guess I needed sleep. Thanks @sparrowDom @tomlinton.
