### ISSUE TITLE
Improve Search Results

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2042]
Our listings search feature does not produce the most helpful results. For example, [a search for "Origin Event Shirt"](https://dapp.originprotocol.com/#/?q=Origin%20Event%20Shirt) reveals 265 listings, and the exactly matching "Origin Event Shirt" is the 12th result. I don't know whether the 11 results ahead of it are promoted for some other reason, or we're just not sorting results based their degree of match. Additionally, there are some [extremely fuzzy match](https://dapp.originprotocol.com/#/listing/1-000-1999)es that arguably should not be returned or should be buried.

**Comment by DanielVF** [comment]
It should be easy to make this a bit better.

https://www.elastic.co/guide/en/elasticsearch/guide/current/proximity-matching.html

I'll update the query tonight or tomorrow.

**Comment by DanielVF** [comment]
PR pushed that makes a search for "Origin Event Shirt" return just that listing.

**Comment by DanielVF** [comment]
"Origin Event Shirt" now only shows one listing:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/837/56434006-e81cc600-62a0-11e9-9afb-f0c8f034d7a6.png">

In the longer term, some more possibilities are:

- [ ] not show sold listings by default in DAPP search results.
- [ ] Reprioritize cheap items (say less than 50 cents worth)
- [ ] Inactive older items rank slightly lower after X time with no events.

**Comment by micahalcorn** [comment]
Thanks @DanielVF! 💙
