### ISSUE TITLE
Prevent Blockchain Modal Dismissal

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2044]
Our browser modal component disappears if the user clicks elsewhere on the page, which is fine for some. But some modals should be blocking ([for now](https://github.com/OriginProtocol/origin/issues/85)) and not allow the user to navigate away or refrain from taking some action. For example, if we know that a MetaMask prompt has been initiated but not yet acted upon, we should encourage the user to confirm or cancel it. Some users accidentally dismiss [the animation](https://github.com/OriginProtocol/origin/issues/386#issuecomment-473599155) modal and don't realize that [the prompt is buried](https://github.com/OriginProtocol/origin/issues/386). Another example is when a blockchain transaction is being mined or confirmed.

**Comment by micahalcorn** [comment]
This fix was effective for mobile, but I can still dismiss the modal in desktop. ☹️

**Comment by micahalcorn** [comment]
Demoting this since it no longer affects mobile 🙂

**Comment by nick** [comment]
Hrm I can't reproduce on desktop... was there a particular modal you can reproduce with?

**Comment by micahalcorn** [comment]
Closing this until I can find the reproduction 😕
