### ISSUE TITLE
Automatically Enabled Messaging

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2063]
In cases where we are capable of under-the-hood signings (such as the app formerly known as Origin Wallet), we should automatically enable messaging without explicitly asking the user to confirm either of the two steps.

**Comment by tomlinton** [comment]
Maybe more of a P1? I don't think it is a release blocker since you can still sign like you would on desktop.

**Comment by micahalcorn** [comment]
I guess so @tomlinton. I was hoping that it was a simple matter of copy over some old code from OriginWallet.js that was removed.

**Comment by micahalcorn** [comment]
Bumping this per @jonhearty and @matthewliu 👍

**Comment by tomlinton** [comment]
It's more complicated than copying the old code because we need to inject the cookies into the WebView. Working on it though. :grin:
