### ISSUE TITLE
Refreshable Webview

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2079]
We need a way to refresh the webview in the mobile app. We've talked about possibly adding a pull-to-refresh feature, but not all of the DApp components would be conducive to that. For example, [this one](https://github.com/OriginProtocol/origin/blob/ab5c421aec5ed8f3ccd39d77baafaac302a36843/dapps/marketplace/src/pages/App.js#L60-L65) needs a button because it won't scroll at all.

![error](https://user-images.githubusercontent.com/273937/56439399-c0c2fa80-629a-11e9-8d1c-83ecf4971dc9.jpg)

**Comment by tomlinton** [comment]
Closed in #2466
