### ISSUE TITLE
Origin Marketplace Tout

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2091]
Build mobile and desktop versions of [this modal](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9?seid=5cb7acb33ce4e433afafb4ba), which will be displayed as soon as a user expresses intent to purchase, add a listing, or contact someone without having a wallet-enabled browser. The QR code and button should point to https://www.originprotocol.com/mobile, which ~[will need to be updated](https://github.com/OriginProtocol/origin-website/issues/361)~ [has been updated](https://github.com/OriginProtocol/origin-website/pull/368/files#diff-8a03279f19a0d21b77323e3f6bb89ca9) since linking is no longer relevant.

**Comment by micahalcorn** [comment]
Sorry, I missed your question @tomlinton. 😇 Now that user activation is getting a refresh from @shahthepro, I think we should probably display the new modal immediately upon loading the DApp in a browser that is not web3-enabled (desktop or mobile). I don't think we need to wait for intent to be expressed because we want to push this app aggressively and it would be clunky to show this and then go to user activation when the modal is dismissed.

@shahthepro, for mobile users, we should show this modal (again) every time the user expresses intent to buy, sell, or contact. Desktop users and those with a web3-enabled mobile browser should be routed to user activation.

**Comment by shahthepro** [comment]
@micahalcorn Got it. :+1:
