### ISSUE TITLE
Browsing Listings

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2092]
Bring back the ability to browse listings by category as an alternative to search.

Quasi-Duplicate: #1705

**Comment by nick** [comment]
Is there a Zeplin screen of this somewhere? 😬

**Comment by micahalcorn** [comment]
@nick something like https://zpl.io/2ymD8vG but without all the fancy filters 🤔 @sparrowDom might be able to shed some light since he originally built it.

**Comment by sparrowDom** [comment]
Didn't @Natasha08 have a pull request opened trying to implement this for the Dapp2. Anybody know what happened with that?

**Comment by micahalcorn** [comment]
Considering this resolved by 𝓓𝓐𝓟𝓟𝟛
