### ISSUE TITLE
Transaction Modal Not Honoring Notifications Approval

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2093]
I’m consistently getting this regardless of my notifications settings.

![7B75507A-7B2B-443C-A0EF-5BDC83933286](https://user-images.githubusercontent.com/273937/56477026-ca877080-64db-11e9-9183-4e032792bfc4.png)

It should only appear if I have not yet granted permission.

Additionally, push notifications don’t seem to be working yet, but that may be expected.

**Comment by tomlinton** [comment]
Any further information? Simulator/real device? Notifications enabled/disabled? I couldn't reproduce from a fresh install.

And yes the server component of push notifications aren't complete yet.

**Comment by micahalcorn** [comment]
Real iPhone, notifications enabled, using Rinkeby and have two accounts in the app 😐

**Comment by tomlinton** [comment]
Xcode build, TestFlight build, or App Store? :)

**Comment by micahalcorn** [comment]
App Store, but now I can't reproduce it after having switched accounts. 😔

**Comment by micahalcorn** [comment]
@tomlinton, @jonhearty was seeing this recently. 🙁

**Comment by tomlinton** [comment]
iPhone too I think?

**Comment by micahalcorn** [comment]
I believe so. 📱
