### ISSUE TITLE
Account Balances Not Updating Reactively

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2097]
In Origin Wallet, we polled for updates to the account balance(s). This is important because we need to be able to detect when there is a compelling reason to backup the wallet. Also, users don't have a reasonable way to proceed after funding their wallet. Right now they have to kill the app or switch networks.

**Comment by tomlinton** [comment]
We still poll for [balances](https://github.com/OriginProtocol/origin/blob/master/mobile/src/OriginWallet.js#L86-L89). Did you see something that makes it appear it wasn't working? Maybe the poll interval needs to be decreased.

**Comment by micahalcorn** [comment]
@tomlinton ten seconds? Yeah, seemingly the entire class today in our workshop thought that they had not received their ETH until someone killed their app and then found money. @kayyoo23 told us that switching networks was the way to find your newly minted ETH. 😬

**Comment by micahalcorn** [comment]
The "waiting for ETH" went on for about five minutes. I'm not sure how long the faucet delay is, but I'm fairly certain that no one in class detected new ETH without reloading the wallet. ♻️

**Comment by tomlinton** [comment]
OK, sounds like it might be a different bug since even with a poll of 10 seconds it should have found it. When you say "waiting for ETH" do you mean a specific loading indicator? Or are you just talking about general waiting?

Is this what I'd do to reproduce?

- Open wallet to balance screen
- Request ETH from faucet
- Stare at balance screen until something happens

**Comment by micahalcorn** [comment]
@tomlinton no specific indicator, just a 0️⃣ balance, thx. 👍 I can report back after tomorrow's workshop and tell the kids to switch networks if necessary.

**Comment by micahalcorn** [comment]
Considering this a non-issue ☺️
