### ISSUE TITLE
Intermittent failure of injectedJavaScript of react-native-webview

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2111]
During yesterday's Korean workshop, there was at least one instance of the account not being connected to the webview. So the user would see "Get Started" in the top right of the nav and get stuck in user activation. Switching the account from Mainnet to Rinkeby and back again resolved it. Unfortunately, I don't know how to reproduce that one.

**Comment by tomlinton** [comment]
This is going to be hard to figure out since its very intermittent. I think I have seen it once or twice during development. If you see it again try and remember if it was Android or iOS please 👍

**Comment by tomlinton** [comment]
As a bit of context, the way we inject JavaScript is a bit hacky. We need to inject it before document load (for web3) so I added an injection on the react-native-webview `onLoadProgress` to make sure it gets injected before the DApp finishes loading. I think perhaps onLoadProgress doesn't always call correctly which causes this issue but I'm not sure under what circumstances. This PR on [react-native-webview](https://github.com/react-native-community/react-native-webview/pull/397) might solve this for us (the author created it for the same web3 use case).

**Comment by micahalcorn** [comment]
@matthewliu this should solve David Luhman's onboarding issue once it hits the App/Play Stores. 🤞

**Comment by micahalcorn** [comment]
This report from @wanderingstan may be a different issue, but it results in the same symptom and at least gives some indication of an error.

![Untitled](https://user-images.githubusercontent.com/273937/57087185-5ce5fc00-6cb4-11e9-8954-2dac09c36295.png)

**Comment by tomlinton** [comment]
Different issue but fixed in #2201.
