### ISSUE TITLE
Force/recommend updates on mobile

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#2136]
We need the option in the mobile app to:

- Force an update, if we drop support for an older version for whatever reason
- Recommend an update, e.g. for stability fixes

I'll add a file into the mobile repository with version numbers for each of these. We'll need to add a component that blocks/nags accordingly. I think this is important to do soon because it is already becoming hard managing older versions.

@micahalcorn should we get mocks or I can just proceed with what I think looks OK.

**Comment by micahalcorn** [comment]
@tomlinton just throw something together when you're ready and we can make it prettier when we get around to it. I'll put it on the list of things for @auregimon, but he has other priorities that are higher, I think.

**Comment by tomlinton** [comment]
The App Store has this in the policy document:

`Apps must not force users to rate the app, review the app, download other apps, or other similar actions in order to access functionality, content, or use of the app.`

So I'm not sure from that whether that includes forcing the user to update the app. I think we should err on the safe side and still allow the user to use the app/dismiss the message but make the wording stronger for the "Force an update" part of this.

Any thoughts?

**Comment by micahalcorn** [comment]
We still want the user to be able to "use the app" because she may want to export her key, for example. I think the main thing is just for it to be abundantly clear that the version is no longer supported and that things will not work as expected. If she wants to do anything meaningful (buy, sell, etc), she needs to update it.

**Comment by tomlinton** [comment]
Closed #2291.
