### ISSUE TITLE
Fractional booking does not work on mobile

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2140]
Reproduction steps:
 - Open Origin mobile app
 - Go to purchase page for a fractional listing
 - Try to select checkin date on calendar
=> Nothing happens

**Comment by micahalcorn** [comment]
This is true on all mobile screens, in my experience; not specifically Origin Marketplace 🗓

**Comment by micahalcorn** [comment]
Related #1217 😐

**Comment by shahthepro** [comment]
Is this reproducible on Android?

I guess this is most likely due to [this issue on React](https://github.com/facebook/react/issues/2055).
