### ISSUE TITLE
Nightly fractional listing price calculation off by 1 night

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2141]
Reproduction steps:
 - Go to purchase page of a nightly fractional listing. For example: https://dapp.staging.originprotocol.com/#/listing/4-000-742
 - Select 2 nights
 - The checkin date and check out date correctly reflect the nights selected
 - But the price only accounts for 1 night.

See screenshot below. 
 - Checkin date is Mon June 3
 - Checkout date is Wed June 5
 - That's a total of 2 nights so I would expect price to be $0.10 * 2 = $0.20 but it is $0.10
<img width="1169" alt="Screen Shot 2019-04-26 at 10 37 20 PM" src="https://user-images.githubusercontent.com/945910/56845334-716d6300-6874-11e9-9f3a-50cc45ae4baa.png">

**Comment by shahthepro** [comment]
@franckc Every fractional listing is treated as a nighly listing as of now. Check out this PR #2104.

@nick I guess this change is causing more confusion. Perhaps we can discuss with the team and come to a decision on this one.

**Comment by franckc** [comment]
@shahthepro What I'm confused about is that in the example above, checkin date (not on the calendar, on the box below the price) shows as Mon and checkout as Wed. So that's a total of 2 nights right ?

**Comment by shahthepro** [comment]
@franckc The checkout date should be Tuesday. It will appear as such in Offer details page. I somehow overlooked this area. Will fix it.

**Comment by franckc** [comment]
@shahthepro Thanks for being so on top of things :) Love it.

We could indeed update the checkout date to be Tuesday in that example...
Having said that, visually when I selected on the calendar 2 days that each had a price, I sort of expected the price would be the sum of those 2.

Also a little counter intuitive that on the calendar, whether I select 1 day or 2, there would not be any difference in the checkin/checkout date.

But maybe it's just me. I'm terrible at UX and should not be trusted to make those decisions :)

Dear fearless product visionary @micahalcorn @matthewliu do you have any thoughts ?

**Comment by shahthepro** [comment]
@franckc 

> Having said that, visually when I selected on the calendar 2 days that each had a price, I sort of expected the price would be the sum of those 2.

> Also a little counter intuitive that on the calendar, whether I select 1 day or 2, there would not be any difference in the checkin/checkout date.

This makes sense to me now. Will submit a PR. We can merge or close it later when we reach a decision.

Thanks. :)

**Comment by shahthepro** [comment]
@franckc 

Have submitted a PR that should address this issue. You can pull the branch [shahthepro/fractional-listing-patch-2141](https://github.com/OriginProtocol/origin/tree/shahthepro/fractional-listing-patch-2141) and see if it works as you expected.

**Comment by matthewliu** [comment]
The confusing part is the nightly thing coupled with all the prices being set on the grid. We're not doing a true check out and check while showing many nights you are doing.

Perhaps the short-term fix is:
1. User selects two grids in the calendar.
2. That means two nights, and we show the sum of the two nights.
3. In small text underneath we say 'Checking out (insert date after)

This would be overfitting for homesharing but is it possible to just add that for this subcategory?

**Comment by shahthepro** [comment]
@matthewliu 

> 1. User selects two grids in the calendar.
> 2. That means two nights, and we show the sum of the two nights.

PR #2145 will make the behavior exactly like this.

> 3. In small text underneath we say 'Checking out (insert date after)

Where exactly should the text appear? Any Zeplin screens for this one?

> This would be overfitting for homesharing but is it possible to just add that for this subcategory?

@nick had suggested adding a new listing type `NightlyListing` when it becomes necessary. If all existing subcategories for fractional listing require nightly pricing, I think we can keep this change for now.

**Comment by lucadgtrip** [comment]
I reported this in #1439 a few days ago

**Comment by matthewliu** [comment]
No Zeplin link for this. I'd just add in small point font below the two dates and above the Total Price, probably in a shade of gray.
