### ISSUE TITLE
Error when trying to add Google account

### ISSUE THREAD

**Issue by simibac** [OriginProtocol/origin#2168]
I get the following error page when trying to link my Google account:

<img width="683" alt="Bildschirmfoto 2019-05-01 um 10 11 57" src="https://user-images.githubusercontent.com/15369592/57009923-f7353980-6bf9-11e9-9115-2c6a4b595370.png">

**Comment by franckc** [comment]
Thanks @simibac for reporting this issue !
This is due to a misconfiguration on our end.

@joshfraser Please close once the Google Origin account config has been updated. Thanks :)

**Comment by franckc** [comment]
Fixed.
