### ISSUE TITLE
[Mobile] Hamburger menu not dismissed when clicking on "Earn Tokens"

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2171]
Repro steps:
 - start Origin mobile app
 - click on hamburger menu in webview
 - pick "Earn tokens"
=> The campaign page loads in the background but the menu does not get dismissed, effectively hiding the campaign page.

Root cause:
From investigator @tomlinton : "Growth enrollment component doesn't fall inside the standard router, its like an overlay on top, so it doesn't integrate properly with the hamburger menu."

No easy peasy fix. We may need to rewrite this component to be mobile friendly.

**Comment by franckc** [comment]
After @nick's fix, the menu now closes but the campaign page does not load

**Comment by sparrowDom** [comment]
A fix for this here: https://github.com/OriginProtocol/origin/pull/2203/files

**Comment by sparrowDom** [comment]
Fixed via https://github.com/OriginProtocol/origin/pull/2203
