### ISSUE TITLE
[Mobile] Campaign page needs styling

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2179]
Campaign page needs mobile specific styling.
This can be reproduced either on Origin mobile app or simpler by using Chrome's mobile device view on desktop

<img width="417" alt="Screen Shot 2019-05-01 at 11 26 55 AM" src="https://user-images.githubusercontent.com/945910/57034368-2ea8e380-6c04-11e9-8a66-6c0a8260a9a3.png">

**Comment by sparrowDom** [comment]
Closed via https://github.com/OriginProtocol/origin/pull/2210
