### ISSUE TITLE
Listing Image Gallery Navigation & Expansion

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2183]
Moved from #1727 🚚

The following changes should be made to the image viewing experience on the listing detail page:

- [ ] Navigation arrows on the main image (shown [here](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c799f8c5c1db5628cf25150))
- [ ] ~Closeable lightbox expansion of main image on click (shown [here](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c799f877890375205bfc49c))~    **moved to https://github.com/OriginProtocol/origin/issues/2412**

**Comment by ldu2** [comment]
I would like to take a look at this issue. But since I am not invited on zeplin, is there any other way I can see the demo? Or if it's possible, can I get invited on zeplin?

**Comment by micahalcorn** [comment]
@ldu2 sure, are you on [our Discord channel](https://www.originprotocol.com/discord)? If so, pm me your email address or you can post it here and I'll delete it.

**Comment by ldu2** [comment]
Message sent on discord, but the email is the same one as the one you see in my profile here.

**Comment by ldu2** [comment]
So I added the arrows in and they work fine. But I am still kind of confused about the second part "Closeable lightbox expansion". Is it like if you click on certain section and it zooms in on the picture? Or is it like a magnifier lens which shows a zoom in section while moving cursor on the image?

**Comment by micahalcorn** [comment]
Hi @ldu2 😬 Are you still working on this, by chance? We're going to start working on a redesign, and it will involve prioritizing a swipe/navigation feature similar to the one described here. Let us know if you have anything that you want to commit before we move forward.

**Comment by ldu2** [comment]
I finished the first feature in the list and that's the part I want to commit. I prefer creating a pull request since it helps me to keep track of different repos in just one account. I will create that right away.

**Comment by micahalcorn** [comment]
Done per #2416 🙁
