### ISSUE TITLE
Custom Gift Card Listing Type

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2185]
Support buying and selling gift cards according to [this spec](https://docs.google.com/document/d/1fdO4iot5Jm5rHaFqP7K88SrmlRdi8arq48s5UpgDSGo/edit).

**Comment by wanderingstan** [comment]
Update: bulk of work was merged Friday. It is now live on:
https://dapp.dev.originprotocol.com/#/

But you must enable it in console with:  `localStorage.setItem('enableGiftCards', 'true');`

**Engineering**
- [ ] Determine how to make gift cards exclusive on our gift card domain (maybe even just if-then). 
- [ ] Once copy is more-or-less final, run `npm translate` and get new strings into `master` (thus to Crowdin)

**Nice to have engineering**
- [X] Put top 5 retailers at top of list, then rest alphabetically. (Done in 6d4845e23ac3b57857654e51d7232a25e7d2e104)
- [X] Script to upload and pin card images. _Where in repo to put this?_ (Done in 9bea929619fb5b59b4a4d610b919c940daae27f7)
- [X] Move retailer info out of Graphql and into dapp. 

**Nice-to-have design**
- [ ] Design of listing detail page
- [ ] Design of listing creation steps
- [ ] Decide on copy for listing creation pages
- [ ] Better card images, especially of the top 5-10 retailers.

**Product Decisions**
- [ ] @joshfraser  wanted the _description_ (aka _Notes_) field to be optional, but our JSONschema validation currently has it as required, with a 10 character minimum. Is this okay?
- [ ] Do we include all EU countries as "Eurozone", or just the few currently there?
- [ ] The UK currently has very long name of _United Kingdom of Great Britain and Northern Ireland_. I just re-use names from Origin Rewards, but maybe we want to revisit?
- [ ] Decide on what retailers to include. @joshfraser suggests we just include all, and I concur.

**Comment by micahalcorn** [comment]
Thanks @wanderingstan 👍 [Here](https://dapp.staging.originprotocol.com/#/?config=https://gist.githubusercontent.com/wanderingstan/39dfca67616a8b5a99d6445864303081/raw/4b79d99b867a3924cd91c229728b313041e76b68/configurltest.json) is the updated link for what was shown in today's meeting (cc @matthewliu).

Just to recap what @auregimon mentioned:

- [ ] yes/no radio buttons instead of checkboxes
- [ ] two-column listing description with more heavily-weighted labels
- [ ] photo upload only if a receipt is available

Another nice-to-have might be a link to find the gift card balance if there is a way to do it. It seems like a lot of other sites offer that.

**Comment by micahalcorn** [comment]
Great work @wanderingstan 👏
