### ISSUE TITLE
[Origin Rewards] User not credited with referral

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2202]
We got a report from a user that he did not get credit for a referral.
Apparently after he signed up, he invited his wife and she completed level 1.

I checked in the DB and there is no entry in growth_referral.

I asked the user to check the invite code stored in local storage on his wife's computer by running the following command from the JS console:
`localStorage.getItem('growth_invite_code')`

The user says this command returns:
`что это?Сложновато ((`
Which would indicate the invite code got corrupted somehow (possibly by email client, or somehow by DApp when writing it to local storage) which would explain why there was no entry for that referral recorded in growth_referral. This all seems very odd...

Here is the data:
 - referrer: 0xa019c73a9205136e12720d447c4a4441a05a508d
 - referee: 0xf3f67fe12ba2481a30327d7d309fe2548c6242b2
 - referrer's invite code: a0108d12853

As far as I know we haven't had any other report from users about referral not being credited.

**Comment by franckc** [comment]
@sparrowDom FYI in case you have any idea what could be happening...

**Comment by sparrowDom** [comment]
@franckc could we get his wife to forward the invitation email? Or perhaps screenshot it + forward it. Perhaps we can deduce something from that. 

Maybe there was some automatic translation that corrupted the invite code?

**Comment by franckc** [comment]
I was thinking along the same lines but here is the screenshot of the invite email he posted in the bug-report channel and I don't see anything wrong about it ?

![screenshot](https://user-images.githubusercontent.com/945910/57150220-8e2cfd80-6d82-11e9-89ee-182bbca99614.jpeg)

**Comment by sparrowDom** [comment]
Hmm interesting could find his post quickly in Discord. Interestingly the button aligns to the left instead of staying centred. I would ask the user if he can to post a screenshot with the mouse over the button. So in the bottom left we can see the URL the button points to: 

<img width="1273" alt="Screenshot 2019-05-03 18 08 03" src="https://user-images.githubusercontent.com/579910/57150518-cf4aff00-6dce-11e9-80de-19be072f41a4.png">

**Comment by franckc** [comment]
I has asked him to check the link in the email. Here is his response: "В письме у жены синяя кнопка  в которой ссылка https://originprotocol.com/#/welcome/a0108d12853 .по этой ссылке жена и регистрировалась" which using google translate seems to mean "In the letter of his wife, there is a blue button in which the link is https://originprotocol.com/#/welcome/a0108d12853. The wife registered the link with this link"

So it does look like the referral link in the email is correct and that his wife clicked on it to register...

**Comment by sparrowDom** [comment]
Hmm that is weird. Looking at the [invite code logic](https://github.com/OriginProtocol/origin/blob/master/dapps/marketplace/src/pages/growth/Welcome.js#L25-L41) I have no idea how this could have happened... I would vote to close this one as can not reproduce.

Btw interestingly the stored invite code user reported `что это?Сложновато (( ` translates to `what is it?Difficult` 🤷‍♂

**Comment by franckc** [comment]
I can't figure it out neither. Perhaps the user was poking with the system and tried to use an invite code they generated themselves manually rather then the one in the invite email link ? Which ended up storing that weird string in local storage.

The only think perhaps we could do is adding a check to make sure the invite code has the proper format (e.g. 11 chars, latin alphanumeric characters only) before storing it in local storage ?

**Comment by sparrowDom** [comment]
@franckc PR with code length check here: https://github.com/OriginProtocol/origin/pull/2233

**Comment by sparrowDom** [comment]
Fixed via: https://github.com/OriginProtocol/origin/pull/2233
