### ISSUE TITLE
Attestations: button on pop up out of screen (not clickable)

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#2212]
Chrome on Os x, this is what I get:
![Screenshot 2019-05-04 at 20 50 19](https://user-images.githubusercontent.com/34341206/57182943-8bc7c200-6eae-11e9-9e92-f059e7680d12.png)

the only way to click the button is to zoom out.

**Comment by shahthepro** [comment]
@lucadgtrip I think you have resized your browser window to an height less than 600px. If yes, PR #2214 should fix it.

**Comment by lucadgtrip** [comment]
fixed
