### ISSUE TITLE
Dispute failure

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2219]
Austin reported he is unable to file a dispute.
 - ListingId: 1-000-923
 - Offer 1-000-923-21

Reproduction steps:
 - Logged in as cryptomerch account in the DApp, go to offer details and click on "report a problem"
 - Add a description and submit
 - Metamask conformation popup shows up, accept it.

Result:
 - Transaction gets reverted and fails. See[ etherscan link](https://etherscan.io/tx/0x431de9408a072811e5a47182b95dd13b267d37996535514d11303e3d448c28e3)

Theory: Austin mentioned he updated the price of the listing from $1 to $15 so it is possible this may cause the issue. Maybe the DApp is using the new price when sending the transaction whereas the offer may have been created for the old price ?

**Comment by franckc** [comment]
@nick FYI in case you have any idea. I'm a bit tied up in the next couple days but can look at it afterwards.

**Comment by AustinVirts** [comment]
I tested out opening a dispute for an item that did not have the price changed but still received an error. This error message is different than the one you get when disputing an offer with the price changed.

<img width="1570" alt="Screen Shot 2019-05-06 at 11 56 57 AM" src="https://user-images.githubusercontent.com/40499782/57248042-3b5b7c00-6ff6-11e9-9234-d1f32459df54.png">

**Comment by nick** [comment]
This is happening because the finalization window has passed which prevents you from disputing. Working on the UI to handle that case now...
