### ISSUE TITLE
Inability To Finalize Offers Involving DAI

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2220]
We have received multiple reports of failing attempts to finalize offers that involve DAI. At least one was a result of insufficient gas. One or more (potentially all) of the others seems to be caused by `Expected event not found`.

![2019-04-30_10 25 59](https://user-images.githubusercontent.com/273937/57245194-11eb2200-6fef-11e9-84ee-9175921b0d2c.png)

**Comment by micahalcorn** [comment]
It's possible that all of these listings were created with CryptoMerch but purchased using the main DApp, if that matters.

**Comment by nick** [comment]
Gas estimate was too low... pushing a PR to increase it now
