### ISSUE TITLE
Sign up redirects for Banned users

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#2239]
If a user is banned instead of showing the banned page sometimes the app keeps prompting user to sign up. To reproduce: 

- use account A to signup for Origin rewards
- go to account B and sign up 
- update growth_participant.status to Banned for account A 
- go back to account A and try to go to campaign page

**Comment by franckc** [comment]
@sparrowDom I'm looking at good first issues for new developers. Is this already fixed ? Or could I assign it to a new developer ?

**Comment by sparrowDom** [comment]
Have tested the steps and it is no longer reproducible. Switching accounts just redirects you (as expected) to "welcome"
