### ISSUE TITLE
Phone numbers should be normalized before they are stored

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin#2243]
We're currently storing international phone numbers in a variety of different formats. It would be better if we normalized these before saving them to the database. Right now, the same number can be saved 3 different ways:

- 1 5558675309
- 1 15558675309
- 1 +15558675309

<img width="389" alt="Screen Shot 2019-05-08 at 12 05 23 PM" src="https://user-images.githubusercontent.com/982234/57401106-cd47be00-7189-11e9-9056-b7297b01d02c.png">

**Comment by franckc** [comment]
This library seems pretty good: https://www.npmjs.com/package/libphonenumber-js
