### ISSUE TITLE
Video project deployment/infrastructure

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#2246]
I'm going to do the deployment this sprint. Could someone in the know outline what we need in terms of services? I'm guessing:

- Origin-linking
- PostgreSQL

The initial plan was to set up a build scheme similar to what we use for the DApp. Builds will trigger off pushes to the branch that the project is in and update the deployments. I'll just reuse most of he existing code for this.

**Comment by joshfraser** [comment]
I already gave @crazybuster his own server this morning. He says he's good to go on setting up everything else up on his own.

**Comment by tomlinton** [comment]
Ok, it was in the sprint goals for the next sprint but I'll remove it. cc @franckc
