### ISSUE TITLE
Fractional Usage: can't block some dates

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#2268]
some dates cannot be blocked.
In this specific case only the first available date after a closed date, can't be blocked while the rest works fine.
See it in this unlisted video:
https://youtu.be/b4NcbiFInxw

https://dapp.tripscommunity.com/#/listing/1-000-2543/edit/details/availability
same behavior on https://dapp.originprotocol.com/#/listing/1-000-2543/edit/details/availability

**Comment by franckc** [comment]
CC @shahthepro in case he has an idea as to what could be the issue...

**Comment by shahthepro** [comment]
@lucadgtrip Do you see any errors on the console?

**Comment by shahthepro** [comment]
@lucadgtrip It was a bug on AvailibilityCalculator that prevented changing availability of current date. PR #2279 should fix it.

Have added an explanation as comment to the code. https://github.com/OriginProtocol/origin/pull/2279/files

@franckc Thanks for bringing it to my notice. :)

@nick @micahalcorn We are having a 1 year limit on fractional/nightly listings but we do allow the user the go past that range on the calendar component. Should we limit it? Also, when user selects a date outside of the range, we log the error in console and but don't show it to the user. Any inputs on that?

**Comment by lucadgtrip** [comment]
console:

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
app.f3c57ca9.js:198 Invalid asm.js: Unexpected token
app.f3c57ca9.js:233 Heads up! ethereum._metamask exposes methods that have not been standardized yet. This means that these methods may not be implemented in other dapp browsers and may be removed from MetaMask in the future.
(anonymous) @ app.f3c57ca9.js:233
3app.f3c57ca9.js:233 Uncaught Cannot update() range outside of one year limit.
![Screenshot 2019-05-14 at 08 06 06](https://user-images.githubusercontent.com/34341206/57672061-277bcf80-761f-11e9-80d1-68f156cc35fe.png)

I just found out that on today's date, also prices can't be saved.

**Comment by shahthepro** [comment]
@lucadgtrip Thanks. PR #2279 will fix it.
