### ISSUE TITLE
WeChat Attestation

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2295]
Allow users to verify their WeChat accounts.

https://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/web/login/login

**Comment by shahthepro** [comment]
Done with PR #2406 but yet to be tested with actual credentials and developer account.

cc @micahalcorn @nick

**Comment by micahalcorn** [comment]
[Per WeChat Developer Portal, we need to register an international-market app](https://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/faq&symbol=faqs-web). But the link to [apply.wechat.com](http://apply.wechat.com/) is dead. Additionally, [the Mobile App and Web SDKs page](https://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/contact) says that registration is temporarily unavailable.
