### ISSUE TITLE
Add Origin to https://dap.ps

### ISSUE THREAD

**Issue by nick** [OriginProtocol/origin#2297]
Used by status.im.

Code [here](https://github.com/status-im/discover-dapps) in `src/common/data/dapps.js`

**Comment by joshfraser** [comment]
Opened a PR: https://github.com/status-im/discover-dapps/pull/39

**Comment by joshfraser** [comment]
They want to wait for performance mode before merging.

**Comment by micahalcorn** [comment]
<img width="1440" alt="Screen Shot 2019-06-07 at 2 20 23 PM" src="https://user-images.githubusercontent.com/273937/59134280-6dcb0280-892f-11e9-9275-b12c184f8382.png">
