### ISSUE TITLE
Test version of Relayer

### ISSUE THREAD

**Issue by nick** [OriginProtocol/origin#2303]
A few things we still need before we can test the relayer on rinkeby:

- [x] Deploy ProxyFactory and IdentityProxy to Rinkeby
- [x] Move latest changes from bridge/relayer.js to relayer/src/relayer.js
- [ ] Use wallet specified in env variable to conduct relayer transactions

**Comment by franckc** [comment]
@nick Thanks for making that list. I'll work on the two remaining items...

**Comment by franckc** [comment]
Merged #2311 to use latest relayer code that was in bridge.

**Comment by nick** [comment]
Closing this one as the test relayer is now live
