### ISSUE TITLE
Fulfillment Checklist: adapt to category

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#2307]
the actual copy:

_____
1      Verify the variants with the seller
2	Package the product and send it out
3	Notify buyer and provide tracking number
4	Wait for buyer to receive product
5	Withdraw your funds
_____
works for products but will be confusing for rents/services and so on.
We need either a neutral text or text adapted to each category

**Comment by micahalcorn** [comment]
Taking this out for now 😓
