### ISSUE TITLE
Refactor mobile detection in DApp

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#2323]
The DApp has a mixture of methods for detecting mobile devices. Some components have something like the following:

`this.state = { mobile: window.innerWidth < 767 }`

We also have the HOC withMobile which uses the same idea but passes `ismobile` as a prop. The HOC should pass a boolean rather than a string and should replace the window.innerWidth checks. Once we have a consistent method we could replace the logic with something else if wanted. 

We should clean this up by bringing the HOC up to scratch and using that everywhere.

**Comment by tomlinton** [comment]
Cleaned up the HOC in #2745. The rest of this issue still applies as there are a few window.innerWidth calls scattered around.

**Comment by rtman** [comment]
I'll clean up the window.innerWidth calls

**Comment by rtman** [comment]
Fixed in #2756

**Comment by micahalcorn** [comment]
Great, thx ✅
