### ISSUE TITLE
IdentityUpdated handler fail

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2361]
Seen on the listener in prod.  Caused the whole thing to come toppling down:

    INFO] - 2019-05-29T15:25:56.726868764Z - ESC[36;22m[DEBUG] ESC[39;1mevent-listenerESC[0m: Got 8315 unfiltered events within interval for IdentityEvents
    [INFO] - 2019-05-29T15:25:56.727178152Z - ESC[32;22m[INFO]  ESC[39;1mevent-listenerESC[0m: Got 1 new events for IdentityEvents
    [INFO] - 2019-05-29T15:25:57.173095782Z - ESC[32;22m[INFO]  ESC[39;1mevent-listenerESC[0m: Processing event: blockNumber=7855285     transactionIndex=171     eventName=I
    dentityUpdated
    [INFO] - 2019-05-29T15:25:57.173176502Z - ESC[32;22m[INFO]  ESC[39;1mevent-listenerESC[0m: Processing Identity event for account 0x6BdE42318942f913bD31855B669ffB417A0D54
    f9
    [ERROR] - 2019-05-29T15:25:57.176035351Z - 2019-05-29T15:25:57.175Z event-cache noop, current
    [ERROR] - 2019-05-29T15:25:59.735878219Z - 2019-05-29T15:25:59.735Z event-cache setLatestBlock to 7855286
    [ERROR] - 2019-05-29T15:25:59.735937309Z - 2019-05-29T15:25:59.735Z event-cache setLatestBlock to 7855286
    [ERROR] - 2019-05-29T15:26:07.194388866Z - (node:122) UnhandledPromiseRejectionWarning: undefined
    [ERROR] - 2019-05-29T15:26:07.194445438Z - (node:122) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of a
    n async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    [ERROR] - 2019-05-29T15:26:07.194453658Z - (node:122) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that a
    re not handled will terminate the Node.js process with a non-zero exit code.
    [ERROR] - 2019-05-29T15:26:09.557681449Z - 2019-05-29T15:26:09.557Z event-cache setLatestBlock to 7855287
    [ERROR] - 2019-05-29T15:26:09.557731390Z - 2019-05-29T15:26:09.557Z event-cache setLatestBlock to 7855287
    [ERROR] - 2019-05-29T15:26:29.842512890Z - 2019-05-29T15:26:29.842Z event-cache setLatestBlock to 7855288
    [ERROR] - 2019-05-29T15:26:29.842619850Z - 2019-05-29T15:26:29.842Z event-cache setLatestBlock to 7855288
    [ERROR] - 2019-05-29T15:26:34.524729805Z - 2019-05-29T15:26:34.524Z event-cache setLatestBlock to 7855289
    [ERROR] - 2019-05-29T15:26:34.524793425Z - 2019-05-29T15:26:34.524Z event-cache setLatestBlock to 7855289
    [ERROR] - 2019-05-29T15:26:39.564177328Z - 2019-05-29T15:26:39.563Z event-cache setLatestBlock to 7855290
    [ERROR] - 2019-05-29T15:26:39.564239259Z - 2019-05-29T15:26:39.563Z event-cache setLatestBlock to 7855290
    [ERROR] - 2019-05-29T15:26:45.248250072Z - 2019-05-29T15:26:45.247Z event-cache setLatestBlock to 7855292
    [ERROR] - 2019-05-29T15:26:45.248305232Z - 2019-05-29T15:26:45.248Z event-cache setLatestBlock to 7855292

CC @franckc

**Comment by franckc** [comment]
I wonder if it might be coming from the identity resolver here https://github.com/OriginProtocol/origin/blob/master/packages/graphql/src/resolvers/IdentityEvents.js#L79
Can eventCache possibly throw any exception for example if an error occurs when calling the provider to fetch events or whatnot ?

**Comment by mikeshultz** [comment]
The only throws in event-cache are on bad config, or params that aren't in the contract.  So, if there's an error originating in EC, it would probably be a bug.

Though the `undefined` part of the promise reject warning is interesting.  I'm not entirely sure what would happen if the `account` parameter of that call would be `undefined`.  First glance says it shouldn't be an issue with the InMemoryBackend, but I haven't tested it.

**Comment by mikeshultz** [comment]
Added a test(PR #2370) to check if `undefined` values to getEvents does anything, and it handles them just fine.

**Comment by mikeshultz** [comment]
Updated error handling should have taken care of this unhandled error handling issue.  Closing.
