### ISSUE TITLE
Duplicate reviews

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin#2365]
Each review is showing up twice on the listing view. Here's an example:

<img width="715" alt="Screen Shot 2019-05-29 at 11 41 22 AM" src="https://user-images.githubusercontent.com/982234/58582634-f8f91980-8206-11e9-956c-bfe3ca69f798.png">

https://dapp.originprotocol.com/#/listing/1-000-2806

**Comment by shahthepro** [comment]
I had fixed this while working on #2213. Seems like there are a few merge conflicts for that PR now. Will work on resolving those conflicts.

**Comment by micahalcorn** [comment]
Resolved by #2213 ✅
