### ISSUE TITLE
Add support for loading sub-schemas by URL to the React JSONSchema library

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin#24]
We're using this awesome React library to load & validate our JSONSchema forms:
https://github.com/mozilla-services/react-jsonschema-form

Unfortunately, this library does not currently support loading sub-schemas by URL. This functionality is supported in the JSONSchema spec but it's not in the React implementation that we're using. We're going to need this to be able to have schemas inherit common reusable components like mailing addresses or phone numbers.

Read up on $refs and the id properties of JSONSchema for more context:
https://spacetelescope.github.io/understanding-json-schema/structuring.html

**Comment by garrisons** [comment]
So it seems like the way we would want to implement a solution is by making a PR for the `react-jsonschema-form` framework? Or is there an easier way to implement a solution that I'm missing?

**Comment by joshfraser** [comment]
we should do some outreach to their team & see how receptive they would be

**Comment by garrisons** [comment]
Yeah that seems like a no go. I missed the attached screenshot from first look. I have some ideas on how to make it work though.

![screen shot 2018-01-22 at 7 12 27 pm](https://user-images.githubusercontent.com/5100597/35252929-54d7e98a-ffa8-11e7-9acd-194c3e14cbd6.png)

**Comment by epicfaace** [comment]
@joshfraser @garrisons I wouldn't mind a PR for this functionality, especially given that it is supported on the JSON Schema spec.

It would be related to https://github.com/mozilla-services/react-jsonschema-form/issues/323

**Comment by micahalcorn** [comment]
Closing this as we no longer use [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form) 😐
