### ISSUE TITLE
Detect browser and make better recommendations

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#240]
When visitors do not have a web3-enabled browser, we detect this and prompt them to either install MetaMask if they are on desktop or download a browser/wallet if they are on mobile. Currently, we only condition our recommendation based on [simple user agent detection](https://github.com/OriginProtocol/demo-dapp/blob/master/src/components/app.js#L68-L78) and we don't make use of the iOS/Android distinction. This all still results in a frustrating experience if someone is on Safari desktop and we send them to MetaMask (which won't do much good). We should find a more robust way to detect more precisely which browser is being used (probably with feature detection) and then better recommend what to install or download.

- [ ] Detect browser vendor (Safari, IE, etc)
- [ ] Detect device type (iOS, Android, etc)
- [ ] Move this function to the [utils directory](https://github.com/OriginProtocol/demo-dapp/tree/develop/src/utils)
- [ ] Update (and maybe consolidate) [Web3 modals](https://github.com/OriginProtocol/demo-dapp/blob/master/src/components/web3-provider.js#L29-L94) with better recommendations

**Comment by MuraraAllan** [comment]
Can I take this one?

**Comment by micahalcorn** [comment]
In our new user activation flow, we're now recommending that all mobile users install our app instead of various wallets. Otherwise, I'll close this in favor of https://github.com/OriginProtocol/origin/issues/1935.
