### ISSUE TITLE
Required IPFS 0.4.21 upgrade with breaking changes

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2408]
Looks like a required upgrade is in order.

> ALL USERS MUST UPGRADE. We intended to introduce a feature this release that, unfortunately, reliably triggered this bug. To avoid partitioning the network, we've decided to postpone this feature for a release or two.
> 
> Specifically, we're going to provide a minimum one month upgrade period. After that, we'll start testing the impact of deploying the proposed changes.
> 
> If you're running the mainline go-ipfs, please upgrade ASAP. If you're building a separate app or working on a forked go-ipfs, make sure to upgrade github.com/libp2p/go-libp2p-secio to at least v0.0.3.

### Breaking Changes

**There may be further software level considerations as well**, not just a simple infra upgrade.  The standard file hash encoding seems to be changing from base58 to base32.  At a minimum, the `@origin/ipfs` module would need to do the necessary conversion to what its consumers expect, though perhaps that's not the best solution, either since as time goes on, users may expect to see these new base32 hashes instead of the old CIDv0 hashes.  

It's late, and this may end up require very little if any changes on our part.  I'm still going over the material, but thought it best to organize here.

### References

- [The v0.4.21 release announcement](https://github.com/ipfs/go-ipfs/releases/tag/v0.4.21)
- [base32 CIDv1 default GH issue](https://github.com/ipfs/go-ipfs/issues/4143)
- [CID documentation](https://github.com/multiformats/cid#cidv1)
- [Migration to CIDv1 GH issue](https://github.com/ipfs/ipfs/issues/337)

**Comment by mikeshultz** [comment]
The go-ipfs client still seems to output the base58 hashes, and accepts them in CLI commands...

    [mike@megan ~]$ ipfs --version
    ipfs version 0.4.21
    [mike@megan ~]$ ipfs pin add Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z
    pinned Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z recursively
    [mike@megan ~]$ ipfs pin ls | grep Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z
    Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z recursive
    [mike@megan ~]$ ipfs cat Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z
    Hello World!

But it also supports base32 equally.

    [mike@megan ~]$ ipfs cid base32 Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z
    bafybeigmfwlweiecbubdw4lq6uqngsioqepntcfohvrccr2o5f7flgydme
    [mike@megan ~]$ ipfs pin add bafybeigmfwlweiecbubdw4lq6uqngsioqepntcfohvrccr2o5f7flgydme
    pinned bafybeigmfwlweiecbubdw4lq6uqngsioqepntcfohvrccr2o5f7flgydme recursively
    [mike@megan ~]$ ipfs pin ls | grep bafybeigmfwlweiecbubdw4lq6uqngsioqepntcfohvrccr2o5f7flgydme
    bafybeigmfwlweiecbubdw4lq6uqngsioqepntcfohvrccr2o5f7flgydme recursive
    [mike@megan ~]$ ipfs cat bafybeigmfwlweiecbubdw4lq6uqngsioqepntcfohvrccr2o5f7flgydme
    Hello World!

You don't have to re-pin for the different encoding as my above example suggests, either.  I can't find any documentation on it yet, but it appears that if you give it a base58 hash(like has been done), that's what you'll get back.  I even got a base58 hash back when adding a new file...

    [mike@megan ipfs-test]$ echo "whatevs" > whatevs.txt
    [mike@megan ipfs-test]$ ipfs add whatevs.txt 
    added QmaLM5azjyJ5g8jr8zXWP1Ny5D5tRv2oikKUXxhW3jVLKv whatevs.txt
     8 B / 8 B [====================================================================================================================================================] 100.00%

So, not really sure yet while it's labeled as "breaking" yet.  Even `ipfs id` shows the node URLs with base58 encoded IDs.  Perhaps this only effects their networking layer, hence the mention of a possible network split.

**Comment by tomlinton** [comment]
Closed by #2488 thanks @mikeshultz!

**Comment by mikeshultz** [comment]
Thanks, forgot about this issue.  We should probably keep an eye on these base32 encoding changes.  I have a feeling that with some version in the near future that encoding will be default.
