### ISSUE TITLE
Filter Listings With Rewards

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2411]
Display [an "Origin Rewards" link](https://zpl.io/2j5BzYr) that allows the user to filter listings to show only those that result in the buyer receiving OGN as a purchase reward. Consider clearing any search queries at the same time if it would otherwise yield a very low number of results.

**Solved by:** https://github.com/OriginProtocol/origin/pull/2638

**Comment by franckc** [comment]
Yes, agreed we should clear the search query since intersection of results will otherwise be very small or null.

Note that the back-end already exposes an endpoint to get the list of listings with reward. @sparrowDom added that capability for showing the OGN badge on browse page. So we should be able to re-use that.

**Comment by sparrowDom** [comment]
Yup good point @franckc we shouldn't even be using discovery for that query.

**Comment by sparrowDom** [comment]
Just posting the mobile Zeplin link: https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5ce5c8aeefa7aa1d3ff65e10

@micahalcorn I couldn't find it, do we have a desktop version for this also?

**Comment by micahalcorn** [comment]
@sparrowDom I think [this one](https://zpl.io/bJpYe7D) depicts it. We'll need to decide how to indicate that the filter is being applied in the results (similar to "## Art Listings").

**Comment by sparrowDom** [comment]
Thanks @micahalcorn . Yeah we should indicate selected category somehow. Should that info be added to this screen: https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5ce5c8aea2d3301e4041f4f7

**Comment by micahalcorn** [comment]
Yeah @sparrowDom maybe something like "## Listings with Origin Rewards"?

**Comment by sparrowDom** [comment]
That sounds nice 👍
