### ISSUE TITLE
Listing Image Gallery Lightbox

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2412]
We previously explored adding a lightbox feature to the listing image gallery. See the DApp2 design [here](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c799f877890375205bfc49c). This will not be a priority for the current redesign, but we may want to revisit it in the future. As an alternative, we could consider [magnification](https://github.com/OriginProtocol/origin/issues/2043).

**Comment by micahalcorn** [comment]
See also #2043

**Comment by rtman** [comment]
@micahalcorn I'm thinking that [react-image-lightbox](https://github.com/frontend-collective/react-image-lightbox) would be a good candidate to use here. It has zoom/carousel controls and is mobile friendly with pinch to zoom/swipe. [demo](https://frontend-collective.github.io/react-image-lightbox/)

Alternatively there is [react-image-magnify](https://github.com/ethanselzer/react-image-magnify) which is more like a typical e-commerce mouse over to zoom experience. It claims to be mobile friendly with a double tap and drag but its not working well on their [demo](https://ethanselzer.github.io/react-image-magnify/#/), it might be possible with proper setup though.

**Comment by micahalcorn** [comment]
As suggested by @lucadgtrip, we should allow for navigating through the images using the arrow keys but only with an open lightbox. See https://www.airbnb.com/rooms/27312690 and click "View Photos" for an example.

**Comment by rtman** [comment]
@micahalcorn it looks like [react-image-lightbox](https://github.com/frontend-collective/react-image-lightbox) has those features. This is pretty low priority so I'll leave this until later on.

**Comment by franckc** [comment]
@micahalcorn Do you think react-image-lightbox is a good choice ?
