### ISSUE TITLE
Mobile-First Transaction Detail

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2422]
Update the transaction detail screen to match these designs:

- mobile starting [here](https://zpl.io/adXRYl7)
- desktop starting [here](https://zpl.io/aMpLj3R)

In addition to the visual changes that are proposed here, we would like to decouple the finalization step from the rating/review step. The buyer's review should now be a separate blockchain transaction using the `addData` method as the seller's review currently does. I'm told by @nick that this will require changing the way that we query for reviews since future ratings/reviews will not be found in the finalization event.

Also, note that the "Learn More" link should lead to a mystery page yet to be designed. For now, it can just open a modal. I can come up with the content for that.

**Comment by micahalcorn** [comment]
Considering this done ✅

**Comment by sparrowDom** [comment]
Thanks @micahalcorn . I should update this stuff more. What is your usual process? When the ticket is in Done agile column is that when it should also be closed?
