### ISSUE TITLE
Mobile-First Origin Rewards

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2425]
Update the Origin Rewards screens as follows:

|   |Mobile|Desktop|
|---|---|---|
|Current Campaign Dashboard|https://zpl.io/amMnqA3|https://zpl.io/amMnqRm|
|Past Campaigns Summary|https://zpl.io/a7dwGzp|https://zpl.io/VYpYPNw|
|Verifications|https://zpl.io/beK1R6p|https://zpl.io/2jMkAAQ|
|Purchases|https://zpl.io/VYpWO6n|https://zpl.io/2GAm8Xm|
|Invitations: Send|https://zpl.io/aMp5ngK|https://zpl.io/V0g9P69|
|Invitations: Track|https://zpl.io/VOdoOL8|https://zpl.io/a3jX06x|
|Country: not eligible|https://zpl.io/bL5O0oG|https://zpl.io/VxRjjMx - but make it white|
|Country: forbidden|https://zpl.io/V1Q848m|make it white|
|Terms signature|https://zpl.io/aBRPv6p|https://zpl.io/bLKXX7Y - but make it white|

TODO: 
- [x] implement referral linking with clipboard

Pull Request: https://github.com/OriginProtocol/origin/pull/2468

**Comment by sparrowDom** [comment]
very nicely organised ticket @micahalcorn thanks!

**Comment by franckc** [comment]
@micahalcorn Great organization. One thing that does not show up here is how the referral flow will work on mobile. More specifically, how do we give credit to the referrer when the referee clicks on an invite ? On desktop, clicking on the link causes the referrer's code to get stored in the local storage of the referee's browser, which then gets detected when the referee signs up for origin reward. But I don't think that will work for mobile... Perhaps we should look at how other mobile apps with referral program handles this.

**Comment by matthewliu** [comment]
Hoping we can just do the same thing that thousands of other existing mobile apps have done in the past? Is there something special because of our wallet authentication stuff that changes things?

**Comment by franckc** [comment]
Let's hash this out during meeting tomorrow... I'm actually not clear on how that would work exactly...
A possibility (but that seems complicated, hoping there is something simpler):
 - referral links lands on a web page
 - referee enters their email. we store in the DB the link between that email and the referrer's code
 - referee then downloads the mobile app
 - referee enters (hopefulyl the same) email in mobile app onboarding flow
 - mobile app looks for a referrer code associated with that referee's email by calling back-end which checks against DB
 - mobile app stores referrers code locally
 - mobile app passes code when user signs up for Origin Reward

**Comment by sparrowDom** [comment]
That is a nice catch @franckc . I see that Firebase has a concept of [Dynamic Links](https://firebase.google.com/docs/dynamic-links) which is similar to deep links except that dynamic links also survive app installation. 

There is going to be some work to get this natively supported on the other hand it is a useful functionality. Another application is someone could share a link to specific listing that the target user would open after he would also install our app in between.

**Comment by franckc** [comment]
Ah yes, Dynamic Links could be a good solution. Is it worth paying for it or is it simple for us to implement something equivalent ?

**Comment by franckc** [comment]
@sparrowDom We had a chat this afternoon and @micahalcorn came up with the following idea:
  - referee click on link
  - link goes to a landing page that stores the referrer code in the mobile clipboard
  - page also instructs referee to download mobile app
  - after referee installs the app, when she goes to the reward signup page, the mobile dapp would get check if there is any referral code from the clipboard.

It seems simpler than integrating with Dynamic Links ? Do you mind taking a look ?

**Comment by sparrowDom** [comment]
I like that idea a lot. It is definitely not as resilient as dynamic links but order of magnitude easier to implement. Lets go with that 👍
