### ISSUE TITLE
Non-Modal Purchase Confirmation

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2451]
When we [add support for shipping addresses in purchases](https://github.com/originprotocol/origin/issues/1653), the purchase confirmation modal should be changed from a modal to a proper screen as shown [here](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/dashboard?seid=5cfebfa07bb35419d694069b) (with or without a shipping address involved).

**Comment by micahalcorn** [comment]
I think we've decided to show the shipping address form before the confirmation step so that the latter is always a single concept for the buyer to comprehend. And it can contain the shipping data that was inputted during the prior step. 🚚 All of this should come before any money is moved from the wallet, including DAI-related transactions.

**Comment by shahthepro** [comment]
Done and merged with #3241
