### ISSUE TITLE
Web Notifications Styling

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2455]
Update the notifications lists to have the following styling:

- [Mobile page](https://zpl.io/29KDXdA)
- [Desktop page](https://zpl.io/2pMd99Q)
- [Desktop dropdown](https://lost)

**Resolved by:** https://github.com/OriginProtocol/origin/pull/2679

**Comment by sparrowDom** [comment]
@micahalcorn Does this look ok for desktop dropdown?
<img width="1025" alt="Screenshot 2019-07-09 12 46 21" src="https://user-images.githubusercontent.com/579910/60883695-28119a80-a24b-11e9-9d94-4132837f9c01.png">

**Comment by micahalcorn** [comment]
@sparrowDom Good Enough For Desktop ™️

**Comment by micahalcorn** [comment]
Resolved by #2679 🔔
