### ISSUE TITLE
Migrate from hidelist to discovery moderation

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin#2463]
We need to remove the old hidelist. The new discovery moderation feature #2459 provides an instant, DB backed ability to hide listings.

I've already copied over all the old data from the hidelist into the new system (at least for mainnet)

**Comment by franckc** [comment]
Yes, agreed the most straight forward approach is to generate the SQL and run it manually. I'm happy to run it against the prod DB once we are ready...

**Comment by DanielVF** [comment]
Will be closed by #2599
