### ISSUE TITLE
Email Verification Failing On Some Android Devices

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2475]
According to @AustinVirts, we are getting reports of users who are unable to verify their email addresses using the Origin Marketplace app on Android devices in Barcelona. According to @franckc, the bridge server produces the following log output: `origin-bridge: Attempted attestation for <email> without session`. @sparrowDom is able to reproduce this by disabling cookies in his browser.

**Comment by tomlinton** [comment]
To fix this I propose we just replace the session storage in bridge with storing the verification value in redis keyed by email with a TTL. It's a pretty easy fix, so maybe make it a P1 and get it done so it doesn't crop up again. I'm happy to do it.

**Comment by tomlinton** [comment]
Closed #2493.
