### ISSUE TITLE
Origin Rewards lock condition

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#2485]
Things to do: 
- mobile download action requires a lock state. 
- Invitations (referral) action needs lock state and lock condition display

This probably won't be a problem for July Rewards Campaign, because we are removing Profile attestation. Still it is good to keep in mind.

The June campaign can get into a confusing state where all Purchases rewards are locked, requiring 2 profile verifications. Origin Profile is also a verification now. And verifying Email + Origin Profile won't unlock purhcases, because Origin Profile used to not be considered a verification. 
Purchases screen: 
<img width="753" alt="Screenshot 2019-06-19 11 52 56" src="https://user-images.githubusercontent.com/579910/59756558-427ad880-928a-11e9-8055-cbcde88be7f3.png">
Verifications screen: 
<img width="763" alt="Screenshot 2019-06-19 23 03 13" src="https://user-images.githubusercontent.com/579910/59800280-7d125e80-92e6-11e9-8ffd-f4c635d13264.png">

Next month this probably won't be a problem, since Origin Profile will no longer be an attestation.

**Comment by sparrowDom** [comment]
@franckc do you want to do anything about this or should we just ignore it since it will sort itself out with the next campaign?

Still created a ticket to let you know of this.

**Comment by franckc** [comment]
@sparrowDom Sorry I'm not clear on this issue...
 1. In the screenshot above, why aren't other attestations like airbnb, fbook, twitter not showing up ? Those should unlock the next level that has the featured listings
 2. What do you mean by "Next month this probably won't be a problem, since Origin Profile will no longer be an attestation."

**Comment by sparrowDom** [comment]
Sorry @franckc for not explaining properly. In the main ticket there are actually 2 images. It wasn't apparent before, it should be better now since I have separated the a bit and updated them. 

I though we are removing the Origin Profile verification (can be seen in the screenshot above) and also not have it as a locking mechanism requirement to claim rewards for additional verifications...

But now on the call we have discussed that we should still keep it in the backend logic (users need to fill out the name but not the photo) that locks additional rewards in case a user has not set his Origin profile name. 

Honestly I am not completely sure on how the locking should work. I have the following thoughts/questions: 
- Will all listings in the "Purchase" section be unlocked at all times. 
- Will we still require users to fill out the name before they can claim/unlock rewards for other verifications
- If we go with the only name requirement we should add another rule similar to [ProfilePublished](https://github.com/OriginProtocol/origin/blob/master/infra/growth/campaigns/june.js#L13) rule with a change that it only checks for the presence of the name 
- When do we validate a referral. Does user need to fill out only a name or any other verifications?
- With the meta-transactions we should watch out that referral program isn't too easily game-able

**Comment by franckc** [comment]
Thanks Domen. Some answers to your questions for the July campaign:
- Will all listings in the "Purchase" section be unlocked at all times ?
The plan is to have all purchases part of Level 2. See [this doc](https://docs.google.com/document/d/1Jfvb2SjL-73ODmmIBK7_YSH3UCSXrUWtAPqyvnuqyS4/edit#heading=h.h60gb0w4nr7n).

- Will we still require users to fill out the name before they can claim/unlock rewards for other verifications
Yes, that's my understanding. First name + Last name + email is required to graduate from Level 0 to Level 1.

- If we go with the only name requirement we should add another rule similar to ProfilePublished rule with a change that it only checks for the presence of the name
Per Micah's request a few weeks ago, I have already made the change to remove the photo requirement. See the [listener code](https://github.com/OriginProtocol/origin/blob/master/infra/discovery/src/listener/handler_identity.js#L243).

- When do we validate a referral. Does user need to fill out only a name or any other verifications?
For a referral to trigger a reward for the referrer, the referee must reach Level 2.

- With the meta-transactions we should watch out that referral program isn't too easily game-able
Yes, I definitely agree ! :) We'll need to monitor referral activity closely in July and potentially adjust oru fraud detection models...

=> So do you think there is still a potential problem ? Do we need to keep this issue open ?

**Comment by sparrowDom** [comment]
Thanks @franckc for an in depth answer, I think I understand now. I think 2 things need to be done from the front-end side: 
- we should have a lock state mobile download action. 
- the whole Invitations (referral) action needs lock state and lock condition display. 

will ping micah and aure on zepplin about it. If it is ok with you will keep this ticket open and add these 2 items as todos.

**Comment by sparrowDom** [comment]
Left comments here: https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5cfeb22619680119d06b3238

**Comment by franckc** [comment]
Thanks Domen for being so detail oriented. Please keep me posted if we end up deciding on making changes to the July rules... I'm planning on sending a draft PR for those in the next few days and will definitely have you as a reviewer...
