### ISSUE TITLE
IPFS Pinner revamp

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin#2543]
Our IPFS pinner is currently broken. 

When the we changed the listener to use the GraphQL backend, the format of the data the IPFS pinner receives changed. It's not been pinning anything since that change.

- [ ] Support new format
- [ ] Add support for storing avatarUrls from profiles

**Comment by franckc** [comment]
Thanks for creating this issue. Would also be good to run a backfill to pin the old data. This could either be done with a separate script that we write specifically for this or might be simpler to re-run the listener and re-process old data (let me know and I can run that in prod).
