### ISSUE TITLE
Identity contract verification "race condition"

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#2576]
When a user triggers 2 identity contract transactions in a way where the second one is triggered before the first one is completed, the changes introduced by the first one shall be lost.

**To reproduce:**
- create any attestation/verification + sign the transaction
- before the first one is mined sign another transaction

**Comment by sparrowDom** [comment]
@mikeshultz notifying you as requested 📯

**Comment by franckc** [comment]
I'm not sure this is a relayer issue but rather an issue in the attestation FE where changes from the first publish are not included in the second publish ? CC @shahthepro since he is the expert in this area...

**Comment by sparrowDom** [comment]
yup @franckc I was thinking that was probably it also. 

We used to have verified and provisional attestations. Once you would publish a profile all provisional attestations would be cleared and converted to verified once the blockchain transaction would be mined. 

One possible fix is probably along the lines of not clearing provisional attestations when publishing a profile, but keeping them. So when it comes to a case when a user does 2 published very closely together all the attestations get included in the latter publish.

**Comment by shahthepro** [comment]
@franckc @sparrowDom 
The thing is we put all verified attestations and the profile bio to IPFS every time a change is made and published. We don't and can't update existing IPFS data.

When querying for the user's published identity, we only take the last published IPFS data (by searching for the latest `IdentityUpdated` event and getting the `ipfsHash`).

If the transaction that publishes an update is not yet mined, we won't get that profile update.

**Comment by sparrowDom** [comment]
@shahthepro would it be possible to publish all the changes a user has made in specific session even if those changes have already been previously published (like a few seconds ago)

**Comment by shahthepro** [comment]
@sparrowDom This can happen even if we bring back the "Publish" button. If you do an attestation in one tab and another update in another tab (before the first transaction gets mined or even on another device) at the same time, you'll end up with the same issue of some updates getting lost. 

Even if we publish all the changes made in that session with the second transaction, We cannot be 100% sure that this second transaction will be published after the first one (Ethereum's transaction race)

**Comment by mikeshultz** [comment]
> We don't and can't update existing IPFS data.

Doesn't each update include all of the previous data?  If say, before publish it pulls from local storage if available(and maybe fallback to IPFS is necessary) the second transaction should have all the data from the first.

> Even if we publish all the changes made in that session with the second transaction, We cannot be 100% sure that this second transaction will be published after the first one (Ethereum's transaction race)

This is incorrect.  The nonce dictates the order of execution.

**Comment by shahthepro** [comment]
> This is incorrect. The nonce dictates the order of execution.

If you submit the transaction from two different devices (before one gets mined), The nonce will be same in that case, right?

**Comment by mikeshultz** [comment]
> If you submit the transaction from two different devices (before one gets mined), The nonce will be same in that case, right?

Assuming both devices control the same account and send a transaction with the same nonce, only one will get mined(likely whichever has the best fee).  But this is an extreme edge case.

**Comment by shahthepro** [comment]
@mikeshultz 

> Doesn't each update include all of the previous data? If say, before publish it pulls from local storage if available(and maybe fallback to IPFS is necessary) the second transaction should have all the data from the first.

As of now, we don't store the data to `localStorage`. Can add that back.

**Comment by mikeshultz** [comment]
> As of now, we don't store the data to localStorage. Can add that back.

Just an idea, since you mentioned that data from the pending transaction was lost.  There might be other ways to go about it.  

You could also issue a replacement transaction(same nonce, higher fee) but that would require some hinky logic that perhaps isn't necessary here.  You could also prevent another identity transaction until the previous one is mined, but that also requires some transaction state tracking.

Might just be best to keep track of the local identity state in a session or semi-permanent local storage.

**Comment by shahthepro** [comment]
> Might just be best to keep track of the local identity state in a session or semi-permanent local storage.

Yes, can do that. Will submit PR for this one. 

Thanks :)

**Comment by nick** [comment]
Yea, makes sense:

- Store new attestations in localStorage, with an expiration time of perhaps 1 hour
- When publishing to the blockchain, include all attestations from the whatever is currently in IPFS + any in localStorage (making sure we also de-dupe those that appear in both)

That will hopefully ensure all attestations appear in the latest event on-chain event
