### ISSUE TITLE
Origin rewards mobile spacing issues

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#2580]
Ran across these two minor spacing/layout issues for Origin Rewards:

![Simulator Screen Shot - iPhone Xʀ - 2019-07-01 at 14 42 25](https://user-images.githubusercontent.com/489202/60407712-e318b300-9c0f-11e9-9202-84b0f45b414b.png)

![Simulator Screen Shot - iPhone Xʀ - 2019-07-01 at 14 52 51](https://user-images.githubusercontent.com/489202/60407718-e90e9400-9c0f-11e9-800f-e257b3f2117f.png)

**Comment by sparrowDom** [comment]
Fixed via: https://github.com/OriginProtocol/origin/pull/2613
