### ISSUE TITLE
Release funds modal doesn't close on confirm

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#2607]
Release funds modal doesn't disappear after an action is taken when finalizing. This results in stacked modals like this:

<img width="320" alt="Screen Shot 2019-07-03 at 2 21 52 PM" src="https://user-images.githubusercontent.com/489202/60573687-3f283680-9dcc-11e9-962e-ee84f630608c.png">

**Comment by micahalcorn** [comment]
@sparrowDom is this resolved in https://github.com/OriginProtocol/origin/pull/2610? 🙏

**Comment by sparrowDom** [comment]
Yup solved in there 🎉

**Comment by sparrowDom** [comment]
due to changes this shall be solved in another PR: https://github.com/OriginProtocol/origin/pull/2612
