### ISSUE TITLE
Update confirm transaction modal for our mobile app when transaction is meta transaction

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#2608]
Modal asks mobile user to still confirm transaction even when it is being handled automatically by meta transactions.

![Simulator Screen Shot - iPhone Xʀ - 2019-07-03 at 14 48 33](https://user-images.githubusercontent.com/489202/60573948-b9f15180-9dcc-11e9-86bb-73a5b28c9a7f.png)

**Comment by micahalcorn** [comment]
I think @shahthepro said there was a reason for this?

**Comment by shahthepro** [comment]
> I think @shahthepro said there was a reason for this?

At present, if relayer is down or the transaction failed, graphql doesn't throw an error. It tries to submit the transaction through the normal way via user's wallet. We have no way to notify the DApp that meta transaction failed and it is going to submit a normal transaction. The graphql mutations don't resolve until we get a transaction hash.

@nick suggested that we should just change the message if the user is mobile wallet and meta transaction is enabled.

**Comment by tomlinton** [comment]
Yea the fail case would be exceptional (hopefully).

We could also just change this to something a bit more generic like "Waiting for mobile confirmation" that makes sense if it is a meta tx or the user actually has to do something in the mobile app.
