### ISSUE TITLE
Listener fails to pickup ProxyCreation events

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2619]
The listener subscribes to the events emitted by the ProxyFactor's contract.
See [code](https://github.com/OriginProtocol/origin/blob/master/infra/discovery/src/listener/listener.js#L123).

In production while the listener initially fetches and processes those events upon a restart, it then seems to not pick up fresh events.

**Comment by franckc** [comment]
CC @mikeshultz In case he has any idea what could be going on...

**Comment by franckc** [comment]
The impact is that Origin Rewards is broken because the engine does not know about the actions recorded via the proxy account.

**Comment by mikeshultz** [comment]
I think this is because latest block isn't being set.  Will have a PR up shortly.
