### ISSUE TITLE
Asked to agree to Origin Rewards terms every time I click on Earn OGN

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2624]
I have a user that is already enrolled in Origin Rewards and agreed to the terms. I check there is a growth_auth_token in the local storage.

But every time I click on the "Earn OGN" button on the profile dropdown, I have to agree to the terms again.

Note that if I click on the "Get more" link next to the OGN balance on the profile dropdown, I do NOT have to agree to terms again - I can see the campaigns page right away.

This is reproducible on desktop and mobile.

**Comment by franckc** [comment]
@sparrowDom Do you know what could be wrong ?

**Comment by sparrowDom** [comment]
Resolved by: https://github.com/OriginProtocol/origin/pull/2629

**Comment by franckc** [comment]
Awesome ! Thanks @sparrowDom :)
