### ISSUE TITLE
Identity published in mobile onboarding does not trigger a refetch of identity in the DApp

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#2625]
The DApp looks like it triggers a refetch when it [deploys an identity](https://github.com/OriginProtocol/origin/blob/57f683a6489fb144410b850b64b04840c6cfe041/dapps/marketplace/src/pages/user/Profile.js#L395). The mobile app can't do this so when mobile deploys an identity it sometimes requires a hard refresh of the DApp before the identity displays. I'm not sure of a good solution here but maybe exposing a refetch method on window.appComponent (like for [onLocale](https://github.com/OriginProtocol/origin/blob/master/dapps/marketplace/src/index.js#L66)) might work?

Note I seem to recall that in some cases it displayed an identity without a refresh.

@nick I know you thought #2611 might fix this but it doesn't appear to have.

**Comment by nick** [comment]
Another way would be to trigger an identity query in the dapp from the mobile app... that would cause the cache to get overwritten with the new values. Perhaps using the same mechanism as calling other GraphQL queries from the mobile app?

**Comment by tomlinton** [comment]
The mobile app queries identities every x (5?) seconds to populate the accounts list in the settings. The query is slightly different to the one in the DApp though, I'm not too clear on how GraphQL does caching, I guess the query needs to be exactly the same for it to bust the cache? If that is not true, is the identity dropdown in the DApp nav responsive to changes in the cache or does the identity refetch need to be explicitly called?

**Comment by tomlinton** [comment]
@nick suggested calling `window.gql.reFetchObservableQueries()` after deploying the identity.

**Comment by tomlinton** [comment]
We may remove native onboarding which would render this issue irrelevant so I'd wait until the outcome of that discussion before doing any work on this issue!

**Comment by micahalcorn** [comment]
No longer relevant post-https://github.com/OriginProtocol/origin/issues/2731 🤞
