### ISSUE TITLE
Origin catcher setup

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#2626]
I am trying to get Origin catcher running. I am probably missing something.... yarn starts serving react-native nicely and the following is running in x-code simulator. Any ideas what I could be missing?

https://www.youtube.com/watch?v=QIy5T7KhbVU&feature=youtu.be

**Comment by tomlinton** [comment]
Video is unavailable? What are you seeing, an error?

**Comment by sparrowDom** [comment]
my bad, had it on `private`. Now it should be available.

**Comment by tomlinton** [comment]
I have never seen that growth issue. You on a fully up to date `master` branch? What simulator?

After the import you should get bounced back to the email screen if the account doesn't have an email attestation. You have to do the attestation to proceed.

**Comment by sparrowDom** [comment]
Sumulator Version 10.2.1, simulating iPhone X. Yup that was on up to date master.

**Comment by tomlinton** [comment]
Same simulator here and can't reproduce. I guess it was either something with your setup or the issue was solved in the meantime. 🤷‍♂

Let me know if it happens again.

**Comment by sparrowDom** [comment]
So the problem was that the identity data persisted in the local storage of the simulator was of an older format: 
```
{ 
  emailAttestation: null,
  phoneAttestation: null,
  noRewardsDismissed: false,
  growth: null,
  complete: false,
  firstName: 'Franck',
  lastName: 'on Staging',
  verifiedAttestations: [],
  avatarUri: 'ipfs://QmNeRFHEKcWKqUvBf2JeGZU4JotApSU6NA1HyjaSE4V2mj'
}
```

Seems that when the data format changes in the Redux the persisted data is not migrated. Reopening ticket in case you want to handle this case.

**Comment by tomlinton** [comment]
Thanks for clarifying, are you getting an error in react native debugger or in xcode? That identity data is not used like that directly.

**Comment by sparrowDom** [comment]
I assumed that t[his part of the code](https://github.com/OriginProtocol/origin/blob/master/mobile/src/Store.js#L60-L69) persists stuff to SSD on phones. I have console logged the state from the above comment inside [this reducer](https://github.com/OriginProtocol/origin/blob/master/mobile/src/reducers/Onboarding.js).

**Comment by tomlinton** [comment]
Do you think you could attach it to react-native debugger and find the error on latest master? That'd be a big help.

**Comment by sparrowDom** [comment]
The error is because of the persisted old format identity I have posted above. The latest code is expecting `indentity.attestations` to be an array and does a [spread in the reducer](https://github.com/OriginProtocol/origin/blob/master/mobile/src/reducers/Onboarding.js#L21). If you have and old format identity stored on your device it will throw an error that it can not use a spread operator on `undefined`. 

So the problem is on any device that has an old identity persisted. I assume when the format of any persisted data changes a data migration would be needed. Or there is a risk of bricking the app and requires uninstall/reinstall.

**Comment by sparrowDom** [comment]
Oh and I can not debug it anymore, because I have cleared the storage in simulator by doing a factory reset.... which has resolved the issue for me. sorry :/

**Comment by tomlinton** [comment]
Hmm yea, that should cause a hard crash though, rather than what was in the video.

**Comment by tomlinton** [comment]
Will update with a fix for that anyway, hopefully that growth issue is gone!

**Comment by sparrowDom** [comment]
nice! Will report if I come across any new issues
