### ISSUE TITLE
Onboarding process error

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#2628]
When I try to purchase a listing with a fresh account I am presented with email onboarding form even though I have already onboarded. To reproduce: 
- have a fresh empty account
- click on one of the listings and try to purchase it
- complete email & profile verifications (don't know if it matters I only put first+last name and no picture)
- after that the email onboarding screen is present again: 
<img width="1083" alt="Screenshot 2019-07-03 21 30 32" src="https://user-images.githubusercontent.com/579910/60668756-fffdf200-9e6c-11e9-9524-652187e82388.png">

**Comment by sparrowDom** [comment]
I might have miss assigned. @shahthepro were you doing this part?

**Comment by shahthepro** [comment]
@sparrowDom Yep, I was working on this. And I submitted a fix for this with PR #2611. Is this on staging or local?

**Comment by sparrowDom** [comment]
I have this problem on local

**Comment by sparrowDom** [comment]
If you can no longer reproduce it on local, we should probably close it?

**Comment by shahthepro** [comment]
Yeah, that change is on staging and it's not reproducible on staging now. Closing this.

**Comment by sparrowDom** [comment]
nice thanks @shahthepro 🎉
