### ISSUE TITLE
Add sticky alert inviting translators to contribute

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#269]
Once localization functionality has been deployed with machine translations, we need to show an alert that invites contributors to improve our translations. Our [Alert component](https://github.com/OriginProtocol/demo-dapp/blob/master/src/components/alert.js) should be used for this, and it will probably require some modifications to meet our requirements:

- [x] Only render when English is not the selected language
- [x] Not automatically disappear after two seconds
- [x] Be dismissible on click
- [x] Have a button linking to our [translation interest form](https://goo.gl/forms/qooAg36lpN07GCVJ2)

**Comment by davecraige** [comment]
Copy pass: "You are viewing a machine translated version of this page. It probably has some mistakes. If you would like to assist us in fixing some of these errors please [click here](Google.com) for more information.

**Comment by micahalcorn** [comment]
This is currently living in the [translators-alert](https://github.com/OriginProtocol/origin-dapp/commits/translators-alert) branch. We need to decide whether or not we are going to do machine translations before committing to the copy. cc @jordajm

**Comment by micahalcorn** [comment]
Hey, @pdandradeb, are you still working on this or can someone else pick it up?

**Comment by drewmo** [comment]
@micahalcorn I can take a stab at this. Should local storage be used to not keep asking people after they dismiss the notification?

**Comment by micahalcorn** [comment]
@drewmo I think it's probably best to do this in dapp2 also. You might run that by @nick or @cuongdo before starting on it.

**Comment by drewmo** [comment]
@micahalcorn who should review the pull request to resolve this?
