### ISSUE TITLE
Pagination Off-By-Two

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2702]
With the introduction of the ["Earn Origin Tokens"](https://github.com/OriginProtocol/origin/issues/2605) and ["Your Listing Here"](https://github.com/OriginProtocol/origin/issues/2606) cards on the home page, we're no longer displaying a multiple of four items in the grid. This may become less apparent if we move forward with [a masonry layout](https://github.com/OriginProtocol/origin/issues/2409), but right now it looks funky on desktop browsers.

**Comment by shahthepro** [comment]
@micahalcorn This has been fixed with PR #2692

**Comment by micahalcorn** [comment]
Oh, okay, great 🙂 I didn't see that one.
