### ISSUE TITLE
Account Lost On Messages Screen

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2714]
**Symptom**

While looking at the top-level messages route that lists all of the conversations, the list disappears (except for the conversation from Origin Support) and clicking on the avatar in the top right corner reveals "Hold on while we load your identity..." despite it being present when the screen was initially loaded.

**Steps To Reproduce**

1. Import a wallet using the Origin Support private key.
1. Go through native onboarding.
1. Wait to see the Origin Logo in the avatar spot in the top right.
1. Open the hamburger menu.
1. Click "Messages".
1. Watch the screen for a minute.

**Comment by micahalcorn** [comment]
This also happens on the conversation screen (one level deeper). 💬

**Comment by micahalcorn** [comment]
Actually, I haven't seen this happen in Coinbase Wallet, but I don't have a power user account there with a lot of messages. Could this be something specific to our webview➡️native connection, or more likely a graphql problem? cc @tomlinton

**Comment by tomlinton** [comment]
This doesn't happen on desktop? At that point everything is happening in the dapp except for calls to `eth.getAccounts`. If something goes wrong with that call it might somehow trigger an identity reload.

**Comment by micahalcorn** [comment]
I haven't seen it happen on desktop. 😐

**Comment by micahalcorn** [comment]
See additional comments on https://github.com/OriginProtocol/origin/issues/2716#issuecomment-524048327 😕

Also, today I was in the middle of replying to a message and my conversations and identity got lost. The identity came back, but the messages didn't.

**Comment by micahalcorn** [comment]
Moving this up 🔝

**Comment by mikeshultz** [comment]
This done now?  Rumor has it @shahthepro released pagination.

**Comment by micahalcorn** [comment]
I think so. 🤞
