### ISSUE TITLE
Account Not Loading From Messages Screen

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2716]
Probably related to #2714, refreshing the conversations list (Messages screen) causes the identity to be lost. This results in the conversations never being found (other than the fake one from Origin Support).

**Comment by micahalcorn** [comment]
This just happened to me on navigation from the home screen (rather than on direct page load via refresh). 😬

**Comment by micahalcorn** [comment]
Actually, I haven't seen this happen in Coinbase Wallet, but I don't have a power user account there with a lot of messages. Could this be something specific to our webview➡️native connection, or more likely a graphql problem? cc @tomlinton

**Comment by shahthepro** [comment]
@micahalcorn I fiddled around this bug. Seems like it happens on all mobile DApp browsers. The problem is that the identity loading takes some time on mainnet. Most likely due to missing cache. If you wait for a minute or so, the identity and messages load (but it doesn't happen always either. Perhaps because of timeout while looking for IPFS Hash?).

**Comment by shahthepro** [comment]
@micahalcorn I had been checking out this issue again today. I remember @franckc telling me that @mikeshultz is working on PR that will push blockchain events to DB. If we plan to query these events from DB rather than hitting the blockchain, this delay should be drastically reduced.

**Comment by mikeshultz** [comment]
For the sake of future decentralized mode(I'd really not like to diverge too far from that possibility if possible), I don't think waiting on EC DB is a good play here.  If the identity is that heavy to load, maybe we should be looking into splitting up the queries or something.  

I'm going to be bug hunting this week, let me know if you'd like me to take a deeper look at this.

**Comment by shahthepro** [comment]
> For the sake of future decentralized mode(I'd really not like to diverge too far from that possibility if possible), I don't think waiting on EC DB is a good play here. If the identity is that heavy to load, maybe we should be looking into splitting up the queries or something.

Agree with that. It does work as of now. But takes some time (both identity and the conversations).

> I'm going to be bug hunting this week, let me know if you'd like me to take a deeper look at this.

Thanks. It'd be great if you can take a look at this. A different perspective is always welcome.

**Comment by mikeshultz** [comment]
@micahalcorn, is this mobile app only?  If not, you got repro steps?

**Comment by micahalcorn** [comment]
@mikeshultz I think @shahthepro said that it is.

**Comment by mikeshultz** [comment]
Curious, when I opened the mobile app, it wouldn't load my identity at all.  It wasn't until I went to the "Test Builds" link and going back that it loaded.  Since then it's snappy(cache?).

![origin-identity_load_issue](https://user-images.githubusercontent.com/1048089/62487262-9b40fa80-b77e-11e9-90e2-aa24d55d61f7.png)

**Comment by shahthepro** [comment]
@mikeshultz Yep, it is mobile only. You have do a "pull-to-refresh". The identity loading takes some time on mainnet.

> Curious, when I opened the mobile app, it wouldn't load my identity at all. It wasn't until I went to the "Test Builds" link and going back that it loaded. Since then it's snappy(cache?).

I believe we do have 10s timeout for loading the data from IPFS. If it goes beyond that, there will be an error logged in the console. But it is not shown anywhere in the DApp though

**Comment by mikeshultz** [comment]
I'm unable to repro this on the Android mobile app with the latest code.  I've uninstalled, reinstalled, created new accounts, tried on wifi and LTE.  Nothing.  I can only imagine this is either an IOS-only issue, or just a temporary network error.  Perhaps raising the timeout could do something, but 10s seems like more than enough.

In my tests, on mainnet and rinkeby, I saw no load times >~1s

**Comment by shahthepro** [comment]
@mikeshultz It might be specific to that account. I can share the private key of that account in DM, if @micahalcorn is fine with it.

**Comment by mikeshultz** [comment]
I really hate the idea of sharing private keys, but if you both really think it's unique to this account, I guess.  @micahalcorn, hit me up on discord and we can figure out a way to secure exchange the key.

**Comment by mikeshultz** [comment]
So, I have seen this issue now using the account mentioned.  Looks like it has to wait on over a hundred requests.  event-cache is making 284 requests to get logs here.  And it's super-speedy after initial load.

I haven't actually seen it not load, but it does take some time.  

One thing that can be done here is to update the IPFS cached event logs.  I'd also like to figure out exactly what this profile card needs there(attestation data?).  See if maybe it can be integrated into performance mode, or better yet, start loading event logs on iniial dapp load. 

Will dig into this further on Monday and see what the best course of action is here.  While it may only currently effect an internal account, this is probably something good to head off before we have power users.

**Comment by mikeshultz** [comment]
PR #2986 should take care of this(and maybe #2714).  It'll go live on next prod deploy.

**Comment by mikeshultz** [comment]
That PR was merged last week.  Could you test again and if fixed close?

**Comment by micahalcorn** [comment]
Not directly related, but I still get "No conversations" for several seconds before anything is loaded. I thought that was mentioned in an issue somewhere, but now I can't find it. 🤔

**Comment by micahalcorn** [comment]
On at least one occasion, I was stuck at "No conversations!" and it never updated. 😕 I can't seem to reproduce that very easily.

**Comment by mikeshultz** [comment]
I thought @shahthepro was looking into conversation/messages loading performance.  Maybe I just closed up #2714?  I don't know, seems like 2 separate issues combined to make 2 separate GH issues.

**Comment by micahalcorn** [comment]
@mikeshultz I just watched a few of my conversations roll in and then it fell back to "No conversations!" for life. ☠️

**Comment by shahthepro** [comment]
@micahalcorn @mikeshultz Yes, I'll be doing some changes related to messaging. I'll address these "Loading..." and "No conversations." issues in the DApp with that one.

**Comment by micahalcorn** [comment]
It's a bit clunky, but the identity does seem to load each time. Thanks @mikeshultz 🙏
