### ISSUE TITLE
Spinner > "Loading..."

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2720]
Replace instances of "Loading..." in [the marketplace DApp](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/src) (where visually appropriate) with the [`LoadingSpinner`](https://github.com/OriginProtocol/origin/blob/db6060c48fc3ba44513873ab6e371d8827fddced/dapps/admin/src/components/LoadingSpinner.js). 😑

**Comment by rtman** [comment]
I'll have a look at this one to start.

**Comment by rtman** [comment]
@micahalcorn  tom said that the linked [LoadingSpinner ](https://github.com/OriginProtocol/origin/blob/db6060c48fc3ba44513873ab6e371d8827fddced/dapps/admin/src/components/LoadingSpinner.js) above is not in the dependencies for marketplace. Is this [LoadingSpinner ](https://github.com/OriginProtocol/origin/blob/db6060c48fc3ba44513873ab6e371d8827fddced/dapps/marketplace/src/components/LoadingSpinner.js) useable as a replacement?

**Comment by micahalcorn** [comment]
Ah, sorry, I linked that recklessly. Try [this one](https://github.com/OriginProtocol/origin/blob/db6060c48fc3ba44513873ab6e371d8827fddced/dapps/marketplace/src/components/LoadingSpinner.js).

**Comment by rtman** [comment]
thanks @micahalcorn I'll get it implemented

**Comment by micahalcorn** [comment]
Resolved by #2769 ✅
