### ISSUE TITLE
ipfs-proxy ERROR: pull access denied for origin

### ISSUE THREAD

**Issue by enrutador** [OriginProtocol/origin#2724]
Congratulations for your great work!

I am testing your software in a private blockchain environment using the Quorum blockchain. I want to run the platform in a private environment and I want to use the local docker.

Once the repository is cloned and following the indications of the manual https://docs.originprotocol.com/guides/getting_started/local-development.html. When I launched the command "docker-compose up"
I get the following error:

```
Creating network "origin_default" with the default driver
Pulling postgres (postgres:10.0)...
10.0: Pulling from library/postgres
3e17c6eae66c: Pull complete
edb9dc1cfcb8: Pull complete
7a344e5b3663: Pull complete
d619f9c5def6: Pull complete
225b82de1e67: Pull complete
10daa23c1d9a: Pull complete
4ba4a4b2d69b: Pull complete
3fc3e282a06c: Pull complete
db8508199c1a: Pull complete
99445470b9b6: Pull complete
dd01bf2076d4: Pull complete
292c6e56e62f: Pull complete
7a07813393c7: Pull complete
Digest: sha256:95e54755cb3a59a56dc2d98d8e8a0b4436537185c7b240eb140069208ec35e22
Status: Downloaded newer image for postgres:10.0
Pulling ipfs-proxy (origin:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling ipfs-proxy (origin:)...
ERROR: pull access denied for origin, repository does not exist or may require 'docker login'
```

Is there some kind of access that does not allow the use of this plugin? Is it my mistake in the configuration? My IPFS system would also be private.

LIB:
Docker version 18.06.1-ce, build e68fc7a
docker-compose version 1.22.0, build unknown

SO:
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco

Thank you

**Comment by tomlinton** [comment]
Hi @enrutador, thanks for raising this issue!

It sounds like you probably ran `docker-compose up ipfs-proxy` instead of `docker-compose up`, is that right? You need to run `docker-compose up` so that the `origin` image gets built (which ipfs-proxy depends on). You could also achieve this by running `docker-compose build` first.

**Comment by enrutador** [comment]
Hi tomlinton
With `docker-compose build`  solve the problem , It start all services:
```
redis-master is up-to-date
Starting elasticsearch ...
postgres is up-to-date
ipfs-proxy is up-to-date
Starting elasticsearch ... done
Starting bridge         ... done
Starting notifications  ... done
Starting messaging      ... done
Starting growth         ... done
Starting event-listener ... done
Starting discovery      ... done
Creating graphql        ... done

```
But don´t startup the admin interface http://localhost:3000.

I tested it on a clean computer , the instalation was perfect(whitout any previus error) , but the same thing, don´t start admin interface on port 3000

```
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000025s latency).
Not shown: 991 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
4000/tcp open  remoteanything
4001/tcp open  newoak
4002/tcp open  mlchat-proxy
5000/tcp open  upnp
5002/tcp open  rfe
5432/tcp open  postgresql
8080/tcp open  http-proxy
9999/tcp open  abyss
```

Thanks

**Comment by tomlinton** [comment]
Great! The admin interface is not part of the `docker-compose` config. That will need to be started separately.
