### ISSUE TITLE
[Mobile onboarding] Email verification not saved in identity

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2751]
- Installed Origin App v0.16.6 on my iPhone 6S.
- Created a new wallet, entered my name + picture and verified my email
- Entered my phone but skipped verification
- My name+pic got saved but my email verification did NOT get saved in my identity.

Account: 0xd505197bf78515b8849c64834391f7c19883a962
Proxy: 0x46ca8372873dbca1502c26ebe17a50071ad29bc5
IPFS identity blob: https://ipfs.originprotocol.com/ipfs/QmQMT3RZq7VegfnJ9XUecDEqcYDMvsZowszHR1KqWjWws2

I don't know if this was cause by me skipped phone verification? If that helps I could test not skipping it.

**Comment by franckc** [comment]
CC @tomlinton

**Comment by tomlinton** [comment]
Did you do anything with the identity after this? E.g. modifying it in the DApp. I'll try and reproduce now.

**Comment by franckc** [comment]
No, I did not do anything with identity after onboarding.

**Comment by tomlinton** [comment]
Anything else you can remember that might help reproduce? I did two on Rinkeby and one on Mainnet without any luck.

It was the build on the App Store rather than TestFlight?

**Comment by franckc** [comment]
Yes, it is the App Store build.

Hmm... no there was not anything out of the ordinary as far as I can remember.
Let me try to reproduce...

**Comment by franckc** [comment]
Tried again from a fresh install and this time it worked. So not sure what happened yesterday...

**Comment by franckc** [comment]
I just did a cursory check in the DB (table identity) and I did not see any other recent accounts that did not have email... so I probably hit a very rare issue.

**Comment by tomlinton** [comment]
Yea - that was my thought. I remember you asked me about skipping phone, so I thought you might have done like a forward/back swipe and wiped the email attestation while looking for a skip option. I tried a few things but couldn't see a way for that to happen. I guess we just keep an eye out for this.

**Comment by tomlinton** [comment]
Will close this for now. I haven't seen or heard of happening again. Will keep it in mind though.
