### ISSUE TITLE
Listing pictures browsing on desktop: click and keyboard arrows

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#2753]
it would be good to be able to browse pictures by:
- clicking on them
- using the arrows (especially the back arrow is important).

BTW: At the moment the desktop experience has gone worse, the picture is by far too big.
This is what I  see on desktop:
![Screenshot 2019-07-18 at 21 01 47](https://user-images.githubusercontent.com/34341206/61480817-7cc9b980-a99f-11e9-94c9-6c90e21d4fcd.png)

I understand it's mobile first, and it may be hard to make it work on desktop too.

**Comment by micahalcorn** [comment]
@lucadgtrip where are you seeing this? 🤔 The listings that I've looked at don't have this problem.

**Comment by lucadgtrip** [comment]
@micahalcorn https://shoporigin.com/#/listing/1-000-2991-8175142

**Comment by micahalcorn** [comment]
@lucadgtrip ah, yeah, Firefox, it appears. 🦊 Do you mean the arrow keys on the keyboard or hoverable arrows on top of the main image?

I think to change the default behavior of the keyboard arrows, we would want to do https://github.com/OriginProtocol/origin/issues/2412 first.

**Comment by lucadgtrip** [comment]
@micahalcorn arrow keys in keyboard and also hoverable keys, but arrow keys in keyboard are more important in my opinion.
