### ISSUE TITLE
Refresh content of the welcome emails

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2760]
When a new user signs up for the Origin marketplace, we send them 3 emails over the course of a few days after they joined, to welcome them and get them oriented.

We need to update those emails to reflect the latest improvements to our platform.
For example, the fact that the app is now available on Android (the email only points to iOS) and that in most cases users don't have to pay for gas since we launched meta-tx.

See the email templates [here](https://github.com/OriginProtocol/origin-website/tree/master/templates/email).

**Comment by franckc** [comment]
CC @micahalcorn

**Comment by joshfraser** [comment]
Thanks for cleaning these up. Honestly, it's still a pretty horrible experience getting a wall of text as a welcome message (my fault). Next time we touch these, let's make them super light and link to blog posts for anyone who's interested.
