### ISSUE TITLE
Search page for listings with OGN has duplicates

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2762]
On the search page by listings with OGN ([see page](https://dapp.originprotocol.com/#/search?ognListings=true)), scrolling down triggers loading more listings but those listings are just duplicates of the first page. It is likely a pagination related bug for this specific category.

**Comment by franckc** [comment]
CC @sparrowDom

**Comment by sparrowDom** [comment]
Pull Request resolving this issue: https://github.com/OriginProtocol/origin/pull/2795

**Comment by sparrowDom** [comment]
Resolved via: https://github.com/OriginProtocol/origin/pull/2795
