### ISSUE TITLE
Authentication UX Flaw + Security Loophole

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2806]
After previously enabling biometric authentication in our mobile app, follow these steps:

1. Kill the app.
1. Open the app.
1. Wait for marketplace to load.
1. See authentication requirement screen.
1. Fail authentication.
1. **Be stuck not knowing how to retry.**
1. Swipe backward.
1. **_Realize that you have access to the funds._**

Thus...
- [x] "Authentication Failed" should be accompanied by a retry button.
- [x] The authentication screen should be a blocking modal instead of being added to the nav stack.
- [x] Authentication should be required every time the app is opened - including from being backgrounded - not just when it's killed.

**Comment by tomlinton** [comment]
Good catch, bad by me! I think originally it was a switch navigator, but the stack navigator now gets used everywhere to allow the sideloading of the dapp for GraphQL queries.

The first part of this is easy, you can retry by clicking on the failure text, but thats not very clear so I added a button in #2835.

I'll work on fixing the navigation issue.
