### ISSUE TITLE
[Social sharing] Sharing does not work on Android Origin Wallet

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2844]
PR fixing this: https://github.com/OriginProtocol/origin/pull/2857

@sparrowDom Reported that sharing a tweet fails on Android when using Origin Wallet.
![Android bug](https://user-images.githubusercontent.com/945910/62309654-cbb22d00-b43c-11e9-9312-7c4a07ab3658.jpg)

**Comment by sparrowDom** [comment]
A fix for this is located here: https://github.com/OriginProtocol/origin/pull/2857 . The downside is that we need to publish another version of Origin App and this bug will still be present on existing android applications.

**Comment by sparrowDom** [comment]
Done via: https://github.com/OriginProtocol/origin/pull/2857
