### ISSUE TITLE
[SocialSharing] Remove the "Read the article" link

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2850]
Suggestion from @joshfraser:
"let's make the images the same height and clickable. can probably drop the "Read the article" links too if we link the images to the article instead." https://dapp.staging.originprotocol.com/#/campaigns/promotions

CC @micahalcorn @shahthepro @sparrowDom

**Comment by sparrowDom** [comment]
👍 seems more user friendly

**Comment by franckc** [comment]
Implemented in #2863 , thanks to @tomlinton ! :)

**Comment by sparrowDom** [comment]
nice work thanks @tomlinton
