### ISSUE TITLE
[Social Sharing] Twitter share/follow broken on dev and staging environment

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2851]
Our corporate Twitter account is on the free tier and only allows us to run a single environment with subscription webhook enabled. We are using it for the bridge prod server and therefore we can't use it in dev and staging.

The impact is that we can't test tweet post/share verification on dev and staging.

Possible options:
- Upgrade to the paid tier for $4k / year. That will give us a max of 2 environments. So we could have staging and prod working. Seems a bit expensive...
 - We currently store the subscription data in redis. we could try to find a way to tunnel redis lookups made from the bridge on dev/prod to the redis prod environment
 - Store the subscription data in a central store accessible by dev/staging/prod. Maybe some GCP storage like memstore or a redis instance that we run separately and make accessible to dev/staging/prod bridge server

@tomlinton @mikeshultz @shahthepro Any thoughts ?

**Comment by mikeshultz** [comment]
Really not a fan of giving systems cross access to resources that are intended to be for one.  I just smell unexpected issues with that.  I say create a redis instance that stays out of the prod/staging/dev namespaces that is accessible by all.

Maybe even go as far as breaking out the twitter service from bridge into a microservice that implements the twitter webhook from our prod/staging/dev namespaces and offers up the data on an API accessible by all namespaces.

**Comment by franckc** [comment]
As suggested by @tomlinton we'll simply use a different account on staging. It will require adding a few extra env var in EnvKey but that seems the simplest solution.
