### ISSUE TITLE
Attestation Signature Validation Fails

### ISSUE THREAD

**Issue by shahthepro** [OriginProtocol/origin#2856]
### Description
@tomlinton reported [this issue first in this comment](https://github.com/OriginProtocol/origin/issues/2728#issuecomment-514458489). However it seems to be unrelated to #2728 (where DApp was not sending all the data/attestations to GraphQL). In Tom's case, the attestations was sent by DApp to GraphQL where it failed to validate signature.

### Things affected
The user could lose all his existing attestations (but the profile data shouldn't be affected by this)

### Steps to reproduce
Still unclear and not always reproducible. But may happen in the following case:

1. Create a wallet on mobile
2. Do some attestations
3. Import the wallet to MetaMask or some other wallet provider
4. Try to do another attestation.

### Observations
`ecrecover` never fails (if the signature is in the right format). It always returns an(y) address. This could mean that the signature is not of the data we are trying to verify against. 

To make things complicated, we do use `json-stable-stringify` to get deterministic JSON data before signing/verification and also use checksum address. This should always return the same  hash.

**Comment by shahthepro** [comment]
I did investigate @tomlinton's address and all the `IdentityUpdated` events from his own address and proxy address. The data in IPFS (even the old ones) are all valid and returned the correct signer address with `ecrecover`. 

Most likely, the `data` field of existing attestation was somehow mutated in the DApp, which resulted in a different message hash than the signed one. In that case, it should no longer be reproducible since with #2845 DApp is no longer in control of existing data/attestations.

I'm still leaving this open and changing it to P2 for now.

**Comment by tomlinton** [comment]
Thanks for looking into it @shahthepro!

**Comment by mikeshultz** [comment]
Just hypothesizing here, but I'd say make sure the validation is getting done against a real signing account and not the identity proxy.  Since most identity stuff is associated with the proxy address, but the only thing that can sign is the real account. I think there's a possibility that the problem here could be that the signature address matching is comparing the real account address from `ecrecover` to the identity proxy address given.

Just a hunch, I haven't actually looked at the code.

**Comment by shahthepro** [comment]
@mikeshultz Yep, only the real account can sign. But we also have address as a parameter in the JSON data that gets signed. We substitute both proxy as well as owner address in that parameter to see if we get the signer account. In Tom’s case, both failed. I had left a few comments regarding this on #2728

**Comment by shahthepro** [comment]
Closing this now since it hasn’t popped up for a while. Feel free to open if anyone encounters it.
