### ISSUE TITLE
Duplicate Messaging Email Notification

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2867]
We're getting 2 emails for every message that is sent to the Origin Support account. The account in question is `0xBfDd843382B36FFbAcd00b190de6Cb85ff840118` and the receiving email address is `support@originprotocol.com`.

**Comment by micahalcorn** [comment]
I have a suspicion here. 🤔 It seems that the duplicate email notification only results from the first message in the conversation. Subsequent messages only produce a single email notification. I think that the first message in the data object is actually the exchange of the asymmetric key. So it should be ignored and only the first "real message" should result in a notification. Does that sounds right @DanielVF @mikeshultz?

A separate, more generalized solution for this would just be to delay the notifications and send one referring to N new messages from this person. This would lead to another improvement that we've discussed before: refraining from sending notifications for messages that have been read [once we are detecting that](https://github.com/OriginProtocol/origin/issues/2255).

**Comment by mikeshultz** [comment]
You remember that super secret ID we added to E-mails?  Could you add them here for the duplicate messages?

**Comment by micahalcorn** [comment]
@mikeshultz 👇 

- `0x823b9d35552a0d6c417ad7cc21bf4b7c3851813ddc483f4e7bb4bc6d899abf5c`
- `0x288c19640ad899022da6d8f8e3b239ab23ef61eda6c9a23bcefe5e428baa23cd`
- `0x7a4b88f5297fad4bed10c71473da42850eb2165e842fe2c78323dc35af6ca22a `

**Comment by mikeshultz** [comment]
@micahalcorn when was this and which network?

**Comment by mikeshultz** [comment]
These are unique messages but I think your suspicion might be spot on.  Two of the messages come within 0.2s of each other and one is marked as being keys:

     is_keys |         created_at         
    ---------+----------------------------
     t       | 2019-08-06 20:45:22.494+00
     f       | 2019-08-06 20:45:22.648+00
     f       | 2019-08-06 20:55:36.642+00
    (3 rows)

Key exchanges shouldn't cause a notification, so I'm going to look into this and see if we can squash it.

**Comment by DanielVF** [comment]
Yeah, the simple solution is just don't send out emails for keys.

However, we should not do this by position, there's nothing protocol-wise stopping additional keys being sent during the flow, and the client is coded to try all the keys it has seen. 

It's easy to spot the key messages though - they have a ".type" of "keys". See:

https://github.com/OriginProtocol/origin/blob/master/packages/messaging-client/src/Messaging.js#L411-L414

**Comment by micahalcorn** [comment]
Good point @DanielVF 👍 I think we were planning to add an "expire/replace my key" feature so that arbitrators can't continue to eavesdrop on the conversation after resolving a dispute.

**Comment by mikeshultz** [comment]
We good to close this now?  I'm thinking the keys message might have dealt with this and I don't recall any more mentions of this in the last month or so.

**Comment by mikeshultz** [comment]
Closing for lack of response.  I be stalebot.
