### ISSUE TITLE
Origin Box - Graphql provider issue

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2889]
Provider appears to be set wrong for the local docker-compose graphql server.  It goes crazy trying and retrying queries to the wrong destination.

    graphql           | { [Error: request to http://services:8545/ failed, reason: getaddrinfo ENOTFOUND services services:8545]
    graphql           |   message:
    graphql           |    'request to http://services:8545/ failed, reason: getaddrinfo ENOTFOUND services services:8545',
    graphql           |   code: -32603 }
    graphql           | retrying request method:  eth_blockNumber
    graphql           | retrying request method:  eth_blockNumber

**Comment by mikeshultz** [comment]
Actually, it's the right destination, not sure why it's failing yet.

**Comment by tomlinton** [comment]
That sounds like the services container isn't running perhaps? Docker should resolve it if it is.

**Comment by mikeshultz** [comment]
Yeah, appears to be another race.  PR #2889 should fix that adding yet another `wait-for.sh` command

**Comment by tomlinton** [comment]
I really wish `docker-compose` had its container ordering config!

**Comment by mikeshultz** [comment]
Doesn't it support ordering with `depends_on`?  Or does that not wait for the service to be ready?  I've always wondered the story behind `wait-for.sh`.

**Comment by tomlinton** [comment]
Yea that is only a container up check, not the service the container runs check. The services container takes a fair bit of time after the container is up to get things running. 

So `depends_on` is practically useless. 😁
