### ISSUE TITLE
Floating Footer Blocking Send Message Button

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2933]
![Screen Shot 2019-08-12 at 11 28 44 AM](https://user-images.githubusercontent.com/273937/62888602-7c99b100-bcf4-11e9-8c43-8a69bbe23d23.png)

I think we could get away with just collapsing it to be only the ellipses on that route. 💬

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment]
Hi Kristofer, here is an issue that could be good for you to become familiar with our DApp. Do you want to take a look at it ? Please do feel free to ping us on the engineering channel in Discord in case you have any question !

**Comment by wperingbart** [comment]
Alrigt @franckc

**Comment by franckc** [comment]
Fixed by #2950
