### ISSUE TITLE
Bring Back Origin Messaging Requirement

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2936]
In order to support #1653, we need to bring Origin Messaging back to user activation. This means that when a user expresses intent to buy, sell, or contact another user, she should be required to go through the following:

1. Be web3-enabled (install MetaMask, or be in a mobile wallet)
1. Verify an email address
1. Create a profile (name only required, I think)
1. Enable Origin Messaging (not applicable in Origin Marketplace)
1. Sign up (or skip) for Origin Rewards
1. Be congratulated on success

For steps 1-4, the user should be forced to return to this flow if she expresses intent again after abandoning it. For the final two steps, they should just be shown once each.

Here is the latest set of mockups that I can recall for this

- [mobile](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/dashboard?seid=5cdf37a2c2475c1e2bf5114f)
- [desktop](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/dashboard?seid=5cc8c8cdcf972734ba4cedc9)

The components should be recoverable from older commits here in the repo. We'll probably want to revisit some of the visual design.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment]
@sparrowDom This is the messaging feature request that is top priority on the product stack ranked list (after website redesign but that won't be ready to start for at least a week...).

**Comment by micahalcorn** [comment]
It's worth noting that, in addition to the necessity for the shipping address feature, we have continued to get a high proportion of sellers requesting a method for contacting their buyers who did not enable messaging during the last couple of months. 💔

**Comment by micahalcorn** [comment]
See also https://github.com/OriginProtocol/origin/issues/1940

**Comment by sparrowDom** [comment]
nice this is the next thing in my pipeline after the native Origin Wallet facebook sdk

**Comment by sparrowDom** [comment]
Resolved by: https://github.com/OriginProtocol/origin/pull/3100
