### ISSUE TITLE
Let Enter send messages in messaging

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2940]
The Enter key should send messaging in the conversation window of messaging in the dapp.  Shift+Enter or ctrl+enter should allow for a newline.

cc @franckc

**Comment by franckc** [comment]
Thanks @mikeshultz for filing this. I've added it to my list of potential good first issues...

**Comment by franckc** [comment]
Hi @wperingbart - would you be ok looking into this issue ? Hopefully should be fairly straight forward.

**Comment by wperingbart** [comment]
sure

**Comment by wperingbart** [comment]
@mikeshultz browser blocks the new line of textarea when you use Ctrl + enter.
is it ok just working with shift key?

**Comment by mikeshultz** [comment]
@micahalcorn might have more say in this, but I'd much rather be able to just use the enter key to send.

**Comment by wperingbart** [comment]
I meant use shift+enter to send.
and otherwise enter sends message
@mikeshultz @micahalcorn

**Comment by mikeshultz** [comment]
Not sure I follow.  shift+enter to send but enter sends.  eh?

**Comment by micahalcorn** [comment]
What is the complication using `control+return` to produce a new line? It works on Facebook. 😕

**Comment by wperingbart** [comment]
sorry. I meant shift+enter for new line}
@mikeshultz

**Comment by wperingbart** [comment]
@micahalcorn 
pls read the following
https://stackoverflow.com/questions/8187512/textarea-control-custom-behavior-enter-ctrlenter

pls let me know if you can find out any solution

**Comment by mikeshultz** [comment]
So, this is what you mean?

- `Enter` to send
- `Shift+Enter` for newline

If so, that fits the original requirements.

**Comment by wperingbart** [comment]
yup @mikeshultz 
but Ctrl + Enter doesn't trigger anything (send or newline) by default.

**Comment by franckc** [comment]
Fixed via #2973
