### ISSUE TITLE
Public User Profile Contact Styling

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2964]
Replace "Contact user" with a "Contact" button.

**Good**

<img width="405" alt="contact-good" src="https://user-images.githubusercontent.com/273937/62996698-6554e380-be1a-11e9-85d2-4342359988c1.png">

**Less Than Good**

![contact-bad](https://user-images.githubusercontent.com/273937/62996707-6b4ac480-be1a-11e9-9b56-f965d47392a0.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by sudheerDev** [comment]
Hey @micahalcorn, i would like to work in this

**Comment by micahalcorn** [comment]
Great 👍 Join us in [Discord](https://originprotocol.com/discord) and let us know what questions you have.

**Comment by sudheerDev** [comment]
@micahalcorn Submitted a PR
