### ISSUE TITLE
White screen on Origin Wallet when doing Telegram Attestation

### ISSUE THREAD

**Issue by shahthepro** [OriginProtocol/origin#2970]
When doing Telegram Attestation on Origin Wallet, switching back to the Origin Wallet from Telegram app results in a white screen of death. 

This might be [because of this line here](https://github.com/OriginProtocol/origin/blob/master/dapps/marketplace/src/pages/user/Profile.js#L297-L299). However, even refreshing the page doesn't load anything until you kill and restart the app.

**Comment by micahalcorn** [comment]
It sounds like this is the same as #2983, yeah? 🏳️

**Comment by shahthepro** [comment]
@micahalcorn Yeah. It is not specific to Telegram attestation.
