### ISSUE TITLE
Failing Rewards Redirect

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2981]
The "New Ways to Earn OGN in August" link points to originrewards.com but is failing to redirect. It results in the browser's default screen for a non-existent page. That one in particular actually redirects to `/welcome`, so we may just want to point it there. But we should probably figure out why the redirect isn't working. If I type originrewards.com into a browser manually, it works fine.

<img width="1228" alt="Screen_Shot_2019-08-15_at_1 53 16_PM" src="https://user-images.githubusercontent.com/273937/63126361-93ded580-bf64-11e9-8c57-cb96bff550bd.png">

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by sparrowDom** [comment]
@micahalcorn it doesn't work because the redirect (code 302 )works as expected for `http` but not `https`. A better fix would be to enable redirect on `www.originrewards.com` for https also. This can probably be done in domain settings. 

Who has access to this? Maybe @franckc or @tomlinton ?

**Comment by tomlinton** [comment]
It looks like it resolves to `216.239.32.21` which isn't one of our Kubernetes addresses. @joshfraser  maybe you set this up using a redirect service?

**Comment by joshfraser** [comment]
We are redirecting using the forwarding feature of Google Domains. I've fixed this to include SSL traffic. Should work once the cached TTL's expire.

**Comment by sparrowDom** [comment]
It is working now for me 👍
