### ISSUE TITLE
Standardize listing location format

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#300]
Currently when creating a new listing, the location is a free text field. Origin.js does not enforce neither any sort of standard formatting/schema for the location. 

In order to be able to index the data and implement search based on listing location (ex: search for listings in a particular country, state or city, or within a given geographic radius), we need to standardize the location data. One idea would be to store in the listing location both:
 - normalized address format
 - (latitude, longitude)

One possible solution would be to have the DApp integrate with Google Maps APIs or any other similar service that provides similar functionalities. In addition, we could also add some validation at the Origin.js layer to enforce that new listings are created with a valid location.

**Comment by ambertch** [comment]
In terms of other services, I looked into using Open Street Maps as part of https://github.com/OriginProtocol/origin-dapp/issues/37

One nice thing about OSM is that it is an open source project and the server that runs the website/service/DB is open source.

However, testing against addresses showed lower lookup success rate than Google Maps API (OSM DB is populated and maintained by volunteers).

**Comment by tomlinton** [comment]
I use Google Places for this in a production system. It's great most of the time, but some addresses can cause mayhem (mostly those with apartment numbers). I tested out OSM and like you say @ambertch the success rate isn't great in comparison. 

I'm not sure if any of the listings will require exact addresses? If only surbub level resolution is required OSM should hopefully work!

**Comment by micahalcorn** [comment]
Resolved (for Housing listings) by https://github.com/OriginProtocol/origin/pull/3797 ✅
