### ISSUE TITLE
Twitter window for attestation opens blank page if auth URL not set

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#304]
The auth URL for Twitter is requested [when the twitter attestation modal is opened](https://github.com/OriginProtocol/origin-dapp/blob/master/src/pages/profile/VerifyTwitter.js#L13-L19) but it is possible to click the continue button prior to the response. This will cause a [new window to open with a blank page](https://github.com/OriginProtocol/origin-dapp/blob/master/src/pages/profile/VerifyTwitter.js#L73).

Some options to resolve this are disabling the continue button or using a loading indicator on the continue button if the user clicks it prior to the auth URL being set.

Edit: this also applies to the Facebook attestation.

**Comment by concerned3rdparty** [comment]
i tried to reproduce this bug in develop branch but npm run start gives these errors : 

> messaging-provider.js:47 Uncaught TypeError: Cannot read property 'events' of undefined
    at MessagingProvider.componentDidMount (messaging-provider.js:47)
    at commitLifeCycles (react-dom.development.js:14361)
    at commitAllLifeCycles (react-dom.development.js:15462)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at commitRoot (react-dom.development.js:15603)
    at completeRoot (react-dom.development.js:16618)
    at performWorkOnRoot (react-dom.development.js:16563)
    at performWork (react-dom.development.js:16482)
componentDidMount @ messaging-provider.js:47
commitLifeCycles @ react-dom.development.js:14361
commitAllLifeCycles @ react-dom.development.js:15462
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:15603
completeRoot @ react-dom.development.js:16618
performWorkOnRoot @ react-dom.development.js:16563
performWork @ react-dom.development.js:16482
performSyncWork @ react-dom.development.js:16454
requestWork @ react-dom.development.js:16354
scheduleWork$1 @ react-dom.development.js:16218
scheduleRootUpdate @ react-dom.development.js:16785
updateContainerAtExpirationTime @ react-dom.development.js:16812
updateContainer @ react-dom.development.js:16839
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:17122
(anonymous) @ react-dom.development.js:17262
unbatchedUpdates @ react-dom.development.js:16679
legacyRenderSubtreeIntoContainer @ react-dom.development.js:17258
render @ react-dom.development.js:17317
./src/index.js @ index.js:9
__webpack_require__ @ bootstrap:61
0 @ translationUtils.js:305
__webpack_require__ @ bootstrap:61
(anonymous) @ bootstrap:178
(anonymous) @ bootstrap:178
react-dom.development.js:14226 The above error occurred in the <MessagingProvider> component:
    in MessagingProvider (created by InjectIntl(MessagingProvider))
    in InjectIntl(MessagingProvider) (created by Connect(InjectIntl(MessagingProvider)))
    in Connect(InjectIntl(MessagingProvider)) (created by Route)
    in Route (created by withRouter(Connect(InjectIntl(MessagingProvider))))
    in withRouter(Connect(InjectIntl(MessagingProvider))) (created by App)
    in Web3Provider (created by Connect(Web3Provider))
    in Connect(Web3Provider) (created by Route)
    in Route (created by withRouter(Connect(Web3Provider)))
    in withRouter(Connect(Web3Provider)) (created by App)
    in ScrollToTop (created by Route)
    in Route (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop) (created by App)
    in Router (created by HashRouter)
    in HashRouter (created by App)
    in IntlProvider (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:14226
logError @ react-dom.development.js:14265
update.callback @ react-dom.development.js:14918
callCallback @ react-dom.development.js:10878
commitUpdateQueue @ react-dom.development.js:10911
commitLifeCycles @ react-dom.development.js:14396
commitAllLifeCycles @ react-dom.development.js:15462
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:15603
completeRoot @ react-dom.development.js:16618
performWorkOnRoot @ react-dom.development.js:16563
performWork @ react-dom.development.js:16482
performSyncWork @ react-dom.development.js:16454
requestWork @ react-dom.development.js:16354
scheduleWork$1 @ react-dom.development.js:16218
scheduleRootUpdate @ react-dom.development.js:16785
updateContainerAtExpirationTime @ react-dom.development.js:16812
updateContainer @ react-dom.development.js:16839
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:17122
(anonymous) @ react-dom.development.js:17262
unbatchedUpdates @ react-dom.development.js:16679
legacyRenderSubtreeIntoContainer @ react-dom.development.js:17258
render @ react-dom.development.js:17317
./src/index.js @ index.js:9
__webpack_require__ @ bootstrap:61
0 @ translationUtils.js:305
__webpack_require__ @ bootstrap:61
(anonymous) @ bootstrap:178
(anonymous) @ bootstrap:178
messaging-provider.js:47 Uncaught TypeError: Cannot read property 'events' of undefined
    at MessagingProvider.componentDidMount (messaging-provider.js:47)
    at commitLifeCycles (react-dom.development.js:14361)
    at commitAllLifeCycles (react-dom.development.js:15462)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at commitRoot (react-dom.development.js:15603)
    at completeRoot (react-dom.development.js:16618)
    at performWorkOnRoot (react-dom.development.js:16563)
    at performWork (react-dom.development.js:16482)
componentDidMount @ messaging-provider.js:47
commitLifeCycles @ react-dom.development.js:14361
commitAllLifeCycles @ react-dom.development.js:15462
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:15603
completeRoot @ react-dom.development.js:16618
performWorkOnRoot @ react-dom.development.js:16563
performWork @ react-dom.development.js:16482
performSyncWork @ react-dom.development.js:16454
requestWork @ react-dom.development.js:16354
scheduleWork$1 @ react-dom.development.js:16218
scheduleRootUpdate @ react-dom.development.js:16785
updateContainerAtExpirationTime @ react-dom.development.js:16812
updateContainer @ react-dom.development.js:16839
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:17122
(anonymous) @ react-dom.development.js:17262
unbatchedUpdates @ react-dom.development.js:16679
legacyRenderSubtreeIntoContainer @ react-dom.development.js:17258
render @ react-dom.development.js:17317
./src/index.js @ index.js:9
__webpack_require__ @ bootstrap:61
0 @ translationUtils.js:305
__webpack_require__ @ bootstrap:61
(anonymous) @ bootstrap:178
(anonymous) @ bootstrap:178
redux-logger.js:1  action WALLET_INIT_SUCCESS @ 16:00:10.678
redux-logger.js:1  prev state {notifications: Array(0), transactions: Array(0), listings: {…}, messages: Array(0), profile: {…}, …}
redux-logger.js:1  action     {type: "WALLET_INIT_SUCCESS", address: "0x877736Df4F3370c547a04b0fEa3291ff221028d8"}
redux-logger.js:1  next state {notifications: Array(0), transactions: Array(0), listings: {…}, messages: Array(0), profile: {…}, …}
warning.js:33 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in ConnectivityDropdown (created by InjectIntl(ConnectivityDropdown))
    in InjectIntl(ConnectivityDropdown) (created by NavBar)
    in div (created by NavBar)
    in div (created by NavBar)
    in nav (created by NavBar)
    in NavBar (created by Connect(NavBar))
    in Connect(NavBar) (created by Layout)
    in main (created by Layout)
    in Layout (created by App)
    in MessagingProvider (created by InjectIntl(MessagingProvider))
    in InjectIntl(MessagingProvider) (created by Connect(InjectIntl(MessagingProvider)))
    in Connect(InjectIntl(MessagingProvider)) (created by Route)
    in Route (created by withRouter(Connect(InjectIntl(MessagingProvider))))
    in withRouter(Connect(InjectIntl(MessagingProvider))) (created by App)
    in Web3Provider (created by Connect(Web3Provider))
    in Connect(Web3Provider) (created by Route)
    in Route (created by withRouter(Connect(Web3Provider)))
    in withRouter(Connect(Web3Provider)) (created by App)
    in ScrollToTop (created by Route)
    in Route (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop) (created by App)
    in Router (created by HashRouter)
    in HashRouter (created by App)
    in IntlProvider (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider

**Comment by concerned3rdparty** [comment]
i tried to reproduce this bug in develop branch but npm run start gives these errors :

messaging-provider.js:47 Uncaught TypeError: Cannot read property 'events' of undefined
    at MessagingProvider.componentDidMount (messaging-provider.js:47)
    at commitLifeCycles (react-dom.development.js:14361)
    at commitAllLifeCycles (react-dom.development.js:15462)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at commitRoot (react-dom.development.js:15603)
    at completeRoot (react-dom.development.js:16618)
    at performWorkOnRoot (react-dom.development.js:16563)
    at performWork (react-dom.development.js:16482)
componentDidMount @ messaging-provider.js:47
commitLifeCycles @ react-dom.development.js:14361
commitAllLifeCycles @ react-dom.development.js:15462
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:15603
completeRoot @ react-dom.development.js:16618
performWorkOnRoot @ react-dom.development.js:16563
performWork @ react-dom.development.js:16482
performSyncWork @ react-dom.development.js:16454
requestWork @ react-dom.development.js:16354
scheduleWork$1 @ react-dom.development.js:16218
scheduleRootUpdate @ react-dom.development.js:16785
updateContainerAtExpirationTime @ react-dom.development.js:16812
updateContainer @ react-dom.development.js:16839
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:17122
(anonymous) @ react-dom.development.js:17262
unbatchedUpdates @ react-dom.development.js:16679
legacyRenderSubtreeIntoContainer @ react-dom.development.js:17258
render @ react-dom.development.js:17317
./src/index.js @ index.js:9
__webpack_require__ @ bootstrap:61
0 @ translationUtils.js:305
__webpack_require__ @ bootstrap:61
(anonymous) @ bootstrap:178
(anonymous) @ bootstrap:178
react-dom.development.js:14226 The above error occurred in the <MessagingProvider> component:
    in MessagingProvider (created by InjectIntl(MessagingProvider))
    in InjectIntl(MessagingProvider) (created by Connect(InjectIntl(MessagingProvider)))
    in Connect(InjectIntl(MessagingProvider)) (created by Route)
    in Route (created by withRouter(Connect(InjectIntl(MessagingProvider))))
    in withRouter(Connect(InjectIntl(MessagingProvider))) (created by App)
    in Web3Provider (created by Connect(Web3Provider))
    in Connect(Web3Provider) (created by Route)
    in Route (created by withRouter(Connect(Web3Provider)))
    in withRouter(Connect(Web3Provider)) (created by App)
    in ScrollToTop (created by Route)
    in Route (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop) (created by App)
    in Router (created by HashRouter)
    in HashRouter (created by App)
    in IntlProvider (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:14226
logError @ react-dom.development.js:14265
update.callback @ react-dom.development.js:14918
callCallback @ react-dom.development.js:10878
commitUpdateQueue @ react-dom.development.js:10911
commitLifeCycles @ react-dom.development.js:14396
commitAllLifeCycles @ react-dom.development.js:15462
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:15603
completeRoot @ react-dom.development.js:16618
performWorkOnRoot @ react-dom.development.js:16563
performWork @ react-dom.development.js:16482
performSyncWork @ react-dom.development.js:16454
requestWork @ react-dom.development.js:16354
scheduleWork$1 @ react-dom.development.js:16218
scheduleRootUpdate @ react-dom.development.js:16785
updateContainerAtExpirationTime @ react-dom.development.js:16812
updateContainer @ react-dom.development.js:16839
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:17122
(anonymous) @ react-dom.development.js:17262
unbatchedUpdates @ react-dom.development.js:16679
legacyRenderSubtreeIntoContainer @ react-dom.development.js:17258
render @ react-dom.development.js:17317
./src/index.js @ index.js:9
__webpack_require__ @ bootstrap:61
0 @ translationUtils.js:305
__webpack_require__ @ bootstrap:61
(anonymous) @ bootstrap:178
(anonymous) @ bootstrap:178
messaging-provider.js:47 Uncaught TypeError: Cannot read property 'events' of undefined
    at MessagingProvider.componentDidMount (messaging-provider.js:47)
    at commitLifeCycles (react-dom.development.js:14361)
    at commitAllLifeCycles (react-dom.development.js:15462)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at commitRoot (react-dom.development.js:15603)
    at completeRoot (react-dom.development.js:16618)
    at performWorkOnRoot (react-dom.development.js:16563)
    at performWork (react-dom.development.js:16482)

**Comment by micahalcorn** [comment]
Hi @concerned3rdparty 👋 it sounds like you may be trying to run the develop branch of this repo with the published package for origin-js or some combination of branches that don’t go well together. Can you confirm?

**Comment by concerned3rdparty** [comment]
origin.js version in package.json : "origin": "0.6.1"

**Comment by micahalcorn** [comment]
Great, thanks @concerned3rdparty 👍 So we recommend running everything with [Origin Box](https://github.com/OriginProtocol/origin-box). It is currently configured to run all three repos on their `develop` branches. I can't promise that they are stable, since we are actively developing on those branches, but that should at least solve your issue of not finding the messaging resource.

**Comment by tomlinton** [comment]
Resolved by dapp2.
