### ISSUE TITLE
Outstanding work on T3

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#3073]
**Blocking release:**

- [x] Handle possible enumeration of valid email address by time signature of SendGrid call in login flow
- [x] Integrate Sentry

**Must-do before lockup period expires**
- [ ] Background processing job needs to be implemented, maybe via a Kubernetes CronJob

**Nice to haves:**

- [x] Could cut down on rerenders by not reloading data if not needed every time, e.g. news.
- [ ] The empty vesting bar (for a future grant) with a cliff indicator from [this screen](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5d368069a9e3ddb29ccc1d82) has not been implemented.
- [ ] Loading indicator could be made into a separate component.
- [ ] 2FA input form could be made into a separate component.
- [ ] Form error handling could use some clean up, maybe use redux state in the form helpers.

**Questions:**

- [ ] Warning about receiving a phone call on [this screen](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5d403421fe7f6b0d6c2c6d2e). Perhaps needs some copy change as I don't think we'll be calling all users.
- [ ] Make sessions timeout after 30 minutes of API inactivity instead of 30 minutes regardless of activity. @micahalcorn thinks he might like the hard timeout.
- [ ] Integrate Sentry.

**Done**

- [x] Security reviews.
- [x] Email templates. _@franckc working on these._
- [x] Phone input requires double entry (async/await of redux action problem)
- [x] Import scripts for importing users from CSV.
- [ ] Legal/disclaimer copy is missing from several screens. Lots of Lorem Ipsum happening.
- [x] ~~Modals need some work on mobile.~~ **I think these are probably ok**
- [x] Fix Kubernetes ingress so logged IP addresses are external ones and not the internal Kubernetes IP
- [x] Misalignment of news headlines in news swiper on dashboard
- [x] Available balance doesn't update when a withdraw is added
- [x] UI recovery from insufficient funds in withdraw modal and switching to choosing an account
- [x] The close link on the withdraw modal causes the heading text to not be centered
- [x] Client side validation of the amount being withdrawn. It is only done on the server so the experience could be a bit better.
- [x] Numbers only for 2FA input
- [x] Inaccurate expiration status on pending withdrawal detail that is less than a minute old.
- [ ] ~~Inaccurate waiting status on pending withdrawal in history that is more than five minutes old.~~ **Didn't experience this, might need some clarification.**
- [x] Phone validation, with country code selector.
- [x] Implement [this screen](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5d6078185cc9e39b8add49b2).
- [x] Update the transfer confirmation below as per the discussion below.
- [x] Discord webhooks.

**Comment by tomlinton** [comment]
Sure not a problem!

The only problem with that is that transfers that never get 2fa are forever in a weird state because they won't expire.

I think we add the email notification to the transfer modal. Transfers that are waiting for the email confirmation don't expire, and they can be cancelled or the email can be sent again from the withdrawal detail page (to deal with people not receiving the email, and not finding them in spam folders etc). Once they click the email they are taken to the withdrawal page and the 5 minute expiration begins, and the 2fa window appears. That work?

**Comment by sparrowDom** [comment]
The tool works nicely well done!

Have 2 minor comments: 
<img width="656" alt="Screenshot 2019-08-28 13 52 55" src="https://user-images.githubusercontent.com/579910/63856902-fe4f3700-c9a2-11e9-9b3f-b9deb4348902.png">
The `QR` in QR Code label is slightly confusing to me. 

<img width="1271" alt="Screenshot 2019-08-28 14 48 30" src="https://user-images.githubusercontent.com/579910/63856971-1cb53280-c9a3-11e9-96be-8c417767b839.png">
After an hour the transaction has not finished for me. Don't know how much it usually takes.

**Comment by tomlinton** [comment]
Thanks @sparrowDom, fixed up that label. The transaction processing hasn't been enabled yet so it won't go anywhere.

**Comment by tomlinton** [comment]
Closing this as all the blocking things are complete.
