### ISSUE TITLE
Fractional Usage: New API Integration

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#308]
With the addition of fractional usage listings and ongoing changes to the purchase stages, ~the purchase detail and purchase progress components~ basically everything will need to be updated to ~reflect the new purchase lifecycles~ use the new API.

☝️ Let me know if I can help with this since I created the existing mess.

**Comment by tyleryasaka** [comment]
This should be done along with the contract refactor mentioned in https://github.com/OriginProtocol/origin-js/issues/281 . The current purchase stages are about to change completely.

**Comment by jordajm** [comment]
Resolved by https://github.com/OriginProtocol/origin/pull/744
