### ISSUE TITLE
Korean Telegram Rewards

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3102]
Add our Korean Telegram channel as an option for Origin Rewards participants to earn OGN by joining. This should only be displayed to users who have Korean as their currently-selected language option. The reward amount should be the same as the English Telegram. A given user should only see one of the two unearned options: Korean or English Telegram group. However, if a user stumbles across both by toggling the language select, we will need to be able to display any earned rewards regardless of language. ↔️

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by shahthepro** [comment]
Closed via #3667
