### ISSUE TITLE
Backup Prompt Triggers

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3114]
When we designed our current native onboarding, we elected to refrain from introducing the seed phrase concept. Instead, we prompt the user to care about security and back up the wallet once funds are detected in the account. This made sense when funds were required as a prerequisite for doing anything interesting on the marketplace. But with the advent of meta transactions, a user is encouraged to create an identity, a listing, join Origin Rewards, etc without ever being told to back up the wallet. We should introduce this concept much earlier in the experience. The exact implementation will depend on [the decision about whether or not to remove native onboarding](https://github.com/OriginProtocol/origin/issues/2731#issuecomment-513064284) entirely.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by tomlinton** [comment]
Decision was made about removing native onboarding. ✅

Now as for this prompt, maybe when:

- Funds are deposited OR
- Identity is created

**Comment by micahalcorn** [comment]
Instead of prompting users in all environments based on their activity, I think we're likely to move the recovery concept to native onboarding as most wallet apps do. 😐 I'll reopen this if we change our mind.
