### ISSUE TITLE
[Growth] Past campaigns should be sorted by date

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3141]
On the past campaign page (https://dapp.staging.originprotocol.com/#/campaigns , then click on Past Campaign"), currently the campaigns  are sorted by name. They should be sorted by date desc.

![Screen Shot 2019-08-29 at 12 00 05 PM](https://user-images.githubusercontent.com/945910/63968449-92c5a200-ca54-11e9-88d9-c23c691bf4c9.png)

**Comment by proabel** [comment]
I will work on this.

**Comment by franckc** [comment]
@proabel Thanks for looking into this ! Our development environment does not make it as easy as it should to test campaigns... :( We need to improve it. But here are a couple of options to test:
- You can point your local DApp to Rinkeby by going to the URL http://localhost:3000/rinkeby after having started your local DApp. This will make the DApp use our staging centralized servers, including the growth server which is the one serving the campaign data.
- Alternatively, you can run a local growth server by using docker compose (see [instructions](https://github.com/OriginProtocol/origin/blob/master/DEVELOPMENT.md#option-2-running-docker-compose)). Then you have to create campaigns manually by getting a shell into the growth container `docker exec -ti graphql /bin/bash` then running the script that populates the campaign `DATABASE_URL=postgres://origin:origin@postgres/origin node infra/growth/src/scripts/manageCampaign.js --action=create --month=august`

Feel free to ask question in the engineering channel in Discord !

**Comment by proabel** [comment]
@franckc Thank you. I was able to use with rinkeby. Just then I realized the app was done in react. I havent learnt react yet. I'll get started with react soon. If this issue is still in open then I'll start working on it.

**Comment by franckc** [comment]
Sounds good @proabel ! Thank you...

**Comment by franckc** [comment]
@angwangri Would you be interested in looking into this issue ?

**Comment by franckc** [comment]
Thanks for fixing this @angwangri ! Good work.
