### ISSUE TITLE
Vertical Margin Problem In Desktop Safari

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3149]
The nav and sort filter are getting lost at the top of the screen in my 1440px-wide browser. Under some circumstances, while searching or navigating, it seems to fix itself at times, but then quickly reverts back.

<img width="1440" alt="Screen Shot 2019-08-29 at 9 49 12 PM" src="https://user-images.githubusercontent.com/273937/63994051-080e9280-caa8-11e9-866f-cc9d25636e38.png">

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by rembrandtreyes** [comment]
@micahalcorn Looks like this issue is still relevant for Safari browsers. I'll tackle this.

**Comment by franckc** [comment]
Fixed in #4364
