### ISSUE TITLE
Not Another Listing

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3150]
It seems that "Other listings by this seller" is always including the listing that I'm currently looking at on a detail page. If the user has no other listings, I think the section should not appear at all.

![Screen Shot 2019-08-29 at 9 51 25 PM](https://user-images.githubusercontent.com/273937/63994298-01344f80-caa9-11e9-813b-457e94899d4f.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by shahthepro** [comment]
@micahalcorn I remember making this change in one of my PRs. But I accidentally committed it to master which I had to revert.
Change on master: https://github.com/OriginProtocol/origin/commit/c098d6ae5c7d839cc662d8476b63abfef5ab2c9b#diff-1aa1f4560424ebfa862436eff64929bf
Revert: https://github.com/OriginProtocol/origin/commit/fc5e067fef3283d5cb1c46e9212c7d1a5dbf541b#diff-1aa1f4560424ebfa862436eff64929bf

However, I redid the change on a branch and submitted a PR, IIRC. Let me check what happened.

**Comment by shahthepro** [comment]
Looking at [that file's commit history](https://github.com/OriginProtocol/origin/commits/master/dapps/marketplace/src/pages/user/_UserListings.js), seems like I lost the change somehow. Will submit another PR for this.

**Comment by micahalcorn** [comment]
The `hideIfEmpty` prop doesn't seem to be having the intended effect. I still get the "Other listings by this seller" heading on that same listing pictured above. 👆

**Comment by micahalcorn** [comment]
Still relevant ☑️
