### ISSUE TITLE
Relayer fails to handle meta transaction because proxy already exists for account

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#3179]
This has been reported by @joshfraser and @milachoi. There are a lot of errors in the relayer logs like:

`[ERROR] relayer: Proxy already exists at 0x... for user 0x...`

Which results in meta transactions being rejected. I'm not sure what the conditions are that would cause that, any ideas? cc @mikeshultz

**Comment by tomlinton** [comment]
Possibly relevant #2893.

**Comment by mikeshultz** [comment]
This is caused when a client sends a transaction to create a proxy but one
already exists. This is an error state that the relayer can not handle. If
it sent the transaction it would just revert.

>
It's likely causes by a client resending these proxy creation transactions.
Either it thinks the proxy doesn't exist, or it's indescriminately
resending transactions.  If you have reason to suspect the proxies don't
actually exist, we should investigate the relayer.

The other issue you linked is likely an error in my script but I never did
get the chance to investigate, so there's a chance it's related. If
predicted proxy address was getting derived wrong a client may be checking
the wrong address for an existing proxy with `eth_getCode`.

**Comment by mikeshultz** [comment]
I looked at #2893 again.  That appears to be a non-issue.  it was due to the predicted addresses being derived on different networks(different proxy factory addresses).

Looking at that does make me wonder though if the use of memozie in these utilities used by the resolver could be making the dapp think that a proxy was not deployed.

Hypothesis:

1)  `hasProxy()` returns false before a proxy is deployed
1) Dapp deploys proxy via relayer
1) Dapp calls `hasProxy()` again, sees the proxy not deployed and tries again

I haven't dug into the dapp code yet so that's entirely unsubstantiated.  Will look a little further this afternoon.

**Comment by mikeshultz** [comment]
Does this only happen on listing creation?  This logic doesn't really make sense to me:

https://github.com/OriginProtocol/origin/blob/a716c6753618759fffbb25e948c492b0279424ab/packages/graphql/src/mutations/_txHelper.js#L103-L106

**Comment by tomlinton** [comment]
They look to be all be `createProxyWithSenderNonce` transactions based on the function signature in the transaction data pulled from the logs, e.g. one example below. So at some point we must be trying to create another proxy when one was already created. We just need to figure out what steps will get an account into that state. It seemed to be happening reasonably regularly at the meetup.

`0xc0394af1000000000000000000000000b8b530afcfc283ee330f9fcaea26468c4007c0c300000000000000000000000000000000000000000000000000000000000000800000000000000000000000004d3d098c30bf5c38dae9c7e3ca4c0d357b31c5f5000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e48fe94fb20000000000000000000000004d3d098c30bf5c38dae9c7e3ca4c0d357b31c5f50000000000000000000000008ac16c08105de55a02e2b7462b1eec6085fa4d86000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000024a30749df800a203ecd60b14615c824a11ab5e9f4a80a963bf1ce3e0221427d0e8b8f8f430000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

**Comment by tomlinton** [comment]
Maybe:

- Proxy gets deployed during native onboarding
- User tries to do something in the DApp but the DApp doesn't know a proxy was already deployed for some reason

**Comment by mikeshultz** [comment]
The one you posted is:

`createProxyWithSenderNonce -> changeOwnerAndExecute -> emitIdentityUpdated`

Do you have any other examples?  Where you getting them, relayer logs?

**Comment by tomlinton** [comment]
Yep, just look for `[ERROR] relayer: Proxy already exists at 0x... for user 0x...` and immediately before that you'll see the `DEBUG` log with the transaction parameters.

**Comment by mikeshultz** [comment]
Could this be caused by #2625?

**Comment by tomlinton** [comment]
Yep good thought, thats probably the likely problem.

**Comment by micahalcorn** [comment]
No longer relevant post-https://github.com/OriginProtocol/origin/issues/2731 🤞

**Comment by mikeshultz** [comment]
I think #3532 should get rid of the vast majority of these issues.
