### ISSUE TITLE
Stuck At Finalization

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3181]
@joshfraser reported getting a perpetual spinner here at the finalization step. I'm not sure if the transaction actually went through or not.

![finalization](https://user-images.githubusercontent.com/273937/64195195-b95d5180-ce35-11e9-95ed-820f34b15e44.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment]
Do we have any extra information that could help troubleshooting this issue ?
- ETH address of the buyer
- Listing ID
- Android vs iOS
- Time of occurrence

**Comment by tomlinton** [comment]
Solved in 0.22.0.
