### ISSUE TITLE
Authoritative Native Settings

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3184]
Add a currency select to the native settings screen and have both it and the language select control the DApp's configuration. In our app, there should be no web-based language or currency options in ⚙︎Settings.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by micahalcorn** [comment]
@tomlinton don't forget that there are elements in the footer in addition to the settings page. 🐘

**Comment by tomlinton** [comment]
I think the footer is already disabled on mobile?

**Comment by micahalcorn** [comment]
![IMG_8553](https://user-images.githubusercontent.com/273937/64306694-8a83d000-cf48-11e9-9d33-c5343bc8df27.PNG)

**Comment by micahalcorn** [comment]
@tomlinton the floating footer element is hidden, but not the footer itself. It is accessed from "More..." in the menu. 🍔

**Comment by tomlinton** [comment]
Ahh got it, thanks!
