### ISSUE TITLE
Focused Search UX

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3186]
When the search field is focused, there needs to be a way to cancel and return to the listings.

For example, when I first focus on the field, I can't find a way to exit without hitting `return` or choosing a filter.

**Bad** ↘
![D51C1182-DEDA-4F26-ADC4-E4918C7D10C5](https://user-images.githubusercontent.com/273937/64223911-71b4e500-ce8a-11e9-8ccc-59fc12bf373a.png)

Once there is a value in the field, we want the 🔍 to switch to a clear icon.

**Half Good** ↘
![28AC86A5-3B06-4740-8AC1-718F566A8DD6](https://user-images.githubusercontent.com/273937/64223910-71b4e500-ce8a-11e9-86f7-ae28df52ebba.png)

But all along, we want the user to be able to just close the modal and forget about it. So there should be an unfortunate second Ｘ visible the entire time.

**Mostly Good** ↘ (https://zpl.io/V0wYBQE)

<img width="335" alt="Screen Shot 2019-09-03 at 8 43 03 PM" src="https://user-images.githubusercontent.com/273937/64224187-74fca080-ce8b-11e9-95f8-a400cb5e106d.png">

Of course, there should also be a state where the field is empty with the 🔍 is still in place and the ever-persistent Ｘ is there to close the modal.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment]
Talked with @micahalcorn - We would like to implement the "Mostly Good" UI referenced above. Mocks is here: https://zpl.io/V0wYBQE

**Comment by micahalcorn** [comment]
Note that we've replaced the "clear" ✖️ icon with a link. 😐

**Comment by angwangri** [comment]
I fixed the issue and pushed the code here. 
https://github.com/OriginProtocol/origin/commit/9cb034d30edefb6b14373eded48f9e0d171d9b97

**Comment by micahalcorn** [comment]
Thanks @angwangri 🙂 When you're ready to submit a PR, can you add a test build here for us to check out? https://github.com/OriginProtocol/test-builds#origin-dapp-build-previews

**Comment by franckc** [comment]
Also @angwangri to be clear, we'd like the fix to do two things, per the mocks here: https://zpl.io/V0wYBQE
1. Clicking on the "clear" link should clear the search query
2. Clicking on the X should dismiss the search page and go back to the listings page

**Comment by franckc** [comment]
@angwangri Here is the mock below. Notice the "Clear" link and the "X".

<img width="380" alt="Screen Shot 2019-09-26 at 11 47 05 AM" src="https://user-images.githubusercontent.com/945910/65716151-6d2bb880-e053-11e9-8426-4efe6cef955d.png">

**Comment by franckc** [comment]
As a bonus, also notice that on this mock, the category filters (Rewards, Apparel, Gift Cards, Housing, Services, ...) get wrapped and are all visible on the screen. Compared to currently where user needs to scroll right to see some of them. Would be great to fix that too... Thanks @angwangri for your work on this issue !

**Comment by micahalcorn** [comment]
For the wrapping to work as intended by @auregimon, the horizontal margin needs to be dynamic based on the width of the screen (so that the left and right alignment is consistent across screen sizes). I believe this can probably be accomplished with some flexbox jiu-jitsu. 🙏

**Comment by angwangri** [comment]
@franckc @micahalcorn 
I fixed it and created PR.
https://github.com/OriginProtocol/origin/pull/3526

Hope you guys review my first PR.
Thanks, 

@angwangri

**Comment by micahalcorn** [comment]
Resolved by #3526 ✅ Thanks @angwangri!
