### ISSUE TITLE
Release funds modal doesn't close when confirm clicked

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#3203]
See below. Modal should close.

![Simulator Screen Shot - iPhone Xʀ - 2019-09-05 at 10 49 41](https://user-images.githubusercontent.com/489202/64299157-39b5bb00-cfcc-11e9-8d97-cce24f19343b.png)

**Comment by tomlinton** [comment]
Duplicate #3182

**Comment by micahalcorn** [comment]
I think @franckc asked me about this and I didn't realize what he was talking about. 😇
