### ISSUE TITLE
Misleading Blockchain Transaction Modal

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3206]
In Coinbase Wallet, I was able to successfully make an offer. But while I was waiting for the blockchain transaction to complete, the modal state went from spinner to error, then to spinner, then to error, then to success. 😐 When it was on error, it wasn't just a flicker. It stuck long enough for me to show @franck before it changed. I later switched back to the browser tab from the wallet tab, and the same modal was in error state for a moment before switching to success state again.

![starbucks-error](https://user-images.githubusercontent.com/273937/64305488-6c1bd580-cf44-11e9-8714-1222a03b7ca1.png)
![starbucks-success](https://user-images.githubusercontent.com/273937/64305489-6c1bd580-cf44-11e9-900d-e276656bbf64.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment]
Not sure yet it is related but I'm seeing some errors in the Alchemy dashboard that occurred about 18h ago, around the time we were doing our round of testing. Errors:
eth_getTransactionByHash
Raw Request:
```
{
"id":424
"jsonrpc":"2.0"
"method":"eth_getTransactionByHash"
"params":[
0:{
"message":"User denied transaction signature"
}
]
}
```
Raw Response:
```
{
"error":{
"code":-32602
"message":"Invalid params: invalid type: map, expected a 0x-prefixed hex string with length of 64."
}
"id":424
"jsonrpc":"2.0"
}
```

eth_getTransactionReceipt
Raw Request:
```
{
"id":360
"jsonrpc":"2.0"
"method":"eth_getTransactionReceipt"
"params":[
0:{}
]
}
```
Raw Response
```
{
"error":{
"code":-32602
"message":"Invalid params: invalid type: map, expected a 0x-prefixed hex string with length of 64."
}
"id":360
"jsonrpc":"2.0"
}
```

**Comment by micahalcorn** [comment]
Couldn't easily reproduce anymore 🙏
