### ISSUE TITLE
Gallery: clicking on zoomed image causes blank gallery on desktop

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3211]
Steps to reproduce:
 - go to a listing details page
 - click on a picture, the zoomed image appears
 - as opposed to dismissing by clocking on the X icon on the top right, click on the image itself

Result: the dapp exits the gallery mode but shows a blank picture on the listing details page.

Reproducible on desktop with chrome, on any listing.

Screenshot:
<img width="1207" alt="Screen Shot 2019-09-04 at 9 16 44 PM" src="https://user-images.githubusercontent.com/945910/64311537-54028100-cf59-11e9-8ad9-eac55cbee384.png">

**Comment by franckc** [comment]
CC @nick

**Comment by mahamat** [comment]
Hi @franckc , this #4050 should fix this issue. Could you verify it, so that the issue can be closed. Thanks.

**Comment by franckc** [comment]
Awesome! Nice work @mahamat. Thanks for fixing this :)
