### ISSUE TITLE
Inappropriate MetaMask Animation

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3213]
Related to https://github.com/OriginProtocol/origin/issues/3212, we should not be attempting to play the MetaMask animation in any mobile wallet apps (including MetaMask).

![IMG_8563](https://user-images.githubusercontent.com/273937/64313606-fe31d700-cf60-11e9-844f-ab0b95cd1104.JPG)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by micahalcorn** [comment]
**Sort of a different issue**

We need to refrain from showing the animation in MetaMask's mobile app. 🦊 It takes over the full screen automatically and is not relevant outside of the desktop environment.

**Comment by micahalcorn** [comment]
Escalating this since @franckc saw it in Coinbase Wallet too 😩

**Comment by sparrowDom** [comment]
@micahalcorn the first screen happens when messaging is being enabled. Do you know when the second screen happens?

**Comment by micahalcorn** [comment]
I think it happened when enabling messaging also, but it likely appears on every attempted transaction. 🤔

**Comment by nick** [comment]
Currently working on this... sorry for stepping on toes Domen - should have checked assignee 😬

**Comment by sparrowDom** [comment]
@nick I think I might have stepped on your toes...  have just reassigned it to me minutes ago. Sorry :)
