### ISSUE TITLE
MakeOffer endless spinner

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3222]
Reported by @micahalcorn 

Using his account 0x96FEb7b6F808dd2BBd09c9E5ccdE77caBd58d019 he attempted to make an offer on https://www.shoporigin.com/#/listing/1-000-3120 using the Origin marketplace on iOS.

He got an endless spinner after pressing the "Purchase" button.
 - Looking at etherchain and etherscan, there was no transaction recorded on the blockchain.
 - No data was found in Sentry
 - No data found in Alchemy dashboard

This is not consistently reproducible. He tried again shortly after and that time the offer went thru.

**Comment by franckc** [comment]
Hopefully #3199 will give us some data to understand what's going on here...

**Comment by micahalcorn** [comment]
To clarify, it worked the second time _after_ refreshing the webview. It's possible that my session predated the deployment of the gas bump. 👆

**Comment by franckc** [comment]
Yeah. If it would be the OutOfGas error, I would have expected to see a reverted transaction in your history.

For the record, his 2nd attempt that was successful has this tx hash: https://etherscan.io/tx/0x06744d1b099d7d486c5e98b1f71c0ea8d8bac0d8c5b2a12bd5984e8b5033ce2e

**Comment by tomlinton** [comment]
You were definitely using the latest TestFlight build right? `0.22.x`.

Should we add mandatory platform/version information to the issue templates? We are testing thing on so many different environments.

**Comment by micahalcorn** [comment]
I was definitely on 0.22 but maybe not the latest build. Even if my webview was old, it would have been from the prior night.

**Comment by tomlinton** [comment]
The only difference between 0.22.1 and 0.22.0 is some descriptive strings for the App store review team so all good there 👍

**Comment by micahalcorn** [comment]
Closing with faith in https://github.com/OriginProtocol/origin/pull/3292 📿
