### ISSUE TITLE
Identity UX Race Condition

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3239]
If a user goes through web-based onboarding and then immediately attempts to make a purchase, she may be routed back to onboarding if her identity is not yet available. Depending on how long this delay is, we may want to block the UI. 🙉 Otherwise, we need to allow the user to continue through the process while the blockchain is still doing its thing. Or we could store the identity centrally and then not care how quickly it gets published. The data that comes from onboarding doesn't necessarily need to be on the blockchain prior to the offer being submitted. We just need to be able to access it for notifications and displaying the identity to the seller.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by micahalcorn** [comment]
@sparrowDom I'm thinking we might just want to go ahead and block the UI ()in the short-term) while we're waiting for the identity to publish. We're not sure what the consequences are if an offer gets made without a proxy. And if the identity publication fails and we don't properly handle retries, then we could end up an offer that has no identity, ever. 🚑

**Comment by sparrowDom** [comment]
Hmm ok that is what we are doing right now, blocking the UI while the profile is being published. Should we leave things as they are currently?

**Comment by micahalcorn** [comment]
@sparrowDom that's what I thought too, but how does the user get to offer submission if the UI is blocked in onboarding? 🤔

**Comment by sparrowDom** [comment]
Tried the following flow 3 times (Mainnet, Chrome, Metamask):
- have a fresh account
- attempt to purchase a listing
- get re-routed to onboarding
- complete email and profile onboarding (blocking UI to confirm transaction)
- enable messaging
- skip rewards
- get redirected back to the listing
- could immediately purchase it

And could not reproduce the error. Any hints how this issue can be reproduced?

**Comment by shahthepro** [comment]
@sparrowDom @micahalcorn You shouldn't be able to reproduce this now. I had changed the code a little bit so that "Purchase" button won't be rendered if wallet/identity/token balance is loading.

**Comment by micahalcorn** [comment]
Oh, okay, thanks @shahthepro 👍 That should work for now. cc @coleman415

**Comment by sparrowDom** [comment]
nice solution @shahthepro 👍
