### ISSUE TITLE
Mobile confirm dates UX

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#3243]
A confusing UI fro me while purchasing a fractional listing on mobile wallet. When a user selects the necessary dates he needs to scroll 4-5 window heights below to click on the `Save` button. 

Perhaps that button could be fixed to the bottom of the screen while the calendar component remaining scrollable: 
![Screenshot_20190906-001208](https://user-images.githubusercontent.com/579910/64418163-c9299f80-d09a-11e9-8745-27cac145c5f7.jpg)
![Screenshot_20190906-001214](https://user-images.githubusercontent.com/579910/64418165-c9299f80-d09a-11e9-91c2-8abf0e17d5b5.jpg)

**Comment by micahalcorn** [comment]
Yes, it should match the Airbnb UX. 📆

**Comment by sparrowDom** [comment]
PR solving this: https://github.com/OriginProtocol/origin/pull/3259
