### ISSUE TITLE
Stuck In Onboarding

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3267]
In Coinbase Wallet, I'm stuck at this screen because I don't want to enable messaging and our back button doesn't appear to do anything. I can use the native back button in the browser, but this wouldn't be available in our app. I suspect that the back button is immediately resulting in a rerender of this same state. In my case, it should return to listing detail where I just clicked the purchase button.

![IMG_8654](https://user-images.githubusercontent.com/273937/64470070-c908be80-d0f1-11e9-9ec9-5dda00b811b2.PNG)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by sparrowDom** [comment]
Fixed via: https://github.com/OriginProtocol/origin/pull/3314
