### ISSUE TITLE
DApp hangs on Coinbase Wallet iOS client

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#327]
We are currently having trouble successfully completing transactions with [Toshi wallet](https://toshi.org) and [Toshi dev wallet](https://developers.toshi.org/docs) on iOS.  The main Toshi app doesn't work on test nets at this time.

✅ We are able to log in to the Toshi developer app on the Ropsten network

🚫 We are unable to successfully create or buy a listing.  The app doesn't complete the purchase or listing creation and we get this error message below.  We are unable to move forward with buying or completing the listing.

<br>
<br>

*Screenshot of error message when trying to make a listing*

![dh3rx_xu0aemduk](https://user-images.githubusercontent.com/2782676/43480715-4a94f540-94c1-11e8-8133-7303ded1d0db.jpg)

**Comment by wanderingstan** [comment]
I think the only way to "See the console" for Toshi is to build the client from source in Xcode. 

Github: https://github.com/toshiapp

**Comment by micahalcorn** [comment]
Thanks @davecraige 😕 @wanderingstan I might try just modifying the DApp to show the real error in that modal and then deploy it to a Heroku instance.

**Comment by davecraige** [comment]
*requested assistance from Toshi on 7/11/18. cc’d @wanderingstan

https://twitter.com/davecraige/status/1017199308293189637?s=21

/ @micahalcorn

**Comment by davecraige** [comment]
Note: I briefly mentioned this to Emre at Coinbase and he said he was aware of the issue being on his end and that it should be fixed in the future:

![screen shot 2018-09-25 at 2 13 39 pm](https://user-images.githubusercontent.com/2782676/46040358-47c93f00-c0cd-11e8-8dfa-650f0d973b6e.png)

**Comment by tyleryasaka** [comment]
I just tested out identity creation on coinbase wallet. I got an email attestation. https://demo.staging.originprotocol.com/#/users/0x33DE3048434933998E704965c0832FBA91BF3789

I was also able to purchase a listing! https://demo.staging.originprotocol.com/#/purchases/4-000-115-1

*Plenty* of UI bugs - won't even bother listing them - but it technically works.

I'm on a Google Pixel (Android).
