### ISSUE TITLE
withdrawOffer not sent via proxy

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#3283]
@micahalcorn just reported an issue rejecting an offer with this tx:[ `0x669aa1a61928bd07062669f65928646102c45284482f1aed16d23b0011da3c4b`](https://etherscan.io/tx/0x669aa1a61928bd07062669f65928646102c45284482f1aed16d23b0011da3c4b).  It's a `withdrawOffer` call sent via the regular account `0x468e625dFD7a1aeb3F4F8B4544a7cA9A8Ad81f00`.  

The contract reverted with `Restricted to buyer or seller` because the seller of that listing is `0xEdd31fBe930f851D551873cfe4d1def1fE97Cc75`, that account's proxy.

If the listing was created with a proxy, it can only be administered by that proxy.  Somewhere along the lines the selection between account and proxy chose wrong here.

**Comment by mikeshultz** [comment]
The tx breakdown:

    { blockHash:
       '0x116de541f28a37a913261f6e4d41effc8529c694e4f204874e63585894ed7de6',
      blockNumber: 8505715,
      from: '0x468e625dFD7a1aeb3F4F8B4544a7cA9A8Ad81f00',
      gas: 150000,
      gasPrice: '7000000000',
      hash:
       '0x669aa1a61928bd07062669f65928646102c45284482f1aed16d23b0011da3c4b',
      input:
       '0xebe65f600000000000000000000000000000000000000000000000000000000000000c2e000000000000000000000000000000000000000000000000000000000000001050f9f095bedfde6f66b05b6f9e388dd8af0f90f636068c9359b8e7efb219eb7d',
      nonce: 119,
      r:
       '0x80e73d780ce71e863799fe3bc6ff8495c8b5ecf9132012b4986af218cac2ca5d',
      s:
       '0x3aef1f5bad27a8056df02bf98bbb986d062c4a75080a7d3e6a9fcd9e8275fa1a',
      to: '0x819Bb9964B6eBF52361F1ae42CF4831B921510f9',
      transactionIndex: 116,
      v: '0x25',
      value: '0' }
    { blockHash:
       '0x116de541f28a37a913261f6e4d41effc8529c694e4f204874e63585894ed7de6',
      blockNumber: 8505715,
      contractAddress: null,
      cumulativeGasUsed: 7584907,
      from: '0x468e625dfd7a1aeb3f4f8b4544a7ca9a8ad81f00',
      gasUsed: 26121,
      logs: [],
      logsBloom:
       '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
      status: false,
      to: '0x819bb9964b6ebf52361f1ae42cf4831b921510f9',
      transactionHash:
       '0x669aa1a61928bd07062669f65928646102c45284482f1aed16d23b0011da3c4b',
      transactionIndex: 116 }
    ============
    0x669aa1a61928bd07062669f65928646102c45284482f1aed16d23b0011da3c4b
    --> 1. withdrawOffer
    { listingID: '3118',
      offerID: '16',
      _ipfsHash:
       '0x50f9f095bedfde6f66b05b6f9e388dd8af0f90f636068c9359b8e7efb219eb7d' }

**Comment by mikeshultz** [comment]
Listing deets:

    {
      "data": {
        "web3": {
          "primaryAccount": null
        },
        "marketplace": {
          "listing": {
            "id": "1-000-3118",
            "contractAddr": "0x819Bb9964B6eBF52361F1ae42CF4831B921510f9",
            "valid": true,
            "validationError": null,
            "status": "active",
            "totalEvents": null,
            "seller": {
              "id": "0xEdd31fBe930f851D551873cfe4d1def1fE97Cc75"
            },
    [...snip...]

**Comment by micahalcorn** [comment]
I have the same experience on staging using a different seller and a different listing. 🙁

**Comment by mikeshultz** [comment]
This also appears to happen with `acceptOffer`.  Example tx: [0xb611aac932aa41e5b8645b01e380084e696bc8b6792de487ae82775c5b5357b2](https://etherscan.io/tx/0xb611aac932aa41e5b8645b01e380084e696bc8b6792de487ae82775c5b5357b2)

**Comment by mikeshultz** [comment]
Would like to wait until #3432 is finalized before working on this.  I think it'll require some changes to txHelper.

**Comment by mikeshultz** [comment]
I think #3485 probably fixes withdraw.  Thanks to the consult from @nick.  But the accept issue still seems illusive.  There've been a lot of recent changes since this issue was reported.  After we get all this deployed, maybe @micahalcorn can try this offer accept again to see if he can trigger it.

**Comment by mikeshultz** [comment]
@micahalcorn can you retry those withdraws and report back?

**Comment by micahalcorn** [comment]
@mikeshultz when attempting to decline a different offer involving that same seller and same listing, I am asked to pay gas. That is not the case if I want to accept it. Should I go ahead and pay the gas? 💸

**Comment by mikeshultz** [comment]
If it's a different listing and account, I'd need those details to know if it's related.  

Any chance you can try with the same listing and maybe even the same account that failed in the original report?  How the listing was created is important.

**Comment by micahalcorn** [comment]
Same listing ✅
Same seller ✅ 
Same offer ❌

**Comment by mikeshultz** [comment]
Alright then, not fixed!  Thanks for testing, @micahalcorn

**Comment by mikeshultz** [comment]
#3500 might fix seller-side `withdrawOffer`issues.  @micahalcorn did you say offer accept actually seemed to prompt you for a signature to send to relayer?  Though I'm not really sure what might've fixed that in the past 5 days...

**Comment by micahalcorn** [comment]
Well, that was an easy fix. 😁 I don't think I was aware of there ever being an issue with offer acceptance.

**Comment by mikeshultz** [comment]
That tx hash above (`0xb611aac932aa41e5b8645b01e380084e696bc8b6792de487ae82775c5b5357b2`) is an `acceptOffer` call and was from the same account in question here, @micahalcorn

**Comment by nick** [comment]
This should hopefully be fixed by #3575

**Comment by micahalcorn** [comment]
An update on this one 👇

I _think_ this is the same seller and same offer, but I've forgotten what originally led to opening this issue. I (`0x468e625dFD7a1aeb3F4F8B4544a7cA9A8Ad81f00`) am trying to decline [this offer](https://shoporigin.com/#/purchases/1-000-3118-3).

I signed with MetaMask and got an error modal accompanied by a trail of "Event not found" in the console. I refreshed and tried again. Now I get an error modal with this in the console:

<img width="366" alt="Screen Shot 2019-10-01 at 1 27 57 AM" src="https://user-images.githubusercontent.com/273937/65946312-bcbf0b00-e3ea-11e9-9a9c-f6b7ba68e55b.png">

After getting the relayer decline, I get prompted to pay gas for this transaction, which I am rejecting for now.

**Comment by mikeshultz** [comment]
Not really related, but we can do it here.

Sounds like your original transaction got reverted and the relayer is preventing you from running it again(rightly so).  Can you give me some kind of info to help track it down?  Approximate time?

Smells like #3275

**Comment by mikeshultz** [comment]
Was looking into `Invalid transaction hash` and it appears this was caused by an attempt to fetch a receipt for a pending transaction and is harmless and irrelevant.  Behavior fixed in #3589.  

The tx in question appears to be [`0x869deccefd164d1a7c873cb21ab736948536c088e50ecc36d5cc11081724ad84`](https://etherscan.io/tx/0x869deccefd164d1a7c873cb21ab736948536c088e50ecc36d5cc11081724ad84) which appears to be a `forward` wrapping `marketplaceFinalizeAndPay` that's wrapping the `withdrawOffer`. 

I assume we don't want to use `marketplaceFinalizeAndPay` if no payment is actually being made.

**Comment by mikeshultz** [comment]
Looks like `marketplaceFinalizeAndPay` was done due to #3236, which works for the buyers.  However, I think it will revert if it tries to sweep money to the seller account from the seller's proxy and there's none there.  Will work on a fix.

**Comment by nick** [comment]
When an offer is withdrawn, whether by the buyer or seller, it should be the buyer who receives the refund. The withdrawOffer mutation currently tries to send funds back to the `from` address, which would be incorrect when the seller is the one withdrawing.

We should use `offer.buyer` instead of `from` in the marketplaceFinalizeAndPay call to fix that.

**Comment by mikeshultz** [comment]
I assume you mean the `_seller` argument of `marketplaceFinalizeAndPay`?  I didn't want to set `from` in #3591 because it would have further implications in the mutation and probably also txHelper(e.g. would be sent to the wrong proxy).  Also, do we really want the seller paying to sweep funds from the buyer's proxy?  That's kind of why I figure we don't want to use `marketplaceFinalizeAndPay` on a seller's `withdrawOffer` at all.

**Comment by nick** [comment]
withdrawOffer should be paid for by the relayer so the seller shouldn't have to pay.

I'm not saying set `from` for the whole mutation, I think just changing [line 31](https://github.com/OriginProtocol/origin/blob/master/packages/graphql/src/mutations/marketplace/withdrawOffer.js#L31) to `offer.buyer` should do it?

**Comment by mikeshultz** [comment]
Not a big fan of relying on the idea that the relayer will always be there, but whatever, as long as we get a fix out.

**Comment by mikeshultz** [comment]
@micahalcorn it's time to test again, please and thank you!

**Comment by micahalcorn** [comment]
I'm a dummy and had to test this with a new offer. Rejecting it worked fine, so I'm going to consider this resolved. Thanks @mikeshultz 👊
