### ISSUE TITLE
Accounts UX

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3286]
I think this was my doing...

As much as I like to see a truncated version of the account address alongside the account nickname in our mobile app, it's frustrating to tap it and get an alert with the full address instead of navigating with the list item. So let's only show the address if the account is not named (and do it in the same style as the name). I was concerned about the list items being indistinguishable from one another, but let's leave it up to the user to come up with unique names for the accounts.

I'm still conflicted about what the click functionality should be on the address itself since I like for the user to be able to expect to see a full address anytime she taps a truncated one. Perhaps the answer is to just go with the navigation and then not truncate the address on the next screen (account detail).

![IMG_8684](https://user-images.githubusercontent.com/273937/64482301-2c532900-d1a4-11e9-9f5e-d53a8de34134.PNG)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment]
@angwangri Another issue that could be interesting for you. This one is on mobile. Our mobile repo is here: https://github.com/OriginProtocol/origin/tree/master/mobile

**Comment by micahalcorn** [comment]
Considering this done ✅
