### ISSUE TITLE
Missing Shipping Address Option

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3288]
***Steps to reproduce:*** 😬 

- [ ] Kill app
- [ ] Open app
- [ ] Open hamburger menu
- [ ] Click "Add a listing"
- [ ] Click "For Sale"
- [ ] Pick a category, any category
- [ ] Add title and description
- [ ] See quantity field
- [ ] Wonder where the shipping address requirement option is
- [ ] Pull to refresh
- [ ] See shipping address requirement option

Related: #3287

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment]
Per discussion on engineering channel, we'd like to first focus on resolving this issue on the Origin mobile app. Then we can look at other platforms.
