### ISSUE TITLE
Listing Promotion Disabled

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3291]
Promoting a listing with OGN in production fails.
TxHash: https://etherscan.io/tx/0x902ddf9e45b750edc3b4649c82778ed1e5227284ea35299961dd2ea52648e0e9
The error comes from this assert in the contract: https://github.com/OriginProtocol/origin/blob/master/packages/contracts/contracts/token/WhitelistedPausableToken.sol#L37

@mikeshultz checked and the _to argument is 0x819bb9964b6ebf52361f1ae42cf4831b921510f9 which is the marketplace contract address which makes sense.

That address 0x819bb9964b6ebf52361f1ae42cf4831b921510f9 is whitelisted, so not sure what's causing the failure...

CC @nick @mikeshultz @DanielVF

**Comment by mikeshultz** [comment]
I didn't actually check that argument, btw. I didn't fully break down that tx.

**Comment by nick** [comment]
Unfortunately, while our token is locked, I believe we can only promote listings directly and not via a proxy. 

Should have realized this earlier 😬

**Comment by micahalcorn** [comment]
Thanks @nick 🙁 Does that make this a non-issue?

**Comment by nick** [comment]
Lets test to make sure you can promote with a non-proxy wallet. 
For proxies, we should at least show a message, or prevent the user from trying to promote.

**Comment by micahalcorn** [comment]
Good suggestion 👍 To do that, I would disable two switches in developer mode?

**Comment by nick** [comment]
No need to use a clean account, just disable proxies in developer settings

**Comment by micahalcorn** [comment]
I'm going to try to commit one more thing and merge https://github.com/OriginProtocol/origin/pull/3293 before doing any more OGN testing. 😁

**Comment by DanielVF** [comment]
The actual `Transfer` call is trying to move money between these two accounts:

```
000000000000000000000000d85a569f3c26f81070544451131c742283360400
0000000000000000000000007cef86ced36dda57dc6d7253ea540f941efbb3fd
```

**Comment by franckc** [comment]
0xD85A569F3C26f81070544451131c742283360400 is my wallet.
0x7CEf86cED36DdA57dc6D7253eA540f941eFbB3fD is the proxy attached to it.

**Comment by micahalcorn** [comment]
Updating this issue to represent [the short-term UI change](https://zpl.io/a8JJZQE) indicating that the feature is not enabled in production 😔
