### ISSUE TITLE
Click on image makes gallery disappear 

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#3298]
Osx, Chrome, Metamask

Clicking on an image in the listingDetail gallery makes the gallery disappear: 
<img width="1522" alt="Screenshot 2019-09-08 11 49 04" src="https://user-images.githubusercontent.com/579910/64486554-d24b7580-d22e-11e9-8c29-42cc2c7fb05b.png">

**Comment by franckc** [comment]
Closing as a duplicate of #3211
