### ISSUE TITLE
Broken Quantity Purchases

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3304]
I've concluded that multi-unit purchases are broken for ***at least*** gift cards and services listings. It appears that [these single-unit defaults](https://github.com/OriginProtocol/origin/blob/5aa1d52bf362f8221ab6258f88f3899c773c461f/dapps/marketplace/src/pages/listing/ConfirmPuchase.js#L64-L65) are being rendered due to the graphql package not returning `true` on the `multiUnit` property for those listings. Since I don't have any experience with that code and have never run it locally, I'm not sure if there is supposed to be a `multiUnit` value on these listings that just isn't getting returned by [the resolver](https://github.com/OriginProtocol/origin/blob/master/packages/graphql/src/resolvers/marketplace/listings.js) or if it's supposed to treat them as multi-unit through some other mechanism. 👯‍♂

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by mikeshultz** [comment]
Affected: https://shoporigin.com/#/listing/1-000-3122 (for sale::gift cards)
Affected: https://shoporigin.com/#/listing/1-000-18 (services)
Not Affected: https://shoporigin.com/#/listing/1-000-3135 (for sale::other ~ shipping required)
Not Affected: https://shoporigin.com/#/listing/1-000-3137 (for sale::other - shipping not required)
Not Affected: https://shoporigin.com/#/listing/1-000-255 (for sale::clothing and accessories)
Not Affected: https://shoporigin.com/#/listing/1-000-2328 (for rent::housing)

**Comment by mikeshultz** [comment]
3122:

    "marketplace": {
      "listing": {
        "id": "1-000-3122",
        "contractAddr": "0x819Bb9964B6eBF52361F1ae42CF4831B921510f9",
        "valid": true,
        "validationError": null,
        "status": "active",
        "totalEvents": null,
        "seller": {
          "id": "0xEdd31fBe930f851D551873cfe4d1def1fE97Cc75"
        },
        [...snip...]
        "unitsTotal": 1000,
        "unitsAvailable": 978,
        "unitsSold": 11,
        "unitsPending": 11,
        "multiUnit": true,
        [...snip...]

18:

    "marketplace": {
      "listing": {
        "id": "1-000-18",
        "contractAddr": "0x819Bb9964B6eBF52361F1ae42CF4831B921510f9",
        "valid": true,
        "validationError": null,
        "status": "active",
        "totalEvents": null,
        "seller": {
          "id": "0x5b2A5d1AB8a5B83C0f22cB1Df372d23946aA7d8F"
        },
        "arbitrator": {
          "id": "0x5b2A5d1AB8a5B83C0f22cB1Df372d23946aA7d8F"
        },
        [...multiUnit missing...]
        "unitsSold": 0,
        "unitsPending": 0,
        "unitsAvailable": 20,

- 3135: `"multiUnit": true,`
- 3137: `"multiUnit": true,`
- 255: `"multiUnit": true,`
- 2328: `multiUnit` undefined

**Comment by mikeshultz** [comment]
Looking at the IPFS data for these listings, the one thing that stands out for those 2 listings is the lack of the `__typename` prop.  `multiUnit` doesn't appear to be the cause, even though it's supposed to use `__typename` to figure this out...  will continue digging.

**Comment by mikeshultz** [comment]
Unless I'm missing something, `__typename` is not available from GraphQL results, but it's in IPFS data only.  Unless the GraphQL client is somehow filling this data in somehow.  If I'm right, this should never work properly:

https://github.com/OriginProtocol/origin/blob/5aa1d52bf362f8221ab6258f88f3899c773c461f/dapps/marketplace/src/pages/listing/ConfirmPuchase.js#L37-L40

Gonna mess around with the dapp on my local a little bit to see what it sees.

**Comment by mikeshultz** [comment]
It does indeed have `__typename`.  I guess that's an internal GraphQL thing.  Though i think I see where the problem lies, should have a PR up in a bit.

**Comment by micahalcorn** [comment]
Resolved by #3309 ✅
