### ISSUE TITLE
Request: Test DApp on Trust Wallet on Android

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#331]
We would love your help testing the DApp on an Android phone with [Trust Wallet](https://trustwalletapp.com).

Please report your findings below for the following:

- Log in to http://demo.orginprotocol.com
- Create an attestation
- Create a listing
- Purchase an item

Feel free to make PR to the [ReadMe test section](https://github.com/OriginProtocol/origin-dapp#browser--wallet-compatibility) with your results.

**Comment by davecraige** [comment]
*shared this request in the #Android section of the Trust wallet Discord:
https://discord.gg/xScu7Rq

**Comment by LukaNarat** [comment]
Tested on 2 separate android devices (lollipop / oreo), both not loading the app at all from within the Trust Wallet browser.

Repro:
- Install latest Trust Wallet via playstore
- Generate wallet
- Navigate to browser tab & open http://demo.orginprotocol.com
- see loader icon (clock)
- white screen remains (nothing loads)

Needs to be looked in to further.

Sidenote: testnets don't seem to be supported at this time as well.

**Comment by davecraige** [comment]
Thank you Luka for looking into this.  Appreciate your help 🙏.

Hope we can get it working in the not too distant future.

**Comment by micahalcorn** [comment]
Closing this for now 😐
