### ISSUE TITLE
Transaction sent to proxy that does not exist

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3312]
While Coleman was testing with (what we think) is poor connectivity, he reported hitting this error: https://github.com/OriginProtocol/origin/blob/master/dapps/marketplace/src/components/WaitForTransaction.js#L143

This would occur if getting the transaction receipt fails. I suspect it is due to a call to Alchemy that failed due to network error.

We should try to harden this code. Perhaps it could retry N times before showing an error to the user.

**Comment by mikeshultz** [comment]
Is there a tx hash?

**Comment by micahalcorn** [comment]
We can get it from @coleman415 but we may need to coach him through finding it in MetaMask. 🦊

**Comment by franckc** [comment]
@coleman415 Here is how to get the tx hash:
- Open Metamask
- Find the transaction in the History
- Click on specific transaction to expand it and see the details
- Click on little arrow on the right of the Details. See screenshot

<img width="358" alt="Screen Shot 2019-09-09 at 10 40 57 AM" src="https://user-images.githubusercontent.com/945910/64554259-e6a37700-d2ef-11e9-945a-60a45491597d.png">

**Comment by coleman415** [comment]
I think this is the tx hash (based on timestamp, I had many tx's):

https://etherscan.io/tx/0x76260ee603555df2ea71e6b89241abad8a2363fea1c5a3e310a7eaec0cc461d1

Here is my IP right now (I am using VPNs with different servers and forgot what server I was using then): 156.234.193.194

Note that it says Los Angeles but I am in China using a Hong Kong VPN server

**Comment by tomlinton** [comment]
@coleman415 who is the VPN provider? It might be worth one of us setting up a VPN and trying out the DApp.

**Comment by franckc** [comment]
@mikeshultz Do you mind taking a look at this issue ? First could you confirm that the DApp fails hard (as opposed to retying) if any call to getTransactionReceipt fails ?

**Comment by mikeshultz** [comment]
I don't think connectivity would cause the event not found issue.  This tx just doesn't have events, which is probably weird in and of itself since I assume this should at least have a `OfferCreated`.  

This tx was supposed to be an offer, right?

**Comment by micahalcorn** [comment]
Yes @mikeshultz 😕

**Comment by mikeshultz** [comment]
Yep, it's an offer and a new mystery, it seems.

tx decoded:

    --> 1. transferTokenMarketplaceExecute
    { _owner: '0x2aE595eddb54f4234B10Cd31Fc00790e379fc6b1',
      _marketplace: '0x819Bb9964B6eBF52361F1ae42CF4831B921510f9',
      _offer:
       '0x51b182500000000000000000000000000000000000000000000000000000000000000c2e5803562e6363dbf94f9ef062c2888a27777c2b4f5d89e1e52ec12f800d71d10400000000000000000000000000000000000000000000000000000000001275000000000000000000000000007ad0fa0e2380a5e0208b25ac69216bd7ff206bf80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ad78ebc5ac62000000000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a2326035900000000000000000000000064967e8cb62b0cd1bbed27bee4f0a6a2e454f06a',
      _token: '0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359',
      _value: '12500000000000000000' }

makeOffer call:

    // txhash 0x76260ee603555df2ea71e6b89241abad8a2363fea1c5a3e310a7eaec0cc461d1
    makeOffer(uint256,bytes32,uint256,address,uint256,uint256,address,address): 51b18250
    0x51b18250
    0000000000000000000000000000000000000000000000000000000000000c2e uint listingID 3118
    5803562e6363dbf94f9ef062c2888a27777c2b4f5d89e1e52ec12f800d71d104 bytes32 _ipfsHash QmUGDY9hq2rnS5GdvyfFPMBWS6bbmuKNAoccAXStWuCbXR
    0000000000000000000000000000000000000000000000000000000000127500 uint _finalizes 1209600
    0000000000000000000000007ad0fa0e2380a5e0208b25ac69216bd7ff206bf8 address _affiliate
    0000000000000000000000000000000000000000000000000000000000000000 uint _commission
    000000000000000000000000000000000000000000000000ad78ebc5ac620000 uint _value 12.5
    00000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a23260359 address _currency (DAI)
    00000000000000000000000064967e8cb62b0cd1bbed27bee4f0a6a2e454f06a address _arbitrator

Receipt:

    {
        'status': 1, 
        'contractAddress': None, 
        'cumulativeGasUsed': 7177063, 
        'from': '0x2ae595eddb54f4234b10cd31fc00790e379fc6b1', 
        'logs': [], 
        'blockHash': HexBytes('0xa88f0624b7fbcd8857a905a634698171a33a40da273737025f3c05d73209837d'), 
        'transactionHash': HexBytes('0x76260ee603555df2ea71e6b89241abad8a2363fea1c5a3e310a7eaec0cc461d1'), 
        'transactionIndex': 168, 
        'blockNumber': 8513260, 
        'to': '0x28900e6bd7eb02a9f42ebe50d0380c3e404928a6', 
        'logsBloom': HexBytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 
        'root': None, 
        'gasUsed': 34328
    }

Zero logs.  There should've been: 

- `OwnerChanged` from Proxy
- `Transfer` from ERC20 (DAI)
- `Approval` from ERC20 (DAI)
- `OfferCreated` from Marketplace

The [parity trace is also suspiciously short](https://www.etherchain.org/tx/76260ee603555df2ea71e6b89241abad8a2363fea1c5a3e310a7eaec0cc461d1/parityTrace).  Still looking into it.

**Comment by DanielVF** [comment]
The gas used is also only 34,328 - that's tiny. 

I wish we could get an execution trace. Etherscan won't give me one.

**Comment by mikeshultz** [comment]
The `to`field for this transaction should be the proxy, right?  What's this about?

    >>> web3.eth.getCode(web3.toChecksumAddress('0x28900e6bd7eb02a9f42ebe50d0380c3e404928a6'))
    HexBytes('0x')

**Comment by mikeshultz** [comment]
So yeah, unless I'm off base ^above^ it looks like the proxy was never deployed and we're sending these transactions to nothing.  Not sure why yet, maybe the dapp was assuming the deploy tx was sent and it was lost to the reported relayer issues and never succeeded.

**Comment by DanielVF** [comment]
That's what it looks like to me.

**Comment by mikeshultz** [comment]
Could be related: #3337 and #3229

**Comment by mikeshultz** [comment]
Suspicious of these lines done in commit 35ac9dc

https://github.com/OriginProtocol/origin/blob/5cf0e5d05ea037d459be3d7d0eb8371f403dffd9/dapps/marketplace/src/pages/listing/mutations/Buy.js#L404-L409

**Comment by mikeshultz** [comment]
There's no checks in here to make sure the proxy actually exists.

https://github.com/OriginProtocol/origin/blob/5cf0e5d05ea037d459be3d7d0eb8371f403dffd9/packages/graphql/src/mutations/marketplace/makeOffer.js#L104-L115

Perhaps normally this was done before this mutation was ever fired?  Checks should be added here, regardless.

**Comment by mikeshultz** [comment]
I asked this in #engineering:

>   so, under what circumstances does [a forced proxy deploy] not happen [during onboarding]?  Does onboarding have to be specifically disabled in localStorage?

@shahthepro responded:

> If you have deployed an identity before proxy contracts/meta transactions were introduced and haven't updated or done anything since then, you would have an identity but not a proxy. Onboarding wouldn't deploy a proxy in that case either. It just checks for a deployed identity

Since @coleman415, I assume, is using a relatively old account he probably falls into this little niche.

I suppose the only question now is where in the dapp to head this off?  That makeOffer mutation should still have a check, but I'm not sure failing there is the best option, either.  Would like to hear from people more immersed in the dapp what would work best here.

**Comment by shahthepro** [comment]
@mikeshultz 

> I suppose the only question now is where in the dapp to head this off? That makeOffer mutation should still have a check, but I'm not sure failing there is the best option, either

We can probably add a check for proxy when user connects his wallet and force republish the profile (with the same data from his previous identity), if he has identity but not proxy. I'll defer to @nick or @micahalcorn on this one though.

**Comment by mikeshultz** [comment]
I think I have a pretty good handle on this and there's a few issues here.

`transferTokenMarketplaceExecute` is explicitly denied proxy execution, because it's transferring tokens from the user's wallet(this actually might be the same issue @nick said he was looking into) to the proxy, then execution a marketplace call.  However, it's still a proxy call, and the `makeOffer` mutation is relying on the predicted proxy address.  And because it's denied txHelper proxy wrapping, we won't auto-deploy a proxy either.

I'm not sure we can use the same auto-deploy as we normally do with this, since it appears to have been explicitly denied in the txHelper logic.  @nick can you shine any light on why we can't do that?  It is a proxy call, after all.

Would like to get #3432 settled before I actually start making any changes here since it looks like it will probably require txHelper changes.

**Comment by mikeshultz** [comment]
Might be fixed by @nick's work in #3439?

**Comment by mikeshultz** [comment]
I think this is probably fixed.  I'm not really sure how we can confirm this or not without a detailed transaction analysis of historical relayer transactions.  If someone things that's worth it, I can spend some time on it.  For now, I'm going to close this unless we hear of this happening again.
