### ISSUE TITLE
Request: Test DApp on Coinbase Wallet on Android

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#332]
We would love your help testing the DApp on an Android phone with [Toshi](https://toshi.org) and [Toshi developer app](https://developers.toshi.org).  

*Note* : We don't believe the main app will work on testnets.  Please start with the developer app. 

Please report your findings below for the following:

- Log in to http://demo.orginprotocol.com
- Create an attestation
- Create a listing
- Purchase an item

Feel free to make PR to the [ReadMe test section](https://github.com/OriginProtocol/origin-dapp#browser--wallet-compatibility) with your results.

**Comment by LukaNarat** [comment]
Tested on Samsung Galaxy S9 (lollipop)

- Attestation (email): https://demo.originprotocol.com/#/users/0xf72afd50850666dbc886c648938116b24205c018
- Listing Created: https://demo.originprotocol.com/#/listing/0xF36C55ea9986dCC1884FBAc2BD6538494A37Ad98
- Item purchased: https://rinkeby.etherscan.io/tx/0x738cc725001631cc8fadf8316d7ff64448c3fe2dffcacefb0f4c028725c316a9

Couldn't test Toshi developer app (can't seem to find a way to switch to rinkbey - looking in to it)

**Comment by davecraige** [comment]
Nice work on this Luka 🙏

**Comment by micahalcorn** [comment]
Closing this for now 😐
