### ISSUE TITLE
Can't Promote Listings From Mobile

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3320]
I'm increasingly convinced that listing promotion from our mobile app is broken. I have not yet tested from other mobile wallet/browsers, but it works fine from desktop with MetaMask. This is separate from https://github.com/OriginProtocol/origin/issues/3291 because I'm using a Rinkeby build. 🌀 I just get a constant spinner on the ERC-20 allowance step after submitting the transaction with gas.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment]
- Tested on Rinkeby using Origin mobile on iOS, v0.22.0.
- Turned off proxy following [instructions here](https://docs.google.com/document/d/1yX6ecu88odUSzIm1jHHUBGeuGQ9w8_SNhvPGDxvNzXg/edit#heading=h.3ditdmmjdk3h)
- Attempted to promote this listing: https://dapp.staging.originprotocol.com/#/listing/4-000-941
- Tapped Promote

=> Got a modal "Writing to the blockchain. This may take a minute". With an endless spinner (waited over 10min). No transaction shows up for my account in etherscan. [See link](https://rinkeby.etherscan.io/address/0xD85A569F3C26f81070544451131c742283360400).

**Comment by micahalcorn** [comment]
Confirmed that this works fine in Coinbase Wallet ☑️

![not-you](https://user-images.githubusercontent.com/273937/64567837-05186b00-d30e-11e9-80fe-431a4151f5f1.gif)

**Comment by tomlinton** [comment]
Worked for me fine 3 times with proxies enabled/disabled. Latest transactions on https://rinkeby.etherscan.io/address/0xd15f105E2667Fd52313877585D4a0b316C7D8a20.

**Comment by tomlinton** [comment]
P.s is this really a P1 since tokens are locked?

**Comment by micahalcorn** [comment]
Sort of... 🔐

**Comment by micahalcorn** [comment]
Demoting this to ℙ② until we are able to reproduce it in 0.23 ⏬

**Comment by tomlinton** [comment]
I can't reproduce this, but please reopen if you can.
