### ISSUE TITLE
Clean Up Contract Comments

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3322]
After deploying v01 of the marketplace contract, we should clean up the source code with appropriate attribution and comments before submitting to Etherscan and verifying the bytecode. 📜

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by mikeshultz** [comment]
This has been done.

https://etherscan.io/address/0x705ea5f4a50fcd8ef5cdfa9d3647b582a196cb5a
https://rinkeby.etherscan.io/address/0xcdde3e2d6b42764db3637b0463d529209526569e

**Comment by franckc** [comment]
@mikeshultz Do you mind committing those headers you added on Etherscan to the repo as well ? So that things are in sync...

**Comment by mikeshultz** [comment]
Well, none of it is exactly in sync, since our contract in the repo has an import.  I can still add it, however.

**Comment by joshfraser** [comment]
For future reference, the v1 contract has been updated and the new address is: https://etherscan.io/address/0x698ff47b84837d3971118a369c570172ee7e54c2
