### ISSUE TITLE
Use consistent error message styling and placement

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#334]
https://github.com/OriginProtocol/origin-dapp/pull/303 adds a nice error experience to the profile attestations. We should be careful to consistently apply similar styles and be aware message placement everywhere that they appear.

**Comment by jordajm** [comment]
Comments in PR review here:
https://github.com/OriginProtocol/origin-dapp/pull/303#pullrequestreview-142848934

**Comment by sparrowDom** [comment]
Done via https://github.com/OriginProtocol/origin-dapp/pull/303
