### ISSUE TITLE
Relayer

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#3355]
Relayer appears to be showing some bad behavior.

When new accounts came online, it attempted to fund them.  Funded only one, and then the new account seemed to be the only point of focus.  It was holding on finding sender accounts because it thought there were no open accounts.  

It appears that the first 2 of the child accounts had no pending.  It also wasn't clearing pending transactions that weren't mined.

Don't have a ton of details to go on here...

**Comment by mikeshultz** [comment]
Here's what was in its gullet when this happened:

     1) "txcount_0x5Fabfc823E13de8F1d138953255Dd020e2B3dED0"
     2) "pending_txobj_0x4ff9e5bc76110a6126edd75d02b0b1f07273cae65e3cad2d661e93078c1c443a"
     3) "pending_txobj_0xfdb0e2471d686e082163ac5b275fe47969d96eb089d5ce7f7d735040f24458c9"
     4) "pending_txobj_0x9eec514381aa9a90389fd6e09ae702056e0cb80b7ede6a517c97e72e9ed90770"
     5) "pending_tx_0xfdb0e2471d686e082163ac5b275fe47969d96eb089d5ce7f7d735040f24458c9"
     6) "txcount_0x9629F3998d08A7Bc479451bE450e897E3240B2b2"
     7) "pending_txobj_0x2be8310b518dfef35280eab53f6e649251d4f61526826b21fc1339d5a074c549"
     8) "pending_tx_0xa8c18e47552df457c893b52f92b0369b391b8149e91320c00392f6472e7cf1d0"
     9) "pending_tx_0x9eec514381aa9a90389fd6e09ae702056e0cb80b7ede6a517c97e72e9ed90770"
    10) "pending_tx_0x2be8310b518dfef35280eab53f6e649251d4f61526826b21fc1339d5a074c549"
    11) "pending_tx_0xcacd6982fcabc1d8fabfde507371f67d6fc441b7cecb40ac690b8010bf37fb02"
    12) "pending_txs"
    13) "txcount_0x000AA034b0Ff6663C2dbE57fec1C184467702690"
    14) "pending_txobj_0xa8c18e47552df457c893b52f92b0369b391b8149e91320c00392f6472e7cf1d0"
    15) "pending_tx_0x4ff9e5bc76110a6126edd75d02b0b1f07273cae65e3cad2d661e93078c1c443a"
    16) "pending_txobj_0xcacd6982fcabc1d8fabfde507371f67d6fc441b7cecb40ac690b8010bf37fb02"
    17) "txcount_0x8007BA35A2d04bD44a28533A9F40F53449977f61"


    127.0.0.1:6378[1]> SMEMBERS pending_txs
    1) "0x4ff9e5bc76110a6126edd75d02b0b1f07273cae65e3cad2d661e93078c1c443a"
    2) "0xa8c18e47552df457c893b52f92b0369b391b8149e91320c00392f6472e7cf1d0"
    3) "0x9eec514381aa9a90389fd6e09ae702056e0cb80b7ede6a517c97e72e9ed90770"
    4) "0xcacd6982fcabc1d8fabfde507371f67d6fc441b7cecb40ac690b8010bf37fb02"
    5) "0xfdb0e2471d686e082163ac5b275fe47969d96eb089d5ce7f7d735040f24458c9"
    6) "0x2be8310b518dfef35280eab53f6e649251d4f61526826b21fc1339d5a074c549"

**Comment by mikeshultz** [comment]
Logs from startup: https://gist.github.com/mikeshultz/7e221a4e32c9c0998293bd6b20dc2790

**Comment by mikeshultz** [comment]
I'm not sure this needs to be high priority or P1.  maybe a P2.  It only occurs when we bring up new accounts.  It's serious, and should be dealt with, but maybe not immediately?  I only bring this up because of all the other P1s assigned to me right now, this one seems like it could wait a bit.

**Comment by micahalcorn** [comment]
@mikeshultz I don't quite understand the issue, but would generally say that new users are primarily what we care about. Is that what you mean by new accounts? I wouldn't deprioritize it simply because it only affects new users. That said, I'll defer to you on what you think is more important. 🙂

**Comment by mikeshultz** [comment]
No, I mean new purse accounts that the relayer uses to send transactions.  Not user accounts.  For instance, this showed up when we scaled the relayer sending accounts to 4 from 2.

**Comment by mikeshultz** [comment]
This may be fixed by #3514. Closing until we see this again.
