### ISSUE TITLE
marketplaceFinalizeAndPay cannot be called directly

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#3357]
Seen in this tx: `0x502686f384686f1ec89f126b176a50680b24cc3c2b4e87c37e89d960716843b9`

It makes a call to `marketplaceFinalizeAndPay` on a user's proxy.  By design, this call appears to not be callable except from the proxy itself:

https://github.com/OriginProtocol/origin/blob/35ac9dcae72316cd455219fbe8c50faf0432869f/packages/graphql/src/mutations/marketplace/finalizeOffer.js#L34-L62

Unless it's already being done, this would have to be wrapped in a proxy exec call in `_txHelper`.  Could be in the dapp otherwise.  Either way, this can't be called directly.

**Comment by micahalcorn** [comment]
For the record, this occurred while using the mobile app, version 0.23 (test build) 📲

**Comment by mikeshultz** [comment]
I think this is similar to the other issues I've been seeing with `acceptOffer` in #3283.  This method call was intended to be wrapped in an `execute` but for some reason was not.  It's not yet clear why this is occurring.

**Comment by mikeshultz** [comment]
maybe not realated.  `acceptOffer()` should can be run via relayer, this can not.  Worth mentioning, though.

**Comment by mikeshultz** [comment]
There's a chance this was fixed by this:

https://github.com/OriginProtocol/origin/commit/b54fc8393216df7383edb77beae466f734e38573#diff-12cd64ad74cc99c454bd7bcc8272c775R114

@nick, do you recall if this error is why you made that change?

**Comment by nick** [comment]
I think that change was for when you're trying to use Dai but don't yet have a proxy. I think we can't call marketplaceFinalizeAndPay directly but it should work if wrapped in Proxy.execute?

**Comment by mikeshultz** [comment]
I think before your change, it was `execute-no-wrap` but it looks to me like after that change it should just be `execute`.  Which I suspect might fix this.

**Comment by mikeshultz** [comment]
@micahalcorn if you remember how to repro this, can you give it a shot again?

**Comment by micahalcorn** [comment]
According to Discord, I was trying to finalize a transaction with `0x96FEb7b6F808dd2BBd09c9E5ccdE77caBd58d019`. 📱 I will attempt the same soon using a newer app version.

**Comment by micahalcorn** [comment]
I've now successfully finalized multiple offers involving escrowed ETH and DAI using that buyer account across various listings. ☑️ Should we close this one @mikeshultz?

**Comment by mikeshultz** [comment]
I would love to close this one! In case it shows up again, we can always reopen...
