### ISSUE TITLE
Unnecessary Messaging Enabled Screen

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3358]
When going through web-based onboarding in our app, I was presented with a "Messaging Enabled" screen with a green checkmark that referred to "2 of 2 MetaMask messages" having been signed. Of course, I didn't knowingly sign anything, particularly using MetaMask. We should not display this step if the user is in our app. And the wallet vendor should be detected instead of just referring to MetaMask. 🦊

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by micahalcorn** [comment]
This still occurs on mobile. 📲

![IMG_8862](https://user-images.githubusercontent.com/273937/65390275-58c58400-dd12-11e9-82bc-dd3f645e4a6b.PNG)

**Comment by shahthepro** [comment]
Fixed with #3709

**Comment by micahalcorn** [comment]
I’m still getting this pretty consistently. 😕
