### ISSUE TITLE
Confirm Purchase After Onboarding

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3359]
The purchase confirmation step of the buying process should not be displayed until the user has gone through all other steps and is ready to submit a blockchain transaction. Currently, it is shown when a cold user clicks "Purchase". It should not be shown before onboarding, and it should not appear at all if the user has insufficient funds. ☹️

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by nick** [comment]
Closing this as a fresh account does indeed take me to onboarding on that listing
