### ISSUE TITLE
Pull to refresh scroll detection broken on Android

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#3360]
Following the merge of #3297 the pull to refresh function is disabled on Android. A JavaScript snippet gets injected that sends a request through window.postMessage to report how far down the page the user has scrolled, and only enables pull to refresh if the user is at the top of the page. Unfortunately `window.onscroll` doesn't fire in the mobile modal component  (see #2884).

The scroll detection needs an alternate approach, maybe a polling function will need to be used to detect scroll in either mobile modal or on the document generally.

**Comment by sparrowDom** [comment]
@tomlinton like you predicted a pretty ugly workaround was required here. Pull request here: 
https://github.com/OriginProtocol/origin/pull/3715

**Comment by tomlinton** [comment]
Fixed by the above PR!
