### ISSUE TITLE
Can't Send Message

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3367]
Steps to reproduce:

**Account 1** ([this one](https://shoporigin.com/#/user/0x2bFF1927e1172b9d18fb280812074551676593f0), in my case)
1. Update mobile app to 0.23.11
1. Create new wallet
1. Initiate a purchase
1. Verify email
1. Add name
1. Publish identity
1. Don't purchase (not necessary)
1. Create a listing (necessary to be easily discovered)

**Account 2** ([Origin Services](https://shoporigin.com/#/user/0xEdd31fBe930f851D551873cfe4d1def1fE97Cc75), in my case)
1. Find Account 1's listing
1. Contact Seller
1. Type a message in the modal
1. Attempt to send it
1. See message disappear
1. See no conversation in /messages

<img width="500" alt="Screen Shot 2019-09-12 at 10 33 34 AM" src="https://user-images.githubusercontent.com/273937/64807312-d4247a00-d549-11e9-9307-0a980d6c99ab.png">

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by tomlinton** [comment]
You don't need to change anything. It works fine for me 0.23.12 and above. What are you seeing? I've noticed something that doesn't work:

- Open a conversation with another one of your own accounts
- Change accounts to the other account
- When you go to the messaging screen it'll show up empty, you'll have to reload it to get the conversation to show up

**Comment by micahalcorn** [comment]
@tomlinton I'm just using account 2️⃣ (Origin Services) in desktop with MetaMask. It refuses to contact account 1️⃣. Do we need a production deployment?

**Comment by tomlinton** [comment]
Ahh sorry, I thought this was something mobile specific. I could send messages successfully with other accounts in the app. I wonder if it is something specific to 2️⃣ .

**Comment by micahalcorn** [comment]
2️⃣ regularly sends messages to a variety of accounts in the wild. The only thing unique here, from my perspective, is that 1️⃣ and its listing were created from the mobile test build.

**Comment by tomlinton** [comment]
No luck reproducing it, worked fine for me with a fresh account on mobile. Will leave it for someone else to look into though.

**Comment by micahalcorn** [comment]
Closing this because I couldn't reproduce it with 0.23.18 🤞
