### ISSUE TITLE
User Listings Pagination

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3381]
It seems as if the "Listings" section of the public user profile is limited to displaying eight listings. I should be able to see more if a seller has more, and they should be revealed by a link rather than horizontal scroll.

See [the Origin Services profile](https://shoporigin.com/#/user/0x468e625dFD7a1aeb3F4F8B4544a7cA9A8Ad81f00) ➡️

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by MuraraAllan** [comment]
I would like to grab this on.

okay @micahalcorn

**Comment by micahalcorn** [comment]
Great, thanks @MuraraAllan 👍 It's good to see you again.

**Comment by IncentiveLoop** [comment]
Hey @micahalcorn I'd like to pick this up if possible. 

Would you like pagination to function similar to the my-listings page (infinite scroll) or click to load more?

**Comment by micahalcorn** [comment]
Thanks for asking @IncentiveLoop 👊 Let's avoid the horizontal scroll there and do a clickable link. This change should be made on the public user profile linked above and also on the listing detail page containing "Other listings by this seller".
