### ISSUE TITLE
Payment Methods

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3383]
In the current version of our DApp, we don't allow the buyer to explicitly choose her payment method when making an offer. This was a conscious decision because we had a strong preference for escrowing DAI and had a (not-so-reliable) way of quietly converting a buyer's ETH to DAI without asking.

With the introduction of OGN as a payment method, we need to give the control back to the buyer. If the seller accepts all three currencies and the buyer holds all three in sufficient amounts to purchase, we shouldn't constrain her to only use DAI, for example. And, of course, we're unlikely to offer a magical ETH-to-OGN automatic conversion in cases where a seller only accept OGN and a buyer only has ETH.

Here are some notes and relevant Zeplin mocks:

**Listing Creation**: https://zpl.io/29nokke
- will have all three currencies selected by default

**Payment Method Step**: https://zpl.io/VqnlQjY
- will be shown after onboarding
- defaults to the currency of which the buyer has a sufficient amount with the following order of preference: DAI > ETH > OGN
- [is disabled when there are insufficient funds for the selected currency](https://zpl.io/aRXEwJK)

**Transaction Detail Page**
- will need updates to the escrow section

**Questions**
- Do we still convert ETH to DAI if the seller is only willing to accept DAI and the buyer only has (sufficient) ETH?
- Do we support partial OGN values or round them up to the nearest whole number?

💛 🖤 💙

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by shahthepro** [comment]
@micahalcorn 

> defaults to the currency of which the buyer has a sufficient amount with the following order of preference: DAI > ETH > OGN

I think @franckc changed the order from `DAI > ETH` to `ETH > DAI` with one of his PRs. Does this mean it should be reverted? Or should the order be `ETH > DAI > OGN`?

**Comment by micahalcorn** [comment]
@shahthepro I think much of logic will change and be simpler. What I'm proposing here is simply the default selection for the UI element, which doesn't currently exist.

@franckc's PR is consistent with this issue; if a buyer has ETH, she can pay without it getting converted (assuming that the seller accepts ETH and that the buyer chooses ETH in the UI)

I'm still not sure about the answer to the first of the two questions I posed above regarding whether or not we will still utilize Uniswap to convert anything - either with explicit direction from the buyer or automatically as we have done up until now. 🤔 I think there's a case for indicating to the buyer that the seller "accepts ETH" even if she actually only accepts DAI and we're going to convert the ETH on the buyer's behalf. But I don't think @matthewliu has had a chance to weigh in on that yet.

**Comment by shahthepro** [comment]
Closed via #3487
