### ISSUE TITLE
Multi-marketplace issues noticed in event-listener

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#3387]
Problem appears likely to be in graphql, since the listener doesn't do any ID assembly.  Instead of a new listing getting indexed properly today, this was seen in the logs:

    Indexing listing in DB:       id=4-000-6-5084518 blockNumber=5084518 logIndex=1
    Indexing listing in Elastic:  id=4-000-6-5084518
    Skipped insert: found 1 past growth event ListingCreated for account 0x564aae0251d49d1f8d4d8d9e5da08f8cceff9ef2
    Handler result: {
      "event": {
        "address": "0xcddE3E2D6b42764DB3637b0463D529209526569e",
        "blockNumber": 5084518,
        "transactionHash": "0xeb08050866b6cf7c179fd5966b3947b10be7711289ae2b22bb35238fb723a276",
        "transactionIndex": 1,
        "blockHash": "0x596e4887040a027763188d6b419ae00438e7c0d7527d268a5bd5d56329be54f4",
        "logIndex": 1,
        "removed": false,
        "id": "log_f52cfae0",
        "returnValues": {
          "0": "0x2cFE427c032b058178deb56C88F1E07200c04b71",
          "1": "6",
          "2": "0x6861e680b478032e9533f8ad11e54419bb2d0be095eb6b0a3bf172039d000c5d",
          "party": "0x2cFE427c032b058178deb56C88F1E07200c04b71",
          "listingID": "6",
          "ipfsHash": "0x6861e680b478032e9533f8ad11e54419bb2d0be095eb6b0a3bf172039d000c5d"
        },
        "event": "ListingCreated",
        "signature": "0xec3d306143145322b45d2788d826e3b7b9ad062f16e1ec59a5eaba214f96ee3c",
        "raw": {
          "data": "0x6861e680b478032e9533f8ad11e54419bb2d0be095eb6b0a3bf172039d000c5d",
          "topics": [
            "0xec3d306143145322b45d2788d826e3b7b9ad062f16e1ec59a5eaba214f96ee3c",
            "0x0000000000000000000000002cfe427c032b058178deb56c88f1e07200c04b71",
            "0x0000000000000000000000000000000000000000000000000000000000000006"
          ]
        }
      },
      "related": {
        "listing": {
          "id": "4-000-6-5084518",
          "valid": true,
      [...snip...]

Notice the contract version is still `000`.

**Comment by franckc** [comment]
Blocker for deploying Marketplace V1. Setting priority as P1

**Comment by mikeshultz** [comment]
https://github.com/OriginProtocol/origin/blob/2626daff65a731095d6fd31fc6a9fb4ccf59a804/packages/graphql/src/utils/getId.js#L1-L11
