### ISSUE TITLE
Gas is overestimated when using a proxy

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3393]
Account 0x5b2A5d1AB8a5B83C0f22cB1Df372d23946aA7d8F
Proxy 0xa95D201E84d2B50c075Fd28ffD3C1DBb0bb00C5B
Purchased: https://shoporigin.com/#/listing/1-000-3161 priced at $1

The MetaMask transaction confirmation showed me a gas estimate of $3.51 because we set the gasLimit to 1M [here](https://github.com/OriginProtocol/origin/blob/master/packages/graphql/src/mutations/_txHelper.js#L220).

Here is the [txHash](https://etherscan.io/tx/0x98cb0a3d54fe98d0b5b42f71c0932b1726bb5a5347993abc7ff62501c22256f4).

That particular makeOffer tx ended up using 201,879 gas, way lower than 1M.

**Comment by franckc** [comment]
@DanielVF Per our chat, if you have some cycles, would be great to tune those gasLimits... Users get frighten when seeing those expensive gas fees ! :)

**Comment by DanielVF** [comment]
Here's an execution trace of that transaction. 

![image](https://user-images.githubusercontent.com/837/66228611-db085d80-e6ad-11e9-886d-576436f0da16.png)

It doesn't actually create a proxy, which means the old code must have set this high gas even though it wouldn't be needing it at all. And indeed, the [old code](https://github.com/OriginProtocol/origin/blob/a716c6753618759fffbb25e948c492b0279424ab/packages/graphql/src/mutations/_txHelper.js#L168-L178) does set 1,000,000 gas price if a proxy is used, regardless of it a new proxy contract needs to be created or not.

The [current code](https://github.com/OriginProtocol/origin/blob/a712c375dd4a3edb0fa7a5e18ada1792dab2aeeb/packages/graphql/src/mutations/_txHelper.js#L698) only uses the ultra-high gas when a proxy is actually created. Much, much better.

I'll figure a formula for doing new proxies with a more exact price and less slop.
