### ISSUE TITLE
Repair DAI Purchases

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3419]
It sounds like https://github.com/OriginProtocol/origin/pull/3331 unintentionally prevented people from making offers using DAI. To recap, here is the current expected behavior:

**Seller Accepts DAI & ETH**
- If buyer has sufficient DAI, payment will be made using DAI
- If buyer has insufficient DAI and sufficient ETH, payment will be made using ETH **_and not converted to DAI_**
- If buyer has insufficient DAI and insufficient ETH, funding message will be displayed

**Seller Accepts DAI Only**
- If buyer has sufficient DAI, payment will be made using DAI
- If buyer has insufficient DAI and sufficient ETH, payment will be made using ETH _and automatically converted to DAI_
- If buyer has insufficient DAI and insufficient ETH, funding message will be displayed

**Seller Accepts ETH only**
- If buyer has sufficient ETH, payment will be made using ETH
- If buyer has insufficient ETH, funding message will be displayed

This will all be simplified by the move to [buyer-controlled payment methods](https://github.com/OriginProtocol/origin/issues/3383). If that isn't going to happen very soon, then we should fix this issue immediately.

😕

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by nick** [comment]
Will take a look at this...

**Comment by shahthepro** [comment]
@micahalcorn @nick FYI, I was planning to start #3383 by the end of this week.
