### ISSUE TITLE
'When' field not working on Firefox when creating a 'Tickets' listing

### ISSUE THREAD

**Issue by jonhearty** [OriginProtocol/origin#342]
Using Firefox and trying to create a 'Tickets' listing but the 'When' field does not accept any input

http://demo.originprotocol.com/#/create

<img width="502" alt="screen shot 2018-08-03 at 4 46 44 pm" src="https://user-images.githubusercontent.com/3673242/43670102-4294e7be-973d-11e8-8626-6e84c93dbc9b.png">

**Comment by anshumanv** [comment]
It does seem to work when you paste a valid timestamp but not sure about other cases, how about we use a lightweight lib for date and time input(which will also make it consistent across browsers)? 

cc @micahalcorn

**Comment by micahalcorn** [comment]
@jordajm are you planning to use a datepicker in the fractional UI? I seem to recall that being one of Aure's action items: to get you a mockup for that element.

**Comment by jordajm** [comment]
@micahalcorn a datepicker is no longer part of the initial fractional usage UI, but may be incorporated later

**Comment by jordajm** [comment]
I dug into this one a little more and found that `react-jsonschema-form` uses `<input type="datetime-local" />` to render their datepicker elements, which is not supported by firefox:
https://caniuse.com/#feat=input-datetime

So, I think we'll need to build a custom datepicker widget (probably using the datepicker lib we're already including in the dapp: https://github.com/airbnb/react-dates) and pass that into the create listing form using `ui-schema`.

**Comment by micahalcorn** [comment]
Thanks @jordajm 😔 I don't think this should be blocking for now. cc @franckc

**Comment by micahalcorn** [comment]
Closing this, as we no longer have custom schemas for the ticketing case 🎟
