### ISSUE TITLE
𝕿𝟥 UX Audit

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3437]
Here are the notes from @auregimon's review of 𝕿𝟥 (in no particular order):

|Description|Assignee|Status|
|:--|:--|:-:|
|Numbers should have commas|@micahalcorn|✅|
|Input fields should be appropriately sized with text alignment|@micahalcorn|✅|
|The logo is blurry in the email template|@tomlinton|✅|
|Height of "News" card should match the variable height of "Available Balance" card|@tomlinton|❔|
|Clicking anywhere on the news card (other than "Read more") should advance to the next article|@tomlinton|✅|
|The news card should be a carousel looping to the beginning instead of having an end|@tomlinton|✅|
|Horizontal space between "Vesting History" and "Investment Details" should be the same as between the "Available Balance" and "News" cards|@tomlinton|✅|
|The "Vesting History" table should always have a visible vertical scrollbar|@tomlinton|✅|
|Nav items need more horizontal spacing|@tomlinton|✅|
|Left align dots with bar|@tomlinton|❔|
|Consistent news article heights|@tomlinton|❔|
|Consistent aspect ratio on news article images|@tomlinton|✅|
|Open Medium links in new tab|@tomlinton|✅|
|Image caption bleeds into article summary|@tomlinton|❔|
|Session timeout occurs with no warning or explanation|@tomlinton|✅|
|Black text in warning alerts|@micahalcorn|✅|
|Withdrawal history rows need hover state|@micahalcorn|✅|
|Less vertical space around "Ethereum Accounts" and "Session History"|@micahalcorn|✅|
|More space needed below alert on withdrawal detail|@micahalcorn|✅|
|Underline on logout hover|@micahalcorn|✅|
|Add a success toast on account CRUD operations|@tomlinton|❔|
|View all history on vesting from dashboard|@tomlinton|❔|

Also: https://github.com/OriginProtocol/origin/issues/3441, https://github.com/OriginProtocol/origin/issues/3442 & https://github.com/OriginProtocol/origin/issues/3443

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by tomlinton** [comment]
```Height of "News" card should match the variable height of "Available Balance" card```

I think the news card is the one with the variable height here right? In that case, should the available balance card add empty whitespace at the bottom to match? This would of course change every time the news carousel changed (if the news card size changed as a result).

**Comment by micahalcorn** [comment]
Sorry @tomlinton 😬 I think @auregimon was hoping for the news card to have a fixed height. The balance card is variable based (at least) on whether or not the tokens are locked. I think it would be fine to let either of them dictate the height of the other one.

**Comment by micahalcorn** [comment]
Considering this done ✅
