### ISSUE TITLE
Enable Meta Transactions?

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3460]
I'm unable to create a listing with a new 0.23 (18) installation and a new wallet. 😕

![IMG_8863](https://user-images.githubusercontent.com/273937/65390361-b954c100-dd12-11e9-9294-385046c3c989.PNG)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by tomlinton** [comment]
Relayer error for this:

```[ERROR] relayer: Proxy already exists at 0xA8D6FA177509b27A9608f09E0F4C57b9E08C2726 for user 0x23d61bF86E64fEe96BE0eb61784dEd0e0c554bbA```

This is tracked in #3179 which we thought was resolved, but will reopen.

**Comment by mikeshultz** [comment]
The txHelper refactor and the work on cache resetting should have helped this...  Can you remember anything from this onboarding that might shed light on this?  This doesn't make any sense on a new install with a brand spanking new wallet.

- Did you refresh while a tx was being sent?
- Any double-prompts?
- You completely sure you didn't re-use a private key?
- Any error modals at all, ever?

For this to have happened, you must have sent a transaction(through the relayer or not), that created your proxy before this prompt.  So, any light you can shed on how you went from that to this would be helpful.

Also, what's with the stupid title of this modal?  "Enable Meta Transactions"?

**Comment by tomlinton** [comment]
I didn’t know what to call it, Create Proxy With Sender Nonce seemed a bit abstract 😂

**Comment by micahalcorn** [comment]
@mikeshultz I 100% did not import a key or phrase. I don't remember refreshing at all. I did publish an identity prior to having this experience, so it's possible that something about that transaction did not work? But I don't remember any other errors. 😕

**Comment by micahalcorn** [comment]
@mikeshultz I was able to publish a listing just now using that account and that app installation. ✅ I basically resumed the session from three days ago. The process was probably killed, resulting in a new webview. But I didn't consciously alter anything.

**Comment by mikeshultz** [comment]
If I had to guess, that's probably because you were no longer on a spoiled cache.  The app now knew about your proxy.  I'm not convinced this is fixed, but thanks for the update.

**Comment by mikeshultz** [comment]
I think #3532 should get rid of the vast majority of these issues.
