### ISSUE TITLE
Clicking on mobile push notification cause app to crash

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3482]
Repro steps (on Mainnet):
 - ios v0.23.18
 - Using the mobile app as a buyer, make an offer
 - Have seller accept it
 - Buyer receives a mobile push notification for the offer being accepted by the seller
 - Tap on the mobile notification
 => It causes the mobile app to crash

**Comment by franckc** [comment]
CC @tomlinton @sparrowDom

**Comment by tomlinton** [comment]
Should be resolved in > `0.24.x`.
