### ISSUE TITLE
Increase Transaction Detail Link Clickable Area

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3508]
I should be able to click anywhere on one of these list items to navigate to the transaction detail. Currently, only the title is linked.

![C3B8FDFA-FA05-4B26-A99F-56F390E000B3](https://user-images.githubusercontent.com/273937/65661392-6450cd80-dfe6-11e9-8ccd-eeff12cf6765.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by vivianedias** [comment]
Hi! I'd like to claim this issue :smile:

**Comment by micahalcorn** [comment]
Welcome @vivianedias 😊 Have you joined us in [Discord](https://originprotocol.com/discord) yet? Please say olá if you have not already.

**Comment by micahalcorn** [comment]
Resolved by #3562 ✅
