### ISSUE TITLE
Price box and 'back'/'done' buttons misaligned when reactively displayed for mobile

### ISSUE THREAD

**Issue by jonhearty** [OriginProtocol/origin#354]
Price box is unreadable when the window width is small enough to display reactive elements (when "ORIGIN" in header goes to "O"). "Back" and "Done" buttons are also misaligned. Using Firefox.
<img width="1915" alt="screen shot 2018-08-06 at 3 25 09 pm" src="https://user-images.githubusercontent.com/3673242/43743999-ef4a6eba-998c-11e8-899a-d485ebda5f28.png">
<img width="683" alt="screen shot 2018-08-06 at 3 22 09 pm" src="https://user-images.githubusercontent.com/3673242/43744000-ef644cea-998c-11e8-9cfb-8d9373621f3e.png">

**Comment by micahalcorn** [comment]
DApp2 fixed it 🙂
