### ISSUE TITLE
"Add Listing" button doesn't work while in process of submitting listing

### ISSUE THREAD

**Issue by jonhearty** [OriginProtocol/origin#355]
Actual: While in step 2+ (create listing, preview listing, etc.) of submitting a listing, the "Add Listing" button in the header doesn't work.

Expected: Clicking "Add Listing" at any time always brings you back to Step 1 of http://demo.originprotocol.com/#/create

Using Firefox

**Comment by jordajm** [comment]
I think this is because the "Add a listing" is just a link to the `/create` route and since the browser is already on the `/create` route, it doesn't make the workflow start over at step 1 of the "create listing" workflow.

**Comment by micahalcorn** [comment]
Now does return the user to step 1️⃣
