### ISSUE TITLE
Can’t Create a Listing on Mainnet

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3561]
![06F43FFD-D058-4D23-BF59-1D40EEBBA159](https://user-images.githubusercontent.com/273937/65834261-2a095980-e28e-11e9-8b4b-d39fe5633837.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by nick** [comment]
Unable to reproduce this any more. Please re-open if you see it again...
