### ISSUE TITLE
Dead Grey Space in Firefox

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3563]
There is some excess margin or padding at the top of the DApp in Firefox. Interestingly, it affects small-screen-desktop a lot, but does not affect the actual Firefox mobile app.

**Large-Screen Desktop**

![Screen Shot 2019-09-29 at 10 53 01 AM](https://user-images.githubusercontent.com/273937/65836920-9775b400-e2a7-11e9-8e66-3c5b6421cf71.png)

**Small-Screen Desktop**

![Screen Shot 2019-09-29 at 10 53 17 AM](https://user-images.githubusercontent.com/273937/65836930-993f7780-e2a7-11e9-8244-2860d0cbadc1.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by mahamat** [comment]
Hey @micahalcorn, is this issue still valid ? cause on Firefox desktop, i am not seeing grey space. Thanks
<img width="335" alt="Screen Shot 2019-11-26 at 19 01 25" src="https://user-images.githubusercontent.com/511262/69650214-528bb500-107f-11ea-80fc-337e105407a7.png">

**Comment by micahalcorn** [comment]
Yep, this seems to have resolved itself, thx 😁
