### ISSUE TITLE
Can't Release Funds

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3566]
When the relayer is out of funds, the following happens:

- MetaMask signature request (as expected)
- "Relayer is overloaded right now" in the console
- MetaMask prompt to pay gas and confirm
- [transaction failure](https://etherscan.io/tx/0x32454ead941e76ca2a7d15aad945338e4b5cc5686cb96baf68c7b0353092c10a) with message "Only buyer can finalize"

Why doesn't paying gas work? Is it attempting the transaction using the wallet account rather than the proxy account? After fixing that, can we include some messaging about why the signature request didn't work and explain why the user is prompted to pay gas?

😕

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by mikeshultz** [comment]
I think the fallback is failing because it expects the transaction to be sent by the relayer, which would send it via the proxy's `forward()` method.

CC @nick 
Ref: #3357, #3283

**Comment by nick** [comment]
Yea the proxy request should be wrapped with `execute` if the relayer is unavailable. I have a fix locally and will make a PR shortly

**Comment by nick** [comment]
Should be fixed by #3575

**Comment by micahalcorn** [comment]
Closing until we see a reproduction 🤞
