### ISSUE TITLE
[Growth] Auth token is cleared every time a new DApp version is deployed

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3611]
[This code ](https://github.com/OriginProtocol/origin/blob/master/dapps/marketplace/src/index.js#L4)causes the token to get cleared every time the DApp detects a new version of the code was deployed.

We have been doing several deploys a week lately.

As a result a user would get presented the flow for signing the growth terms very frequently.

We could consider optimizing this and not clear the auth token so aggressively.

Another nice enhancement would be allow to switch between account and not require to sign in again. By either prefixing the token name with the eth address or by storing the data as a JSON structure that maps eth address to auth token.

**Comment by franckc** [comment]
CC @sparrowDom @micahalcorn @milachoi

**Comment by sparrowDom** [comment]
Pr solving this: https://github.com/OriginProtocol/origin/pull/3612

**Comment by sparrowDom** [comment]
fixed via: https://github.com/OriginProtocol/origin/pull/3612

**Comment by micahalcorn** [comment]
Does something similar happen with messaging keys? I am constantly having to reenable messaging and I think it is not just attributable to switching accounts. 😕

**Comment by franckc** [comment]
@shahthepro Do you know re @micahalcorn's question above ?

**Comment by shahthepro** [comment]
@franckc  Not sure about that. But I'm fixing a bunch of issues that popped up after moving #3171 to staging. If I can reproduce this, will fix that.

**Comment by sparrowDom** [comment]
@micahalcorn messaging keys are stored as cookies, so they aren't affected by the localStorage clearing itself. 

Though if you reinstall the app on the phone the cookies don't survive that
