### ISSUE TITLE
Rewards Following w/Wrong Prerequisites

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3616]
In the screenshot below, I clicked "Follow us on Twitter". I _do_ have name, photo, and email completed. But I _don't_ have a Twitter verification. I thought we fixed this issue in regard to Telegram, but I can't find a reference to it.

![IMG_9046](https://user-images.githubusercontent.com/273937/66071506-1cf79f00-e508-11e9-98f6-ac618d398761.PNG)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment]
@micahalcorn What's your eth address ?

@sparrowDom Any idea what could be wrong ?

**Comment by micahalcorn** [comment]
@franckc `0x96FEb7b6F808dd2BBd09c9E5ccdE77caBd58d019` 📲

**Comment by sparrowDom** [comment]
fixed via: https://github.com/OriginProtocol/origin/pull/3638

@franckc when we deploy this to staging/production. Could you please update the October rules on growth?

**Comment by franckc** [comment]
@sparrowDom Awesome ! You are so fast. I don't think we need to update the rules in the DB. We just need to deploy the code to prod. I can do a prod deploy today...

**Comment by franckc** [comment]
Prod deployed with the fix and rules updated in the prod DB.
So this should not happen anymore in prod...
