### ISSUE TITLE
Unnecessary DAI Conversion

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3619]
When I attempt to purchase a listing with 0 DAI in my wallet but with sufficient ETH, the DAI conversion is only supposed to come into play when DAI is the only currency accepted by the seller. [This was the decision that we reached last month](https://github.com/OriginProtocol/origin/issues/3419) due to the problems that were being caused by unnecessary DAI swaps. Currently, I'm able to make a DAI-to-ETH offer on [this listing](https://dapp.staging.originprotocol.com/#/listing/4-000-883) even though the seller accepts ETH. If we want to revisit this decision, we need to all be aware of the conclusion and update references to it. Otherwise, this should be fixed.

😐

cc @nick @franckc @shahthepro 

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by nick** [comment]
I think this is a result of the new Payment page. I had exposed a `suggestedToken` prop via the `WithPrices` component which suggests the default payment method to use based on your current balances and what payments are accepted on the listing. It will always suggest Eth if the listing accepts both Eth and Dai.

@shahthepro perhaps we can use that prop in the new payment flow?
