### ISSUE TITLE
Improve Telegram Verification UX

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3627]
Add the following, if possible, as discussed in Discord:

1. When the Telegram app is opened, the bot should welcome you buy saying "Hi, get started verifying your Telegram account by clicking "/start" below."

2. After you click "/start", the bot should reply with "Great, now reopen the Origin Marketplace app to complete your verification".

3. After the app is reopened, automatically initiate the verification and change the button copy from "Verify" to some kind of loading state.

🤖

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by shahthepro** [comment]
Closed through #3667
