### ISSUE TITLE
Search location picker UI

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#366]
Build a UI component for search location picker, per mock here: https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5b5178822f0b6de02778f914

**Comment by micahalcorn** [comment]
No longer relevant per https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/dashboard?seid=5d4ca9dc6986389b1e310c77 😐
