### ISSUE TITLE
[Growth] Featured listings title should not be translated

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3661]
Per a discussion on the #translation channel on Discord, it would be preferable to not translate the listing titles on the campaign purchase page: https://shoporigin.com/#/campaigns/purchases

Reasons:
 - The listings themselves are in various languages, not only english and translator get confused. For example we featured a listing from Venezuela with a spanish title "Perros Calientes La elegancia". And this title showed up as a string to translate in crowding... but translators expect all strings to be in english...
 - We can't be sure translators will translate correctly listing titles and sellers may not be happy about that.

**Comment by franckc** [comment]
CC @micahalcorn @sparrowDom

**Comment by franckc** [comment]
@sparrowDom If you have some cycles would be great to fix this since we have an important partner in November that will have featured origin rewards listings with titles in chinese...

This issue applies to both the title and description of the featured listing.

I think the fix would be to get the title directly from the campaign config and not wrap it in a fbt call in the DApp. Though we have to be a bit careful about backward compatibility since for some period of time users may run an old DApp that still wraps with fbt...
a few different options come to mind:
a) add 2 new fields to the growth schema called "title" and "details". We leave for now "titleKey" and "detailsKey" and we'll deprecate them a bit later once we are sure no client is using them.
b) we could just use the existing "titleKey" and "detailsKey" and just not wrap them with fbt calls
c) have both "title"+"titleKey" and "details"+"detailsKey". Have the DApp check. If "title" is defined, use without fbt wrapping, otherwise use "titleKey" with fbt wrapping. Same for details.

Maybe c) gives us the most flexibility for the future ?

**Comment by sparrowDom** [comment]
On it, yeah I like the `c)` option the most also. Seems the most clean and versatile.

**Comment by sparrowDom** [comment]
fix here: https://github.com/OriginProtocol/origin/pull/3853

**Comment by franckc** [comment]
ah yes, thanks a bunch for fixing this @sparrowDom 
Closing this now
