### ISSUE TITLE
Recovery phrase display

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#3679]
User **djfunny28** reported on Discord that he deleted the marketplace app and was frustrated because that meant loosing OGN and access to a listing he was selling. He felt that recovery phrase should be present as part of the on-boarding. 

I know we don't want to introduce extra steps to already somewhat lengthy on-boarding process. Perhaps we could show the recovery phrase once a user has something meaningful to lose. I think that could be as soon as user has Eth / OGN / Listing / Offer connected to the wallet.

**Comment by sparrowDom** [comment]
@micahalcorn just recording the experience from Discord. Will let you decide what (if anything) to do about this issue.

**Comment by 9racoin** [comment]
Thanks for raising this issue. It's painful to lose access to listings as I'm not aware I need to recover account by private keys

**Comment by sparrowDom** [comment]
Closing this for now, since @micahalcorn says we already have mockups for this and is in the funnel to be created.
