### ISSUE TITLE
Error modal get console logs 

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#3684]
Currently when an error happens inside the dapp an error modal pops up and users can click on the "console" text to retrieve the last error. 

We can add a guide (or link to a guide) on that modal for the user to explain how to:
- turn on `Screen console`
- try to reproduce the error
- see screen console results and report them to us

**Comment by sparrowDom** [comment]
@micahalcorn ☝️

**Comment by sparrowDom** [comment]
Thinking a bit more about it, we might consider how other companies deal with this issue. Usually the reporting of the error steps are a lot more automatic. Users just need to click on "send report" and sometimes they are asked to write down what they were trying to achieve before the error happened. 

We could hold the last X console logs in memory (not surviving refreshes) without performance impact and sending them automatically (or when user clicks "report error").

**Comment by micahalcorn** [comment]
Agreed @sparrowDom 👍 This felt a bit misguided to me. We basically need an extension of https://github.com/OriginProtocol/origin/issues/3346 for exceptions.

**Comment by sparrowDom** [comment]
@micahalcorn seems to me that https://github.com/OriginProtocol/origin/issues/3346 would be a better one for error reporting. Have added an item to the list of: 
```
last (15-20) browser console logs (could also limit by timestamp. -> console logs in the last 30 seconds before the error)
```

Closing the issue in favour of https://github.com/OriginProtocol/origin/issues/3346.
