### ISSUE TITLE
App Browsing: back brings you back to the top of search

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#3707]
- browse the listings search results
- visit a listing
- go back to all listings
- **you are sent back the top of search listings** and you have to scroll down again to continue.
As a result browsing is uncomfortable.

**Comment by micahalcorn** [comment]
Thx @lucadgtrip 👍 I'm going to close this in favor of https://github.com/OriginProtocol/origin/issues/3303.
