### ISSUE TITLE
Potentially non-localizable string

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#372]
For localization, we cannot be assembling sentences from component parts, as other languages' grammar/segmenting/ordering may not be like English, and they may have extra requirements around gender/case changes.

This code is used to create sentences like "In order to create a listing, you must install MetaMask":
 
```
    <div>In order to {props.web3Intent}, you must install MetaMask.</div>
```
([link](https://github.com/OriginProtocol/origin-dapp/blob/master/src/components/web3-provider.js#L41))

This needs to be structured into complete sentences that can be translated whole.

**Comment by micahalcorn** [comment]
No longer relevant in DApp2 🌐
