### ISSUE TITLE
String not localized

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#373]
When selected German, this english text still shows up: 

<img width="1392" alt="screen shot 2018-08-09 at 5 06 44 pm" src="https://user-images.githubusercontent.com/673455/43930787-a7fddd94-9bf8-11e8-9198-7734fbb3da14.png">

The string is in translated, according to crowdin. 
https://crowdin.com/translate/originprotocol/63/en-de#q=you+must+sign+in+to

**Comment by micahalcorn** [comment]
No longer relevant in DApp2 🌐
