### ISSUE TITLE
Cannot Confirm Purchase

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3762]
This confirm purchase screen sticks with a "Loading..." button in our mobile app. 😕

https://dapp.staging.originprotocol.com/#/listing/4-000-383

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by shahthepro** [comment]
@micahalcorn Just tested it on iOS as well as on desktop. Works fine for me. I cannot seem to reproduce this. :/ 

https://dapp.staging.originprotocol.com/#/purchases/4-000-383-0
https://dapp.staging.originprotocol.com/#/purchases/4-000-383-1

**Comment by micahalcorn** [comment]
![A28EF460-3B5F-4EF9-96E5-3B8532FDD4FE](https://user-images.githubusercontent.com/273937/67255396-c1e60780-f436-11e9-8f3f-c5c2ae3ea340.png)

**Comment by micahalcorn** [comment]
This is what I get both on and off WiFi. ☹️

**Comment by franckc** [comment]
@micahalcorn Any error in the console ?

**Comment by micahalcorn** [comment]
@franckc none in the mobile "screen console" as far as I can tell. It's a bit difficult to confirm because I am in a nested route when this happens and can't access the hamburger menu without navigating backward a few steps. 🍔

**Comment by mikeshultz** [comment]
To add a bit of info: The staging relayer appears to have seen zero traffic since the deploy at 3:50PM PST yesterday.

**Comment by franckc** [comment]
As a data point, I just tested on Desktop with metamask and it works fine for me...

**Comment by franckc** [comment]
Tested on iOS with v0.24.3 of the mobile app and was able to reproduce. Got stuck on the"Loading..." button on the Confirm Purchase page...
After a couple min waiting I navigated back to home page and checked the console. It was empty.

Anyone knows what the DApp is waiting on when showing that "Loading..." button on the Confirm Purchase page ?

**Comment by mikeshultz** [comment]
Should be noted that that console that was added is for the dapp, not the mobile app.  So if there is an error, it's on the mobile app side.

I was able to repro:

  
![loading-purchase](https://user-images.githubusercontent.com/1048089/67312500-ab838e80-f4be-11e9-958b-2b163eb6aa4b.png)

**Comment by sparrowDom** [comment]
@shahthepro I am able to reproduce the bug (debugging right now). The above fix didn't solve the problem for me.

**Comment by micahalcorn** [comment]
Confirmed: resolved ✅
