### ISSUE TITLE
Tiny/Missing User Activation Wallet Step Vendor Logos

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3774]
This seems to be caused by certain screen widths.

![mobile-no-logos](https://user-images.githubusercontent.com/273937/67385069-314b1c80-f547-11e9-8fa4-2c7e9b3ef679.png)

<img width="424" alt="Screen Shot 2019-10-23 at 3 34 07 AM" src="https://user-images.githubusercontent.com/273937/67385082-34dea380-f547-11e9-909f-7a8038f7edf3.png">

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by shahthepro** [comment]
Closed via #3910
