### ISSUE TITLE
Responsive Email Templates

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3783]
Our emails don't render so well on a lot of screens and we haven't invested much time in perfecting them. As we all know, email markup and styling is archaic and difficult. Let's explore converting our templates to use [mjml](https://mjml.io/) or something similar.

I'm not sure where all we would want to do this, but the best place to start would probably be our transactional [notification emails](https://github.com/OriginProtocol/origin/tree/master/infra/notifications/templates).

📧

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment]
For another project (T3) we have been using mjml and I would highly recommend we use it...
See https://github.com/OriginProtocol/origin/tree/master/infra/token-transfer-server/src/templates and https://github.com/OriginProtocol/origin/blob/master/infra/token-transfer-server/src/lib/email.js

**Comment by rembrandtreyes** [comment]
> For another project (T3) we have been using mjml and I would highly recommend we use it...
> See https://github.com/OriginProtocol/origin/tree/master/infra/token-transfer-server/src/templates and https://github.com/OriginProtocol/origin/blob/master/infra/token-transfer-server/src/lib/email.js

Perfect. I can use MJML.
