### ISSUE TITLE
Update translation status for all languages in README.md

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/origin#379]
The README here:
https://github.com/OriginProtocol/origin/tree/master/origin-dapp/translations
contains a table that needs to be updated with the translation status of all supported languages based on crowdin completion percentage found here:
https://crowdin.com/project/originprotocol

Similar to the Origin website translations README found here:
https://github.com/OriginProtocol/origin-website/tree/master/translations

**Comment by vikaskyadav** [comment]
Can I push the relevant table in the readme?

**Comment by jordajm** [comment]
Hi @vikaskyadav - yes, thanks! @micahalcorn can add you as a contributor so you don't have to PR from a fork. Let me know if you have any quesitons

**Comment by micahalcorn** [comment]
@vikaskyadav I see that you are already a contributor, but your visibility is set to private. Please consider changing that to public. 😊 As for these changes, you won't be able to push them to master or develop, but please do create a pull request, thanks!

**Comment by devotebest** [comment]
https://github.com/OriginProtocol/origin-dapp/tree/develop/translations this branch doesn't exist.
@micahalcorn

**Comment by micahalcorn** [comment]
Updated ✅ Thx @devotebest!

**Comment by micahalcorn** [comment]
Resolved by #422 😐
