### ISSUE TITLE
Missing Verification Success

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3790]
After publishing my profile, I should see that step in the completed section of my Verifications in the dashboard. Currently, it’s missing and there is no padding below the horizontal rule.

![1037AF07-36B3-4951-9094-4E8429EB1A53](https://user-images.githubusercontent.com/273937/67624978-e18d7f00-f7ec-11e9-9a58-4ba27425e7c4.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by micahalcorn** [comment]
Under some circumstances, there is no "Completed" heading at all. I'm not sure how to reproduce it, but I've seen it several times. Also, the phone number verification has the same problem as profile verification (not showing up under completed). 👎

**Comment by micahalcorn** [comment]
I think the missing completed section is an issue for a few seconds when the page is first rendered and there is some loading going on. It eventually appears. 😕

**Comment by micahalcorn** [comment]
Twitter is also not appearing after completion. 👻

**Comment by mikeshultz** [comment]
Since this is expected for my project and completed items are always missing for me, I'll poke at this a bit.
