### ISSUE TITLE
Telegram Verification Confusion

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3792]
After `/start`, I manually return to the Origin app.

![B6506959-7606-4872-ABF9-68325DD3524E](https://user-images.githubusercontent.com/273937/67625263-a8570e00-f7f0-11e9-8916-00283d7db2b2.png)

There I see a timeout, which doesn't make a lot of sense because I don't think I sat on the Telegram app for very long at all.

![45203054-DE6E-43D0-8B96-E8DE0F06EC66](https://user-images.githubusercontent.com/273937/67625264-a8570e00-f7f0-11e9-87b6-4e151cde7541.png)

After manually returning to Telegram and then immediately returning to the Origin app again, it seems to be magically working.

![82C0ACB0-515B-4A69-AB0F-0AE5D1B6EDB3](https://user-images.githubusercontent.com/273937/67625265-a8570e00-f7f0-11e9-9c93-3608d01f081b.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by shahthepro** [comment]
Considering this closed with #4054
