### ISSUE TITLE
Unable To Proceed w/Rewards

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3799]
Here is a report of a user whose verifications are not detected when he signs up for Origin Rewards.

I've inferred that the identity address is likely 0xa17456c07fad4b1764345af62f4fa26b3102b00a.

He subsequently republished his email address and it didn't change anything.

![Screen Shot 2019-10-28 at 10 25 52 AM](https://user-images.githubusercontent.com/273937/67701936-1543e280-f96e-11e9-98f3-8949d5d8290a.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment]
Should be fixed by #3801
The listener had a bug causing the proxy table to not get updated. That would then cause the identity to not be able to find the attestations (since those are key off by proxy address).
