### ISSUE TITLE
Show other jsonschema fields on listing-detail page

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#38]
Right now we only show photos, title, description, and price. 

We should at least show the other fields if present.

**Comment by wanderingstan** [comment]
Right now all the listing fields (both ipfs and from the contract) are stored flat in the component state, along with housekeeping fields for the component like `step`.

I think we should instead have a `state.ipfsData` and `state.contractData`, which contain the correspondent fields. Then we can iterate over extra fields in ipfsData to display them (if we know how)

**Comment by wanderingstan** [comment]
> contract and IPFS data could be stored separately
This is perhaps an issue unto itself. Currently we return ipfs+contract data merged together in one json ([docs](http://docs.originprotocol.com/#getbyindex)) 

For the purposes of this issue, we should just display any fields that are not handled by the GUI.

Aure (our designer) will surely have more to say about it, but for now just dumping them onto the display is a good first step. We'll sometime need to do a bigger design overhaul of extended data is shown on `listings-detail` page -- the seller address and "view on ipfs" sections are also just sort of tacked on right now. 

![image](https://user-images.githubusercontent.com/673455/38937337-382545fa-42e0-11e8-9a79-88b0c57b4e95.png)

**Comment by ambertch** [comment]
Linked to #115

**Comment by ambertch** [comment]
This is blocked by https://github.com/OriginProtocol/origin-js/issues/139
