### ISSUE TITLE
Invalid Login Token

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3828]
When I try to reuse an expired, single-use token, I'm not presented with a very friendly path to access my account from a different device (or from the same one a second time). Since I did not navigate directly to the Investor Portal, I don't think I should be expected to know how to do that. I only know of my invitation email as my primary point of entry for accessing this app. I should be given a button or link to request another token or at least be routed back to the root path.

![Screen Shot 2019-10-31 at 12 37 16 PM](https://user-images.githubusercontent.com/273937/67981347-a79ded80-fbdd-11e9-8562-66e3eace9f17.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by tomlinton** [comment]
Closed by #3904.
