### ISSUE TITLE
URL in deprecated 'origin-js' repo description points nowhere

### ISSUE THREAD

**Issue by Zero-1729** [OriginProtocol/origin#3841]
It doesn't look like the issues in the now deprecated [origin-js](https://github.com/OriginProtocol/origin-js) repo are responded to anymore. So for the sake of not having a better place to open this issue, I decided to just open it here.

![Screen Shot 2019-11-03 at 1 39 54 AM](https://user-images.githubusercontent.com/23586626/68078723-b1417400-fddc-11e9-8774-4413fb95f7f7.png)

It seems the URL in the description of the now deprecated [origin-js](https://github.com/OriginProtocol/origin-js) repo points [nowhere](https://github.com/OriginProtocol/origin/tree/master/origin-js). It was probably trying to point to [this monorepo](https://github.com/OriginProtocol/origin), as the link in the README correctly does. 

The maintainer(s) of the aforementioned repo (`origin-js`) should probably consider remedying this, at least for the sake of consistency.

**Comment by micahalcorn** [comment]
Resolved, thx @Zero-1729 ✅
