### ISSUE TITLE
Maximum Update Depth in Onboarding

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3844]
From ShopOrigin.com on Brave desktop with MetaMask installed...

1. Click the avatar in the top right
1. Be told to log in to MetaMask
1. Log in to MetaMask
1. See "MetaMask Connected"
1. Click "Continue" (from `/onboard/metamask`)
1. Get this screen (at `/onboard/email`)

<img width="1440" alt="Screen Shot 2019-11-04 at 8 04 38 AM" src="https://user-images.githubusercontent.com/273937/68136397-0d3df280-feda-11e9-9613-c05f3ca79932.png">

`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by sudheerDev** [comment]
@micahalcorn i ran into this while fixing another issue and made a PR https://github.com/OriginProtocol/origin/pull/3882

**Comment by micahalcorn** [comment]
Nice, thx @sudheerDev 👍

**Comment by tomlinton** [comment]
Relevant Sentry errors https://sentry.io/organizations/origin-protocol/issues/1321436492/events/25fa11d4f8644a5ab33dcfe8cb037b96/?project=1402589

**Comment by tomlinton** [comment]
Bumping this up to a `P0`.

**Comment by micahalcorn** [comment]
Do we just need to merge and deploy #3882 @tomlinton? 😐

**Comment by shahthepro** [comment]
Adding one more thing that I noted about this issue. It is reproducible only if you go through onboarding when you already have a deployed identity.
