### ISSUE TITLE
Onboarding broken with zippy identity

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3848]
The onboarding flow seems broken when zippy identity is enabled.
Tested on desktop with MetaMask:
 - create a new metamask account with no previous identity associated with it
 - got to https://dapp.staging.originprotocol.com/#/
 - go through the onboarding flow
 - the identity gets correctly saved in the back-end
 - but at the end of the flow, the identity does not get refreshed. It looks as if the DApp does not know the identity was saved. Forcing a browser refresh of the page loads the newly created correctly

**Comment by franckc** [comment]
CC @micahalcorn @sparrowDom

**Comment by sparrowDom** [comment]
fixed via: https://github.com/OriginProtocol/origin/pull/3853/files

**Comment by franckc** [comment]
Thanks so much! Will test on staging once it is up...

**Comment by sparrowDom** [comment]
Have tested on staging, works now.
