### ISSUE TITLE
Force MetaMask Intrusive Popup

### ISSUE THREAD

**Issue by acal** [OriginProtocol/origin#386]
[micah] **Edit 9/24/2018**

We should investigate whether or not there is a way to force MetaMask to intrusively pop up unless explicitly dismissed by the user **_per transaction_** rather than display the number on the icon. This is particularly problematic in Brave and when we have back-to-back transactions such as enabling messaging for the first time.

-----
When using Brave / Win10 / Metamask / OP Dapp found that Metamask Reject/Submit modal does not popup as with Chrome and Firefox. Instead the Metamask toolbar icon simply shows a numerical indicator for queued transactions. This works but is inconsistent with the Chrome / Firefox flow and can frustrate users. Assuming this is not due to browser-side settings would be nice to get a modal to pop with metamask when approving listings / sales / attestations etc.

**Comment by davecraige** [comment]
Experiencing this as well.  The icon is very small and may be missed by a number of users.  Screenshot below:

![screen shot 2018-08-14 at 5 11 49 pm](https://user-images.githubusercontent.com/2782676/44123407-6ad004e2-9fe5-11e8-91cd-25eefbc32a27.png)

**Comment by davecraige** [comment]
This issue is happening frequently on https://demo.staging.originprotocol.com

**Comment by micahalcorn** [comment]
Editing this title and opening comment... 🛠

**Comment by roschler** [comment]
This issue I posted may have some helpful debugging info:

https://github.com/MetaMask/metamask-extension/issues/5594

**Comment by micahalcorn** [comment]
Thanks @roschler 😐

**Comment by micahalcorn** [comment]
Punting on this and relying on an animation 👇 

![mm](https://user-images.githubusercontent.com/273937/54482607-6817c200-4803-11e9-857f-6eae98c13f48.gif)
