### ISSUE TITLE
[Nov. Rewards] Twitter share verification failure

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3867]
User with account 0xf82a63dbf88922350e9556eed63fc2e5b70f5a17 is reporting that Twitter sharing verification is broken.

I checked the user's Twitter account and they did tweeted the content. See [tweet](https://twitter.com/hodlecs/status/1191653530223947779).

I checked the bridge logs and I see that the DApp made multiple requests to verify the content. All of them failed.

Here is a sample of the bridge logs:
```
I 2019-11-05T09:48:33.769889547Z [36;22m[DEBUG] [33;1morigin-bridge[0m: Verification Status false
I 2019-11-05T09:48:33.769854733Z [36;22m[DEBUG] [33;1morigin-bridge[0m: Found 0 matching Growth events
I 2019-11-05T09:48:33.767341994Z ContentHash: 2652f5480f3ebc9f4267572c2e85baae
I 2019-11-05T09:48:33.767338251Z UntranslatedContent: Decentralized commerce can empower local communities to buy and sell freely in the emerging world. Here is a recap of @OriginProtocol's recent meetup in Venezuela. 
I 2019-11-05T09:48:33.767333585Z Content: Decentralized commerce can empower local communities to buy and sell freely in the emerging world. Here is a recap of @OriginProtocol's recent meetup in Venezuela. 
 ```

**Comment by franckc** [comment]
@shahthepro Do you think we are having an issue again with the Twitter firehose API breaking?
It's been fairly unstable. 

I wonder if we should consider switching to doing an API call to Twitter per verification. I understand we might hit the rate limits but currently our verification volume is so low that I don't think we would hit that limit anytime soon... Let's discuss.

**Comment by franckc** [comment]
CC @sparrowDom since we briefly discussed about this.

**Comment by shahthepro** [comment]
@franckc Will look into this

**Comment by shahthepro** [comment]
@franckc @sparrowDom This seems to be a misconfiguration problem. Somehow, we missed to add links to the tweet contents. The bridge filters content based on the link it has. So, it ignored all the tweets without a link. 

Have opened a PR for this #3873

**Comment by franckc** [comment]
I updated the November rules in prod to pick up the changes made in #3873 

@shahthepro @sparrowDom Could you please test in prod to make sure this works now? I'll do some testing as well this morning when I get in the office... Thanks :)

**Comment by franckc** [comment]
FYI - Verified with my account in prod and worked for me.
