### ISSUE TITLE
Can’t Make Offer

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3898]
I'm getting two separate errors when attempting to purchase [this listing](https://shoporigin.com/#/listing/1-000-3145) in separate environments.

**Case 1**

Account: `0x96FEb7b6F808dd2BBd09c9E5ccdE77caBd58d019`
Environment: Origin Marketplace `0.24.3` (Mainnet)
Experience: Click purchase on the confirmation screen and never get a native confirmation prompt

![E502B8DF-1D8A-4F23-96CE-988FC04B1010](https://user-images.githubusercontent.com/273937/68417614-9314a480-014b-11ea-894a-4ca9593f58f7.png)

**Case 2**

Account: `0x4604F2F49F5aC7ddE394eF877F9f920D207235eB`
Environment: IMToken (Rinkeby)
Experience: Sign the native confirmation prompt and never reach success

![93FDE1A6-0C93-42A6-A4CB-70661685C060](https://user-images.githubusercontent.com/273937/68417253-e63a2780-014a-11ea-90a4-2445625cec7e.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by micahalcorn** [comment]
In the second case (IMToken), I was using the wrong Ethereum node (Rinkeby, Infura). I was not told by the DApp to change networks, so it took me a while to figure that out. 😕

**Comment by mikeshultz** [comment]
The first is weird.  The only part of our codebase that mentions `words` is the new mobile dictionary(CC @tomlinton) but I don't expect that should have anything to do with this...

https://github.com/OriginProtocol/origin/blob/db6060c48fc3ba44513873ab6e371d8827fddced/infra/bridge/src/utils/dictionary.js

**Comment by micahalcorn** [comment]
Switching nodes in IMToken produced a different but not expected result.

![74695838-0A7E-4D2E-A8CD-B7CB47984D8C](https://user-images.githubusercontent.com/273937/68418380-fa7f2400-014c-11ea-920c-81f0fc94c0d7.png)

Despite this error, I later received a push notification from IMToken indicating that my Ether had been sent. I followed that notification to https://cn.etherscan.com/tx/0xee2cbf57e38d4a9ee7572611eb1dd9c7286439e8b2f5725a1368c2307b106df2?locale=en-US&utm_source=imtoken.

**Comment by franckc** [comment]
Datapoint: I was not able to reproduce on desktop+metamask - I bought listing 1-000-3145 on Mainnet without seeing any error. I used account 0xD85A569F3C26f81070544451131c742283360400

**Comment by franckc** [comment]
Here is the newBlockHeader error Micah ran into in Sentry: https://sentry.io/organizations/origin-protocol/issues/1321350415/?project=1402589&query=is%3Aunresolved

**Comment by tomlinton** [comment]
Succeeded on mobile 0.24.3 after a few goes, ran into this https://github.com/OriginProtocol/origin/pull/3882 and I suspect a few of the other errors in Sentry like the one above. They seem to be releated to updating blocks. 😞

**Comment by mikeshultz** [comment]
This is the subscription init for `newBlockHeaders`: 

https://github.com/OriginProtocol/origin/blob/master/packages/graphql/src/contracts.js#L481

**Comment by micahalcorn** [comment]
Regarding the block headers subscription:

![2AAEA0B2-93C6-425C-AAC6-FC7B66792779](https://user-images.githubusercontent.com/273937/68425437-f22de580-015a-11ea-80bf-c3e0db3a88f5.png)

**Comment by franckc** [comment]
I deployed to prod PR #3900 that disables the websocket provider.
I installed ImToken wallet, created an identity, got 5 USD in my wallet.
Then I tried to purchase listing 1-000-3145 and I got a different kind of error. Blank page with message "Error! Please refresh the page"
The console in in the app shows:
```
[{"method":"error","log":"{"line":93,"column":84384,"sourceURL":"https://shoporigin.com/app.0eeb14f9.js/%22%7D%22%7D]
```

**Comment by franckc** [comment]
Good news. I just tested on mainnet with imtoken wallet and my onboarding issue that was causing the error "Error! Please refresh page" when clicking on the purchase button is fixed. #3910 must have fixed it.

**Comment by micahalcorn** [comment]
I'm downgrading this since the second case is resolved. I believe that purchases are still not possible using our app. 🙁

**Comment by tomlinton** [comment]
My guess here is something to do with the messaging/encryption of shipping address. One thing I noted is that when you hit the purchase button an error is generated in the messaging logs: `participant is not a proxy!`. This doesn't happen on desktop. The `words` referenced in the error might be part of the encryption.

**Comment by tomlinton** [comment]
`e.words` is most likely `key` in this call https://github.com/OriginProtocol/origin/blob/master/packages/messaging-client/src/Messaging.js#L1201.

The key here is `const key = convObj.keys[0]` so that messaging request failure is probably the cause here.

Sentry shows the following POST prior to this error:

`https://messaging.originprotocol.com/messages/0x522731a061e896B5Db9dDff9234fB5461A533710-0xd15f105E2667Fd52313877585D4a0b316C7D8a20/10`

Did something change with messaging and universal login or some other recent changes? cc @shahthepro

**Comment by shahthepro** [comment]
@tomlinton 

Yes, can confirm that `e.words` error is related to messaging. It gets thrown when there is no encryption key in the messages. 

> Did something change with messaging and universal login or some other recent changes? 

No, AFAIK, nothing has been changed wrt messaging.

I'll check this out.

**Comment by tomlinton** [comment]
Thanks shah, I have been hunting around for what might have changed but no luck yet. Another possibility is this has just never worked.

**Comment by micahalcorn** [comment]
Considering this resolved in regard to case 2 ✅ If case 1 is still a problem in the next build, we can open a separate issue.

**Comment by tomlinton** [comment]
I don't believe case 1 is related to mobile builds at all, it is DApp side.
