### ISSUE TITLE
Docker auth_server broken

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#3914]
Somthing is wrong when [this part of code](https://github.com/OriginProtocol/origin/blob/master/packages/auth-utils/src/helpers/index.js#L21-L24) is trying to encrypt the payload. 
<img width="793" alt="Screenshot 2019-11-08 11 53 08" src="https://user-images.githubusercontent.com/579910/68506471-92007780-021e-11ea-8a17-f1737fdc570b.png">

Have generated a fresh set of certificates, but couldn't figure out why the signature fails.

**Comment by shahthepro** [comment]
Thanks @sparrowDom for reporting. It was an issue with newlines in environment variable. Apparently `\n` within double quotes doesn't work. Had to use '|' operator. Will have a PR up now

**Comment by sparrowDom** [comment]
Nice @shahthepro I have gotten that far to remove the new line characters. But that didn't fix it for me, and that is when I gave up :)
