### ISSUE TITLE
Can't edit a listing

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3927]
Tested in prod using chrome+metamask.

Clicking on "Edit Listing" on listing details page causes the UI to go in an infinite loop where it keeps going back and forth between the #/onboarding and the #/signin routes.

This is likely related to the recent SignIn changes...

**Comment by franckc** [comment]
CC @shahthepro @micahalcorn

**Comment by tomlinton** [comment]
Closed by #3941.
