### ISSUE TITLE
FaceID Permissions Not Quite Accurate

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3936]
Minor confusion 🙂

With FaceID enabled as an authentication method in Origin Marketplace, click the toggle switch to disable the setting. The FaceID prompt will appear. Cause it to fail (face not recognized). Be told that _"...you have FaceID disabled. You will need to enable it in the settings..."_, which isn't quite accurate.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by tomlinton** [comment]
Closed by #3902.
