### ISSUE TITLE
Require Changed PIN Code Confirmation

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3937]
When changing the PIN code in Origin Marketplace, entering the old PIN is required. But the new PIN only needs to be entered once, which is inconsistent with creating a PIN from scratch. We should require confirmation to reduce the likelihood of the user mistakenly entering a PIN that won't be remembered. ⛑

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by tomlinton** [comment]
Closed by #3902.
