### ISSUE TITLE
Gas Price: 0 € or something?

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#3958]
![Screenshot_20191112-164834_XRecorder](https://user-images.githubusercontent.com/34341206/68691624-b8a31300-057c-11ea-8641-6c222499c471.jpg)
![Screenshot_20191112-164854_XRecorder](https://user-images.githubusercontent.com/34341206/68691625-b8a31300-057c-11ea-83ee-7b12c395f301.jpg)

Did I pay some ETH or not?
There is a gas price in both cases but the total displayed in € is zero.
So, it's not clear whether I paid or not.

**Comment by micahalcorn** [comment]
I can confirm that the same is true for USD when making an offer using DAI. The gas cost for the allowance approval should be around $0.10, I believe. 🙁

**Comment by micahalcorn** [comment]
This is a significantly bigger problem than I realized. It seems that no ETH conversions to USD are accurate.

![31BC8E14-0DFF-431E-985E-D020E0DC361D](https://user-images.githubusercontent.com/273937/68879605-8dc0d800-06be-11ea-8898-2db5970de939.png)
