### ISSUE TITLE
Undefined is not an object (words)

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3970]
From #3898 🔽

Account: `0x96FEb7b6F808dd2BBd09c9E5ccdE77caBd58d019`
Environment: Origin Marketplace `0.24.3` (Mainnet)
Experience: Click purchase on the confirmation screen and never get a native confirmation prompt

![E502B8DF-1D8A-4F23-96CE-988FC04B1010](https://user-images.githubusercontent.com/273937/68417614-9314a480-014b-11ea-894a-4ca9593f58f7.png)

> The only part of our codebase that mentions `words` is the new mobile dictionary(CC @tomlinton) but I don't expect that should have anything to do with this...
> 
> https://github.com/OriginProtocol/origin/blob/db6060c48fc3ba44513873ab6e371d8827fddced/infra/bridge/src/utils/dictionary.js

> My guess here is something to do with the messaging/encryption of shipping address. One thing I noted is that when you hit the purchase button an error is generated in the messaging logs: `participant is not a proxy!`. This doesn't happen on desktop. The `words` referenced in the error might be part of the encryption.

> `e.words` is most likely `key` in this call https://github.com/OriginProtocol/origin/blob/master/packages/messaging-client/src/Messaging.js#L1201.
> 
> The key here is `const key = convObj.keys[0]` so that messaging request failure is probably the cause here.
> 
> Sentry shows the following POST prior to this error:
> 
> `https://messaging.originprotocol.com/messages/0x522731a061e896B5Db9dDff9234fB5461A533710-0xd15f105E2667Fd52313877585D4a0b316C7D8a20/10`
> 
> Did something change with messaging and universal login or some other recent changes? cc @shahthepro

> @tomlinton
> 
> Yes, can confirm that `e.words` error is related to messaging. It gets thrown when there is no encryption key in the messages.
> 
> > Did something change with messaging and universal login or some other recent changes?
> 
> No, AFAIK, nothing has been changed wrt messaging.
> 
> I'll check this out.

> Thanks shah, I have been hunting around for what might have changed but no luck yet. Another possibility is this has just never worked.

> I don't believe case 1 is related to mobile builds at all, it is DApp side.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by tomlinton** [comment]
Following on from that failed key request to the messaging server - a likely culprit or cause of this is the state of messaging between the buyer and the seller, i.e. whether they have any open conversations. This looks like it alters the key request.

**Comment by shahthepro** [comment]
@micahalcorn 

Spent some time on debugging this and had a look at all encrypted keys/messages on the DB. Everything looks good to me. I can get the native tx screen (with a different account). 

The only way to reproduce this is if `convObj.keys[0]` is undefined. `convObj.keys` will be an empty array only [if this line fails for all keys](https://github.com/OriginProtocol/origin/blob/master/packages/messaging-client/src/Messaging.js#L466) in the conversation. 

I'm not sure why `ecDecrypt` would fail for that account. But can you send a message to the seller (instead of purchasing) and see if it gets sent or do you get the same error?

**Comment by micahalcorn** [comment]
@shahthepro one thing that I just noticed (and may or may not have been true before): on an existing offer detail page involving this same buyer, seller, and listing, I see "Could not decrypt shipping address".

**Comment by micahalcorn** [comment]
@shahthepro I can confirm that sending a message from this buyer to this seller fails silently. There is no error in the console and the modal messaging form just resets itself. 🙁
