### ISSUE TITLE
Twitter share verification failures

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#4025]
A couple users reported that after sharing a tweet he did not get a reward.
User 1:
 - account: 0xDB59B63738E27E6d689C9d72c92C7a12f22161Bb
 - tweet: https://twitter.com/freakslot777/status/1196512931531415554
User 2:
 - account 0x58B61d71A801BEffe49Ed1A8E01A908be965Ca1B
 - https://twitter.com/Gozing21/status/1196736929389256704

I checked the bridge logs and I'm seeing verification failure errors similar to the ones below for both accounts. I stared at the November config but don't see anything obviously wrong...:(

![Screen Shot 2019-11-19 at 11 51 33 AM](https://user-images.githubusercontent.com/945910/69180928-0363e400-0ac3-11ea-95b3-babe9397fd18.png)

**Comment by franckc** [comment]
@shahthepro Any idea what could be wrong?

**Comment by franckc** [comment]
Another user complained so I took another quick look.

In the bridge prod logs, I don't see any logs starting with "[TWITTER] Pushed" since Nov 13th. This leads me to think the bridge webhook is not called by Twitter for new event related to the OriginProtocol account... I recall this happened before...

@shahthepro How do you reset this subscription again?

**Comment by shahthepro** [comment]
@franckc We may have to revoke access from Twitter and reauthorize.

**Comment by franckc** [comment]
@shahthepro Please ping me when you wake up and let's reconfigure this together. I'll write down the steps so that next time anyone can do this...

**Comment by shahthepro** [comment]
@franckc I just revoked the permission and reauthorized it. Here are the steps:
1. Login to Twitter with `@OriginProtocol` account
2. Goto https://twitter.com/settings/applications
3. Find OriginProtocol app and click on it and then on `Revoke Access`
4. Hit this URL to reauthorize: https://bridge.originprotocol.com/hooks/twitter/__init

I'm looking at the Telegram issue from mobile. Will add this to the Readme when I submit a PR for that one.

**Comment by franckc** [comment]
Great! Thanks a bunch @shahthepro - you are a pro! :)
