### ISSUE TITLE
Origin Rewards mobile signup attribution

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#4057]
Currently we only attribute signups to a referrer if the referee signs up on desktop.
The flow is as follow:
 - Referrer gets their referral link from https://shoporigin.com/#/campaigns/invitations It looks like this: https://shoporigin.com/#/welcome/d85400fe30
 - Referrer shares their referral link via the built-in email tool or via social media, etc...
 - New user clicks on the link and lands on the welcome page. The invite code is stored in the browser's local storage under the key "growth_invite_code".
 - Once the user completes the Origin Rewards terms signing, the DApp calls the "enroll" mutation on the growth server with the invite code as an argument.
 - The growth server then attributes the signup to the referrer by inserting a row in the growth_referral table. See [code](https://github.com/OriginProtocol/origin/blob/master/infra/growth/src/apollo/resolvers.js#L206)

While this flow works well on desktop, it does not work if the user signs up for Origin Rewards after having downloaded the Origin mobile app. That's because the webview in the mobile app where the sign up happens does not have the "growth_invite_code" key.

We'd like to fix this so that the referrer gets credit for the referral regardless of the new user signing up on desktop or mobile.
The fix likely involves using a similar mechanism than what was built for the partnership referral feature:
 - Upon clicking on referral link, user lands on an originprotocol.com landing page that copies the code in the clipboard. This could the same landing page as for partnership referral, or a very similar page. Landing page directs user to download the app.
 - Upon startup, app copies the value of the clipboard.
 - TBD should make that value available to the webview so that it can be used when sending the mutation to the growth server for enrolling the new user.

**Comment by franckc** [comment]
@micahalcorn @matthewliu I created this issue to track the work related to fixing the Origin Rewards mobile referral flow.

@mikeshultz Thanks for looking into this! Please let me know any question regarding the current referral flow.

**Comment by micahalcorn** [comment]
Thanks @franckc 👍 Relevant mockups are [here](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/dashboard?seid=5db8adc457bcf62c39604baf).
