### ISSUE TITLE
Can't Click Purchase Button

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#4066]
I'm stuck in this state for several minutes on the appropriate network with MetaMask fully connected on [this listing](https://shoporigin.com/#/listing/1-000-255) with no console output.

Possibly related: https://github.com/OriginProtocol/origin/issues/4039

<img width="545" alt="Screen Shot 2019-11-29 at 2 09 19 AM" src="https://user-images.githubusercontent.com/273937/69861639-9df3be00-124d-11ea-8431-6c6f0c89f72d.png">

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment]
The issue was that the messaging server was crashing due to the domain whitelist I added to Alchemy... 
Should be fixed now (@tomlinton undid the whitelisting for now).
