### ISSUE TITLE
Add `application/json` header to gateway responses

### ISSUE THREAD

**Issue by ryana** [OriginProtocol/origin#41]
We want to do this for security reasons so that people cannot host malicious content on the gateway.

**Comment by ryana** [comment]
Adding this header may not be enough: https://stackoverflow.com/questions/37863357/why-do-browsers-execute-script-with-content-type-json

Investigating other ideas.

**Comment by wanderingstan** [comment]
Any update on this, @ryana , or should we call this closed?

**Comment by ryana** [comment]
Yikes no. No update here. I will circle back this week.

**Comment by tomlinton** [comment]
This should no longer be an issue due to `origin-ipfs-proxy`.
