### ISSUE TITLE
Partner Welcome Screen Changes

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#4104]
- The reward view isn't quite centered.
- We should change the reward view background color to `#f0f6f9` and make the text `#000000` or make both of them configurable.
- Let's change the text to "Welcome! We see you’re a `{config.partner.name}` customer. Click continue to create your account and join Origin Rewards."

![8D056322-C459-4A42-A382-99157761AE84](https://user-images.githubusercontent.com/273937/70409987-6c73b300-1a02-11ea-8b84-607d5214d38c.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by mikeshultz** [comment]
Maybe instead of "Click continue" it could tell the user the general actions we expect of them.  In fact, there's really no other option other than clicking continue.

Will have a PR up shortly.
