### ISSUE TITLE
Taxonomy overlap

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#411]
+ I believe there may be a bit of an overlap when it comes to musical performances.  _For sale >> Tickets_ and _Tickets >> Music_ seem to basically be the same thing.  It may make searching less optimal in the future.

+ I wonder if other users will mix up the taxonomy a bit.  I accidentally clicked "For Sale" when I was supposed to relist the real estate in "Housing" for Stan (https://github.com/OriginProtocol/origin-dapp/issues/402) .  I wonder if the term "**Items for sale**" might be clearer.

Any feedback appreciated.

**Comment by micahalcorn** [comment]
Fixed long ago ✅
