### ISSUE TITLE
Form validation not localized

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#419]
Form validation in the DApp is not localized:

<img width="494" alt="screen shot 2018-08-20 at 4 31 43 pm" src="https://user-images.githubusercontent.com/673455/44370244-99f7be80-a496-11e8-923f-921e53ca0235.png">

Looks to be a known issue:
https://stackoverflow.com/questions/5392882/why-is-chrome-showing-a-please-fill-out-this-field-tooltip-on-empty-fields
https://drupal.stackexchange.com/questions/189488/how-do-i-translate-please-fill-out-this-field-on-the-user-registration-form

But note, in last link the guy says for him it shows in french
> I have my system in French and the message comes in French, and I don't have the French language installed in my site.

So one thought might be that we're not setting a language on the page, and that's what the browser is looking at to decide language. (Rather than the `browser.language` setting?) 
We can do it either at [top level](https://www.w3.org/International/questions/qa-html-language-declarations#attributes) or (maybe easier in a react app?) [per element](https://www.w3.org/International/questions/qa-html-language-declarations#contentvsattribute). 

If not, we'll have to fall back to setting our own with `.setCustomValidity("This is a custom message");`

**Comment by micahalcorn** [comment]
This appears to no longer be an issue, at least not in listing creation 🤔
