### ISSUE TITLE
Broken Rewards Welcome on Desktop

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#4194]
When a new user clicks on "Sign up now" at https://shoporigin.com/#/welcome on desktop, it produces some DApp screen without a navbar. During the onboarding flow, it ultimately breaks with an exception on a button. I'm not sure yet whether we want to fix this or replace the welcome page itself. 🤔

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by sparrowDom** [comment]
Solved via https://github.com/OriginProtocol/origin/pull/4221
