### ISSUE TITLE
Unable to Submit Offer on Mobile

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#4198]
When I try to make an offer on [this listing](https://shoporigin.com/#/listing/1-000-624), the native prompt is stuck with a loading button forever. I couldn't find any console errors.

![IMG_0616](https://user-images.githubusercontent.com/273937/71837041-52ada600-306a-11ea-90b4-3c7f635aa06c.PNG)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by mikeshultz** [comment]
I think this is probably a temporary network error.  This isn't very reproducable, correct @micahalcorn?

Probably these:
https://sentry.io/organizations/origin-protocol/issues/1252257192/events/1533dffa500f4ef19cb7607eb94ea94c/?project=1402589&statsPeriod=14d
https://sentry.io/organizations/origin-protocol/issues/1317325357/?project=1402589&query=is%3Aunresolved+user.id%3A0x96FEb7b6F808dd2BBd09c9E5ccdE77caBd58d019&statsPeriod=14d

Could also be this but not really sure what exactly this is. Looks like it happened immediately after landing on the listing page, though.  :man_shrugging: 
https://sentry.io/organizations/origin-protocol/issues/1319388970/events/297d873c4be544348e8ff4b113586fc8/?project=1402589&statsPeriod=14d

**Comment by micahalcorn** [comment]
Likely a network error since I wasn't able to reproduce after some time passed 😕
