### ISSUE TITLE
Page Title not Localized

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#420]
The HTML `<TITLE>` of the page is not localized—the one that appears in the browser tab.

![image](https://user-images.githubusercontent.com/673455/44413705-46828080-a529-11e8-9a0d-3b5011135c8c.png)

SO Answer:
https://stackoverflow.com/a/8660499/59913

**Comment by riverfor** [comment]
Is this issue resolved? Can I try to fix it as my good first issue please ?

**Comment by micahalcorn** [comment]
@riverfor please do, thanks 🙏

**Comment by riverfor** [comment]
Thank your for accepting this PR.

**Comment by tomlinton** [comment]
Thank you @riverfor!
