### ISSUE TITLE
Track additional signals upon Origin Rewards signups on mobile

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#4208]
Currently on mobile we only track a UUID.
We'd like to capture the following additional signals:
 - OS type and version
 - Screen resolution
 - UserAgent of the webview
 - Language

**Comment by franckc** [comment]
CC @DanielVF Tracking signals we discussed this afternoon in this issue...

**Comment by shahthepro** [comment]
This is done but we need to release a new version of the app. Leaving this open until we do that.

cc @tomlinton
