### ISSUE TITLE
"Make Offer" step: wrong currency value displayed

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#4209]
I am trying to make a booking and this is what I get:

![Screenshot_20200106-153255_Origin](https://user-images.githubusercontent.com/34341206/71889851-bc51b100-314b-11ea-92ea-47c4fadf8ccd.jpg)

here above the price is correct: 189 € 
On the next step the value changes to 212 €, but it's probably 212 USD

![Screenshot_20200106-153303_Origin](https://user-images.githubusercontent.com/34341206/71889938-ef944000-314b-11ea-9d7d-1c3fd10a4da8.jpg)

Android Version 0.29.01 (Beta Tester)

**Comment by micahalcorn** [comment]
@lucadgtrip any chance that this is an older listing? That is our current theory before doing any investigation. 🤔

**Comment by lucadgtrip** [comment]
@micahalcorn it was created a couple of days ago https://shoporigin.com/#/listing/1-001-227-9234936

**Comment by sparrowDom** [comment]
Fix for this here: https://github.com/OriginProtocol/origin/pull/4248
