### ISSUE TITLE
Invalid Attestion(s)

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#4217]
We're getting quite a few reports of this with Telegram. I haven't been able to find a way to reproduce it.

![invalid](https://user-images.githubusercontent.com/273937/71958060-301fa800-31a4-11ea-8a45-cc1c761de968.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by sparrowDom** [comment]
I can't reproduce it either
