### ISSUE TITLE
Spinning White Screen of Death

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#4233]
Many users are reporting that the webview never loads after native onboarding. It is a white screen with an endless spinner. All of the reports that I have seen involve Android devices, but there's a slim chance that this is only due to the fact that the vast majority of our usage is coming from Android. The IP addresses that I have tried to match in Sentry reveal no errors at all. @tomlinton theorized that this could be caused by https://github.com/OriginProtocol/origin/issues/2344. I've confirmed that many of the users are on Android 6, but at least a couple of people claim to be on Android 7.

⚪️

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by micahalcorn** [comment]
Getting more reports of this on Android 7. 😕

**Comment by tomlinton** [comment]
Same as #2344.

**Comment by micahalcorn** [comment]
@tomlinton how confident are we about that? I couldn't prove that it was happening on 7️⃣ but received more than one report indicating that it might be happening there too. Would it affect both?

**Comment by micahalcorn** [comment]
FAQ article [here](https://help.originprotocol.com/hc/en-us/articles/360041319274-Why-does-my-app-just-spin-and-never-load-) ❓

**Comment by tomlinton** [comment]
Yea the Android version isn't the important bit, it's the version of WebView that shipped with those Android releases. I can't find a list of the versions anywhere but I'm confident it is the same thing.

**Comment by micahalcorn** [comment]
Got it, that makes sense. ☑️
