### ISSUE TITLE
Campaigns home page crash when there is no active campaign

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#4259]
We just announced we'll be ending the January campaign sooner than anticipated (tomorrow).
That means that until the new February campaign starts, there won't be any active campaign.

I updated staging to end the January campaign and the [rewards home page](https://dapp.staging.originprotocol.com/#/campaigns) crashes. The console has the following error:
``` TypeError: Cannot read property 'actions' of undefined```

When there is no active campaign we should show a message along the lines of "There is currently no active campaign, please come back later and check".

**Comment by franckc** [comment]
@sparrowDom Would you mind taking a look at this when you wake up tomorrow?

@micahalcorn Please provide feedback regarding what the UI should say when there is no active campaign.

**Comment by sparrowDom** [comment]
On it 👍

**Comment by sparrowDom** [comment]
Fix for this here: https://github.com/OriginProtocol/origin/pull/4263
