### ISSUE TITLE
Rewards Redirect Interrupting Transaction Flow

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#4286]
If I'm not signed in to the DApp when I initiate a purchase, I get redirected to onboarding (as intended). Once I sign in, I'm presented with the Origin Rewards signup invitation. Regardless of how I answer this, the congratulations page leads me to the campaign dashboard. This should not happen if I'm in the process of buying or selling something. I should only go to the rewards section if I was coming from a referral link or the Origin Rewards welcome page. 👎

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by sparrowDom** [comment]
fix here: https://github.com/OriginProtocol/origin/pull/4307
