### ISSUE TITLE
Recursion is resolving

### ISSUE THREAD

**Issue by fredfortier** [OriginProtocol/origin#433]
I followed this local development guide: http://docs.originprotocol.com/

I ran `npm run start` on the `origin-js` project but it's trying to install `origin@0.7.1` in my `/usr/lib` so I ran `sudo npm install -g origin@0.7.1` in addition.

I was able to run `npm run install:dev` from `origin-dapp` without a problem. However, I get this error on `npm run start`.

```
Failed to compile.

./src/services/origin.js Module not found: Error: Recursion in resolving
```

**Comment by tomlinton** [comment]
This should be resolved following changes to the webpack configs for origin-js and origin-dapp. Feel free to reopen if you still encounter this issue @fredfortier.
