### ISSUE TITLE
App not loading in Android Trust Wallet

### ISSUE THREAD

**Issue by LukaNarat** [OriginProtocol/origin#439]
Tested on 2 separate android devices (lollipop / oreo), both not loading the app at all from within the Trust Wallet browser.

Repro:
- Install latest Trust Wallet via playstore
- Generate wallet
- Navigate to browser tab & open http://demo.orginprotocol.com
- see loader icon (clock)
- white screen remains (nothing loads)

Sidenote: testnets don't seem to be supported at this time as well. However this is not related to the loading issue, but influences priority for the fix.

**Comment by davecraige** [comment]
Thank you for taking a look at this @LukaNarat. 

_Note_: mobile usage is not a high priority at this time.  You can see [the priorities](https://dzwonsemrish7.cloudfront.net/items/0K0Z1b100v013I3H0B2q/image0-1.jpg) in engineering notes.

*shared this issue to Trust's Discord in the #Android section.

**Comment by micahalcorn** [comment]
@LukaNarat are you still unable to run https://dapp.originprotocol.com in your Android Trust Wallet? I can't reproduce this issue in my emulator. 🤞 I'm hoping that this naturally resolved itself.
