### ISSUE TITLE
Fancy image uploads

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#44]
Aure's design calls for images to be uploaded via a slick UI with thumbnails: 

![image](https://user-images.githubusercontent.com/673455/34649956-eb59d948-f375-11e7-959b-70c7330b803e.png)

We're using [react-json-schema-form](https://github.com/mozilla-services/react-jsonschema-form), which does only old-school style file uploads. (Click a button to open native OS file selector.)

So there are multiple ways to go: 
1. Break image uploading into its own step in `listing-create.js`. (One idea would be to use the same react-json-schema-form, but hide the image part when entering details, and hide everything BUT the image step when uploading photos.) 
2. Perhaps use a natve `FileReader()` to do the upload, and inject the results into the react-json-schema-form. ([Docs](https://developer.mozilla.org/en-US/docs/Web/API/FileReader))
2. Use [HTML5 image uploader](https://hacks.mozilla.org/2011/01/how-to-develop-a-html5-image-uploader/
) to show preview of uploaded images, and possibly even resize them.

**Comment by nikkwong** [comment]
I'll take a stab at this.

**Comment by nikkwong** [comment]
@wanderingstan Are Aure's designs publicly available, so I can get a better idea of how these flows work together?

**Comment by wanderingstan** [comment]
@nikkwong doesn't look like they are, and I can't publish them. FWIW, the link is here:
https://app.zeplin.io/project/59fa2311bac7acbc8d953da9?seid=5a361ba792b402caa8e2de28

BUT, I can just upload the image: 
![demo app - create listing 3](https://user-images.githubusercontent.com/673455/35457832-7c74edf2-0297-11e8-9d50-369e9541817d.png)

The idea is that this would be a step in between entering the details and just before preview. 

For how it would work, I think we can just propegate the jsonschema-form to the next component, and hide everything. (Or store the form data in state, and add images to it there.) Not totally sure.

**Comment by wanderingstan** [comment]
@nikkwong Oh crap, just realized that image was already in this issue. I'll get Aure's entire flow to post here.

**Comment by nikkwong** [comment]
@wanderingstan got it. Yeah, it starts getting a wee-bit hacky because you don't want to remove the ```pictures``` field from the json schemas as it breaks the contract between the json and the jsonschema-form component. 

I think we should do a bit of refactoring to make the ListingCreate component more robust and able to handle future use cases. First, I think we should remove the submit handler from the continue button here:
````
<button type="submit" className="float-right btn btn-primary">Continue</button>
````

Instead, we should have a handler which can read from the state and decide where to go next based on the state, so, ex:

````
<button type='button' onclick='goToNextStep()'>
...
nextStep() {
   // Potentially check for various things, for example ..
   if (step === 'DETAILS' && this.state.selectedSchema.photos) { // If selected schema needs photos 
      this.setState({step: this.STEP.UPLOAD_PHOTOS})
   }
}
```


When the user has filled out this step, it updates the ```formListing.formData``` property and runs ```onDetailsEntered``` (which may more aptly be named onFormComplete``` or ```onSubmit```.

**Comment by wanderingstan** [comment]
Thanks Nikk! Again, sorry for the delay--this came in midst of a ton of pull requests and just as the website repo was needed a ton of attention. Feel free to ping me on slack too. 

> we should have a handler which can read from the state and decide where to go next based on the state, so, ex:
I feel a `goToNextStep()` abstraction could be premature optimization for such a small app, but go for it if you like.

> The STEP.UPLOAD_PHOTOS step could then just use html5 apis for photo handling and once completed, write the file blob back to the formData
Yes, this seems exactly the way to do it! 

> 1. Probably would want to change the type of pictures in the json to input[type=hidden] rather than input[type=file], since we'll just be assigning the string result from the upload photos step back to the formData.
The schema json needs to best represent the data being stored, and shouldn't bend to UI considerations. My early thought on this was to use css to hide the image field on `STEP.DETAILS`, or see if react-jsonschema-form has some way to selectively hide fields. Other ideas? 

> 3. It's worth keeping in mind that onDetailsEntered currently checks the state of the entire formData object...
`onDetailsEntered()` should be paired with `STEP.DETAILS` as it's completion handler and validation. Then `STEP.UPLOAD_PHOTOS` would have its own, e.g. `onPhotosUploaded()`, which is where the photo size check should happen. I.e. each step of process should do it's own validation. 

I'll also get you access to the full Zeplin graphic of Aure's flow design.

**Comment by jordajm** [comment]
@nikkwong thanks for the thorough research / game plan on this one. Are you still planning to implement it?

**Comment by micahalcorn** [comment]
This should handle adding AND removing one image at a time in both the listing creation form and the messaging form.

**Comment by micahalcorn** [comment]
This should also handle re-ordering the images, probably via drag-and-drop or something.

**Comment by jordajm** [comment]
This is mostly resolved by https://github.com/OriginProtocol/origin/pull/731, but we would need to pull images out into its own step to make it work like Aure's designs. I'm thinking we should close this ticket and create a new one if/when we decide to do that...
