### ISSUE TITLE
Newly created listings sometimes don't appear for a while

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#45]
When a new listing is created, and user returns to listing-grid page, the new listing sometimes doesn't appear right away but will after  another page reload. 

We wait for the transaction to be confirmed in blockchain [here](https://github.com/OriginProtocol/demo-dapp/blob/master/src/services/contract-service.js#L137). 

Possibilities:
- React caching results
- Metamask caching contract results
- Web3 not updating -- even though we know the transaction has been mined, perhaps there is delay before the contract method `listingsLength()` "knows" about the new listing?
- Hack in a [2 second] pause to give time for it to settle?

**Comment by wanderingstan** [comment]
The 2 second hack seems to work surprisingly well. https://github.com/OriginProtocol/demo-dapp/commit/59bc3658b9149abdd8f962ce74a422968097ddda

**Comment by micahalcorn** [comment]
This seems like it might be related to the need to [delay re-fetching the purchase after the state is changed](https://github.com/OriginProtocol/demo-dapp/blob/master/src/components/purchase-detail.js#L225).

**Comment by micahalcorn** [comment]
Assuming that DApp2 fixes this 🙏
