### ISSUE TITLE
Provide context to users regarding "paying for gas" on DApp

### ISSUE THREAD

**Issue by mek32390** [OriginProtocol/origin#463]
with attestations, we assume people don't understand the implications of publishing data on the blockchain. Should we assume the same in that people may not know it costs gas to publish data  on the blockchain? If so, we should provide additional context before we ask users to pay gas, explaining what gas is and why it's needed, just as we do with attestations. 

This could be done inside the modal that instructs users to confirm transactions in MetaMask, or elsewhere, although we haven't gotten that far. 

This is an issue I separated from #427.

**Comment by micahalcorn** [comment]
I think the plan here is most likely to abstract it away. 😶
