### ISSUE TITLE
Tell users we are sponsoring their gas fees

### ISSUE THREAD

**Issue by mek32390** [OriginProtocol/origin#464]
we may want to indicate and provide more context to users when we sponsor gas fees for certain transactions. For those used to Metamask, this could make it hard to determine if they are experiencing a bug or feature while using the DApp.

No design has been made, as this was just a suggestion I had while reviewing the DApp.

This is an issue I separated from #427

**Comment by micahalcorn** [comment]
I think the plan here is most likely to abstract it away. 😶
