### ISSUE TITLE
Register functions with MetaMask to provide more context to users

### ISSUE THREAD

**Issue by mek32390** [OriginProtocol/origin#465]
![image](https://user-images.githubusercontent.com/7400892/44557025-78464380-a6f1-11e8-9c67-6c9ea7d8cfc4.png)

Relating to the above screen shot, if the `UNKNOWN FUNCTION` was [registered](https://github.com/MetaMask/metamask-extension/issues/2847#issuecomment-414769467) and [(here too)](https://github.com/parity-contracts/signature-registry) and even better, provided context on the transaction, it would make the MetaMask dialogue more informative. Since the Metamask dialogue is acting somewhat as a shopping cart at this point, something more descriptive than `UNKNOWN FUNCTION` would help if it could be done. 

Separated this issue from #427

**Comment by micahalcorn** [comment]
Seems to have been done ✅
