### ISSUE TITLE
Purchased items not showing in chronological order

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#529]
It appears as though purchased are not being displayed chronologically in both the "pending" and "all" sections . Note the timestamps for these purchased items below.  I believe users will want to see their most recent purchases at the top similar to the heuristic used by marketplaces such as Amazon, eBay and others.

https://demo.originprotocol.com/#/my-purchases

<img width="1088" alt="screen shot 2018-09-19 at 3 42 01 pm" src="https://user-images.githubusercontent.com/2782676/45783339-bcf6c900-bc22-11e8-800f-3d718a132b0a.png">

**Comment by davecraige** [comment]
Somewhat related issue where messages also are not yet displayed with the most recent message first.  https://github.com/OriginProtocol/origin-dapp/issues/490

**Comment by micahalcorn** [comment]
Apparently fixed by DApp:two:
