### ISSUE TITLE
Category naming consistency 

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#533]
In the codebase for the most part we use terms `Category` (For Sale, Housing, ...) and `Sub Category` (Vacation & Rentals, Baby & Kid Stuff....). See inconsistencies where DApp once refers to SubCategory as Category and another time as SubCategory:
<img width="491" alt="screenshot 2018-09-20 15 38 01" src="https://user-images.githubusercontent.com/579910/45822506-edef0080-bceb-11e8-9b6b-9c8ba7ce885c.png">
<img width="850" alt="screenshot 2018-09-20 15 42 43" src="https://user-images.githubusercontent.com/579910/45822510-efb8c400-bceb-11e8-8643-b6723b929856.png">

So should we name SubCategory a Category in the DApp? Or use the same naming as in the code?

**Comment by sparrowDom** [comment]
Might be interesting to @jordajm @franckc @micahalcorn @DanielVF

**Comment by franckc** [comment]
Yes, we should clean this up since it is very confusing. I'd vote for using same terminology in DApp as in origin-js: category and subCategory.

**Comment by micahalcorn** [comment]
I believe this is a no longer relevant. 😐
