### ISSUE TITLE
Pending transactions not chronological

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#551]
Would this be clearer if the most recent transaction in progress was at the top? (Note how it is currently progressing but at the very bottom of the list)

<img width="618" alt="screen shot 2018-09-21 at 3 58 57 pm" src="https://user-images.githubusercontent.com/2782676/45907938-5a830180-bdb7-11e8-9f92-b18f110e2b95.png">

**Comment by micahalcorn** [comment]
Apparently resolved ⬆️
