### ISSUE TITLE
🐃 Invalid IPFS offer file causes never ending error popups

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin#563]
If you make an offer to someone with invalid IPFS data, then the seller sees a grey popup with an error message about it, over and over and over again.

**Comment by DanielVF** [comment]
This also happens for offer amounts that are too low:

![image](https://user-images.githubusercontent.com/837/45963256-c2705c80-bff0-11e8-8a52-17c0ee14fa2b.png)

**Comment by franckc** [comment]
@DanielVF Can you confirm this only happens if someone creates an offer by interacting directly with IPFS/contracts rather than using origin-js, correct ?

**Comment by DanielVF** [comment]
You can do it with origin.js - just set the offer price lower than the listing price.
