### ISSUE TITLE
Browse page: fetch listingIds from back-end rather than web3

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#568]
This improve dramatically performance of the browse page on Mainnet.

**TODO:**
- [x] read listings from discovery server
- [x] create devops script that uses index aliases, reindexing

Devops script Pull Request: https://github.com/OriginProtocol/origin/pull/844
Implement hidden/featured listings in Apollo PR: https://github.com/OriginProtocol/origin/pull/890

**Comment by sparrowDom** [comment]
@franckc thanks for creating this. 

@tomlinton since we will be relying on search more from now on (the listings on home-page are going to be queried using elasticsearch) are there any devops tools that you would critically require for launch? Perhaps something like: 
- script that deletes the listing index
- script that applies (like database migrations) the mappings/ index schema
- something else?

**Comment by tomlinton** [comment]
@sparrowDom yes if we want to change the indexes post launch we'll need something to handle that. A way to do migrations would be amazing, but I'm not too sure what is available with elasticsearch. Initially a script that would deletes an index and recreates it would probably be fine. I started putting together a script that creates the indexes based on what you added to the elasticsearch dockerfile [here](https://github.com/OriginProtocol/origin-box/blob/master/development/scripts/create-es-index.sh). I was planning on just adding a delete of the index at the start. We can then update this script and run it to change the indexes if needed.

Do you think that will suffice? I doubt we'll be changing the indexes too much anyway.

**Comment by sparrowDom** [comment]
Hey @tomlinton yeah that is a good start, the only downside is that this causes downtime every time we need to alter indexes. As part of the solution to this issue I will prepare a script that creates index aliases. So the steps for index mutation would be: 
- create an alias for listings index
- when index mutation is required create a fresh index with the updated mappings schema
- reindex all the content from the original index that is currently live to the freshly created index
- switch aliases from the old index to the new one
- delete old index (this step should be manual, so we can fallback any time)

Does that make sense to you?

**Comment by tomlinton** [comment]
Yep that is a much better approach if you think it is achievable. Go for it. :+1:

**Comment by sparrowDom** [comment]
@tomlinton in [this branch](https://github.com/OriginProtocol/origin/tree/sparrowDom/esIndexMigration) I have prepared a script that should make index migrations easier and without downtime. The script is located here: `development/scripts/elasticsearch/migrationTool.sh` and this is how the functionality looks like: 
![screenshot 2018-10-29 17 46 10](https://user-images.githubusercontent.com/579910/47666076-f7993d00-dba2-11e8-90bc-9e05b7e6202c.png)

Is there anything else you think would be useful for this script to do?

**Comment by tomlinton** [comment]
Looks great @sparrowDom. I'm wondering if this script will ever need to be run non-interactively (i.e. by a CI tool). My thinking is that index changes probably won't happen very often and we can just take care of each one by hand using this script. What do you think?

cc @franckc.

**Comment by sparrowDom** [comment]
I guess when (or if ever) index migrations become more frequent we should include it as part of the CI. Until that happens I agree that doing it manually should be ok. 

(of course then I will do the modifications so that script can be ran with arguments non-interactively)

**Comment by sparrowDom** [comment]
Solved via https://github.com/OriginProtocol/origin/pull/890 and https://github.com/OriginProtocol/origin/pull/844
