### ISSUE TITLE
Contradictory copy after transaction approval

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#579]
After a seller approves a listing this copy is provided that seems to say two contradictory things.  It says that the seller should ship the item _and_ it says to also wait on the buyer.  

(Thanks @DanielVF for noticing this with me)

![screen_shot_2018-09-25_at_2 45 35_pm](https://user-images.githubusercontent.com/2782676/46044679-acd66200-c0d8-11e8-86bc-510fb5a090d3.png)

**Comment by micahalcorn** [comment]
Eh, I think we're scrapping the checklist. 🤷‍♂
