### ISSUE TITLE
Correct copy on status of items in /my-listings page

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#580]
When an item moves to the next stage of the sales funnel we could possibly update the status in the top right corner. 

In this screenshot below you will see that it says "Active" in the corner, however both of these items have been sold to @DanielVF and have been approved by me.  I believe the correct status may be something like "Payment received, waiting for seller to ship item'

![screen shot 2018-09-25 at 3 41 02 pm](https://user-images.githubusercontent.com/2782676/46044967-8533c980-c0d9-11e8-80f5-cd3b51ab3ab0.png)

**Comment by davecraige** [comment]
Oh wait, we do have this.  It is in a different section, the /my-sales section however.  

![screen shot 2018-09-25 at 3 53 58 pm](https://user-images.githubusercontent.com/2782676/46045543-3e46d380-c0db-11e8-8035-f1b6e0fb1bd8.png)

I have filed an user experience issue about this if that is ok.  I believe many users are going to be confused by these dual sections.  

✅ https://github.com/OriginProtocol/origin-dapp/issues/581

**Comment by micahalcorn** [comment]
Considering this done ☑️
