### ISSUE TITLE
Lack of consistent copy when offer is withdrawn

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#582]
When an offer is withdrawn there is a lack of copy explaining to the users what happened.  
Here is a screenshot of the buy side.  Note how it says the item is "sold" and yet it also says that the listing is still "active".  It also says "pending" at the top as well. It doesn't mention that the offer has been withdrawn and the buyer’s item is actively for sale again.

![screen shot 2018-09-25 at 4 00 53 pm](https://user-images.githubusercontent.com/2782676/46045924-67b42f00-c0dc-11e8-9ccb-12825bcc1eb5.png)

**Comment by davecraige** [comment]
Additionally, the copy in the Next Steps section is blank.

![screen shot 2018-09-25 at 4 00 28 pm](https://user-images.githubusercontent.com/2782676/46045951-86b2c100-c0dc-11e8-9277-aad938586d43.png)

**Comment by micahalcorn** [comment]
Closing in favor of #1724 😐
