### ISSUE TITLE
Load/Validate/Migrate from IPFS listing data into data model

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin#59]
Data coming from IPFS is completely outside our DAP's control. It can be safely assumed to be as maliciously formed as possible. It could also be in an outdated schema.

We can't have react components responsible for parsing and validating IPFS data.

When we are loading information about a listing, we need to:
- [ ] Create a new object, and only copy over whitelisted fields
- [ ] Migrate any schema differences between the data loaded and the current version
- [ ] Validate each field
- [ ] Discard invalid listings

We also need to start keeping some kind of schema version in our IPFS data.

**Comment by nick** [comment]
Think this is solved with the eventsource module
