### ISSUE TITLE
Autodetect links in messaging

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#591]
It may be a bit early but just wanted to mention this idea.  Any thoughts on autodetecting links so they are clickable in messages?  It may make the customer experience smoother if people are able to chat with each other and share clickable URL's.

Screenshot:
<img width="531" alt="screen shot 2018-09-26 at 3 56 44 pm" src="https://user-images.githubusercontent.com/2782676/46111591-d0ff7500-c1a4-11e8-87de-8bbfed6c829d.png">

(Note: SF team, feel free to remove this issue if you feel as though it is too early at this stage.  Happy to repost it in the future when we take a few more passes to improve the customer experience.)

**Comment by micahalcorn** [comment]
Thanks @davecraige and @shahthepro 💙
