### ISSUE TITLE
Temporary: Featured Listings

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#594]
We need a temporary solution for manually featuring listings. This will require adding the listing ids to an environment variable or file on GitHub (like our original hidelist). We will also need to add back the featured flag to the listing cards and details.

- [x] store an array in a place that can be easily updated without a deployment
- [x] display the badge in the UI

Pull Requests for this issue: 
- https://github.com/OriginProtocol/origin-js/pull/571
- https://github.com/OriginProtocol/origin-dapp/pull/617

**Comment by sparrowDom** [comment]
Changing the priority label of this to `p1` since we have decided to implement a simpler solution for V1 launch: https://github.com/OriginProtocol/origin-dapp/issues/643#event-1875878859

**Comment by micahalcorn** [comment]
Done per @sparrowDom ☑️
