### ISSUE TITLE
Settings/Config Page

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#596]
Some variables are subject to user configuration, and they should be listed on a separate route.

**Possible Cases**
1. Language select
1. Manage notifications
1. Browse without an indexing server
1. "Log out" of messaging
1. Disconnect mobile wallet

**Comment by joshfraser** [comment]
Also letting people choose their own:

- IPFS gateway 
- Ethereum node
- Bridge server

**Comment by tomlinton** [comment]
Closed as a duplicate of #1210.
