### ISSUE TITLE
Allow line breaks on listings

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#624]
Just a quick note, line breaks don't seem to work on new listings.
Example listing: https://demo.originprotocol.com/#/listing/4-000-12

Screenshot of when I made the listing:
![screen shot 2018-09-28 at 3 11 38 pm](https://user-images.githubusercontent.com/2782676/46233747-105acc80-c331-11e8-821c-6ae8db3bec5b.png)

Listing up on the DApp, note the lack of formatting and line breaks:
![screen shot 2018-09-28 at 3 12 02 pm](https://user-images.githubusercontent.com/2782676/46233751-12bd2680-c331-11e8-91ac-7e436ab3bc57.png)

**Comment by joshfraser** [comment]
Looks like the line breaks are getting stripped out before the blobs are being saved to IPFS. 

At a minimum, we should make sure the line breaks survive, and then replace them with <br>'s when we display them to the end user.

As a stretch goal, it might be nice to support markdown or another standard to allow *minimal* formatting of listings. I don't want to open it up to allow all sorts of colors and crazy fonts or anything like that. 

For security reasons, you shouldn't be able to embed arbitratry HTML or load remote images.

**Comment by micahalcorn** [comment]
Depending on how the come out of IPFS, we can potentially just use CSS.

https://www.w3schools.com/cssref/pr_text_white-space.asp

**Comment by DanielVF** [comment]
Looks like @wanderingstan did this in #658!

Yay!

**Comment by davecraige** [comment]
Awesome, thanks @wanderingstan 🙏
