### ISSUE TITLE
New design for selected listing in "Create Listing" workflow

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/origin#626]
The current design of the selected listing causes the "next" button to be pushed below the fold. Aure designed a new way of showing examples of the selected listing and we need to update the styling to match the new designs:

![create_listing_design](https://user-images.githubusercontent.com/5402813/46236561-b233e680-c33c-11e8-9e73-acfa83721965.png)
![create_listing_design_2](https://user-images.githubusercontent.com/5402813/46236562-b3651380-c33c-11e8-8fe5-de8b906caae7.png)

**Comment by davecraige** [comment]
And a quick props to @andrewhyde for his idea about improving this.

**Comment by micahalcorn** [comment]
Closing as no longer relevant ✅
