### ISSUE TITLE
Clearer copy on how much the buyer offered (lower priority)

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#627]
Note: this may be a P1 or P2 priority but wanted to share it after a discussion and encouragement from @jordajm .  

On the offer page, there is no visual indication above the fold of what the offer was.  Even if it was the listed amount, should we include some copy to visually show in the "accept/reject" box the price that the buyer is sending us for a listing? Example copy "The buyer has offered you $75 for your item.  Accept or reject the buyer's offer"

Note: I do realize that there is a little price in the bottom right, but I personally have missed that many times and I think users will as well.  

Current screenshot:
![screen shot 2018-09-28 at 4 52 51 pm](https://user-images.githubusercontent.com/2782676/46237015-1a83c780-c33f-11e8-8946-141f57d340f6.png)

**Comment by jordajm** [comment]
@micahalcorn I think this could be a P1 - totally confusing from a seller's point of view and would be an easy fix. Also - it says "Sold to unnamed user" when the offer hasn't been accepted.

**Comment by micahalcorn** [comment]
Addressed by a recent redesign ✅
