### ISSUE TITLE
Previous notifications not displaying on /notifications

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#628]
Previous notifications are currently not displaying for me on the /notifications page. 

Screenshot:
![screen shot 2018-09-28 at 5 09 40 pm](https://user-images.githubusercontent.com/2782676/46237392-77807d00-c341-11e8-8daa-c9f99cc9bf02.png)

**Comment by micahalcorn** [comment]
Closing this since DApp 1️⃣ is no more :cry:
