### ISSUE TITLE
Update instructions link / make configurable

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#636]
Currently if metamask isn't configured right, we offer a "Full Instructions" link that goes to a [Medium post from January](https://medium.com/originprotocol/origin-demo-dapp-is-now-live-on-testnet-835ae201c58). Obviously not relevant to Mainnet beta. 

I suggest we make this an env var so that we can modify easily even post-launch without a full dapp redeploy. 

❓We might want to also add this link to the initial "This is beta" popup, for people that want more context about the DApp: how to use it and it's current state. 

![image](https://user-images.githubusercontent.com/673455/46259866-57f96980-c493-11e8-9054-9f0596688b48.png)

**Comment by micahalcorn** [comment]
I think this can be closed per #637, but...

1) should it be added [here](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/dev.env)?
2) should there be [a fallback](https://github.com/OriginProtocol/origin/commit/d2525d26b2861e2b4be06b39006d098b48124282#diff-3c3b42c902b1aab458ca8225ba8112aaR19)?
3) did we end up with a [blog post](https://github.com/OriginProtocol/origin/pull/637#issuecomment-425797068)?

**Comment by micahalcorn** [comment]
Covered by the new and improved User Activation ™️
