### ISSUE TITLE
Seller with 0 ETH Onboarding

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#661]
If a user has no (or not enough) ETH to create a listing, we don't currently prompt her before she gets to the end of the process only to find out that it's not possible. Then, of course, all of her work is lost. We should do one or more of the following:

- suggest funding the wallet
- ~store the listing creation inputs in Redux and/or `localStorage`~ https://github.com/OriginProtocol/origin/issues/919
- poll for wallet balance changes

**Comment by matthewliu** [comment]
Renaming this issue to be more explicit. Broke user could be broken user experience.

**Comment by micahalcorn** [comment]
Indeed it is. 😑

**Comment by riverfor** [comment]
Does anybody work on this, can I work on this ?

**Comment by micahalcorn** [comment]
Sure, thanks @riverfor 🙏

**Comment by riverfor** [comment]
It's my pleasure, 

I have submitted the [pull request](https://github.com/OriginProtocol/origin/pull/784) already, please have a look when you are free.

**Comment by micahalcorn** [comment]
This will be handled by the stablecoin merge. 🙏
