### ISSUE TITLE
Create maintenance page for Dapp

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#67]
To show when the dapp is down. Needs to be plain html/css. (No React)

**Comment by owocki** [comment]
hi from https://gitcoin.co 👋 

@joshfraser @andrewhyde is this a good github issue to place a bounty upon?  gitcoin is a platform for crowdsourcing tasks from your community (and the gitcoin community).  i'd love to help you push your project forward.. ideal issue is something that's important, low overhead to manage, but can't quite make it onto the frontburner..

you bring the work needed and i can bring budget.  just point me in the direction of an issue you want turned around!

**Comment by garrisons** [comment]
How can we tell if the dapp is down? What loses connectivity I guess is my question?

**Comment by tomlinton** [comment]
The DApp is static JavaScript so it no longer has a concept of up/down. I think we should deal with this by surfacing errors in the DApp when it can't contact services it requires (e.g. bridge, IPFS).
