### ISSUE TITLE
Linked Message Avatar & Name

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#689]
**Edit** 10/16/2018 [micah]: There also appears to be a bug, as "Unnamed User" should appear when the user has not added a name. It, the avatar, and the ETH address should all link to the public profile but none of them should be colored `var(--clear-blue)`.

---

When chatting with a user, it would be helpful to be able to click their avatar or name to be able to go to their profile and see their listings, reviews etc.  This is the heuristic that other messaging systems like FB/Twitter use.

Screenshot:
<img width="1097" alt="screen shot 2018-10-05 at 1 02 15 pm" src="https://user-images.githubusercontent.com/2782676/46557545-1a377f00-c89f-11e8-8308-df2a2bf76bf8.png">

/ Thanks @DanielVF for the encouragement to file this one

**Comment by DanielVF** [comment]
As it is, if someone has not uploaded a profile with a name, there's no way to click to go to their profile.

![image](https://user-images.githubusercontent.com/837/46563250-60f09d80-c8ce-11e8-81de-e62e88d5c825.png)

**Comment by micahalcorn** [comment]
Moving this into the prioritized column as requested by @AustinVirts :point

**Comment by micahalcorn** [comment]
Resolved by #1037 ✅
