### ISSUE TITLE
Images are difficult to side scroll on mobile 

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#698]
Listing images on the mobile DApp listing page carousel currently require multiple swipes to get to the next image. They do not snap yet with one swipe like on other mobile sites. 

Screenshot showing how you have to swipe multiple times to advance the image:
![img_0431](https://user-images.githubusercontent.com/2782676/46633811-acd85800-cb03-11e8-8a2b-409307b132d4.PNG)

**Comment by micahalcorn** [comment]
Addressed by a recent redesign 🎨
