### ISSUE TITLE
Tighten up the BETA header on mobile

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin#699]
The warning header takes up way too much vertical space on mobile devices. We can tighten up the language by changing "You're currently using the Origin Mainnet Beta" to "Welcome to Origin's Mainnet Beta"

We can also hide the beta icon on small width devices if needed.

I know that we have a long list of things that we need to improve for the mobile experience, but we can at least improve the first impression for any mobile wallets or DApp browsers, like Coinbase Wallet that might be interested in featuring us.

**Comment by micahalcorn** [comment]
Resolved by https://github.com/OriginProtocol/origin/pull/747 per @Natasha08 ✅
