### ISSUE TITLE
Edit profile form doesn't pre-populate with saved data

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/origin#717]
Steps to reproduce:
1) Fill out name, description, etc
2) Publish profile
3) Refresh page
4) Click edit profile button

Notice that edit profile form isn't pre-populated with saved data

**Comment by Natasha08** [comment]
When I open the Edit Profile Modal, and upload a photo, the photo never displays in the Edit Profile Modal (this is before publishing).

**Comment by micahalcorn** [comment]
No longer an issue ☑️
