### ISSUE TITLE
Users often unable to see contact button on profile pages

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#725]
I believe the contact button only appears for logged in users.  

New users are not able to clearly see the contact button on the profile pages.  

This issue came up today when a Telegram user wanted to test messaging and tried to send me a message over Trust wallet but was unable to do so.

Screenshot.  Note the lack of contact button below the ETH address.  I believe he was even logged in as well.
![image 2018-10-11 15 36 02](https://user-images.githubusercontent.com/2782676/46835528-a9dfa080-cd6b-11e8-8329-08640214ae78.jpg)

**Comment by davecraige** [comment]
And screenshot from desktop.  Same issue:

![screen shot 2018-10-11 at 3 42 20 pm](https://user-images.githubusercontent.com/2782676/46835721-46a23e00-cd6c-11e8-9f26-3f3cfa57c242.png)

**Comment by whytecleon** [comment]
I encountered this issue, didn’t see the contact button while using chrome browser on my mobile device.

**Comment by micahalcorn** [comment]
Resolved long ago ✅
