### ISSUE TITLE
Buyers don't see how much money they are charged on final page

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#734]
The final stage of the checkout process is a little challenging to the buyers I believe.  There is no place on the page above the fold that actually tells the buyer how much he or she is now sending out.  This especially is important for our power users who have many listings.

I believe it would be good to clearly show in the modal exactly how much money is being sent from the buyer's wallet.  

Screenshot:

![screen shot 2018-10-12 at 12 08 18 pm](https://user-images.githubusercontent.com/2782676/46886338-dbae4100-ce17-11e8-8a83-1cccc36e2db3.png)

**Comment by micahalcorn** [comment]
Addressed by a recent redesign 🎨
