### ISSUE TITLE
International Airbnb Accounts

### ISSUE THREAD

**Issue by simibac** [OriginProtocol/origin#745]
When I tried to connect my Airbnb account it didn't accept the URL is not .com here in Switzerland (.ch). Now sure if everyone is aware that they can easily change it to .com and it still is a link to their account. So maybe you want to change that.
<img width="733" alt="bildschirmfoto 2018-10-13 um 10 45 08" src="https://user-images.githubusercontent.com/15369592/46903572-4c686280-ced7-11e8-81c3-884dc31328e4.png">

**Comment by davecraige** [comment]
Thanks for catching this @simibac 🙏. We will take a look.

**Comment by joshfraser** [comment]
Related issue https://github.com/OriginProtocol/origin-bridge/issues/136

**Comment by tomlinton** [comment]
Fixed in #748.
