### ISSUE TITLE
Long strings bleed into profile

### ISSUE THREAD

**Issue by jonhearty** [OriginProtocol/origin#773]
When there is a link with a really long length, it bleeds into the profile section of the listing page.

Examples:

https://dapp.originprotocol.com/#/listing/1-000-99
https://dapp.originprotocol.com/#/listing/1-000-98

<img width="1163" alt="screen shot 2018-10-17 at 9 58 31 am" src="https://user-images.githubusercontent.com/3673242/47116632-06810680-d217-11e8-9c3d-d704a27a1bd7.png">
<img width="1193" alt="screen shot 2018-10-17 at 9 56 44 am" src="https://user-images.githubusercontent.com/3673242/47116633-06810680-d217-11e8-8b01-4fbe9c95c250.png">

**Comment by micahalcorn** [comment]
Should just be a matter of setting a CSS property to get the text to wrap 👍

**Comment by micahalcorn** [comment]
Resolved by #839 ✅
