### ISSUE TITLE
Separate repo for deployment state

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#780]
The state of the deployments is recorded in the monorepo by [committing deployed image tags every time a deployment happens](https://github.com/OriginProtocol/origin/commit/643e957c207650e018cd10f8bb016b1afd283d27). We are doing this manually, but it will be automated when the CI/CD stuff happens. I'd like to break out this stuff into a separate repository for a few reasons:

- Reduce commit spam. If the CI/CD server is updating deployments several times a day we'll end up with a bunch of commits on our main repo (and announcements in Discord) that aren't very interesting. We'll need visibility over when deployments are complete but that will be handled in a better way than git commits.
- CI/CD system doesn't need commit access to main repo anymore.
- It's better to just have a single branch and commit to master for the deployment state. And I think @micah and @franckc might have a major falling out if @franckc keeps committing image tags to master. :grin:
- Easier to trigger actions (e.g. deployment update) off changes to a separate repo.

Basically this just involves moving [this directory](https://github.com/OriginProtocol/origin/tree/master/deployment/kubernetes/values) out of the monorepo. I'd also prefer if it were a private repo because it isn't relevant outside of Origin and we don't want to distract people from our main repo. That would also make me more comfortable about the encrypted SOPS secrets we have in there.

@franckc I think you were concerned about the overhead that this might add to doing deployments. It will be annoying for a little while but I plan to automate you out of a job ASAP. It'll also allow for that safety check of verifying the remote commit hash against the local one before the deploy script will let you deploy.

I can't quite believe I'm wanting new repos right after monorepo.

Any thoughts or objections?

**Comment by joshfraser** [comment]
We can't have private repos without paying for every single contributor (already quite expensive at our current levels). We could open a new Github account that's private but I'd prefer to keep everything open unless there's a very compelling reason. It makes a big difference being able to say we're 100% open-source vs. mostly open-source.

**Comment by tomlinton** [comment]
I did not think about that - so scratch the private repo idea. I think the key thing I'm getting at is that using git as a key value store is awkward. Perhaps there is an alternative place to store this data. I will have a look around for some other solutions.

**Comment by joshfraser** [comment]
Can we store a single key on each environment and then pull everything else from EnvKey?

**Comment by tomlinton** [comment]
Yea that is a cool idea, I'll see if its workable. It would be nice to have everything in one place. I didn't know you were such a fan of centralisation. :grin:

**Comment by joshfraser** [comment]
Scratch that, let's publish all our passwords on the blockchain.

**Comment by franckc** [comment]
Yes, storing all secrets in EnvKey could be good since we are already using it anyway.

For the image tags, it would be nice to have history. Ideally, we would keep track a history of what image got pushed at what time and by who. This is good for 2 reasons: auditing and also making it easier to rollback (side note: I'm a huge fan of rollback capabilities to allow our team to move fast: in case a newly deployed code breaks in production, the simplest thing to do is to rollback, then take the time to investigate and fix properly). One possibility maybe could be to store this data in a "devops" database, on GCP ?

**Comment by tomlinton** [comment]
Just thought I'd bump this as everyone has probably seen the `Update deployed image tags - OriginCI` commits on the repository now that the CI/CD is starting to work. If they are annoying we can break out to a separate infrastructure repo.

@franckc Helm provides that rollback functionality, it maintains its own database and every time we update a release it increments an ID and you can use the Helm cli to roll back to any previous ID. I gave instructions in Discord but I should document it somewhere so anyone can do it.

**Comment by franckc** [comment]
@tomlinton Thanks for pointing our helm's rollback capabilities - I think it totally meets our needs for now. Regarding the CI commits on the repo they haven't been problematic to me. But I let other chime in...

**Comment by tomlinton** [comment]
It doesn't look like it is bothering anyone too much so I'll close this for now and the CI system seems to be working well. Can revisit if it becomes problematic.
