### ISSUE TITLE
[Marketplace] Re-cycling offerId can cause loading incorrect offer data

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#787]
All this came up because I was looking into storing offer data in the database and needed a unique  ID...

Looking at the getOffer(offerId) method:
https://github.com/OriginProtocol/origin/blob/master/origin-js/src/contractInterface/marketplace/resolver.js#L65

Given that we are re-using offerId to save on gas (see https://github.com/OriginProtocol/origin/blob/master/origin-js/contracts/contracts/marketplace/v00/Marketplace.sol#L272), I think we could potentially load incorrect offer information for a user.

Here is the scenario I'm thinking off:
 - User A makes an offer on a listing, offerId=0
 - User A withdraws her offer. Contract deletes the offer data.
 - User B makes an offer on same listing. It will get re-assigned offerID=0
 - When user A loads up offer data she will get data from user B's offer since we look for Ethereum logs based on listingId and offerId.

Am I missing something ? It's definitely an edge case right now since we won't have that many listings with more than a single offer. But could become more common when we implement multi-units support (a listing will have potentially lot more offers).

If we update our contracts in the Q4, how about using a unique ID for each offer and not recycling it ?

**Comment by franckc** [comment]
CCing @nick @wanderingstan @DanielVF @cuongdo @jordajm since you are all on the list of engineers working on listing types in Q4...

**Comment by nick** [comment]
Hmm a new offer will generate a new ID... it shouldn't be possible to reuse the same ID. [This line](https://github.com/OriginProtocol/origin-js/blob/master/contracts/contracts/marketplace/v00/Marketplace.sol#L199) essentially increments the offerID every time makeOffer is called.

**Comment by franckc** [comment]
ohhh. deleting from an array in solidity does not change the array's length ! got it. my bad - I'm still not versed into solidity's specifics. thanks @nick !
