### ISSUE TITLE
Trailer: X-Stream-Error headers being returned from IPFS

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#794]
IPFS is returning `Trailer: X-Stream-Error` headers for me when uploading anything from the DApp. As far as I can tell the IPFS server responds with a 200 status code and begins streaming, but for whatever reason it thinks the streaming failed before it completes and so adds that header. The response actually looks fine and I don't think this causes any issues anywhere. Except for some load tests I was trying to write for `ipfs-proxy` where a package I'm using doesn't think the requests were successful and so the load tests fail.

I suspect it is an IPFS thing and is not fixable by us. It's happened with all the IPFS servers I've tried (both `go-ipfs` and `js-ipfs` on our production deployment and locally on my machine). I mostly wanted to document it here so I can refer to it in comments and in case it causes any issues down the road. And in case anyone smarter than me knows why this is happening!

Things I've tried that didn't help:

- Adding `?stream-channels=false` to the `/api/v0/add` POST request.
- Adding `?progress=false` to the `/api/v0/add` POST request.
- Modifying the CORS configuration on my local setup.

**Comment by nick** [comment]
I think we can probably close this now
