### ISSUE TITLE
Mobile Navigation Bar

### ISSUE THREAD

**Issue by Natasha08** [OriginProtocol/origin#811]
Note: This issue was created based on testing in Coinbase Wallet (previously Toshi).

- [x] Should be easy to change mobile padding so the navigation bar doesn’t end up being two lines
- [ ] Bizarre rendering error when tapping on blockchain transactions (haven’t been able to reproduce)
- [ ] Transactions dropdown doesn’t actually show any meaningful information e.g. Does not show any transaction hashes
- [ ] Alignment of all dropdown windows is off by 15 pixels or so on the right

**Comment by micahalcorn** [comment]
Resolved by #834 ✅
