### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by Natasha08** [OriginProtocol/origin#812]
Note: This issue was created based on testing in Coinbase Wallet (previously Toshi).

- [ ] The DApp freezes with use (and on initial load). 
  - Is it a performance issue for the DApp or Coinbase Wallet?
  - Maybe messaging resources is locking up the DApp
- [ ] Generally Sluggish scrolling. Is there a 300ms delay for certain touch actions in the browser?
- [ ] Very laggy scrolling in the messaging window.

**Comment by micahalcorn** [comment]
Considering this resolved by DApp:two:
