### ISSUE TITLE
Mainnet beta modal

### ISSUE THREAD

**Issue by Natasha08** [OriginProtocol/origin#813]
Note: This issue was created based on testing in Coinbase Wallet (previously Toshi).

- [ ] In some cases the modal does not dismiss on 'Proceed' and the screen scrolls behind the modal.
- [ ] Verify that all modals are not allowing for scrolling behind the modal

**Comment by Natasha08** [comment]
There is a bug in Bootstrap 4 (Search for `<body> with overflow:hidden CSS is scrollable on iOS` [here](https://getbootstrap.com/docs/4.0/browser-bugs/)). I have tried quite a few strategies, but have not found a solution yet.

**Comment by Natasha08** [comment]
Additionally, because we are using Bootstrap4 (and therefore JQuery) to render the modals, React does not know about these DOM updates. Particularly the `modal-open` class is often times removed from the DOM.

**Comment by micahalcorn** [comment]
Resolved by #1083 ✅
