### ISSUE TITLE
Mobile Seller Onboarding Modal

### ISSUE THREAD

**Issue by Natasha08** [OriginProtocol/origin#814]
Note: This issue was created based on testing in Coinbase Wallet (previously Toshi).

When a user is on mobile without wallet functionality they cannot create listings or verify their identities. Even when a user does have a mobile wallet, the onboarding mobile blocks the messaging UI.

- [x] For mobile browsers hide the seller onboarding modal.

**Comment by micahalcorn** [comment]
Resolved by #865 ✅
