### ISSUE TITLE
Mobile Messaging UI

### ISSUE THREAD

**Issue by Natasha08** [OriginProtocol/origin#815]
Note: This issue was created based on testing in Coinbase Wallet (previously Toshi).

- [x] text input box needs to be bigger
- [ ] ~~the address should be below the user name, and date below that. Everything left aligned will fix the truncation issues.~~
- [x] css to make messaging more usable (padding and font size changes)

[This Issue](https://github.com/OriginProtocol/origin/issues/812) will fix the laggy scrolling in the messaging window.

**Comment by micahalcorn** [comment]
Related to #809 👍

**Comment by micahalcorn** [comment]
Resolved by #1037 ✅
