### ISSUE TITLE
Mobile Photos

### ISSUE THREAD

**Issue by Natasha08** [OriginProtocol/origin#817]
Note: This issue was created based on testing in Coinbase Wallet (previously Toshi).

- [x] Problem uploading iPhone X photos (increase the current 1.5MB limit?) [Fixed here](https://github.com/OriginProtocol/origin/pull/731)
- [ ] Error message on file upload size runs through divs. (Try uploading an unsupported file type)
  - [ ] Font size is too large for error message

**Comment by Natasha08** [comment]
https://github.com/OriginProtocol/origin/pull/731 addresses the problem with uploading iPhone X photos

**Comment by micahalcorn** [comment]
Resolved by #1084 ✅
