### ISSUE TITLE
Edit profile modal

### ISSUE THREAD

**Issue by Natasha08** [OriginProtocol/origin#819]
Note: This issue was created based on testing in Coinbase Wallet (previously Toshi).

- [ ] (mobile) Window scrolls behind the modal [Should be fixed with jQuery removal](https://github.com/OriginProtocol/origin/issues/813)
- [ ] Image upload bleeds through the cropped rounded squares

**Comment by micahalcorn** [comment]
Resolved by #1083 ✅
