### ISSUE TITLE
Mobile Phone and Email Attestation

### ISSUE THREAD

**Issue by Natasha08** [OriginProtocol/origin#820]
Note: This issue was created based on testing in Coinbase Wallet (previously Toshi).

On mobile when a user is adding a phone number and when they are entering verification codes for an attestation, the keyboard should default to a numerical keyboard. 

![image](https://user-images.githubusercontent.com/17957496/47464486-8de5f100-d7a6-11e8-8ee1-922f7140eed7.png)
![image](https://user-images.githubusercontent.com/17957496/47464491-90484b00-d7a6-11e8-8a2a-ad8c35263ff5.png)

**Comment by micahalcorn** [comment]
Resolved by #988 ✅
