### ISSUE TITLE
Mobile Publish modal

### ISSUE THREAD

**Issue by Natasha08** [OriginProtocol/origin#821]
Note: This issue was created based on testing in Coinbase Wallet (previously Toshi).

- [x] Padding is off compared to other modals
- [x] The icons for attestation types are center-aligned, which works great if they are on the same line but looks terrible if it runs to two or three lines.
  - To reproduce this add several attestations (i.e. phone, email, google)

**Comment by micahalcorn** [comment]
Resolved by #989 ✅
