### ISSUE TITLE
Network Loading

### ISSUE THREAD

**Issue by Natasha08** [OriginProtocol/origin#822]
Note: This issue was created based on testing in Coinbase Wallet (previously Toshi).

The app usually takes a long time to load -- both on desktop & mobile. On mobile, the connectivity dropdown takes up the entire screen.

On desktop:
- [ ] Implement rotating messages under the spinner that say "Connecting to the Ethereum Mainnet", "Connecting to IPFS", etc.
- [ ] the connectivity dropdown should only open if a user taps on the four dots.

On mobile:
- [x] do not show connectivity dropdown [fixed in this PR](https://github.com/OriginProtocol/origin/pull/834)

NB: May have to use a real device to reproduce the connectivity dropdown behavior issue.

**Comment by micahalcorn** [comment]
Let's remove the connectivity dropdown entirely from mobile screens. Aure is working on a general overhaul of the navbar as well.

**Comment by micahalcorn** [comment]
Considering this closed 😐
