### ISSUE TITLE
Mobile Photo Upload

### ISSUE THREAD

**Issue by Natasha08** [OriginProtocol/origin#828]
Note: This issue was created based on testing in Coinbase Wallet (previously Toshi).

- [x] photos were oriented incorrectly coming from the iPhone camera

This issue exists in:
  - profile photos
  - conversation photo uploads
  - listing photos

NB: One culprit could be rotation metadata in the image not being read. I.e. the phone doesn't actually rotate the pixels, it just sets metadata for the preferred rotation.

**Comment by micahalcorn** [comment]
Resolved by #1014 ✅
