### ISSUE TITLE
Docker-compose stability

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#850]
Soon we shall be reading listings from elasticsearch and that will require functioning of `event-listener`, `origin-discovery` and `elasticsearch` containers. Running origin locally without docker might not be practical anymore.  

The purpose of this ticket is to discuss what changes we could incorporate in order to make it easier for people to use docker containers. Once we decide on the change (in the discussion below) lets just add it to the list: 

**Proposed changes:**
- [ ] first change

**Comment by sparrowDom** [comment]
this might be interesting to: @franckc @tomlinton @micahalcorn

**Comment by sparrowDom** [comment]
One of the things that we could improve IMHO is the way we define environmental variables. Some are defined in `docker-compose.yml` ( [example](https://github.com/OriginProtocol/origin/blob/master/docker-compose.yml#L16) ) and some are mounted into the container using the .env file  ( [example](https://github.com/OriginProtocol/origin/blob/master/docker-compose.yml#L169) ). I think it would be better if all the configuration is in `.env` files and none of it in `docker-compose.yml`. Changing stuff in docker compose for me required the deletion of the container, rebuilding that container and sometimes restarting docker.

**Comment by tomlinton** [comment]
Thanks for raising this @sparrowDom!

The intention was for the env vars that are in `docker-compose.yml` to be those settings that are only related to Docker Compose. Anything that is DApp specific and has nothing to do with Docker Compose should live in the `.env` file. Modifying settings should require a `docker-compose down && docker-compose up`.

99% of the Docker Compose issues we are having relate to npm package management. It seems to be very hard to get the installation and startup right. If anyone runs into a bug please raise an issue. It's hard to get visibility of problems just via Discord. It is also hard to discuss solutions and for other people to contribute if bugs get lost in the Discord chats.

I'm thinking about a few other things that might work for our dev environments. I think local development of `origin-js` + `origin-dapp` could be done with lerna and just preconfigure everything for our dev deployment. I'm also looking at [Telepresence](https://www.telepresence.io/) which allows you to inject a locally built Docker container into a remote Kubernetes deployment which seems like it might be a good idea.

**Comment by sparrowDom** [comment]
Currently it is possible to develop `origin-js` + `origin-dapp` locally with only those 2 repos, but once we are reading listings from the backend the `listener`, `discovery` and `elasticsearch` containers will be a required for the environment to function. I suppose everyone will need to run containers from docker. 

As for `docker-compose` environment variables [these](https://github.com/OriginProtocol/origin/blob/master/docker-compose.yml#L30-L32) are the only ones I think should stay in docker-compose.yml. I would move all other to `.env` files. As said in my case I need to delete the container and build it in order for `environement:` variables change to take effect.

**Comment by tomlinton** [comment]
I don't have any problem with moving the env variables around, but the container doesn't need to be removed for changes in `environment:` to take effect. It only has to be restarted. You can verify with a minimal `docker-compose.yml` like:

```
version: "3"

services:
  api:
    image: 'ubuntu'
    environment:
      - TEST_ENV=origin
    entrypoint: printenv
```


e.g.

```
➜  docker-test docker-compose up
Recreating docker-test_api_1 ... done
Attaching to docker-test_api_1
api_1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
api_1  | HOSTNAME=e9cbc1191bc9
api_1  | TEST_ENV=decentralize
api_1  | HOME=/root
docker-test_api_1 exited with code 0
➜  docker-test vim docker-compose.yml
➜  docker-test docker-compose up
Recreating docker-test_api_1 ... done
Attaching to docker-test_api_1
api_1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
api_1  | HOSTNAME=bd84390fff44
api_1  | TEST_ENV=origin
api_1  | HOME=/root
```
If you are seeing some issue where the environment variables aren't matching what you set there is problem some other configuration issue at play.

I think it will still be possible to develop on `origin-js` + `origin-dapp` locally, we just point the discovery servers to the dev deployment.

**Comment by sparrowDom** [comment]
@tomlinton you are right, I am getting to know docker better :) I though `docker-compose down/up` just stops/starts all the containers. Seems that it does a bit more (Stop and remove containers, networks, images, and volumes). 

So container restart does not pickup the environment variables, but down/up does. Thanks for that info!

As to local development, we were just discussing this with @franckc yesterday. There will be a switch in the DApp to instruct origin to read all data either from web3 or discovery. In the initial phases default developer configuration will read stuff from web3 (or discovery if someone manually configures differently) and we will test reading from discovery on staging. Once we are happy with performance/stability we can deploy to production. 

At that point imo it would be better for developers to switch to reading from discovery mode (or at least have local environment configured so that both options are operational, to mimic the production environment as close as possible. 

I think switching discovery server to dev deployment won't be enough since listings created on localhost blockchain won't get picked up by the `event-listener` running on dev deployment and not persisted to `postgres` and `elasticsearch`, and thus not served by `discovery`. 

We could probably configure `event-listener` to connect to dev deployment of `postgres` and `elasticsearch`, but then some listings with the same ids (each developer running his own local blockchain) might get overwritten on dev deployment. 

I guess that could be mitigated by each developer having a unique network id for localhost instead of `999`. Though locally running `event-listener` would still be required.

**Comment by tomlinton** [comment]
@sparrow are you happy to close this? I think with the new single container setup it is a lot more stable, and the hoisting has also helped out.

**Comment by sparrowDom** [comment]
👍 yup seems that most of the issues discussed above are no longer relevant.
