### ISSUE TITLE
Expose dashboard to public

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#867]
We have a dashboard running on an internal IP on Google Cloud. We want to expose this publicly. It uses Metabase which is a software package that generates dashboards from SQL data. This means that it has access to our databases which poses a risk if we expose it publicly. Some options:

1. Write a small script that runs on the Metabase server that scrapes the dashboard and publishes a static page somewhere.
2. Configure nginx rules so that the only publicly accessible page served from Metabase is the dashboard, e.g. `dashboard.originprotocol.com/` -> `/public/dashboard/b116e092-2ed4-40a3-9625-cbe4e45528c0`. This removes most of the attack vectors from login pages etc.

I think I prefer 2. It isn't quite as secure as a purely static page, but it is less likely to break and less work. If there are no objections I'll go with that, but please discuss if you think other options are preferred.

**Comment by joshfraser** [comment]
I'm comfortable with option 2. We'll probably end up with 4 or 5 dashboards in Metabase that we'll want to share (website, dapp, social, dev stats, etc). Most will be public, but we may choose to keep a few more private. I think your scheme still works for this. We can just append the specific dashboard that we want to the URL (ie. `dashboard.originprotocol.com/dapp`) or fall back to the default.

**Comment by tomlinton** [comment]
Had a bit of a chat with @matthewliu about this. There are a couple of options on the public/private spectrum:

- Network restricted (i.e. issue VPN certificates and only people on the VPN can access them which is what is happening with the office dashboard now)
- Publicly available but with a URL that is not publicly known, e.g. `dashboard.originprotocol.com/b116e092-2ed4-40a3-9625-cbe4e45528c0`
- Publicly available with a URL that is publicly known

To get the current one setup should we go fully public (`dashboard.originprotocol.com`), semi-public (`dashboard.originprotocol.com/b116e092-2ed4-40a3-9625-cbe4e45528c0`) or private (VPN)? I'm thinking public is OK given our bias to transparency. We can decide the privacy level of other dashboards on a case by case basis.

In terms of the URL schemes I think it makes sense to have a primary dashboard at `dashboard.originprotocol.com` and any secondary ones at a path, e.g. `dashboard.originprotocol.com/b116e092-2ed4-40a3-9625-cbe4e45528c0`.

**Comment by tomlinton** [comment]
This is done. Just noting that Metabase uses a [REST API](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md) to load data for the public dashboards. I limited it as much as I could, only `/api/public/*` endpoints are available.
