### ISSUE TITLE
[Notifications] Implement mechanism to prevent sending duplicates

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#875]
For context, see #852 
Since the event-listener does not guarantee only-once delivery, the notifications server should implement a mechanism to keep track of notifications already sent in order to avoid sending duplicates. Suggestion is to use Redis for storing that data.

**Comment by gauravsavanur07** [comment]
hey my name is @Geek Blocks I would love to work on prevent duplicates event listener issue.

**Comment by franckc** [comment]
@gauravsavanur07 Did you send an email saying you would be interested in working on this ? For some reason it did not get recorded in this issue...

Anyway, if you did, here are a few pointers/ideas, in terms of how I could imagine this would work to get you started:
 - Define a scheme to create uid for messages received by notifications servers from the event-listener via webhook. The tuple (blockNumber, logIndex) could be a good choice.
 - When receiving a new message, notifications server first checks against persistent storage if message has already been processed by doing a lookup by uid. If already processed, do nothing, otherwise send notification(s) to user(s). Then store uid in storage.
 - For persistent storage, Redis is probably a good choice. We haven't set it up in production yet but will do soon since we need it for another service.

Let me know any questions...

**Comment by micahalcorn** [comment]
Considering the first version of this to be done ✅
