### ISSUE TITLE
Error Tracking

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#878]
Should we implement error tracking now that we're live with a Mainnet DApp? I recall some discussion earlier this year about using [Sentry](https://sentry.io/) for the website, but don't remember if we ever did anything about that. My only concern was that we don't want just a bunch of noise coming from `localhost` and random browser extensions. I'm also not suggesting that we try to reproduce and solve every client-side error, as it can be an endless struggle with little, if any, benefit. But it would be good to get some insight if we are throwing something regularly that needs to be investigated, such as the [ones that](https://github.com/OriginProtocol/origin/issues/799) [have been](https://github.com/OriginProtocol/origin/issues/871) plaguing our team.

Thoughts? @franckc @jordajm @sparrowDom @wanderingstan @tomlinton @Natasha08 @DanielVF @nick @cuongdo

**Comment by tomlinton** [comment]
I like Sentry. You can do good filtering on to remove `localhost` and stuff that happens from browser extensions. It gives you a good idea of how often specific errors are being seen by real users.

**Comment by franckc** [comment]
Yes, sentry is pretty good. Looks like they have good JS support: https://sentry.io/for/javascript/
We could either use their SAAS product (I know people there and could probably get us some free trial) or just set it up ourselves (it is open source) - I would vote for the latter: it would be one less thing for us to run ourselves.

Probably not a huge priority right now given our very low user volume, but on the other hand it looks super straight forward to setup so we could probably do this as a side project... Maybe a good topic to discuss during eng weekly ?

**Comment by sparrowDom** [comment]
I don't have experience with Sentry but I am all for error tracking. Like pointed out it should be a pretty straight-forward implementation. Noise shouldn't be a problem since we can have an configuration for [different environments](https://docs.sentry.io/learn/environments/?platform=javascript). So we can focus and differentiate between staging and production.

**Comment by cuongdo** [comment]
I used Sentry for my previous job, which was an open-source Go project. We used the SaaS version, and it worked well in that instance and helped to prioritize bugs partly based on frequency. It seemed to do a reasonable job of combining similar stack traces. I’m not sure how well Sentry does with JS, but it seems like a good thing to try.

**Comment by Natasha08** [comment]
I've used Sentry previously as well, and using JS. It's great for tracking frequency of bugs and you can send it information about the state of the DApp with the error.
