### ISSUE TITLE
Invalid Address Error From web3-eth-abi

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#907]
This error seems to be throwing when we try to interact with a contract without an ETH address, for example, when the user's browser is not web3-enabled or she is not signed in to MetaMask (aka when `web3.eth.getAccounts()` returns `[]`). I suspect that the same error may occur prior to receiving the user's [permission to access her account](https://github.com/OriginProtocol/origin/pull/836).

`Error: invalid address (arg="", coderType="address", value=undefined)`

**Comment by micahalcorn** [comment]
I think this is coming from [here](https://github.com/OriginProtocol/origin/blob/master/origin-js/src/contractInterface/users/v00_adapter.js#L50). cc @tyleryasaka

**Comment by micahalcorn** [comment]
@heychessy It is not, so please do! 😄 I've sent you an invitation to join the GitHub organization. Once you accept that, you will be able to push your branch directly instead of forking.

**Comment by heychessy** [comment]
Alright :)

Can you tell me how can I reproduce the error

**Comment by micahalcorn** [comment]
@heychessy it is currently visible if you visit https://dapp.originprotocol.com/ in a browser that does not have MetaMask. I'm not sure how to debug it with a local blockchain. We need to find a way to connect our own httpProvider to Ganache without it loading the 10 test accounts. You could prevent it from generating the accounts, but you would also have to disable many of the migrations. Let us know if you are able to figure it out. 🙏

**Comment by micahalcorn** [comment]
@heychessy additionally, you could use a browser that _does_ have MetaMask installed. Enable "privacy mode" and reject any prompts for access to your account. 🤔

**Comment by micahalcorn** [comment]
@heychessy are you still working on this or should someone else pick this up? 🙂

**Comment by micahalcorn** [comment]
Assuming this is fixed by the move to identity v2 or dapp v2 🐫
