### ISSUE TITLE
[Markeplace contract] withdrawListing can be called more than once

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#930]
There is no check preventing a listing from being withdrawn more than once:
https://github.com/OriginProtocol/origin/blob/master/origin-contracts/contracts/marketplace/v00/Marketplace.sol#L166

This is a regression caused by removing the code that used to delete a listing from storage when it listing was withdrawn.

The impact is that the deposit amount would get sent twice to the affiliate.

A possible fix would be to set deposit to 0 once listing is withdrawn.

CC @cuongdo Since that is probably an issue the audit will raise.

**Comment by kyriediculous** [comment]
Didn't mean to hijack but as suggested by @franckc 
```
    // @dev Listing depositManager withdraws listing. IPFS hash contains reason for withdrawl.
    function withdrawListing(uint listingID, address _target, bytes32 _ipfsHash) public {
        Listing storage listing = listings[listingID];
        //Throw early and loud instead of on token.transfer(_target, 0)
        require(listing.deposit != 0, "No deposit to withdraw");
        require(msg.sender == listing.depositManager, "Must be depositManager");
        require(_target != 0x0, "No target");
        uint _deposit = listing.deposit;
        listing.deposit = 0; //Set deposit to 0 on succesful token transfer
        tokenAddr.transfer(_target, _deposit); // Send deposit to target
        emit ListingWithdrawn(_target, listingID, _ipfsHash);
    }
```

**Comment by micahalcorn** [comment]
Resolved per @nick ✅
