### ISSUE TITLE
Data verification for JSON schema listings

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/origin#949]

**Comment by micahalcorn** [comment]
@tomlinton I just transferred this issue from [origin-js](https://github.com/OriginProtocol/origin-js) using [the new Beta feature](https://help.github.com/articles/transferring-an-issue-to-another-repository/). 🎉

**Comment by tomlinton** [comment]
Wow awesome, I'm glad I didn't do that migration we had planned!
