### ISSUE TITLE
Home page listings order

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#965]
currently listings on homepage are ordered first by "Featured" then by OGN commission after that order is undefined. The rest of the listings should be ordered by creation date descending.

**Comment by franckc** [comment]
Good catch @sparrowDom - yes agreed we should order by time created desc.
Though glancing at the code, it does not look like the listing model stores any creation date so that data won't get indexed in elastic search.... should we add it so that we can then sort by that field ? or were you thinking of a different way to solve this ?

**Comment by sparrowDom** [comment]
Hmm good point. Since we are on the blockchain maybe `blockNumber` and `logIndex` of the `CreateListing` event should be enough?

**Comment by micahalcorn** [comment]
I would favor recording a timestamp, which can be approximately derived from the block number after the fact. What about relying on the id? I have this silly util in a local branch to accommodate client-side sorting:
```
/**
 * Takes a listing id and converts it to a large integer with consistent 0 padding for use in sorting
 * e.g. '999-001-23' becomes 0010000000023
 * @param {string} string - an id containing two hyphens separating three numbers
 * @return {string} the padded, combined second and third numbers
 */

export function idToPaddedNumericString(id) {
  const PAD = '0'
  const DIGITS_IN_A_HUNDRED = 3
  const DIGITS_IN_A_BILLION = 10
  const parts = id.split('-')
  const contractVersion = parts[1]
  const listingIndex = parts[2]

  return `${PAD.repeat(DIGITS_IN_A_HUNDRED - contractVersion.length)}${contractVersion}` +
         `${PAD.repeat(DIGITS_IN_A_BILLION - listingIndex.length)}${listingIndex}`
}
```

**Comment by sparrowDom** [comment]
Relying on the `id` seems the most straightforward solution, though has the disadvantage you point out @micahalcorn. If only needed for sorting I would rather rely on `blockNumber` + `logIndex` than `timestamp` after the fact, because with the former approach the sorting inside each block will also be correct. 

On the other hand, we will probably implement some kind of date filtering in the future and `createdTimestamp` and `updatedTimestamp` seem the most practical. For those reasons I would rather go with timestamp fields.

**Comment by micahalcorn** [comment]
From @lskip11:

> I don't really understand what the idea or algorithm behind listing new items? It's not by date, or price or if it supposed to be random it's really not. I added 4 piece and all of them "randomly" shows on the 8 page next to each other! :( https://peerart.io/#/page/8
> 
> Also  I used to have 2 of my pieces placed on the first page but after I edit them (change the text and add new image) they went to the 2nd page :( not cool at all

**Comment by matthewliu** [comment]
Given the recent spam listings, we should probably re-visit our assumptions here and come up with some very basis search quality heuristics. We want to bring legitimate listings to the forefront, especially if they can be purchased multiple times, and we want to penalize (but not remove) fake listings.

**Comment by franckc** [comment]
@matthewliu Agreed. Let's book time this spring to improve ranking. It should be relatively simple.

**Comment by franckc** [comment]
Just chatted with @DanielVF - he has some spare cycle this week and is going to take a stab at demoting those listings in the search index...

**Comment by matthewliu** [comment]
Sounds excellent. 

This brings up a related question. Over time, what listings do we want to promote algorithmically (vs. just featured manually)? We can revisit at a later date.

**Comment by micahalcorn** [comment]
Resolved by https://github.com/OriginProtocol/origin/pull/2270 🚀
