### ISSUE TITLE
Token transfer tool productionization

### ISSUE THREAD

**Issue by cuongdo** [OriginProtocol/origin#966]
The impending PR for the token transfer tool is a work in progress. The tool needs at least the following to be production ready:

- [ ] Validate capabilities of tool vs. the Origin token grants that exist
- [x] SSL support
- [x] Productionize serving of client app
   * I *think* this means running webpack on the client app and somehow serving it from the backend.
- [ ] Make the client code better
   * The client code was my attempt at prototyping a frontend (and my first code using React & Redux) so that I could test the backend.
- [ ] Tests for vesting tool logic
- [ ] Tests for token transfer logic
- [ ] Creation of data to be imported into token grant database
   * This can only be done by the limited people who have the complete set of token grants & investments.
   * This may require creating a simple tool to import from CSV or something similar.
- [ ] Deploy VM with:
   * A wallet
   * Locked down configuration
   * This software
   * Regular snapshot backups
   * Cron job for the vesting tool

cc @tomlinton @nick @matthewliu @joshfraser

**Comment by cuongdo** [comment]
@tomlinton I cc'ed you because I could definitely use your help with several of these tasks.

**Comment by cuongdo** [comment]
I've submitted the initial PR for T3: #967

**Comment by tomlinton** [comment]
Great work @cuongdo. As a first step I'll get it deployed and running with SSL and such and I'll get the tests running on the CI server so we can add tests. Then we can have a discussion about how we tackle the wallet bit. 😱

**Comment by tomlinton** [comment]
Closed in favour of #3073.
