### ISSUE TITLE
Strange migration problems with origin-notifications

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin#970]
When I `docker-compose up` a fresh new box, the origin-notifications db migration is marked as migrated in DB, but the actual migration not applied in the database. This happens every time.

The table `push_subscription` that should be created by the notification is not there. 

    origin=# \dt
                List of relations
    Schema |      Name       | Type  | Owner
    --------+-----------------+-------+--------
    public | SequelizeMeta   | table | origin
    public | alembic_version | table | origin
    public | attestation     | table | origin
    public | event           | table | origin
    public | listener        | table | origin
    public | listing         | table | origin
    public | offer           | table | origin
    (7 rows)

The migration marker is present in the DB:

    origin=# select * from "SequelizeMeta";
                        name
    --------------------------------------------
    20181018224855-listing-create-table.js
    20181018224856-offer-create-table.js
    20181023225253-event-create-table.js
    20181102175025-create-listener.js
    20181112190527-listing-add-block-num.js
    20181029174407-create-push-subscription.js
    (6 rows)

If I delete the migration marker:

    origin=# delete from "SequelizeMeta" where name = '20181029174407-create-push-subscription.js';
    DELETE 1

Then rerun the origin-notifications migration, the table is created, and the notification service works.

**Comment by DanielVF** [comment]
@tomlinton Any ideas here?

**Comment by tomlinton** [comment]
That is strange, it does it every time after that? I would have said that it just somehow failed to run properly and got in an incorrect state, but if it does it every time that can't be right.

Maybe check the logs for the notification container to see the migration output with `docker-compose logs origin-notifications`. Or you could also try and just bring up the notifications container with `docker-compose down && docker-compose up origin-notifications` and see if the migration output sheds any light.

**Comment by DanielVF** [comment]
It does it every time from a fresh `prune` state.

**Comment by tomlinton** [comment]
And then on subsequent `docker-compose down && docker-compose up` it is OK? I'll try and debug it from the pruned state if so.

**Comment by DanielVF** [comment]
It stays broken until you do the manual process above. After doing that, it stays working through subsequent docker-compose down && docker-compose up's.

**Comment by tomlinton** [comment]
From a fresh state I get this output:

```
origin-notifications    |
origin-notifications    | > origin-notifications@0.0.1 migrate /app
origin-notifications    | > sequelize db:migrate
origin-notifications    |
origin-notifications    |
origin-notifications    | Sequelize CLI [Node: 10.13.0, CLI: 5.3.0, ORM: 5.0.0-beta.14]
origin-notifications    |
origin-notifications    | Loaded configuration file "src/config/config.js".
origin-notifications    | Using environment "production".
origin-notifications    |
origin-notifications    | ERROR: connect ECONNREFUSED 172.19.0.2:5432
origin-notifications    |
origin-notifications    | npm ERR! code ELIFECYCLE
origin-notifications    | npm ERR! errno 1
origin-notifications    | npm ERR! origin-notifications@0.0.1 migrate: `sequelize db:migrate`
origin-notifications    | npm ERR! Exit status 1
origin-notifications    | npm ERR!
origin-notifications    | npm ERR! Failed at the origin-notifications@0.0.1 migrate script.
origin-notifications    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
origin-notifications    |
origin-notifications    | npm ERR! A complete log of this run can be found in:
origin-notifications    | npm ERR!     /root/.npm/_logs/2018-11-22T01_59_39_724Z-debug.log
```

It looks like it is running migrations before PostgreSQL starts, so I'll add a wait for that port to open. That doesn't seem to fully explain how SequelizeMeta got populated and the migrations didn't get run but perhaps this will avoid it getting into that state.

**Comment by micahalcorn** [comment]
Is this resolved by https://github.com/OriginProtocol/origin/pull/980?

**Comment by tomlinton** [comment]
I think it should have fixed it, please reopen if you run into it again @DanielVF.
